force-app/main/default/objects/BU_Staging_Field_Mapping_Metadata__mdt/BU_Staging_Field_Mapping_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>BU Staging Field Mapping Metadata</label>
    <pluralLabel>BU Staging Field Mapping Metadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/BU_Staging_Field_Mapping_Metadata__mdt/fields/Column_Header__c.field-meta.xml
<CustomField>
    <fullName>Column_Header__c</fullName>
    <label>Column Header</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_CSV_File_Maximum_Record__mdt/Bulk_Upload_CSV_File_Maximum_Record__mdt.object-meta.xml
<CustomObject>
    <description>Used to store the count for maximum number of records in the csv file upload for bulk upload.</description>
    <label>Bulk Upload CSV File Maximum Record</label>
    <pluralLabel>Bulk Upload CSV File Maximum Records</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bulk_Upload_CSV_File_Maximum_Record__mdt/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>maximum number of records to be uploaded in BU Staging object.</description>
    <label>Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BulkUploadStagingRecords.cls
/*------------------------------------------------------------
Author:        Pawan Tiwari
Company:       Arxxus Technology Partners
Description:   1. Get total number of staging records being inserted after the file upload.
               2. Get count for maximum number of records allowed for a upload.
               3. List of csv column header from 'BU Staging Field Mapping Metadata'
Inputs:        Uploaded file content

History
16/06/2017      Pawan Tiwari         Created.
------------------------------------------------------------*/
public with sharing class BulkUploadStagingRecords {
    
    //Input :- Content of CSV file uploaded 
    //Output :- Number of successfully inserted records
    @AuraEnabled
    public static Integer addRecordsCSV(String fileContent){
        Integer successUploads;
        System.debug('fileContent is = '+fileContent);
        BulkUploadStagingRecordsCntrl bfl = new BulkUploadStagingRecordsCntrl(fileContent);
        successUploads = bfl.execute();
        System.debug('SuccessFully inserted '+ successUploads +' Stagging Records');
        return successUploads;
    }

    // Get count for maximum number of records allowed for a upload.
    @AuraEnabled
    public static Integer getUploadRecordCount(){
        Integer recordCount;

            List<Bulk_Upload_CSV_File_Maximum_Record__mdt> mappingMetadataRecList = [SELECT Count__c 
                                                                                    FROM Bulk_Upload_CSV_File_Maximum_Record__mdt
                                                                                    LIMIT 1];
                
            if(mappingMetadataRecList.size() > 0){
                recordCount = Integer.valueOf(mappingMetadataRecList[0].Count__c);
            }

            return recordCount;
        
    }

    // Get list of csv column headers from 'BU Staging Field Mapping Metadata'
    @AuraEnabled
    public static List<String> getCSVColumnHeaders(){
         List<String> columnHeaders = new List<String>();
            List<BU_Staging_Field_Mapping_Metadata__mdt> mappingMetadataRecList = [SELECT Column_Header__c
                                                                                    FROM BU_Staging_Field_Mapping_Metadata__mdt ];
                
            
            for(BU_Staging_Field_Mapping_Metadata__mdt mappingMetadataRec : mappingMetadataRecList){
                columnHeaders.add(mappingMetadataRec.Column_Header__c);
            }
            System.debug('getCSVColumnHeaders :: ' + columnHeaders );
            return columnHeaders;
        
    }

}