force-app/main/default/objects/CaseFilterSetting__c/CaseFilterSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Case Keyword Filter Setting</label>
</CustomObject>

force-app/main/default/objects/CaseFilterSetting__c/fields/origin__c.field-meta.xml
<CustomField>
    <fullName>origin__c</fullName>
    <description>Comma separated list of Case Origins</description>
    <inlineHelpText>Comma separated list of Case Origins</inlineHelpText>
    <label>Case Origins</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseFilterSetting__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <description>Comma separated list of Record Type API names for which keywords are to be scanned</description>
    <inlineHelpText>Comma separated list of Record Type API names for which keywords are to be scanned</inlineHelpText>
    <label>Case Record Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Keywords__c/Keywords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configured words with their priority, on occurrence of which in either body or subject will lead to the case being elevated to corresponding priority</description>
    <label>Keywords</label>
</CustomObject>

force-app/main/default/objects/Keywords__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>&quot;High&quot;</defaultValue>
    <description>Priority of the case in which the corresponding keyword is found</description>
    <inlineHelpText>Priority of the case in which the corresponding keyword is found</inlineHelpText>
    <label>Priority</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CasePriorityUtility.cls
/*------------------------------------------------------------
Author:        Dipankar Barman
Company:       Arxxus.com
Description:   it checks the Input Text and body for key words that are configured as high priority
                returns the ministreal correspondance record type for cases

Test Class:    CaseTriggerDispatcher_Test
History
30 Mar 2015      Dipankar Barman     created
------------------------------------------------------------*/
public with sharing class CasePriorityUtility {
    static Pattern highPriority;
    static Set<Id> scannedRecTypeIds= new Set<Id> ();
    static Set<String> scannedOrigins=new Set<String>();
    static{
        //fetch the MinCorro case recordTypes to check against reprioritising them
        CaseFilterSetting__c caseFilterSetting=CaseFilterSetting__c.getValues(GlobalConstants.CASE_FILTER_SETTING_NAME);
        if(caseFilterSetting!=null){
            String origins=caseFilterSetting.origin__c.normalizeSpace();
            String scannedRecTypes=caseFilterSetting.RecordType__c.normalizeSpace();
            List<String> scannedRecordTypeDeveloperNames=scannedRecTypes.split(',',0);
            Map<Id,RecordType> caseTypes=new Map<Id,RecordType> ([SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName in :scannedRecordTypeDeveloperNames]);
            scannedOrigins.addAll(origins.split(',',0));
            scannedRecTypeIds=caseTypes.keySet();
        }
        

        //fetch the configured words from custom settings
        Set<Keywords__c> highPriorityKeywords = new Set<Keywords__c>();
        Map<String, Keywords__c> mapOfKeyWordsSettings = Keywords__c.getAll();
        for(Keywords__c keyword : mapOfKeyWordsSettings.values()) {
            if(keyword.Priority__c == GlobalConstants.CASE_PRIORITY_HIGH) {
                highPriorityKeywords.add(keyword);
            }
        }        
        String regexPre='(?i).*(\\s';
        String regexPost='\\s).*';
        String regexMid;
        for (Keywords__c aKey:highPriorityKeywords){
            regexMid=regexMid==null?aKey.Name:regexMid+'\\s|\\s'+aKey.Name;
        }
        //prepare pre compiled pattern
        String highPriorityRegex=regexPre+regexMid+regexPost;
        highPriority=Pattern.compile(highPriorityRegex);

    }
    /*------------------------------------------------------------
    Author:        Dipankar Barman
    Company:       Arxxus.com
    Description:   Returns the configured case record type ids for which keywords are to be scanned
            except Ministreal Correspondance case type if configured on case else returns null

    History
    <Date>      <Authors Name>     <Brief Description of Change>
    ------------------------------------------------------------*/
    public static Set<ID> getScannedRecTypeIds(){
        return scannedRecTypeIds;
    }

    /*------------------------------------------------------------
    Author:        Dipankar Barman
    Company:       Arxxus.com
    Description:   Returns the configured case record origins for which keywords are to be scanned
            except Ministreal Correspondance case type if configured on case else returns null

    History
    <Date>      <Authors Name>     <Brief Description of Change>
    ------------------------------------------------------------*/
    public static Set<String> getScannedOrigins(){
        return scannedOrigins;
    }

    /*------------------------------------------------------------
    Author:        Dipankar Barman
    Company:       Arxxus.com
    Description:   it checks the Input Text and body for key words that are configured as high priority
    Inputs:         The string to check
    History
    <Date>      <Authors Name>     <Brief Description of Change>
    ------------------------------------------------------------*/
    public static Boolean checkMatchesKeyword(String textIn){
        Boolean result=false;
        if (textIn!=null){
            String cleanText= ' ' + textIn.replaceAll('[^a-zA-Z]', ' ').normalizeSpace() + ' ';
            Matcher textMatcher= highPriority.matcher(cleanText);
            if (textMatcher.matches()){
                result= true;

            }else{
                result= false;
            }

        }
        return result;
    }
}