force-app/main/default/objects/Einstein_API_Settings__c/fields/Case_Origin_to_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin_to_Stamp__c</fullName>
    <description>The Case Origin Details values for which Einstein predictions will be stamped on the front-end fields (other Cases will only have back-end fields stamped)</description>
    <inlineHelpText>The Case Origin Details values for which Einstein predictions will be stamped on the front-end fields (other Cases will only have back-end fields stamped)</inlineHelpText>
    <label>Case Origin to Stamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Einstein_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Einstein_Access_Token__c</fullName>
    <description>This is the OAuth2 Access Token to be sued to call the Einstein API. It is refreshed every 24 hours by a scheduled job.</description>
    <inlineHelpText>This is the OAuth2 Access Token to be sued to call the Einstein API. It is refreshed every 24 hours by a scheduled job.</inlineHelpText>
    <label>Einstein Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Einstein_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Einstein_Base_URL__c</fullName>
    <description>This is the base url of the endpoint for the Einstein API</description>
    <inlineHelpText>This is the base url of the endpoint for the Einstein API</inlineHelpText>
    <label>Einstein Base URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Einstein_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Einstein_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if Einstein predictions are enabled</description>
    <inlineHelpText>Indicates if Einstein predictions are enabled</inlineHelpText>
    <label>Einstein Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Einstein_Registration_Email__c.field-meta.xml
<CustomField>
    <fullName>Einstein_Registration_Email__c</fullName>
    <description>This is the email address used when signing up with Einstein. It is required to generate the access token.</description>
    <inlineHelpText>This is the email address used when signing up with Einstein. It is required to generate the access token.</inlineHelpText>
    <label>Einstein Registration Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Issue_Model_Id__c.field-meta.xml
<CustomField>
    <fullName>Issue_Model_Id__c</fullName>
    <description>This is the Einstein Model Id for the Issue. We pass this to the Einstein API to make Issue predictions.</description>
    <inlineHelpText>This is the Einstein Model Id for the Issue. We pass this to the Einstein API to make Issue predictions.</inlineHelpText>
    <label>Issue Model Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Location_Model_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Model_Id__c</fullName>
    <description>This is the Einstein Model Id for the Location. We pass this to the Einstein API to make Taxonomy Location predictions.</description>
    <inlineHelpText>This is the Einstein Model Id for the Location. We pass this to the Einstein API to make Taxonomy Location predictions.</inlineHelpText>
    <label>Location Model Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Max_Records_per_Process__c.field-meta.xml
<CustomField>
    <fullName>Max_Records_per_Process__c</fullName>
    <description>This is the maximum amount of records that will be processed by Einstein in one transaction</description>
    <inlineHelpText>This is the maximum amount of records that will be processed by Einstein in one transaction</inlineHelpText>
    <label>Max Records per Process</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Minimum_Probability_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Probability_Level__c</fullName>
    <description>This is the minimum probability for an Einstein prediction that we will allow before stamping a Case with the predicted values</description>
    <inlineHelpText>This is the minimum probability for an Einstein prediction that we will allow before stamping a Case with the predicted values</inlineHelpText>
    <label>Minimum Probability Level</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/PEM_FileName__c.field-meta.xml
<CustomField>
    <fullName>PEM_FileName__c</fullName>
    <description>This is the name of the PEM file containing the key used to generate the access token.</description>
    <inlineHelpText>This is the name of the PEM file containing the key used to generate the access token.</inlineHelpText>
    <label>PEM FileName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Token_Expiration_Time__c.field-meta.xml
<CustomField>
    <fullName>Token_Expiration_Time__c</fullName>
    <description>The time in milliseconds before the token expires. A scheduled job will update the token every 24 hours so the expiration time will be set ~48 hours to ensure there is always a valid token.</description>
    <inlineHelpText>The time in milliseconds before the token expires. A scheduled job will update the token every 24 hours so the expiration time will be set ~48 hours to ensure there is always a valid token.</inlineHelpText>
    <label>Token Expiration Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Staff_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Staff_Facing__c</fullName>
    <inlineHelpText>Identifies whether this value is available (active) for selection in staff-facing channels</inlineHelpText>
    <label>Status - Staff Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EinsteinAITests.cls
@isTest
global class EinsteinAITests {
    
    private static testMethod void testTokenRefreshSettingsOnly() {
        
    
        Einstein_API_Settings__c settings = new Einstein_API_Settings__c(Einstein_Base_URL__c='http://dummyendpoint', 
                                                                         Einstein_Registration_Email__c='test@test.com', 
                                                                         PEM_FileName__c='einstein-pem', 
                                                                         Token_Expiration_Time__c=200);
        insert settings;                                                                 

        ContentVersion v = new ContentVersion();
        v.versionData = Blob.valueOf('MIIEpAIBAAKCAQEAo0qkzcckbLucWej4OJOeoU42u7HR61yOvhs55UZANTOwGoxNIEiVI30y2iYTP9yM');
        v.title = 'einstein-pem';
        v.pathOnClient ='/somepath.txt';
        insert v;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpSuccess());
        
        Test.StartTest();
        String sch = '0 0 12 * * ?';
        RefreshEinsteinToken rt = new RefreshEinsteinToken();
        System.schedule('Refresh Einstein Token', sch, rt);
        Test.stopTest();
    }
    
    private static testMethod void testTokenRefreshNoData() {
        Test.setMock(HttpCalloutMock.class, new MockHttpSuccess());
        Test.StartTest();
        String sch = '0 0 12 * * ?';
        RefreshEinsteinToken rt = new RefreshEinsteinToken();
        try {
           System.schedule('Refresh Einstein Token', sch, rt);
        }
        catch(Exception e) {}    
        Test.stopTest();
    }
    
    private static testMethod void testTokenRefreshFail() {
        
    
        Einstein_API_Settings__c settings = new Einstein_API_Settings__c(Einstein_Base_URL__c='http://dummyendpoint', 
                                                                         Einstein_Registration_Email__c='test@test.com', 
                                                                         PEM_FileName__c='einstein-pem', 
                                                                         Token_Expiration_Time__c=200);
        insert settings;                                                                 

        ContentVersion v = new ContentVersion();
        v.versionData = Blob.valueOf('MIIEpAIBAAKCAQEAo0qkzcckbLucWej4OJOeoU42u7HR61yOvhs55UZANTOwGoxNIEiVI30y2iYTP9yM');
        v.title = 'einstein-pem';
        v.pathOnClient ='/somepath.txt';
        insert v;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpSuccess());
        ContentVersion base64Content = [SELECT Title, VersionData FROM ContentVersion where Title=:settings.PEM_FileName__c ORDER BY Title limit 1];
        String keyContents = base64Content.VersionData.tostring();
        JWT jwt = new JWT('RS256');
        jwt.pkcs8 = keyContents;
        jwt.iss = 'developer.force.com';
        jwt.sub = settings.Einstein_Registration_Email__c;
        jwt.aud = 'FAIL';
        jwt.validFor = integer.valueOf(settings.Token_Expiration_Time__c);
        
        Test.StartTest();
        String access_token = JWTBearerFlow.getAccessToken('FAIL', jwt);
        Test.stopTest();
    }
    
    private static testMethod void testEinsteinTrigger() {
        Einstein_API_Settings__c settings = new Einstein_API_Settings__c(Einstein_Base_URL__c='http://dummyendpoint', 
                                                                         Case_Origin_to_Stamp__c='DFSI',
                                                                         Einstein_Access_Token__c='testToken',
                                                                         Einstein_Enabled__c=true,
                                                                         Issue_Model_Id__c='qwerty12345',
                                                                         Location_Model_Id__c='qwerty12345',
                                                                         Max_Records_per_Process__c=10,
                                                                         Minimum_Probability_Level__c=10);
        insert settings;
        
        Taxonomy_Metadata__c tm = new Taxonomy_Metadata__c(Name='Test', Status_Staff_Facing__c='Active');
        insert tm;
        
        Case testCase = new Case (Subject='Text Case',
                                  Description='A test description',
                                  Origin_Details__c='DFSI');
                                                          
        insert testCase;                      
    }
    
    private static testMethod void testEinsteinEngineFail() {
        
     	EinsteinPredictionEngine einsteinPrediction = new EinsteinPredictionEngine('testToken', 'http://dummyendpoint');
     	
     	Map<String, Decimal> einsteinLocationPredictionMap = einsteinPrediction.getPredictionLabelAndProbability('FAIL',
     	                          'dummy_Model_Id', '/language/intent', 1);                      
    }
    
    //When running specific tests, code coverage for CaseTriggerDispatcher is 74%
    //This method runs the bypass trigger code to get the coverage to 75%
    private static testMethod void testCaseTrigger(){
    	User invoker=[select Id, Bypass_Triggers__c from User where Id=:UserInfo.getUserId() limit 1];
    	invoker.Bypass_Triggers__c = 'Case';
    	update invoker;
    	
    	Test.startTest();
    	Case testCase = new Case (Subject='Text Case',
                                  Description='A test description',
                                  Origin_Details__c='DFSI');
                                                          
        insert testCase;
        Test.stopTest();
    }
    
global class MockHttpSuccess implements HttpCalloutMock {
     // Implement this interface method
    global HTTPResponse respond(HTTPRequest req) {
         // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"access_token":"test"}');
        res.setStatusCode(200);
        return res;
    }
}

global class MockHttpFailure implements HttpCalloutMock {
     // Implement this interface method
    global HTTPResponse respond(HTTPRequest req) {
         // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('');
        res.setStatusCode(400);
        return res;
    }
}
}