force-app/main/default/objects/Einstein_API_Settings__c/fields/Einstein_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Einstein_Access_Token__c</fullName>
    <description>This is the OAuth2 Access Token to be sued to call the Einstein API. It is refreshed every 24 hours by a scheduled job.</description>
    <inlineHelpText>This is the OAuth2 Access Token to be sued to call the Einstein API. It is refreshed every 24 hours by a scheduled job.</inlineHelpText>
    <label>Einstein Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Einstein_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Einstein_Base_URL__c</fullName>
    <description>This is the base url of the endpoint for the Einstein API</description>
    <inlineHelpText>This is the base url of the endpoint for the Einstein API</inlineHelpText>
    <label>Einstein Base URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Einstein_Registration_Email__c.field-meta.xml
<CustomField>
    <fullName>Einstein_Registration_Email__c</fullName>
    <description>This is the email address used when signing up with Einstein. It is required to generate the access token.</description>
    <inlineHelpText>This is the email address used when signing up with Einstein. It is required to generate the access token.</inlineHelpText>
    <label>Einstein Registration Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/PEM_FileName__c.field-meta.xml
<CustomField>
    <fullName>PEM_FileName__c</fullName>
    <description>This is the name of the PEM file containing the key used to generate the access token.</description>
    <inlineHelpText>This is the name of the PEM file containing the key used to generate the access token.</inlineHelpText>
    <label>PEM FileName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Einstein_API_Settings__c/fields/Token_Expiration_Time__c.field-meta.xml
<CustomField>
    <fullName>Token_Expiration_Time__c</fullName>
    <description>The time in milliseconds before the token expires. A scheduled job will update the token every 24 hours so the expiration time will be set ~48 hours to ensure there is always a valid token.</description>
    <inlineHelpText>The time in milliseconds before the token expires. A scheduled job will update the token every 24 hours so the expiration time will be set ~48 hours to ensure there is always a valid token.</inlineHelpText>
    <label>Token Expiration Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RefreshEinsteinToken.cls
/**
Overview:       This class refreshes the Access Token used by the Einstein API when it makes callouts to retrieve predictions from
                the Einstein model.
                It will be initially scheduled to run every 24 hours.
Created Date :  20/Feb/2018
Created By:     Ian Fitzgerald, TNSW Salesforce Practice
 */
global class RefreshEinsteinToken implements Schedulable {

	   global void execute(SchedulableContext SC) {
           refreshToken();
	   }
	   
	   @future(callout=true)	
	   static public void refreshToken(){
	   	   try{
	   	       //Retrieve the Custom Metadata Type Settings
    	       Einstein_API_Settings__c settings = [SELECT Einstein_Base_URL__c, Einstein_Registration_Email__c, PEM_FileName__c, Token_Expiration_Time__c
	                                                FROM Einstein_API_Settings__c  limit 1];
	                                                    
	           String AUTH = settings.Einstein_Base_URL__c+'/oauth2/token';
	       
	           //Create the JWT                                             
    	       JWT jwt = new JWT('RS256');
           
               //Read the Key from the PEM file
               ContentVersion base64Content = [SELECT Title, VersionData FROM ContentVersion where Title=:settings.PEM_FileName__c ORDER BY Title limit 1];
               String keyContents = base64Content.VersionData.tostring();
               keyContents = keyContents.replace('-----BEGIN RSA PRIVATE KEY-----', '');
               keyContents = keyContents.replace('-----END RSA PRIVATE KEY-----', '');
               keyContents = keyContents.replace('\n', '');
               jwt.pkcs8 = keyContents;
               
                   jwt.iss = 'developer.force.com';
               jwt.sub = settings.Einstein_Registration_Email__c;
               jwt.aud = AUTH;
               jwt.validFor = integer.valueOf(settings.Token_Expiration_Time__c);
               String access_token = JWTBearerFlow.getAccessToken(AUTH, jwt);
               if (access_token==null || access_token.length()==0){
               	   System.debug('RefreshEinsteinToken : JWTBearerFlow did not return an Access Token');
    		
                   List<ApplicationLogMessage> messages = new List<ApplicationLogMessage>();

                   ApplicationLogMessage message = new ApplicationLogMessage();
                   message.source = 'RefreshEinsteinToken';
                   message.sourceFunction = 'refreshToken';
                   message.logMessage = 'JWTBearerFlow did not return an Access Token';
                   message.debugLevel = GlobalConstants.ERROR;
                   messages.add(message);
                   ApplicationLogUtility.logMessage(messages);
                   messages.clear();
               }
               else{
                   settings.Einstein_Access_Token__c  = access_token;
           
                   update settings;
               }
	   	   }
    	catch(Exception e){
    		System.debug(e);
    		
            List<ApplicationLogMessage> messages = new List<ApplicationLogMessage>();

            ApplicationLogMessage message = new ApplicationLogMessage();
            message.source = 'RefreshEinsteinToken';
            message.sourceFunction = 'refreshToken';
            message.logMessage = e.getMessage();
            message.ex = e;
            message.debugLevel = GlobalConstants.ERROR;
            messages.add(message);
            
            ApplicationLogUtility.logMessage(messages);
            messages.clear();
            //THROW_EXCEPTIONS is a global constant, it is set to the current user's "Throw Exceptions" value 
            //"Throw Exceptions" is a checkbox on the User record. 
            if (GlobalConstants.THROW_EXCEPTIONS){
                Throw(e);
            }
    	}
	   }
	   
}