force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Keywords__c/Keywords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configured words with their priority, on occurrence of which in either body or subject will lead to the case being elevated to corresponding priority</description>
    <label>Keywords</label>
</CustomObject>

force-app/main/default/objects/Keywords__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>&quot;High&quot;</defaultValue>
    <description>Priority of the case in which the corresponding keyword is found</description>
    <inlineHelpText>Priority of the case in which the corresponding keyword is found</inlineHelpText>
    <label>Priority</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventTriggerDispatcherTest.cls
@isTest
private class EventTriggerDispatcherTest
{	static RecordType HOUSEHOLD;
	static RecordType CUSTOMER;
	static RecordType ORGANIZATION;
	private static void createKeyWordSettings(){
		List<Keywords__c> adviceSubjects= new List<Keywords__c>();
		adviceSubjects.add(new Keywords__c(Name='injured',Priority__c=GlobalConstants.CASE_PRIORITY_HIGH));
		adviceSubjects.add(new Keywords__c(Name='blood',Priority__c=GlobalConstants.CASE_PRIORITY_HIGH));
		adviceSubjects.add(new Keywords__c(Name='hospital',Priority__c=GlobalConstants.CASE_PRIORITY_HIGH));

		insert adviceSubjects;
	}
	
	static void setup(){
		//insert the recordtypes and set them 
		HOUSEHOLD = [SELECT ID FROM RecordType WHERE sObjectType = 'Account' AND DeveloperName = 'household'];
		CUSTOMER = [SELECT ID FROM RecordType WHERE sObjectType = 'Contact' AND DeveloperName = 'Customer'];
		ORGANIZATION= [SELECT ID FROM RecordType WHERE sObjectType = 'Account' AND DeveloperName != 'household' limit 1];
	}
	private static Event getTestEvent(){
		setup();
		Account existingAccount=new Account(
				Name='preexisting',
				RecordTypeId=ORGANIZATION.Id
			);
		insert existingAccount;
		Contact cont= new Contact(
				FirstName='AB',
				LastName='Normal',
				RecordTypeId=CUSTOMER.Id,
				AccountId=existingAccount.Id
			);
		
		insert cont;
		createKeyWordSettings();
		String pattern= '%'+GlobalConstants.MIN_CORRO_RECTYPE_NAME+'%';
		List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName Like :pattern];
		RecordType MINCORRO = caseTypes.size()==0?null:caseTypes[0];
		Case minCase=new Case(Subject='I was Injured because of the sharp metal jutting out ',
								Description='I was Injured because of the sharp metal jutting out ',
								RecordTypeId=MINCORRO.Id,
								Status='New',
								Origin='Web',
								Priority='Normal');
		insert minCase;
		return  new Event(
            OwnerId = UserInfo.getUserId(),
            WhatId = minCase.Id,
            StartDateTime = System.today(),
            EndDateTime = System.today()+1,
            Subject = 'Go Live'

        );
		 
	}
		

	@isTest
	static void itShould()
	{
		Event testEvent;
		User nonAdmin=[select Id,ProfileId from User where Profile.Name != 'System Administrator' And Profile.Name != 'TfNSW Operator Portal User' And isActive = true limit 1];
		system.runAs(nonAdmin){
			testEvent=getTestEvent();
			insert testEvent;
			Event obtained=[select id from Event where Id =:testEvent.Id];
			system.assertNotEquals(null,obtained);

			try{
				delete obtained;
			}catch(Exception e){
				Event obtained2=[select id from Event where Id =:testEvent.Id];
				system.assertNotEquals(null,obtained2);

			}
			

		}
		delete testEvent;
		List<Event> obtained3=[select id from event where Id =:testEvent.Id];
		system.assertEquals(0,obtained3.size());
		

		

	}
	@isTest
	static void deleteErrorEventBeforeDeleteTriggerHandler()
	{

		ApplicationLog_Test.setLoggingSettings();
		EventBeforeDeleteTriggerHandler deleter= new EventBeforeDeleteTriggerHandler();
		User nonAdmin=[select Id,ProfileId from User where Profile.Name != 'System Administrator' And Profile.Name != 'TfNSW Operator Portal User' and isActive = true limit 1];
		
		system.runAs(nonAdmin){
			deleter.mainEntry(null);
		}
		List<Application_Log__c> eventErrorLogs= [select Id ,Debug_Level__c from Application_Log__c ];
		system.assertEquals(GlobalConstants.ERROR,eventErrorLogs[0].Debug_Level__c);

	}
}