force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Conga_Response_PDF_Generated__c.field-meta.xml
<CustomField>
    <fullName>Conga_Response_PDF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for code purpose to track if PDF is generated for the current Response WordML document.</description>
    <inlineHelpText>This field is used for code purpose to track if PDF is generated for the current Response WordML document.</inlineHelpText>
    <label>Conga Response PDF Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <inlineHelpText>This allows user to mark security disposition of the record. Default is &quot;Standard&quot;</inlineHelpText>
    <label>Privacy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW NOTE</description>
    <label>Note</label>
</RecordType>

force-app/main/default/classes/NoteOrAttachmentTriggerDispatcher_Test.cls
@isTest
public class NoteOrAttachmentTriggerDispatcher_Test{

    static testMethod void insertPrivateNotesTest() {
        Case caseRecord = getCaseRecord();
        insert caseRecord;
        
        Test.startTest();
            NoteOrAttachment__c pn1 = getNoteOrAttachment('Private Note 1', caseRecord.Id);
            NoteOrAttachment__c pn2 = getNoteOrAttachment('Private Note 2', caseRecord.Id);
            insert new list <NoteOrAttachment__c> { pn1, pn2};
        Test.stopTest();
        
        Case updatedCaseRecord = [Select Id,Private_Notes_Count__c From Case Where Id =: caseRecord.Id];
        system.assertEquals(2, updatedCaseRecord.Private_Notes_Count__c);
        
    }
    
    static testMethod void updatePrivateNotesTest() {
        
        Case caseRecord = getCaseRecord();
        insert caseRecord;
        
        Case caseRecord1 = getCaseRecord();
        insert caseRecord1;
        
        Test.startTest();
            NoteOrAttachment__c pn1 = getNoteOrAttachment('Private Note 1', caseRecord.Id);
            NoteOrAttachment__c pn2 = getNoteOrAttachment('Private Note 2', caseRecord.Id);
            
            insert new list <NoteOrAttachment__c> {pn1, pn2};
            
            NoteOrAttachment__c thunderHeadDummyResponseDraft = getNoteOrAttachment('response_dummy Thunderhead Response Draft', caseRecord.Id);
            insert thunderHeadDummyResponseDraft;
            
            Attachment attach = new Attachment();    
            attach.Name = 'Dummy Thunderhead Response Draft WordML';
            Blob bodyBlob = Blob.valueOf('Dummy Thunderhead Response Draft WordML');
            attach.body = bodyBlob;
            attach.parentId = thunderHeadDummyResponseDraft.id;
            insert attach;
            
            thunderHeadDummyResponseDraft.Attachment__c = attach.Id;
            thunderHeadDummyResponseDraft.ContentType__c = 'application/msword';
            update thunderHeadDummyResponseDraft;
            
            pn2.Case__c = caseRecord1.Id; //reparenting the private note
            update pn2; 
        Test.stopTest();
        
        Case updatedCaseRecord = [Select Id,Private_Notes_Count__c From Case Where Id =: caseRecord.Id];
        system.assertEquals(2, updatedCaseRecord.Private_Notes_Count__c);
        
        Case updatedCaseRecord1 = [Select Id,Private_Notes_Count__c From Case Where Id =: caseRecord1.Id];
        system.assertEquals(1, updatedCaseRecord1.Private_Notes_Count__c);
        
        thunderHeadDummyResponseDraft = [SELECT Conga_Response_PDF_Generated__c FROM NoteOrAttachment__c WHERE Id = :thunderHeadDummyResponseDraft.Id];
        System.assertEquals(TRUE, thunderHeadDummyResponseDraft.Conga_Response_PDF_Generated__c);
    }
    
    //Exception handling test for NoteOrAttAfterUpdateTriggerHandler
    @isTest
    static void exceptionHandlingTest() {
   
     NoteOrAttAfterUpdateTriggerHandler tempAftrUpdateHandler = new NoteOrAttAfterUpdateTriggerHandler();
     tempAftrUpdateHandler.mainEntry(NULL);
     System.assertEquals(TRUE, tempAftrUpdateHandler.exceptionInvoked);
     
     NoteOrAttBeforeUpdateTriggerHandler tempBeforeUpdateHandler = new NoteOrAttBeforeUpdateTriggerHandler();
     tempBeforeUpdateHandler.mainEntry(NULL);
     System.assertEquals(TRUE, tempBeforeUpdateHandler.exceptionInvoked);
    }
 
    static testMethod void deletePrivateNotesTest() {
        Case caseRecord = getCaseRecord();
        insert caseRecord;
        
        Test.startTest();
            NoteOrAttachment__c pn1 = getNoteOrAttachment('Private Note 1', caseRecord.Id);
            NoteOrAttachment__c pn2 = getNoteOrAttachment('Private Note 2', caseRecord.Id);
            insert new list <NoteOrAttachment__c> { pn1, pn2};
        Test.stopTest();
        
        delete pn1;
        
        Case updatedCaseRecord = [Select Id,Private_Notes_Count__c From Case Where Id =: caseRecord.Id];
        system.assertEquals(1, updatedCaseRecord.Private_Notes_Count__c);
    }
    
    static testMethod void undeletePrivateNotesTest() {
        Case caseRecord = getCaseRecord();
        insert caseRecord;
        NoteOrAttachment__c pn1 = getNoteOrAttachment('Private Note 1', caseRecord.Id);
        NoteOrAttachment__c pn2 = getNoteOrAttachment('Private Note 2', caseRecord.Id);
        insert new list <NoteOrAttachment__c> { pn1, pn2};
        delete pn1;
        Test.startTest();
            Case updatedCaseRecord = [Select Id,Private_Notes_Count__c From Case Where Id =: caseRecord.Id];
            system.assertEquals(1, updatedCaseRecord.Private_Notes_Count__c);
        Test.stopTest();
        
        undelete pn1;
        updatedCaseRecord = [Select Id,Private_Notes_Count__c From Case Where Id =: caseRecord.Id];
        system.assertEquals(2, updatedCaseRecord.Private_Notes_Count__c);
    }
    
    static testMethod void bulkInsertTest() {
        Case caseRecord = getCaseRecord();
        insert caseRecord;
        
        Test.startTest();
            list <NoteOrAttachment__c> pNotes = new list <NoteOrAttachment__c> ();
            for(Integer i = 0; i < 100; i++) {
                NoteOrAttachment__c pn1 = getNoteOrAttachment('Private Note ' + i , caseRecord.Id);
                pNotes.add(pn1);
            }
            insert pNotes; 
        Test.stopTest();
        
        Case updatedCaseRecord = [Select Id,Private_Notes_Count__c From Case Where Id =: caseRecord.Id];
        system.assertEquals(100, updatedCaseRecord.Private_Notes_Count__c);
    
    }
    
    static testMethod void errorTest() {
        ApplicationLog_Test.setLoggingSettings();
        
        NoteOrAttBeforeInsertTriggerHandler handler = new NoteOrAttBeforeInsertTriggerHandler();
        handler.mainEntry(null);
        
        NoteOrAttAfterDeleteTriggerHandler handler1 = new NoteOrAttAfterDeleteTriggerHandler();
        handler1.mainEntry(null);
        
        NoteOrAttAfterInsertTriggerHandler handler2 = new NoteOrAttAfterInsertTriggerHandler();
        handler2.mainEntry(null);
        
        NoteOrAttAfterUndeleteTriggerHandler handler3 = new NoteOrAttAfterUndeleteTriggerHandler();
        handler3.mainEntry(null);
        
        NoteOrAttAfterUpdateTriggerHandler handler4 = new NoteOrAttAfterUpdateTriggerHandler();
        handler4.mainEntry(null);
        
        Test.startTest();
        List<Application_Log__c> caseTriggerLogs= [select Id ,Debug_Level__c from Application_Log__c ];
        system.assertEquals(GlobalConstants.ERROR,caseTriggerLogs[0].Debug_Level__c);
        Test.stopTest();
        
    }
    /*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   This method creates a case record sobject
    Inputs:        
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    20/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/
    public static Case getCaseRecord() {
        return new Case(Subject = 'Pothole',
                        Description = 'Theres a pothole in the east street, west end crossing in front of busstop',
                        Status = 'New',
                        Agency__c = 'Agency1',
                        Priority = 'Normal');
    }
    
    /*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   This method creates a private note record
    Inputs:        
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    20/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/
    public static NoteOrAttachment__c getNoteOrAttachment(String title, Id caseId) {
        return new NoteOrAttachment__c(Name = title,
                                       Body__c = 'Sample Body of ' + title,
                                       Case__c = caseId,
                                       Privacy__c = 'Restricted');
    }
}