force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerDispatcher_Test.cls
@isTest
private class ContactTriggerDispatcher_Test
{	
	static RecordType HOUSEHOLD;
	static RecordType CUSTOMER;
	static RecordType ORGANIZATION;

	static void setup(){
		//insert the recordtypes and set them 
		HOUSEHOLD = [SELECT ID FROM RecordType WHERE sObjectType = 'Account' AND DeveloperName = 'household'];
		CUSTOMER = [SELECT ID FROM RecordType WHERE sObjectType = 'Contact' AND DeveloperName = 'Customer'];
		ORGANIZATION= [SELECT ID FROM RecordType WHERE sObjectType = 'Account' AND DeveloperName != 'household' limit 1];
	}
	@isTest
	static void deletingContactOrganizationAccountUnScathed()
	{
		setup();
		Account existingAccount=new Account(
				Name='preexisting',
				RecordTypeId=ORGANIZATION.Id
			);
		insert existingAccount;
		Contact cont= new Contact(
				FirstName='AB',
				LastName='Normal',
				RecordTypeId=CUSTOMER.Id,
				AccountId=existingAccount.Id
			);
		
		insert cont;
		Test.startTest();
		delete cont;
		Test.stopTest();
		List<Account> correspondingAccounts=[select Id, Name,recordTypeId from Account];
		system.assertEquals(correspondingAccounts.size(),1);


	}
	@isTest
	static void createAccountOnInsertContact()
	{
		setup();

		Contact cont= new Contact(
				FirstName='AB',
				LastName='Normal',
				RecordTypeId=CUSTOMER.Id
			);
		Test.startTest();
		insert cont;
		Test.stopTest();
		Account correspondingAccount=[select Id, Name,recordTypeId from Account where Primary_Contact_Id__c=:cont.Id];
		system.assertNotEquals(correspondingAccount,null);
		system.assertEquals(correspondingAccount.Name,'AB Normal Account');

	}

	@isTest
	static void updateAccountNameOnUpdateContact()
	{
		setup();

		Contact cont= new Contact(
				FirstName='AB',
				LastName='Normal',
				RecordTypeId=CUSTOMER.Id
				
			);
		
		insert cont;
		Test.startTest();
		cont.FirstName='Perfectly';
		update cont;
		Test.stopTest();
		Account correspondingAccount=[select Id, Name,recordTypeId from Account where Primary_Contact_Id__c=:cont.Id];
		system.assertEquals(correspondingAccount.Name,'Perfectly Normal Account');
	}
	@isTest
	static void deletingContactDeletesAccount()
	{
		setup();

		Contact cont= new Contact(
				FirstName='AB',
				LastName='Normal',
				RecordTypeId=CUSTOMER.Id
			);
		
		insert cont;
		Test.startTest();
		delete cont;
		Test.stopTest();
		List<Account> correspondingAccounts=[select Id, Name,recordTypeId from Account];
		system.assertEquals(correspondingAccounts.size(),0);

	}
	@isTest
	static void creatingContactWithAccountCreatesNoAccount()
	{
		setup();
		Account existingAccount=new Account(
				Name='preexisting'
			);
		insert existingAccount;
		Contact cont= new Contact(
				FirstName='AB',
				LastName='Normal',
				AccountId=existingAccount.Id,
				RecordTypeId=CUSTOMER.Id
			);
		Test.startTest();
		insert cont;

		
		Test.stopTest();
		List<Account> correspondingAccounts=[select Id, Name,recordTypeId from Account where Name!='preexisting'];
		system.assertEquals(correspondingAccounts.size(),0);

	}
	@isTest
	static void insert101householdContacts()
	{
		setup();
		List<Contact> contacts=new List<Contact>();
		for(integer ii=0; ii<100;ii++){
			contacts.add(new Contact(
				FirstName='AB'+ii,
				LastName='Normal',
				RecordTypeId=CUSTOMER.Id
			));
		}
		
		Test.startTest();
		insert contacts;
		Test.stopTest();
		List<Account> correspondingAccounts=[select Id, Name,recordTypeId from Account];
		system.assertEquals(correspondingAccounts.size(),100);

	}

	@isTest
	static void insert101householdContactsBypassTrigger()
	{
		setup();
		User invoker=[select Id, Bypass_Triggers__c from User where Id=:UserInfo.getUserId()];
		invoker.Bypass_Triggers__c='Contact';
		update invoker;
		List<Contact> contacts=new List<Contact>();
		for(integer ii=0; ii<100;ii++){
			contacts.add(new Contact(
				FirstName='AB'+ii,
				LastName='Normal',
				RecordTypeId=CUSTOMER.Id
			));
		}
		
		Test.startTest();
		insert contacts;
		Test.stopTest();
		List<Account> correspondingAccounts=[select Id, Name,recordTypeId from Account];
		system.assertEquals(correspondingAccounts.size(),0);

	}
	@isTest
	static void updateErrorIfTriggerParameterNotProper()
	{

		ApplicationLog_Test.setLoggingSettings();
		ContactBeforeUpdateTriggerHandler updater= new ContactBeforeUpdateTriggerHandler();
		
		updater.mainEntry(null);
		List<Application_Log__c> caseTriggerLogs= [select Id ,Debug_Level__c from Application_Log__c ];
		system.assertEquals(GlobalConstants.ERROR,caseTriggerLogs[0].Debug_Level__c);

	}
	@isTest
	static void insertErrorIfTriggerParameterNotProper()
	{

		ApplicationLog_Test.setLoggingSettings();

		ContactAfterInsertTriggerHandler inserter= new ContactAfterInsertTriggerHandler();
		inserter.mainEntry(null);
		List<Application_Log__c> caseTriggerLogs= [select Id ,Debug_Level__c from Application_Log__c ];
		system.assertEquals(GlobalConstants.ERROR,caseTriggerLogs[0].Debug_Level__c);

	}
	@isTest
	static void deleteErrorIfTriggerParameterNotProper()
	{

		ApplicationLog_Test.setLoggingSettings();
		ContactAfterDeleteTriggerHandler updater= new ContactAfterDeleteTriggerHandler();
		
		updater.mainEntry(null);
		List<Application_Log__c> caseTriggerLogs= [select Id ,Debug_Level__c from Application_Log__c ];
		system.assertEquals(GlobalConstants.ERROR,caseTriggerLogs[0].Debug_Level__c);

	}

}