force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <inlineHelpText>This allows user to mark security disposition of the record. Default is &quot;Standard&quot;</inlineHelpText>
    <label>Privacy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/classes/NoteOrAttachmentOwnershipUpdater_Test.cls
@isTest
private class NoteOrAttachmentOwnershipUpdater_Test {
	
	@testSetup
	static void setUpUser() {
		User testUser = RetrieveNextUtils_WS_Test.createTestUser('System Administrator', 'STA');
	}


	@isTest static void ownershipChangedToUser() {
		User newOwner = [Select Id From User Where Email = 'md@demo.com' limit 1];
		Case parent = new Case(Subject = 'parent',
                        		Description = 'Theres a parent in the east street, west end crossing in front of busstop',
                        		Status = 'New',
                        		Agency__c = GlobalConstants.STA_AGENCY,
                        		Modes__c= GlobalConstants.MULTI_ISSUE_TYPE);

        System.runAs(new User(Id=UserInfo.getUserId())){
            insert parent;
        }

        NoteOrAttachment__c att1 = new NoteOrAttachment__c(Name = 'Restricted Attachment',
					                                        Case__c = parent.Id,
					                                        Privacy__c = GlobalConstants.NOTEORATTACHMENT_PRIVACY_RESTRICTED);

        NoteOrAttachment__c att2 = new NoteOrAttachment__c(Name = 'Standard Attachment',
					                                        Case__c = parent.Id,
					                                        Privacy__c = GlobalConstants.NOTEORATTACHMENT_PRIVACY_STANDARD);

        System.runAs(new User(Id=UserInfo.getUserId())){
        	insert new list <NoteOrAttachment__c> {att1, att2};
    	}

    	Test.startTest();
    		Case c = [Select Id, OwnerId From Case Where Id =: parent.Id limit 1];
    		c.OwnerId = newOwner.Id;
    		update c;

    		list <NoteOrAttachment__c> updatedAtts = [Select Id,OwnerId From NoteOrAttachment__c];
    		System.assertEquals(2, updatedAtts.size());
    	Test.stopTest();
	}
	
	@isTest static void ownershipChangedToQueue() {
		Group q = [Select Id From Group Where Type = 'Queue' And DeveloperName =: GlobalConstants.MAGS_OFFICER_QUEUE_API_NAME limit 1];

		Case parent = new Case(Subject = 'parent',
                        		Description = 'Theres a parent in the east street, west end crossing in front of busstop',
                        		Status = 'New',
                        		Agency__c = GlobalConstants.STA_AGENCY,
                        		Modes__c= GlobalConstants.MULTI_ISSUE_TYPE);

        System.runAs(new User(Id=UserInfo.getUserId())){
            insert parent;
        }

        NoteOrAttachment__c att1 = new NoteOrAttachment__c(Name = 'Restricted Attachment',
					                                        Case__c = parent.Id,
					                                        Privacy__c = GlobalConstants.NOTEORATTACHMENT_PRIVACY_RESTRICTED);

        NoteOrAttachment__c att2 = new NoteOrAttachment__c(Name = 'Standard Attachment',
					                                        Case__c = parent.Id,
					                                        Privacy__c = GlobalConstants.NOTEORATTACHMENT_PRIVACY_STANDARD);

        System.runAs(new User(Id=UserInfo.getUserId())){
        	insert new list <NoteOrAttachment__c> {att1, att2};
    	}

    	Test.startTest();
    		Case c = [Select Id, OwnerId From Case Where Id =: parent.Id limit 1];
    		c.OwnerId = q.Id;
    		update c;

    		list <NoteOrAttachment__c> updatedAtts = [Select Id,OwnerId From NoteOrAttachment__c];
    		System.assertEquals(2, updatedAtts.size());
    	Test.stopTest();
	}
	
	@isTest static void errorHandling() {
		NoteOrAttachmentOwnershipUpdater handler = new NoteOrAttachmentOwnershipUpdater();
		handler.updateOwnership(null);

		list <Application_Log__c> logs = [Select Id From Application_Log__c];
		system.assert(logs != null);
	}
}