force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>The originating class (e.g. CustomerManagement)</description>
    <inlineHelpText>The originating class (e.g. CustomerManagement)</inlineHelpText>
    <label>Source</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseFilterSetting__c/CaseFilterSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Case Keyword Filter Setting</label>
</CustomObject>

force-app/main/default/objects/CaseFilterSetting__c/fields/origin__c.field-meta.xml
<CustomField>
    <fullName>origin__c</fullName>
    <description>Comma separated list of Case Origins</description>
    <inlineHelpText>Comma separated list of Case Origins</inlineHelpText>
    <label>Case Origins</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseFilterSetting__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <description>Comma separated list of Record Type API names for which keywords are to be scanned</description>
    <inlineHelpText>Comma separated list of Record Type API names for which keywords are to be scanned</inlineHelpText>
    <label>Case Record Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Keywords__c/Keywords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configured words with their priority, on occurrence of which in either body or subject will lead to the case being elevated to corresponding priority</description>
    <label>Keywords</label>
</CustomObject>

force-app/main/default/objects/Keywords__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>&quot;High&quot;</defaultValue>
    <description>Priority of the case in which the corresponding keyword is found</description>
    <inlineHelpText>Priority of the case in which the corresponding keyword is found</inlineHelpText>
    <label>Priority</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QueueVsAgency__c/QueueVsAgency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores mapping of all queue name v/s agency. division, branch</description>
    <label>QueueVsAgency</label>
</CustomObject>

force-app/main/default/objects/QueueVsAgency__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueVsAgency__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QueueVsAgency__c/fields/QueueName__c.field-meta.xml
<CustomField>
    <fullName>QueueName__c</fullName>
    <label>Queue Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReopenDuration__c/ReopenDuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>case reopen duration per agency in days since case closure</description>
    <label>Reopen Duration Per Agency</label>
</CustomObject>

force-app/main/default/objects/ReopenDuration__c/fields/duration__c.field-meta.xml
<CustomField>
    <fullName>duration__c</fullName>
    <description>Reopening within this Duration Since Closure is allowed</description>
    <label>Duration</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTriggerDispatcher_Test.cls
@isTest
private class CaseTriggerDispatcher_Test {
	
   private static void createKeyWordSettings() {
        List<Keywords__c> adviceSubjects= new List<Keywords__c>();
        adviceSubjects.add(new Keywords__c(Name='injured',Priority__c=GlobalConstants.CASE_PRIORITY_HIGH));
        adviceSubjects.add(new Keywords__c(Name='blood',Priority__c=GlobalConstants.CASE_PRIORITY_HIGH));
        adviceSubjects.add(new Keywords__c(Name='hospital',Priority__c=GlobalConstants.CASE_PRIORITY_HIGH));
        insert adviceSubjects;
    }

    @isTest
    static void shouldNotMatchIfBodyContainsKeywordButNoSettings(){
        insert new CaseFilterSetting__c(Name='default',origin__c='Web',RecordType__c='Bus');
        System.Assert(CasePriorityUtility.checkMatchesKeyword('I was injured because of the sharp metal jutting out ')==false);

    }

    @isTest
    static void shouldMatchIfBodyContainsKeywordDifferentCase(){
        insert new CaseFilterSetting__c(Name='default',origin__c='Web',RecordType__c='Bus');
        createKeyWordSettings();
        System.Assert(CasePriorityUtility.checkMatchesKeyword('I was Injured because of the sharp metal jutting out ')==true);

    }

    @isTest
    static void newCaseShouldNotChangePriorityBecauseMinCorroRecType(){

        createKeyWordSettings();
        String pattern= '%'+GlobalConstants.MIN_CORRO_RECTYPE_NAME+'%';
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName Like :pattern];
        RecordType MINCORRO = caseTypes.size()==0?null:caseTypes[0];
        Case minCase=new Case(Subject='I was Injured because of the sharp metal jutting out ',
                                Description='I was Injured because of the sharp metal jutting out ',
                                RecordTypeId=MINCORRO.Id,
                                Status='New',
                                Origin='Web',
                                Priority='Normal');
        Test.startTest();
        insert minCase;
        Test.stopTest();
        minCase=[select Id,Priority from Case where Id=: minCase.Id];
        system.assert('Normal'==minCase.Priority);
    }

    @isTest
    static void newCaseShouldNotChangePriorityBecauseCaseOriginNotWeb(){

        createKeyWordSettings();
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
        RecordType BUS = caseTypes.size()==0?null:caseTypes[0];
        Case busCase=new Case(Subject='I was Injured because of the sharp metal jutting out ',
                                Description='I was Injured because of the sharp metal jutting out ',
                                RecordTypeId=BUS.Id,
                                Status='New',
                                Origin='Email',
                                Priority='Normal');
        Test.startTest();
        insert busCase;
        busCase=[select Id,Priority from Case where Id=: busCase.Id];
        system.assert('High'==busCase.Priority);
        Test.stopTest();
        
    }

    @isTest
    static void newCaseShouldNotChangeBecauseAlreadyHighCasePriority(){
        createKeyWordSettings();
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
        RecordType BUS = caseTypes.size()==0?null:caseTypes[0];
        Case busCase=new Case(Subject='I was Injured because of the sharp metal jutting out ',
                                Description='I was Injured because of the sharp metal jutting out ',
                                RecordTypeId=BUS.Id,
                                Status='New',
                                Origin='Web',
                                Priority=GlobalConstants.CASE_PRIORITY_HIGH);
        Test.startTest();
        insert busCase;
        Test.stopTest();
        List<Application_Log__c> caseTriggerLogs= [select Id from Application_Log__c where Source__c='CaseBeforeInsertTriggerHandler'];
        system.assertEquals(0, caseTriggerLogs.size());
    }

    @isTest
    static void newCaseShouldMarkHighPriorityIfBodyContainsKeywordDifferentCase() {

        createKeyWordSettings();
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
        RecordType BUS = caseTypes.size()==0?null:caseTypes[0];
        system.debug('case record type - '+BUS);
        Case busCase=new Case(Subject='I was Injured because of the sharp metal jutting out ',
                                Description='I was stopped because of the sharp metal jutting out ',
                                RecordTypeId=BUS.Id,
                                Status='New',
                                Origin='Web',
                                Priority='Normal');
        insert new CaseFilterSetting__c(Name='default',origin__c='Web',RecordType__c='Bus');
        Test.startTest();
        insert busCase;
        Test.stopTest();
        busCase=[select Id,Priority from Case where Id=: busCase.Id];
       
    }

    @isTest
    static void oldCaseUpdatedSubjectItShouldMarkHighPriorityIfBodyContainsKeywordDifferentCase() {

        createKeyWordSettings();
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
        RecordType BUS = caseTypes.size()==0?null:caseTypes[0];
        system.debug('case record type - '+BUS);
        Case busCase=new Case(Subject='I was stopped because of the sharp metal jutting out ',
                                Description='I was stopped because of the sharp metal jutting out ',
                                RecordTypeId=BUS.Id,
                                Status='New',
                                Origin='Web',
                                Priority='Normal');
        insert new CaseFilterSetting__c(Name='default',origin__c='Web',RecordType__c='Bus');

        insert busCase;

        Test.startTest();
        busCase.Subject ='I was Injured because of the sharp metal jutting out ';
        update busCase;
        Test.stopTest();
        busCase=[select Id,Priority from Case where Id=: busCase.Id];
        system.assertEquals(GlobalConstants.CASE_PRIORITY_HIGH, busCase.Priority);
    }

    @isTest
    static void oldCaseUpdatedDescriptionShouldNotChangePriorityBecauseMinRecType() {
        createKeyWordSettings();
        String pattern= '%'+GlobalConstants.MIN_CORRO_RECTYPE_NAME+'%';
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName like :pattern];
        RecordType MINCORRO = caseTypes.size()==0?null:caseTypes[0];
        Case minCase=new Case(Subject='I was stopped because of the sharp metal jutting out ',
                                Description='I was stopped because of the sharp metal jutting out ',
                                RecordTypeId=MINCORRO.Id,
                                Status='New',
                                Origin='Web',
                                Priority='Normal');

        insert minCase;
        Test.startTest();
        minCase.Description='I was Injured because of the sharp metal jutting out ';
        update minCase;
        Test.stopTest();
        minCase=[select Id,Priority from Case where Id=: minCase.Id];

        system.assert('Normal'==minCase.Priority);
    }

    @isTest
    static void oldCaseUpdatedSubjectShouldNotChangeBecauseAlreadyHighCasePriority() {
        createKeyWordSettings();
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
        RecordType BUS = caseTypes.size()==0?null:caseTypes[0];
        Case busCase=new Case(Subject='I was stopped because of the sharp metal jutting out ',
                                Description='I was stopped because of the sharp metal jutting out ',
                                RecordTypeId=BUS.Id,
                                Status='New',
                                Origin='Web',
                                Priority=GlobalConstants.CASE_PRIORITY_HIGH);
        insert busCase;
        Test.startTest();
        busCase.Subject='I was Injured because of the sharp metal jutting out ';
        update busCase;
        Test.stopTest();
        List<Application_Log__c> caseTriggerLogs= [select Id from Application_Log__c where Source__c='CaseBeforeInsertTriggerHandler'];
        system.assertEquals(0, caseTriggerLogs.size());
    }
    
    @isTest
    static void updateErrorIfTriggerParameterNotProper() {
        ApplicationLog_Test.setLoggingSettings();
        CaseBeforeUpdateTriggerHandler updater= new CaseBeforeUpdateTriggerHandler();
        
        updater.mainEntry(null);
        List<Application_Log__c> caseTriggerLogs= [select Id ,Debug_Level__c from Application_Log__c ];
        system.assertEquals(GlobalConstants.ERROR,caseTriggerLogs[0].Debug_Level__c);
    }
    
    @isTest
    static void insertErrorIfTriggerParameterNotProper() {
        ApplicationLog_Test.setLoggingSettings();
        CaseBeforeInsertTriggerHandler inserter= new CaseBeforeInsertTriggerHandler();
        inserter.mainEntry(null);
        List<Application_Log__c> caseTriggerLogs= [select Id ,Debug_Level__c from Application_Log__c ];
        system.assertEquals(GlobalConstants.ERROR,caseTriggerLogs[0].Debug_Level__c);
    }
    
    
    @isTest
    static void caseOwnerChangedNoteRepareneted() {
        id currentAdminUser = UserInfo.getUserId();
        User testUser = RetrieveNextUtils_WS_Test.createTestUser('HCF Case Manager', 'HCF');
        System.runAs(testUser) {
        
            Case c = RetrieveNextUtils_WS_Test.getCaseRecord('Normal');
            c.OwnerId = currentAdminUser;
            insert c;
            
            NoteOrAttachment__c privateNote = NoteOrAttachmentTriggerDispatcher_Test.getNoteOrAttachment('abc.png', c.Id);
            insert privateNote;
            
            Test.startTest();
                c.OwnerId = testUser.Id;
                update c;
                NoteOrAttachment__c noteRecord = [Select Id, OwnerId From NoteOrAttachment__c Where Id =: privateNote.Id];
                system.assertEquals(testUser.Id, noteRecord.OwnerId);
            Test.stopTest();
        }
    }
    
    
    @isTest
    static void caseOwnerChangedToSameOwnerNotesNotReparented() {
        Case c = RetrieveNextUtils_WS_Test.getCaseRecord('Normal');
        insert c;
        
        NoteOrAttachment__c privateNote = NoteOrAttachmentTriggerDispatcher_Test.getNoteOrAttachment('abc.png', c.Id);
        insert privateNote;
        
        Test.startTest();
            c.OwnerId = UserInfo.getUserId();
            update c;
            NoteOrAttachment__c noteRecord = [Select Id, OwnerId From NoteOrAttachment__c Where Id =: privateNote.Id];
            system.assertEquals(UserInfo.getUserId(), noteRecord.OwnerId);
        Test.stopTest();
    }
    
    @isTest
    static void caseDeleteTest() {
        Case c = RetrieveNextUtils_WS_Test.getCaseRecord('Normal');
        insert c;
        
        NoteOrAttachment__c privateNote = NoteOrAttachmentTriggerDispatcher_Test.getNoteOrAttachment('abc.png', c.Id);
        insert privateNote;
        
        delete c;
        
        Test.startTest();
            list <Case> cases = [Select Id From Case];
            system.assertEquals(0, cases.size());
            
            list <NoteOrAttachment__c> attachments = [Select Id From NoteOrAttachment__c];
            system.assertEquals(0, attachments.size());
        Test.stopTest();
    }
   
    //Capture the date when Status is changed to Closed
    private static void testCapturedDateWhenStatusChangedToClosed() {
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
        RecordType bus = caseTypes.size()==0?null:caseTypes[0];
        Case caseRecord = new Case( Subject = 'I was Injured because of the sharp metal jutting out ',
                                    Description = 'I was Injured because of the sharp metal jutting out ',
                                    RecordTypeId = bus.Id,
                                    Status ='New',
                                    Origin ='Phone',
                                    Priority ='Normal',
                                    Agency__c = 'STA',
                                    Division__c = null,
                                    modes__c ='Bus',
                                    ownerid= UserInfo.getUserId(),
                                    branch__c ='');
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            insert caseRecord;
        }
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            ReopenDuration__c rd = new ReopenDuration__c(duration__c = 90, Name = 'STA');
            insert rd;
        }
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            Case c = [Select Id, Status, Reopen_Till_Date__c, Case_Resolution_Date__c From Case Where Id =: caseRecord.Id limit 1];
            Test.startTest();
                c.Status = GlobalConstants.CASE_SOFTCLOSED_STATUS;
                update c;
            Test.stopTest();
            
            
            Date reOpenTillDate = date.today().addDays(90);
            system.assertEquals(reOpenTillDate, c.Reopen_Till_Date__c);   
        }
    }
    
    //Set the RecentActivityFlag to true if the case status is changed to reopened.
    private static void RecentActivityFlagTest() {
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
        RecordType bus = caseTypes.size()==0?null:caseTypes[0];
        String caseId= UtilityClass.getFakeId(Case.SObjectType);
        Case busCase=new Case(Id=(Id)caseId,
                                Subject='I was Injured because of the sharp metal jutting out ',
                                Description='I was Injured because of the sharp metal jutting out ',
                                RecordTypeId=bus.Id,
                                Status = GlobalConstants.CASE_REOPENED_STATUS,
                                Origin='Phone',
                                Priority='Normal',
                                Agency__c = 'STA',
                                Division__c = null,
                                modes__c='Bus',
                                RecentActivityFlag__c = false,
                                ownerid=  UserInfo.getUserId(),
                                branch__c='');
        
        Case busCaseOld=new Case(Id=(Id)caseId,
                                Subject='I was Injured because of the sharp metal jutting out ',
                                Description='I was Injured because of the sharp metal jutting out ',
                                RecordTypeId=bus.Id,
                                Status= GlobalConstants.CASE_SOFTCLOSED_STATUS,
                                Origin='Phone',
                                Priority='Normal',
                                RecentActivityFlag__c = false,
                                Agency__c = 'STA',
                                Division__c = null,
                                modes__c='Bus',
                                ownerid = UserInfo.getUserId(),
                                branch__c='STA');
        
        List<Case >lists=new List<Case> ();
        lists.add(busCase);
        
        List<Case>oldList= new List<Case> ();
        oldList.add(busCaseOld);
        
        TriggerParameters tp=new TriggerParameters(oldList, lists, new Map<Id,Case>(oldList), new Map<Id,Case>(lists),
                                                  true, false, false, false, true, false, false);
        
        CaseBeforeUpdateTriggerHandler th= new CaseBeforeUpdateTriggerHandler();
        insert new CaseFilterSetting__c(Name='default',origin__c='Web',RecordType__c='Bus');
        
        Test.startTest();
            th.mainEntry(tp);
        Test.stopTest();
        system.assertEquals(true, busCase.RecentActivityFlag__c);
    }
    
    //Check for Case Group D: Parent of Multi Agency
    private static void stampAgencyOnGroupDCaseOnOwnershipChange() {
        Group STAQueue =[Select Id, Name, DeveloperName, Type from Group where Type = 'Queue' and  DeveloperName =: GlobalConstants.STA_QUEUE_TEST limit 1];
        Id RecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' And DeveloperName =: GlobalConstants.CASE_RECORD_TYPE_MULTI_ISSUE_DEV limit 1].id;
        Case caseRecord = new Case(Subject='I was Injured because of the sharp metal jutting out ',
                                 Description='I was Injured because of the sharp metal jutting out ',
                                 Status= GlobalConstants.CASE_SOFTCLOSED_STATUS,
                                 Origin='Phone',
                                 RecordTypeId = RecordTypeId,
                                 MultiAgency__c = false,
                                 Priority='Normal',
                                 RecentActivityFlag__c = false,
                                 Agency__c = null,
                                 Division__c = null,
                                 modes__c='Bus',
                                 ownerid = UserInfo.getUserId(),
                                 branch__c= '');
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            insert caseRecord;    
        }
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            Case c = [Select Id, MultiAgency__c From Case Where Id =: caseRecord.Id limit 1];
            c.MultiAgency__c = true;
            c.OwnerId = STAQueue.Id;
            update c;
            
            Test.startTest();
            c = [Select Id, Agency__c, MultiAgency__c From Case Where Id =: caseRecord.Id limit 1];
            system.assertEquals('STA', c.Agency__c);
            Test.stopTest();
        }   
    } 
        
    // 25/08/2015 : Added by Pawan Tiwari => Bulk upload cases to create the due date.    
    @isTest
    static void insertAndUpdateBulkCasesForDueDateCalculation(){

        RecordType rt = [Select Id From RecordType Where DeveloperName =: GlobalConstants.CASE_RECORD_TYPE_NAME_MINCORR_TRANSPORT limit 1]; 
        List<Case> caseListToBeInsertedOrUpdated = new List<Case>();
        
        for(Integer i =0; i< 100;i++){
            Case caseRecord = new Case(Subject='Test Case for due date calculation',
                                 Description='Test cases for bulk insert',
                                 Status= GlobalConstants.ALLOCATION_STATUS_MIN_CORRO,
                                 Origin='Phone',
                                 RecordTypeId = rt.Id,
                                 Priority=GlobalConstants.CASE_PRIORITY_INDIVIDUAL_STANDARD,
                                 Portfolio__c = GlobalConstants.MIN_CORR_PORTFOLIO_TRANSPORT,
                                 Signatory__c = 'Minister for Transport and Infrastructure');

            caseListToBeInsertedOrUpdated.add(caseRecord);
        
        }
        Test.startTest();
        insert caseListToBeInsertedOrUpdated;
        System.debug('caseListToBeInsertedOrUpdated :: ' + caseListToBeInsertedOrUpdated);
        System.assertEquals(caseListToBeInsertedOrUpdated.size(),100);

        for(Integer i = 0; i< caseListToBeInsertedOrUpdated.size(); i++ ){
            caseListToBeInsertedOrUpdated[i].Status = GlobalConstants.ALLOCATION_STATUS_MIN_CORRO;
            caseListToBeInsertedOrUpdated[i].Priority = GlobalConstants.CASE_PRIORITY_MP_STANDARD;
        }
        update caseListToBeInsertedOrUpdated;
        System.debug('DML Count :: ' + Limits.getDMLRows());
        System.debug('Soql Queries Count :: ' + Limits.getQueries());
        Test.stopTest();
    }


    //Populate the PBO/LRO email address from custom settings
      
    private static void createQueueVsAgencyBranchDivCustomSetting() {
        list <QueueVsAgency__c> mapping= new list <QueueVsAgency__c>();
        mapping.add(new QueueVsAgency__c(Name = '1', QueueName__c = 'STA_Brookvale_Depot_CFM', Agency__c = 'STA', Division__c = 'Northern Region', Branch__c = 'Brookvale Depot'));
        mapping.add(new QueueVsAgency__c(Name = '2', QueueName__c = 'RMS_AMD_Engineering_Services_CFM', Agency__c = 'RMS', Division__c = 'Asset Maintenance', Branch__c = 'ENGINEERING SERVICES'));
        insert mapping;
    }
}