force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>The originating class (e.g. CustomerManagement)</description>
    <inlineHelpText>The originating class (e.g. CustomerManagement)</inlineHelpText>
    <label>Source</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Settings__c/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExceptionLogger_Test.cls
@isTest
private class ExceptionLogger_Test {

    private static testMethod void testForLoggingSuccess() {
    	setLoggingSettings();
       	System.Test.startTest();
       	ExceptionLogger.logException('ExceptionLogger_Test','testForLoggingSuccess', new TestException('Test Exception'), null);
       	System.Test.stopTest();
       	List<Application_Log__c> logs = [SELECT Id FROM Application_Log__c WHERE Source__c = 'ExceptionLogger_Test'];
       	System.assert(!logs.isEmpty());
    }
    
    private static testMethod void testForLoggingFailure() {
    	setLoggingSettings();
        System.Test.startTest();
        try {
        	ExceptionLogger.logException(null,'testForLoggingSuccess',new TestException('Test Exception'), null);
        	System.assert(false);
        } catch(Exception e) {
        	System.assert(true);
        }       	
       	System.Test.stopTest();
    }
    
    private static void setLoggingSettings(){
		insert new System_Settings__c(
			Name='Test',Debug__c=true,Error__c=true,Info__c=true,Warning__c=true
		);
	}
    
    public class TestException extends Exception {}
}