force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message to log</description>
    <inlineHelpText>Message to log</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Settings__c/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WebToCaseSpamSettings__c/WebToCaseSpamSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WebToCase Spam Settings</label>
</CustomObject>

force-app/main/default/objects/WebToCaseSpamSettings__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WebToCaseSpamSettings__c/fields/Within_duration_in_min__c.field-meta.xml
<CustomField>
    <fullName>Within_duration_in_min__c</fullName>
    <label>Within duration (in min)</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SuspectedSpamCaseLogger_Test.cls
@isTest
private class SuspectedSpamCaseLogger_Test {
    private static String ipAddress = '192.143.67.167';
    private static String source = 'SuspectedSpamCaseLogger_Test';
    private static String functionName = 'testMethod';
    
    private static testMethod void testForInvalidData() {
        System.Test.startTest();
        try{
            SuspectedSpamCaseLogger.logSpamCase(null, source, functionName);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        try{
            SuspectedSpamCaseLogger.logSpamCase(ipAddress, null, functionName);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        try{
            SuspectedSpamCaseLogger.logSpamCase(ipAddress, source, null);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }

    private static testMethod void testForNewSpamLog() {
        setUpTestData(true);
        System.Test.startTest();
        SuspectedSpamCaseLogger.logSpamCase(ipAddress, source, functionName);
        System.Test.stopTest();
        List<Application_Log__c> appLog = [SELECT Id, Message__c FROM Application_Log__c];
        System.assert(!appLog.isEmpty());
        System.assert(appLog[0].Message__c != null);
        System.assert(appLog[0].Message__c.endsWith(SuspectedSpamCaseLogger.NUMBER_OF_TIMES_REQ_SENT_STR + 1));
    }
    
    private static testMethod void testForSpamCheckWithoutCustomSetting() {
        setUpTestData(true);
        List<WebToCaseSpamSettings__c> settings = [SELECT ID FROM WebToCaseSpamSettings__c ];
        delete settings;
        System.Test.startTest();
        SuspectedSpamCaseLogger.logSpamCase(ipAddress, source, functionName);
        System.Test.stopTest();
        List<Application_Log__c> appLog = [SELECT Id, Message__c FROM Application_Log__c];
        System.assert(!appLog.isEmpty());
        System.assert(appLog[0].Message__c != null);
        System.assert(appLog[0].Message__c.endsWith(SuspectedSpamCaseLogger.NUMBER_OF_TIMES_REQ_SENT_STR + 1));
    }
    
    private static testMethod void testForMultipleSpam() {
        setUpTestData(false);
        System.Test.startTest();
        SuspectedSpamCaseLogger.logSpamCase(ipAddress, source, functionName);
        System.Test.stopTest();
        List<Application_Log__c> appLog = [SELECT Id, Message__c FROM Application_Log__c];
        System.assert(!appLog.isEmpty());
        System.assert(appLog[0].Message__c != null);
        System.debug(appLog[0].Message__c);
        System.assert(appLog[0].Message__c.endsWith(SuspectedSpamCaseLogger.NUMBER_OF_TIMES_REQ_SENT_STR + 2));
    }
    
    private static void setUpTestData(Boolean isNewSpam) {
        setUpCustomSetting();
        if(!isNewSpam) {
            createSpamLog();
        }       
    }
    
    private static void createSpamLog() {
        ApplicationLogMessage message = new ApplicationLogMessage();
        message.source = source;
        message.sourceFunction = functionName;
        message.logMessage = 'Suspected spam request to create case from web form. Details as below \nSource=' + source
            + '\nIp=' + ipAddress + '\n'  + SuspectedSpamCaseLogger.NUMBER_OF_TIMES_REQ_SENT_STR + 1;     
        message.debugLevel = GlobalConstants.WARNING;
        message.logCode = GlobalConstants.SUSPECTED_SPAM_CASE;
        message.referenceId = ipAddress;
        ApplicationLogUtility.logMessage(message);
    }
    
    private static void setUpCustomSetting() {
        WebToCaseSpamSettings__c spamSetting = new WebToCaseSpamSettings__c();
        //create spam setting for max 10 allowed cases within 10 mins.
        spamSetting.Within_duration_in_min__c = 10;
        spamSetting.Frequency__c = 10;
        spamSetting.Name = 'WebToCase';
        insert spamSetting;
        
        insert new System_Settings__c(
            Name='Test', Debug__c=true, Error__c=true, Info__c=true, Warning__c=true
        );
    }
}