force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>Reference_Info__c</fullName>
    <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
    <inlineHelpText>The related record info (e.g. Apex Batch Job Id, Contact etc)</inlineHelpText>
    <label>Reference Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>The originating class (e.g. CustomerManagement)</description>
    <inlineHelpText>The originating class (e.g. CustomerManagement)</inlineHelpText>
    <label>Source</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <description>The originating function in the class (e.g. UpdateDivision() )</description>
    <inlineHelpText>The originating function in the class (e.g. UpdateDivision() )</inlineHelpText>
    <label>Source Function</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MaskContactDetailsBatch.cls
/*******************************************************************************************
* Author:         Abhi Indulkar
* Company:        TfNSW
* Description:    Batch class to Mask contact details from Contacts
* 
* Test Class:    MaskContactDetailsBatchTest
* History
* <Date>      <Authors Name>      <Brief Description of Change>
* 10/12/2018  Abhi Indulkar    		Created
*******************************************************************************************/
global class MaskContactDetailsBatch implements Database.Batchable<SObject>, Database.Stateful {
    private static String MASK_SFX = '.invalid';
    private Boolean isSandbox = false;
    private Set<String> lExceptions = new Set<String>();
    private static String resultEmail;
    public static String sCRMTeamEmail = 'salesforcerequests@transport.nsw.gov.au';
    private Integer batchSize = 200;
    public Boolean callNextBatchJob = true;
    
    private Integer failedRecCount = 0;
    private Integer successRecCount = 0;
    
    global MaskContactDetailsBatch() {
        this.isSandbox = runningInASandbox();
    }
    
    global MaskContactDetailsBatch(String pEmail, Integer pBatchSize, Boolean callRemainingBatchJob) {
        this.isSandbox = runningInASandbox();
        resultEmail = pEmail;
        batchSize = pBatchSize;
        callNextBatchJob = callRemainingBatchJob;
    }
    
    /**
    * @description gets invoked when the batch job starts
    * @param context contains the job ID
    * @returns the record set as a QueryLocator object that will be batched for execution
    */
    global Database.QueryLocator start(Database.BatchableContext context) {
        String dummyId = '000000000000000';
        if (this.isSandbox || Test.isRunningTest()) {           
            return Database.getQueryLocator([SELECT Email, MOEmail__c FROM Contact]);
        }else{
            return Database.getQueryLocator([SELECT Email, MOEmail__c FROM Contact WHERE Id = :dummyId]);
        }
    }
    
    /**
    * @description gets invoked when the batch job executes and operates on one batch of records. Contains or calls the main execution logic for the batch job.
    * @param context contains the job ID
    * @param scope contains the batch of records to process.
    */
    global void execute(Database.BatchableContext context, List<Contact> scope) {       
        
        List<Contact> lContacts = new List<Contact> ();
        Boolean toggle = true;
        for (Contact c : scope) {
            if(String.isNotBlank(c.Email) || String.isNotBlank(c.MOEmail__c) ){
                c.Email = getInvalidEmail(c.Email);
                c.MOEmail__c = getInvalidEmail(c.MOEmail__c);       
                if(Test.isRunningTest() && toggle){
                    c.No_CFM_cases_12_mth_rolling__c = 1235473474; //more than 6 digit number
                    toggle=false;
                }
                lContacts.add(c);
            }
        }
        if(!lContacts.isEmpty()){
            Database.SaveResult[] updateResultList =  Database.update(lContacts, false);
            
            Map<Id, String> mFailedRecords = new Map<Id, String>();
            // Iterate through each returned result
            for(Database.SaveResult sr : updateResultList){              
                if(!sr.isSuccess()) {
                    // Operation failed, so get all errors
                    String sErrorDetails;               
                    for(Database.Error err : sr.getErrors()) {
                        sErrorDetails = err.getMessage() + ': Error Fields- ' + err.getFields();
                        lExceptions.add(sErrorDetails);
                    }
                    mFailedRecords.put(sr.id, sErrorDetails);
                    failedRecCount++;
                }else{
                    successRecCount++;
                }
            }
            
            //Log errors in application log
            List<Application_Log__c> lAppLogs = new List<Application_Log__c>();
            for(Id recId : mFailedRecords.keySet()){
                Application_Log__c log = new Application_Log__c();
                log.Debug_Level__c = 'Info';
                log.Reference_Id__c = recId;
                log.Reference_Info__c = mFailedRecords.get(recId);
                log.Source__c = 'MaskContactDetailsBatch';
                log.Source_Function__c = 'execute';
                lAppLogs.add(log);
            }
            insert lAppLogs;
        }
        
    }
    
    /**
    * @description gets invoked when the batch job finishes. Place any clean up code in this method.
    * @param context contains the job ID
    */
    global void finish(Database.BatchableContext context) {
        
        // Send an email to the Apex job's submitter notifying of job completion.  
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();        
        String[] toAddresses = new String[] {sCRMTeamEmail};        
            if(String.isNotBlank(resultEmail)){
                toAddresses.add(resultEmail);
            }
        mail.setToAddresses(toAddresses);        
        mail.setSubject('Contact masking batch completed');
        String bodyText = 'BATCH MaskContactDetailsBatch Summary:\n\n';
        bodyText = bodyText + 'Number of total records: ' + (successRecCount + failedRecCount);
        bodyText = bodyText + '\n\tSuccessfully updated records: ' + successRecCount;
        bodyText = bodyText + '\n\tFailed to update records: ' + failedRecCount;
        
        if(!lExceptions.isEmpty()){
            bodyText = bodyText + '\n\nError Summary\n\n';
            for(String err : lExceptions) {
                bodyText = bodyText + '\n' + err + '\n';
            }
        }
        
        bodyText = bodyText + '\n\n';
        mail.setPlainTextBody (bodyText);
        try{ 
        	Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
        }catch(Exception e){
        	//Do Nothing
        }
        
        //Invoke next batch jobs if requested
        if (!Test.isRunningTest() && this.isSandbox) {
			if (callNextBatchJob)
				ID batchProcessId = Database.executeBatch(new MaskCaseDetailsBatch(), this.batchSize);
		}
        
    }
   /* 
    private String getInvalidNumber(String pNumber) {
        String sInvalidNumber;
        if (String.isNotBlank(pNumber) && pNumber.length() > 3) {
            sInvalidNumber = pNumber.substring(0, 3) + '1' + pNumber.substring(3);
        } else {
            sInvalidNumber = pNumber;
        }
        return sInvalidNumber;
    }*/
    
    private String getInvalidEmail(String pEmail) {
        String sInvalidEmail;
        if (String.isNotBlank(pEmail) && !pEmail.endsWith(MASK_SFX)) {
            pEmail = pEmail.length() > 245 ? pEmail.substring(10) : pEmail;
            sInvalidEmail = pEmail + MASK_SFX;
        } else {
            sInvalidEmail = pEmail;
        }
        return sInvalidEmail;
    }
    
    public static Boolean runningInASandbox() {
        return [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }
}