force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/classes/AttachmentTriggerDispatcherTest.cls
@isTest
private class AttachmentTriggerDispatcherTest
{
    
     @testSetup
    static void setUpUser(){

        Profile p1 = [SELECT Id FROM Profile WHERE Name = 'MinCo Webform API Integration User'];        
       
        User u1 = new User(Alias = 'standt', Email = 'standarduser1@nsw.gov.au.com', EmailEncodingKey='UTF-8', FirstName = 'MinCo Webform', LastName='API Integration User', LanguageLocaleKey='en_US',
                            LocaleSidKey='en_US', ProfileId = p1.Id, TimeZoneSidKey='Australia/Sydney', UserName='md' + System.currentTimeMillis() + '@nsw.gov.au.com', isActive = true);
        insert u1;

    } 
    
    @isTest
    static void createCustomNotesAndAttachemntBeforeInsertingAttachmentToCase()
    {
        Case thisCase= setupCase();
        insert thisCase;
        Attachment thisAttachment= new Attachment(
            parentId=thisCase.Id,
            Name='This is dummy name for the attachment used to test the 80 characters size limit.pdf',
            Body=Blob.valueOf('test'));
        Test.startTest();
        insert thisAttachment;
        Test.stopTest();
        List<NoteOrAttachment__c> thisNoteAttachments= [select Id from NoteOrAttachment__c where Attachment__c=:thisAttachment.Id];
        system.assertEquals(1,thisNoteAttachments.size() );

    }


    @isTest
    static void createCustomNotesAndAttachemntAfterInsertingAttachmentToCase()
    {
        Case thisCase= setupCase();
        insert thisCase;
        Attachment thisAttachment= new Attachment(
            parentId=thisCase.Id,
            Name='Incoming Correspondence MO 20161109 153150 0001',
            Body=Blob.valueOf('Incoming Correspondence MO 20161109 153150 0001'));
        Test.startTest();
        insert thisAttachment;
        system.debug('attachment :: ' + thisAttachment);
        Test.stopTest();
        List<NoteOrAttachment__c> thisNoteAttachments= [select Id from NoteOrAttachment__c where Attachment__c=:thisAttachment.Id];
        system.debug('thisNoteAttachments :: ' + thisNoteAttachments);
        system.assertEquals(1,thisNoteAttachments.size() );

    }

    @isTest
    static void createCustomNotesAndAttachemntAfterInsertingAttachmentToCaseWithMinCorroUser()
    {
        User u = [Select Id from User where Email = 'standarduser1@nsw.gov.au.com' limit 1];
        
        system.runAs(u){
            Case thisCase= setupCase();
            insert thisCase;

            NoteOrAttachment__c customAttachment = new NoteOrAttachment__c();
            customAttachment.Name = 'Incoming Correspondence MO 20161109 153150 0001';
            customAttachment.Case__c = thisCase.Id;
            insert customAttachment;

            Attachment thisAttachment= new Attachment(
                parentId=customAttachment.Id,
                Name='Incoming Correspondence MO 20161109 153150 0001',
                Body=Blob.valueOf('Incoming Correspondence MO 20161109 153150 0001'));
            Test.startTest();
            insert thisAttachment;
            system.debug('attachment by :: ' + thisAttachment);
            customAttachment.Attachment__c = thisAttachment.Id;
            update customAttachment;
            Test.stopTest();
            List<NoteOrAttachment__c> thisNoteAttachments= [select Id,CreatedBy.Name from NoteOrAttachment__c where Attachment__c=:thisAttachment.Id ];

            system.debug('thisNoteAttachments by :: ' + thisNoteAttachments[0].CreatedBy.Name);
            system.assertEquals(1,thisNoteAttachments.size() );
        }
    }

    @isTest
    static void deleteCustomNotesAndAttachemntAfterDeletingAttachmentfromCase()
    {
        Case thisCase= setupCase();
        insert thisCase;
        Attachment thisAttachment= new Attachment(
            parentId=thisCase.Id,
            Name='test',
            Body=Blob.valueOf('test'));
        insert thisAttachment;
        Test.startTest();
        delete thisAttachment;
        Test.stopTest();
        List<NoteOrAttachment__c> thisNoteAttachments= [select Id from NoteOrAttachment__c where Attachment__c=:thisAttachment.Id];
        system.assertEquals(0,thisNoteAttachments.size() );

    }
    @isTest
    static void createCustomNotesAndAttachemntAfterUndeletingAttachmentfromCase()
    {
        Case thisCase= setupCase();
        insert thisCase;
        Attachment thisAttachment= new Attachment(
            parentId=thisCase.Id,
            Name='test',
            Body=Blob.valueOf('test'));
        insert thisAttachment;
        delete thisAttachment;

        Test.startTest();
        undelete thisAttachment;
        Test.stopTest();
        List<NoteOrAttachment__c> thisNoteAttachments= [select Id from NoteOrAttachment__c where Case__c=:thisCase.Id];
        system.assertEquals(1,thisNoteAttachments.size() );

    }
    
    @isTest
    static void beforeInsertErrorIfTriggerParameterNotProper()
    {
        ApplicationLog_Test.setLoggingSettings();
        AttachmentBeforeInsertTriggerHandler beforeInserter= new AttachmentBeforeInsertTriggerHandler();
        
        beforeInserter.mainEntry(null);
        List<Application_Log__c> attachemntLogs= [select Id ,Debug_Level__c from Application_Log__c ];
        system.assertEquals(GlobalConstants.ERROR,attachemntLogs[0].Debug_Level__c);

    }
    
    @isTest
    static void insertErrorIfTriggerParameterNotProper()
    {
        ApplicationLog_Test.setLoggingSettings();
        AttachmentAfterInsertTriggerHandler inserter= new AttachmentAfterInsertTriggerHandler();
        
        inserter.mainEntry(null);
        List<Application_Log__c> attachemntLogs= [select Id ,Debug_Level__c from Application_Log__c ];
        system.assertEquals(GlobalConstants.ERROR,attachemntLogs[0].Debug_Level__c);

    }
    @isTest
    static void deleteErrorIfTriggerParameterNotProper()
    {
        ApplicationLog_Test.setLoggingSettings();
        AttachmentAfterDeleteTriggerHandler deleter= new AttachmentAfterDeleteTriggerHandler();
        
        deleter.mainEntry(null);
        List<Application_Log__c> attachemntLogs= [select Id ,Debug_Level__c from Application_Log__c ];
        system.assertEquals(GlobalConstants.ERROR,attachemntLogs[0].Debug_Level__c);

    }
    @isTest
    static void undeleteErrorIfTriggerParameterNotProper()
    {
        ApplicationLog_Test.setLoggingSettings();
        AttachmentAfterUndeleteTriggerHandler undeleter= new AttachmentAfterUndeleteTriggerHandler();
        
        undeleter.mainEntry(null);
        List<Application_Log__c> attachemntLogs= [select Id ,Debug_Level__c from Application_Log__c ];
        system.assertEquals(GlobalConstants.ERROR,attachemntLogs[0].Debug_Level__c);

    }

    public static Case setupCase(){
        Case aCase=new Case(Subject='I was Injured because of the sharp metal jutting out ',
                                Description='I was Injured because of the sharp metal jutting out ',
                                Status='New',
                                Origin='Web',
                                Priority='Normal');
        return aCase;
    }
}