force-app/main/default/objects/AusStates__c/AusStates__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of states to be displayed on web to case form</description>
    <label>Australian States</label>
</CustomObject>

force-app/main/default/objects/AusStates__c/fields/Sort_order__c.field-meta.xml
<CustomField>
    <fullName>Sort_order__c</fullName>
    <label>Sort order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/WebformContactController_Test.cls
@isTest
private class WebformContactController_Test {

    private static testMethod void testForStates() {
        List<AusStates__c> ausStates = new List<AusStates__c>();
        ausStates.add(new AusStates__c(Name='NSW', Sort_order__c = 1));
        ausStates.add(new AusStates__c(Name='VIC', Sort_order__c = 2));
        ausStates.add(new AusStates__c(Name='QLD', Sort_order__c = 3));
        insert ausStates;
        System.Test.startTest();
        WebformContactController controller = new WebformContactController();
        List<SelectOption> states = controller.getStates();
        controller.setStates(states);
        System.Test.stopTest();
        System.assert(states.size() == 4);
    }
    
    private static testMethod void testForPreviouslyRaisedOptions() {
        System.Test.startTest();
        WebformContactController controller = new WebformContactController();
        List<SelectOption> options = controller.getPreviouslyRaisedIssueOptions();
        controller.setPreviouslyRaisedIssueOptions(options);
        System.Test.stopTest();
        System.assert(!options.isEmpty());
    }
}