force-app/main/default/objects/BU_Staging__c/BU_Staging__c.object-meta.xml
<CustomObject>
    <description>Used as a staging object for bulk upload on private operator portal.</description>
    <label>PO Upload</label>
    <nameField>
        <displayFormat>BU - {000000}</displayFormat>
        <label>BU Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Upload</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulk_Upload_CSV_File_Maximum_Record__mdt/Bulk_Upload_CSV_File_Maximum_Record__mdt.object-meta.xml
<CustomObject>
    <description>Used to store the count for maximum number of records in the csv file upload for bulk upload.</description>
    <label>Bulk Upload CSV File Maximum Record</label>
    <pluralLabel>Bulk Upload CSV File Maximum Records</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bulk_Upload_CSV_File_Maximum_Record__mdt/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>maximum number of records to be uploaded in BU Staging object.</description>
    <label>Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BulkUploadStagingRecordsCntrl.cls
/*------------------------------------------------------------
Author:        Pawan Tiwari
Company:       Arxxus Technology Partners
Description:   Parse Staging records from the uploaded file and return numeber of the inserted staging records.

History
16/06/2017      Pawan Tiwari         Created.
------------------------------------------------------------*/
public with sharing class BulkUploadStagingRecordsCntrl {

    public Integer rowCount;
    public Integer maxRecordCount;
    private String filedata;
    private Exception ex;
    public BulkUploadStagingRecordsCntrl(String filedata){
        this.filedata = filedata;
        rowCount = 0;
        List<Bulk_Upload_CSV_File_Maximum_Record__mdt> mappingMetadataRecList = [SELECT Count__c 
                                                                                    FROM Bulk_Upload_CSV_File_Maximum_Record__mdt
                                                                                    LIMIT 1];
        Integer recordCount = 0;
        if(mappingMetadataRecList.size() > 0){
            maxRecordCount = Integer.valueOf(mappingMetadataRecList[0].Count__c);
        }
    }

    //Executes the process of insertion of staging records
    //returns number of successfully inserted records
    public Integer execute(){
        Integer success = 0;
        Savepoint sp = Database.setSavepoint();
        List<ApplicationLogMessage> messages =new List<ApplicationLogMessage>();
        try{
            System.debug('In Execute');
            
            if(filedata == null) {
                throw new BulkLoadException('Incorrect type of data - required data');
            }

            List<BU_Staging__c> stagingRecList;
            stagingRecList = parseStagingRec();
            rowCount = stagingRecList.size();
        
            if(rowCount > maxRecordCount) {
                System.debug('row count greater than allowed limit.');
               // throw new BulkLoadException(Label.MAXIMUM_RECORD_SIZE);
               // return 10000000;
               return rowCount;
            }

            if(rowCount < 1) {
                System.debug('No rows found in the CSV');
               return rowCount;
            }


            
            
            else {
                Database.SaveResult[] srList = Database.insert(stagingRecList, true);

                for (Database.SaveResult sr : srList) {
                    System.debug('srResult = '+sr);
                    if (sr.isSuccess()) {
                        success++;
                        System.debug('success === '+ sr);
                    }else{
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            ApplicationLogMessage message= new ApplicationLogMessage();
                            message.source='BulkUploadStagingRecordsCntrl';
                            message.sourceFunction='execute';
                            message.logMessage=err.getMessage();
                            message.debugLevel=GlobalConstants.ERROR;
                            messages.add(message);
                            ApplicationLogUtility.logMessage(messages);
                            messages.clear();
    
                        }
                        throw new BulkLoadException('Exception in BUlk Upload staging records');
                    }
                }
            }
            System.debug('Get CPU Timeout execute: '+Limits.getCpuTime() + '-'+ Limits.getLimitCpuTime() ); 
            
            //Save records in database not allowing partial insertion
            
            
      
        }catch(Exception e){
      //Rollback the transaction if an exception is occured
            Database.rollback(sp);
            ex = e;
            //throw new BulkLoadException('Exception in BUlk Upload staging records');
      
        } finally{
            System.debug('finally executing.');
      		if(ex != NULL) {
                ApplicationLogMessage message= new ApplicationLogMessage();
                message.source='BulkUploadStagingRecordsCntrl';
                message.sourceFunction='execute';
                message.logMessage=ex.getMessage() + '--' + ex.getLineNumber();
                message.ex=ex;
                message.debugLevel=GlobalConstants.ERROR;
                messages.add(message);
                ApplicationLogUtility.logMessage(messages);
                messages.clear();
            }
        }
        return success;
    }
    
    // Parse the input file content and return the staging records
    @TestVisible
    private List<BU_Staging__c> parseStagingRec() {
        
        System.debug('filedata :: ' + filedata);
        List<BU_Staging__c> newstagingRecords = new List<BU_Staging__c>();
        ATP_CSVParser parser = new ATP_CSVParser(filedata, true, ',', '\r'); 
        
        List<String> headerRow = parser.getHeaderRow();
        List<String> stagingRecord = new List<String>();
        BU_Staging__c newstagingRecord = new BU_Staging__c();
        System.debug('headerRow********'+headerRow);
        newstagingRecords = StagingRecordBuilder.buildStagingRecord(parser,headerRow);
        return newstagingRecords; 
        
    }

    public class BulkLoadException extends Exception {}

}