force-app/main/default/objects/BU_Staging__c/BU_Staging__c.object-meta.xml
<CustomObject>
    <description>Used as a staging object for bulk upload on private operator portal.</description>
    <label>PO Upload</label>
    <nameField>
        <displayFormat>BU - {000000}</displayFormat>
        <label>BU Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Upload</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BU_Staging__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>BU_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Case_Number_Operator__c.field-meta.xml
<CustomField>
    <fullName>Case_Number_Operator__c</fullName>
    <label>Ext Case No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Triage</fullName>
            </value>
            <value>
                <fullName>Pre-Registration</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Awaiting Advice</fullName>
            </value>
            <value>
                <fullName>Draft in Progress</fullName>
            </value>
            <value>
                <fullName>Senior Review</fullName>
            </value>
            <value>
                <fullName>Editor Review</fullName>
            </value>
            <value>
                <fullName>Manager Review</fullName>
            </value>
            <value>
                <fullName>MAGS Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting MO Contact Approval</fullName>
            </value>
            <value>
                <fullName>MO Contact Rejected</fullName>
            </value>
            <value>
                <fullName>Advice Received</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Ready For Printing</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Signed and Emailed</fullName>
            </value>
            <value>
                <fullName>Signatory Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - NRR</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed with Customer</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>BU_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Contact_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Contact_Mobile__c</fullName>
    <label>Contact Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Contact_Second_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Second_Name__c</fullName>
    <label>Contact Second Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Contact_Work__c.field-meta.xml
<CustomField>
    <fullName>Contact_Work__c</fullName>
    <label>Contact Work</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Date_Time_of_Incident__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_of_Incident__c</fullName>
    <label>Date / Time of Incident</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failure_Reason__c</fullName>
    <description>Used to store all the exception occurred while processing the record from staging to the case and contact object.</description>
    <label>Failure Reason</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Location_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Level 3</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipName>BU_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Location_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3_Id__c</fullName>
    <label>Location Level 3 (ID)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <defaultValue>&#39;Success&#39;</defaultValue>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Re_assignment_Reason__c.field-meta.xml
<CustomField>
    <fullName>Re_assignment_Reason__c</fullName>
    <label>Re-assignment Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Resolution_Detail__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Detail__c</fullName>
    <label>Resolution Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BUStagingBeforeInsertTriggerHandlerHlpr.cls
/*------------------------------------------------------------
Author:        Yogiraj Sarode
Company:       Arxxus.com
Description:   BU Staging before insert handler helper
               This class is responsible for all the validations need to be performed 
               on the staging data before start processing for create Case and Contact object.
               MappingRecord class is used/refernced to get all data for validation.

History
12/06/2017       Yogiraj Sarode        Created   
------------------------------------------------------------*/
public with sharing class BUStagingBeforeInsertTriggerHandlerHlpr {
    
    //store staging picklist field name with the picklist values
    public static Map<String,Set<String>> stagingPicklistFieldNamevsValue = new Map<String,Set<String>>();
    //store column staging field api name vs csv file columnheader
    public static Map<String,String> stgingFieldVsColumnHeader = new Map<String,String>();
    Set<String> uniqueExternalCaseNumber = new Set<String>();
    /* store staging api name vs madatory fields
    *(Is Staging Field Mandatory in 'BU Staging Field Mapping Metadata') for Case object
    */
    public static Map<String,String> stagingApiNameVsCaseForMandatory = new Map<String,String>();
    /* store staging api name vs madatory fields
    *(Is Staging Field Mandatory in 'BU Staging Field Mapping Metadata') for Contact object
    */
    public static Map<String,String> stagingApiNameVsContactForMandatory = new Map<String,String>();
    //store staging apiname vs case apiname (used to map data from staging object to case object for insert/update record)
    public static Map<String,String> stagingObjectToCaseMapping = new Map<String,String>();
    //store staging apiname vs contact apiname (used to map data from staging object to contact object for insert/update record)
    public static Map<String,String> stagingObjectToContactMapping = new Map<String,String>();
     
    Set<String> cntIds = new Set<String>();
    Set<String> caseIds = new Set<String>();
    Set<String> taxonomyIds = new Set<String>();
    Set<String> mandatoryFields;
    Set<String> notMandatoryFields = new Set<String>{'Case_Manager__c','Re_assignment_Reason__c','Resolution_Detail__c'};

    //Helper constructor to reterive metadata mapping data from the MappingRecord.cls
    public BUStagingBeforeInsertTriggerHandlerHlpr(){
        System.debug('Staging class Helper');
        
        MappingRecord.getMappingMetadataList();
        stagingPicklistFieldNamevsValue = MappingRecord.stagingPicklistFieldNamevsValue;
        stgingFieldVsColumnHeader = MappingRecord.stgingFieldVsColumnHeader;
        stagingApiNameVsCaseForMandatory = MappingRecord.stagingApiNameVsCaseForMandatory;
        stagingApiNameVsContactForMandatory = MappingRecord.stagingApiNameVsContactForMandatory;
        stagingObjectToCaseMapping = MappingRecord.stagingObjectToCaseMapping;
        stagingObjectToContactMapping = MappingRecord.stagingObjectToContactMapping;

    }
    
     /*This method is used to process the staging record for below mentioned validation
    * 1. Case Id is valid or not (Only if Case Id is populated=>18 characters salesforce id)
    * 2. Contact Id is valid or not (Only if Contact Id is populated=>18 characters salesforce id)
    * 3. Taxonomy Id is valid or not (Only if Taxonomy Id is populated=>18 characters salesforce id)
    * 4. For new case: External case number uniqueness('External Case Number' column in csv file)
    * 5. For new case: Mandatory fields as specificed in 'BU Staging Field Mapping Metadata' with 
         'Is Staging Field Mandatory' checkbox checked(only if any of the case field is populated).
    * 6. For new/existing case/contact: check if picklist value exists or not
    * 7. For new contact: check if LastName and Email or any of phone fields are 
         populated (only if any of contact fields are populated).
    * 8. For new contact: Validate the date time field.
    */
    public void processStagingRecords(List<BU_Staging__c> stagingRecList){
        System.debug('Staging Record List :: ' + stagingRecList.size());
        Set<String> caseIdsInFile = new Set<String>();
        Set<String> contactIdsInFile = new Set<String>();
        Set<String> taxonomyIdsInFile = new Set<String>();
        Map<String,BU_Staging__c> stagingTrimmedRecordMap = new Map<String,BU_Staging__c>();

        Set<String> objectFields = Schema.SObjectType.BU_Staging__c.fields.getMap().keySet();
        // Iterate over the staging records to get Case Ids, Contact Ids and taxonomy Ids
        for(BU_Staging__c stagingRec : stagingRecList){
			stagingRec.Created_Date__c = System.today();            
            system.debug('Staging record :: ' + stagingRec);
            if(stagingRec.Case_Id__c != NULL) {
                caseIdsInFile.add(stagingRec.Case_Id__c);
            }
            if(stagingRec.Contact_Id__c != NULL) {
                contactIdsInFile.add(stagingRec.Contact_Id__c);
            }
            if(!String.isEmpty(stagingRec.Location_Level_3_Id__c)){
                taxonomyIdsInFile.add(stagingRec.Location_Level_3_Id__c);
            }
        }
        // create set of contact ids for valid contact ids otained from staging record
        for(Contact cnt : [SELECT ID FROM Contact WHERE Id IN : contactIdsInFile]){
            cntIds.add(cnt.Id);
        }        
        // create set of case ids for valid case ids otained from staging record
        for(Case cs : [SELECT ID FROM Case WHERE Id IN : caseIdsInFile]){
            caseIds.add(cs.Id);
        }

        // create set of taxonomy Ids for valid taxonomy ids obtained form the staging record.
        for(Taxonomy_Metadata__c taxonomyRec : [SELECT ID FROM Taxonomy_Metadata__c WHERE ID IN : taxonomyIdsInFile ]){
            taxonomyIds.add(taxonomyRec.Id);
        }

        System.debug('Get CPU Timeout processStagingRecords 1: '+Limits.getCpuTime() + '-'+ Limits.getLimitCpuTime() ); 
        
        // iterate over staging records for data validation
        for(BU_Staging__c stagingRec : stagingRecList){
            Integer count = 0;
            String mandatoryFiledError = '';
            mandatoryFields = new Set<String>();
            System.debug('Get CPU Timeout processStagingRecords ##: '+Limits.getCpuTime() + '-'+ Limits.getLimitCpuTime() ); 
            // Logic to check the external case number uniqueness
            if(!String.isBlank(stagingRec.Case_Number_Operator__c)){
                System.debug('Case_number_Operator__c :: ' + stagingRec.Case_number_Operator__c );
                if(!uniqueExternalCaseNumber.contains(stagingRec.Case_Number_Operator__c)){
                    System.debug('uniqueExternalCaseNumber not :: ' + uniqueExternalCaseNumber );
                    uniqueExternalCaseNumber.add(stagingRec.Case_Number_Operator__c);  
                }else{
                    System.debug('uniqueExternalCaseNumber out  :: ' + uniqueExternalCaseNumber +' -- '+stgingFieldVsColumnHeader.containsKey('Case_Number_Operator__c')+ '--' +stgingFieldVsColumnHeader );
                    if(stgingFieldVsColumnHeader.containsKey('Case_Number_Operator__c')){
                        // check if the Failure reason is blank
                        if(stagingRec.Failure_Reason__c == null || stagingRec.Failure_Reason__c == ''){
                            stagingRec.Failure_Reason__c = 'Please ensure '+ stgingFieldVsColumnHeader.get('Case_Number_Operator__c') +' values are unique.'+' \r\n';
                        }else{
                            stagingRec.Failure_Reason__c += 'Please ensure '+ stgingFieldVsColumnHeader.get('Case_Number_Operator__c') +' values are unique.'+' \r\n';
                        }   
                    }
                }
            }

            System.debug('Stagging Record :: ' + stagingRec +'--'+ String.isEmpty(stagingRec.Contact_Id__c));

            //UPDATE CASE: validate the case id
            if(!String.isEmpty(stagingRec.Case_Id__c)){
                System.debug('case Id Populated :: ' + caseIds + '--' + stagingRec.Case_Id__c);
                if(!caseIds.contains(stagingRec.Case_Id__c)){
                    if(stgingFieldVsColumnHeader.containsKey('Case_Id__c')){
                        if(String.isEmpty(stagingRec.Failure_Reason__c)){
                            stagingRec.Failure_Reason__c = stgingFieldVsColumnHeader.get('Case_Id__c') + ' is invalid. '+' \r\n';
                        }else{
                            stagingRec.Failure_Reason__c += stgingFieldVsColumnHeader.get('Case_Id__c') + ' is invalid. '+' \r\n';
                        }
                    }  
                }else{// update case lookup with case id populated in text field.
                    stagingRec.Case__c = stagingRec.Case_Id__c;
                }
            }

            // UPDATE CONTACT: validate the contact Id
            if(!String.isEmpty(stagingRec.Contact_Id__c)){ 
                System.debug('Contact Id Populated :: ' + cntIds + '--' + stagingRec.Contact_Id__c);
                if(!cntIds.contains(stagingRec.Contact_Id__c)){
                    if(stgingFieldVsColumnHeader.containsKey('Contact_Id__c')){
                        if(String.isEmpty(stagingRec.Failure_Reason__c)){
                            stagingRec.Failure_Reason__c = stgingFieldVsColumnHeader.get('Contact_Id__c') + ' is invalid. '+' \r\n';
                        }else{
                            stagingRec.Failure_Reason__c += stgingFieldVsColumnHeader.get('Contact_Id__c') + ' is invalid. '+' \r\n';
                        }
                    }  
                }else{// update contact lookup with case id populated in text field.
                    System.debug('Contact Id Populated after :: ' + stagingRec.Contact_Id__c);
                    stagingRec.Contact__c = stagingRec.Contact_Id__c;
                }
            }

            // validate location level 3 id is valid.
            if(!String.isEmpty(stagingRec.Location_Level_3_Id__c)){
                if(!taxonomyIds.contains(stagingRec.Location_Level_3_Id__c)){
                    if(stgingFieldVsColumnHeader.containsKey('Location_Level_3_Id__c')){
                        if(String.isEmpty(stagingRec.Failure_Reason__c)){
                            stagingRec.Failure_Reason__c = stgingFieldVsColumnHeader.get('Location_Level_3_Id__c') + ' is invalid. '+' \r\n';
                        }else{
                            stagingRec.Failure_Reason__c += stgingFieldVsColumnHeader.get('Location_Level_3_Id__c') + ' is invalid. '+' \r\n';
                        }
                    }  
                }else{// update location level lookup with case id populated in text field.
                    stagingRec.Location_Level_3__c = stagingRec.Location_Level_3_Id__c;
                }
            }

            // NEW CASE: Will validate the mandatory fields
            if(String.isEmpty(stagingRec.Case_Id__c)){

                Set<Boolean> caseBlankValueCheck = new Set<Boolean>();
                Boolean isCaseBlank = TRUE;
                caseBlankValueCheck.add(FALSE);
                for(String caseFieldName : stagingObjectToCaseMapping.keySet()){
                    if(!caseFieldName.equals('Contact_Id__c')){
                        if(!String.isEmpty(String.valueOf(stagingRec.get(caseFieldName)))){
                            isCaseBlank = FALSE;
                            break;
                        }    
                    }
                    
                }
                // Iterate over the mandatory fields to check if they have values or not
                System.debug('stagingApiNameVsCaseForMandatory :: ' + stagingApiNameVsCaseForMandatory);
                System.debug('isCaseBlank :: ' + isCaseBlank);
                if(isCaseBlank == FALSE){
                    for(String fieldName : stagingApiNameVsCaseForMandatory.keySet()){
                        System.debug('Case field value :: ' + fieldName +'--'+String.valueOf(stagingRec.get(fieldName))+'--'+String.isEmpty(String.valueOf(stagingRec.get(fieldName))) );
                        if(String.isEmpty(String.valueOf(stagingRec.get(fieldName)))){
                            String caseStatus = String.valueOf(stagingRec.Case_Status__c);
                            if(!notMandatoryFields.contains(fieldName)){
                                if(!mandatoryFields.contains(fieldName)){
                                    mandatoryFields.add(fieldName);
                                    if(String.isEmpty(mandatoryFiledError))
                                        mandatoryFiledError = stgingFieldVsColumnHeader.get(fieldName);
                                    else
                                        mandatoryFiledError += ', '+ stgingFieldVsColumnHeader.get(fieldName);
                                }else{
                                    // do nothing
                                }
                            }else if( ((fieldName.equals('Case_Manager__c') && String.isNotEmpty(caseStatus) && caseStatus.equals(GlobalConstants.CASE_IN_PROGRESS_STATUS))
                                || (fieldName.equals('Re_assignment_Reason__c') && String.isNotEmpty(caseStatus) && caseStatus.equals(GlobalConstants.CASE_STATUS_REASSIGNED))
                                || (fieldName.equals('Resolution_Detail__c') && String.isNotEmpty(caseStatus) && caseStatus.equals(GlobalConstants.CASE_SOFTCLOSED_STATUS)) ) ){
                                if(!mandatoryFields.contains(fieldName)){
                                    mandatoryFields.add(fieldName);
                                    if(String.isEmpty(mandatoryFiledError))
                                        mandatoryFiledError = stgingFieldVsColumnHeader.get(fieldName);
                                    else
                                        mandatoryFiledError += ', '+ stgingFieldVsColumnHeader.get(fieldName);
                                }else{
                                    // do nothing
                                }  
                            }
                        }
                    }
                }
            }

            // NEW CONTACT: Will validate the contact mandatory fields
            if(String.isEmpty(stagingRec.Contact_Id__c)){ 
                
                Boolean isContactBlank = TRUE;
                Set<Boolean> contactBlankValueCheck = new Set<Boolean>();
                contactBlankValueCheck.add(FALSE);

                // check if all fields for contact are blank
                for(String contactFieldName : stagingObjectToContactMapping.keySet()){
                    System.debug('Contact Field and value :: ' + contactFieldName +'::'+  String.valueOf(stagingRec.get(contactFieldName)) + '--' + String.isEmpty(String.valueOf(stagingRec.get(contactFieldName))));
                    if(!String.isEmpty(String.valueOf(stagingRec.get(contactFieldName)))){
                       isContactBlank = FALSE;
                       break;
                    }
                }
                System.debug('Check fileds check flag :: ' + contactBlankValueCheck);
                // Check for the contact mandatory fields
                if(isContactBlank == FALSE){
                    // Check for the mandatory fields specified in metadata mapping
                    for(String fieldName : stagingApiNameVsContactForMandatory.keySet()){
                      if(String.isEmpty(String.valueOf(stagingRec.get(fieldName)))){
                            if(!mandatoryFields.contains(fieldName)){
                                mandatoryFields.add(fieldName);
                                if(String.isEmpty(mandatoryFiledError))
                                    mandatoryFiledError = stgingFieldVsColumnHeader.get(fieldName);
                                else
                                    mandatoryFiledError += ', '+ stgingFieldVsColumnHeader.get(fieldName);
                            }else{
                                 // do nothing
                            }
                        }
                    }

                    // check for contact LastName, Email or Phone check
                    if(String.isEmpty(stagingRec.Contact_Second_Name__c) 
                        || (String.isEmpty(stagingRec.Contact_Email__c)
                          && String.isEmpty(stagingRec.Contact_Phone__c)
                          && String.isEmpty(stagingRec.Contact_Mobile__c)
                          && String.isEmpty(stagingRec.Contact_Work__c))){
                        System.debug('Check contact LastName,Email and Phone details');
                        if(stagingRec.Failure_Reason__c == null || stagingRec.Failure_Reason__c == ''){
                            stagingRec.Failure_Reason__c = 'Contact Second Name,Contact Email and any one from Contact Mobile,Phone and Work are Mandatory. '+' \r\n';
                        }else{
                            stagingRec.Failure_Reason__c += 'Contact Second Name,Contact Email and any one from Contact Mobile,Phone and Work are Mandatory. '+' \r\n';
                        }
                    }

                }
            }
			
            // Append error message for all the mandatory fields
            if(mandatoryFields.size() > 0 && mandatoryFields.size() ==1){
                if(stagingRec.Failure_Reason__c == null || stagingRec.Failure_Reason__c == ''){
                    stagingRec.Failure_Reason__c = mandatoryFiledError +' is Mandatory. '+' \r\n';
                }else{
                    stagingRec.Failure_Reason__c += mandatoryFiledError +' is Mandatory. '+' \r\n';
                }
            }else if(mandatoryFields.size() > 1){
                if(stagingRec.Failure_Reason__c == null || stagingRec.Failure_Reason__c == ''){
                    stagingRec.Failure_Reason__c = mandatoryFiledError +' are Mandatory. '+' \r\n';
                }else{
                    stagingRec.Failure_Reason__c += mandatoryFiledError +' are Mandatory. '+' \r\n';
                }
            }
            // Logic to evaluate the bad values for the picklist values mentioned in the csv upload template
            for(String fieldName : MappingRecord.picklistFieldApiName){
                if( stagingRec.get(fieldName) != null && stagingRec.get(fieldName) != '' ){
                    String value = String.valueOf(stagingRec.get(fieldName));
                    System.debug('Field Value :: ' + value + '--' + fieldName + '--' + stagingPicklistFieldNamevsValue);
                    // check if the field picklist value map contains the fieldname
                    if(stagingPicklistFieldNamevsValue.containsKey(fieldName)){
                        //check if picklist value doe not have the field value 
                        if(!(stagingPicklistFieldNamevsValue.get(fieldName)).contains(value)){
                            // check if the staging map has the field name and then get the field label
                            if(stgingFieldVsColumnHeader.containsKey(fieldName)){
                                // check if the Failure reason is blank
                                if(stagingRec.Failure_Reason__c == null || stagingRec.Failure_Reason__c == ''){
                                    stagingRec.Failure_Reason__c = stgingFieldVsColumnHeader.get(fieldName) + ' contains Bad Value. '+' \r\n';
                                }else{
                                    stagingRec.Failure_Reason__c += stgingFieldVsColumnHeader.get(fieldName) + ' contains Bad Value. '+' \r\n';
                                }
                            }
                        } 
                    }
                }
            }
            
            // validate and populated the date time incident on case record.
            if(String.isNotEmpty(stagingRec.Date_Time_of_Incident__c)) {
                String dateTimeOfIncident = stagingRec.Date_Time_of_Incident__c;
                try{
                    DateTime dt = Datetime.valueOf(dateTimeOfIncident);    
                    System.debug('dateTimeOfIncident: '+dateTimeOfIncident);
                }catch(Exception ex ){
                    system.debug('ex:'+ex.getMessage());
                    if(stagingRec.Failure_Reason__c == null || stagingRec.Failure_Reason__c == ''){
                        stagingRec.Failure_Reason__c = ex.getMessage() +' \r\n';
                    }else{
                        stagingRec.Failure_Reason__c += ex.getMessage() +' \r\n';
                    }
                }
            }
	
            System.debug('stagingRec.Failure_Reason__c  :: ' + stagingRec.Failure_Reason__c + '--' + stagingRec );
            if(!String.isBlank(stagingRec.Failure_Reason__c))
                stagingRec.Processing_Status__c = 'Failed';
            else
                stagingRec.Processing_Status__c = 'Success';  
       
            System.debug('stagingRec ::' + stagingRec);
        } 
        System.debug('Get CPU Timeout processStagingRecords 2#: '+Limits.getCpuTime() + '-'+ Limits.getLimitCpuTime() ); 
        
    }
    
}