force-app/main/default/objects/BU_Staging__c/BU_Staging__c.object-meta.xml
<CustomObject>
    <description>Used as a staging object for bulk upload on private operator portal.</description>
    <label>PO Upload</label>
    <nameField>
        <displayFormat>BU - {000000}</displayFormat>
        <label>BU Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Upload</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BU_Staging__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>BU_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>BU_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Location_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Level 3</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipName>BU_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU_Staging__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <defaultValue>&#39;Success&#39;</defaultValue>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BUStagingAfterInsertTriggerHandler.cls
/*------------------------------------------------------------
Author:        Pawan Tiwari
Description:   After Insert handler class for the BUStaging trigger
               Invoke the  UpsertContactHandler class to insert/update the contact 
               Invoke the UpsertCaseHandler class to insert/update the case

History
15-June-2017   Pawan Tiwari       Created.
------------------------------------------------------------*/
public with sharing class BUStagingAfterInsertTriggerHandler extends TriggerHandlerBase{
    
    public override void mainEntry(TriggerParameters tp) {
        process(tp);
    }
    

    private void process(TriggerParameters tp) {
       
        List<BU_Staging__c> stagingList = (List<BU_Staging__c>)tp.newList;

        Map<String,String> stagingWithContactMap = new Map<String,String>();
        Map<String,String> stagingWithCaseMap = new Map<String,String>();

        // Apex class responsible for insert/update of the contact records
        UpsertContactHandler upsertContactHandler = new UpsertContactHandler(stagingList);
        stagingWithContactMap = upsertContactHandler.exceute();
        system.debug('stagingWithContactMap :: ' + stagingWithContactMap);

        // Query to reterive the staging object record updated by UpsertContactHandler apex class 
        String soqlQuery = 'select Case__c, Processing_Status__c, Contact__c, Location_Level_3__c, '+MappingRecord.stagingApiName+' FROM BU_Staging__c WHERE Id IN :stagingList';
        System.debug('soqlQuery :: ' + soqlQuery);
        List<BU_Staging__c> stagingRecordList = Database.Query(soqlQuery);
        
        // Apex class responsible for insert/update of the case records
        UpsertCaseHandler upsertCaseHandler = new UpsertCaseHandler(stagingRecordList);
        stagingWithCaseMap = upsertCaseHandler.exceute(stagingWithContactMap);
        system.debug('stagingWithCaseMap :: ' + stagingWithCaseMap);

        system.debug('***getCpuTime()***'+Limits.getCpuTime());
 
    }

}