force-app/main/default/objects/BU_Staging__c/BU_Staging__c.object-meta.xml
<CustomObject>
    <description>Used as a staging object for bulk upload on private operator portal.</description>
    <label>PO Upload</label>
    <nameField>
        <displayFormat>BU - {000000}</displayFormat>
        <label>BU Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Upload</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BU_Staging__c/fields/Bus_Driver_ID__c.field-meta.xml
<CustomField>
    <fullName>Bus_Driver_ID__c</fullName>
    <label>Bus Driver ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/No_of_Days_to_Delete_BU_Staging_recs__mdt/No_of_Days_to_Delete_BU_Staging_recs__mdt.object-meta.xml
<CustomObject>
    <label>No. of Days to Delete BU Staging recs</label>
    <pluralLabel>No. of Days to Delete BU Staging recs</pluralLabel>
</CustomObject>

force-app/main/default/objects/No_of_Days_to_Delete_BU_Staging_recs__mdt/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Number of Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DeleteBUStagingRecords_Test.cls
@isTest
private class DeleteBUStagingRecords_Test {
	
	@testSetup
    static void setUpTestData(){

    	BU_Staging__c buStagingRecord = new BU_Staging__c(Bus_Driver_ID__c = 'Test Driver ID',Case_Id__c = 'Dummy Id',Case_Manager__c = 'Test Manager');
    	insert buStagingRecord;
    }

    @isTest 
    static void testDeleteBUStagingRecords() {

    	Test.startTest();
            No_of_Days_to_Delete_BU_Staging_recs__mdt metadataRec = [SELECT Number_of_Days__c 
                                                                 FROM No_of_Days_to_Delete_BU_Staging_recs__mdt 
                                                                 WHERE DeveloperName = 'Mapping_001' 
                                                                 LIMIT 1];
        Integer numberOfdays = metadataRec.Number_of_Days__c.intValue();
        
        System.debug('Time: '+System.now().addDays(-numberOfdays).formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
        String dateTimeFormat = System.now().addDays(-numberOfdays).formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        
        String query = 'Select Id FROM BU_Staging__c WHERE CreatedDate > '+dateTimeFormat;

            Database.executeBatch(new BatchExecutor(new DeleteBUStagingRecords(), query, null));
        
        Test.stopTest();

    }
}