force-app/main/default/objects/Additional_Corro_Recipients__c/Additional_Corro_Recipients__c.object-meta.xml
<CustomObject>
    <label>Additional Corro Recipient</label>
    <nameField>
        <displayFormat>ACR-{0000}</displayFormat>
        <label>Additional Corro Recipients Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Corro Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Corro_Recipients__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Additional Corro Recipients</relationshipLabel>
    <relationshipName>Additional_Corro_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Additional_Corro_Recipients__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Additional Corro Recipients</relationshipLabel>
    <relationshipName>Additional_Corro_Recipients</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CaseRecordTypesToExcludeFromRtFlip__c/CaseRecordTypesToExcludeFromRtFlip__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of case record types that needs to be excluded from case record type flips</description>
    <label>CaseRecordTypesToExcludeFromRtFlip</label>
</CustomObject>

force-app/main/default/objects/CaseRecordTypesToExcludeFromRtFlip__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <inlineHelpText>Record type name/label</inlineHelpText>
    <label>Record Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Response</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Unsigned Response</fullName>
            </value>
            <value>
                <fullName>Enclosures</fullName>
            </value>
            <value>
                <fullName>Incoming</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>Stores the standard attachment file name</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/objects/referral_template_by_response_type__c/referral_template_by_response_type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Referral templates by response type</description>
    <label>Referral Template by Response Type</label>
</CustomObject>

force-app/main/default/objects/referral_template_by_response_type__c/fields/Additional_Contact_Attachment_Categories__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contact_Attachment_Categories__c</fullName>
    <description>Additional Contact Attachment Categories</description>
    <inlineHelpText>Additional Contact Attachment Categories</inlineHelpText>
    <label>Additional Contact Attachment Categories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/referral_template_by_response_type__c/fields/Additional_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Additional_Contacts__c</fullName>
    <description>Additional Corro recipient template developer name</description>
    <inlineHelpText>Additional Corro recipient template developer name</inlineHelpText>
    <label>Additional Contacts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/referral_template_by_response_type__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Customer template  developer name</description>
    <inlineHelpText>Customer template  developer name</inlineHelpText>
    <label>Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/referral_template_by_response_type__c/fields/customer_attachment_categories__c.field-meta.xml
<CustomField>
    <fullName>customer_attachment_categories__c</fullName>
    <description>customer attachment categories</description>
    <inlineHelpText>customer attachment categories</inlineHelpText>
    <label>Customer Attachment Categories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/referral_template_by_response_type__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <description>Template for staff member developer name</description>
    <inlineHelpText>Template for staff member developer name</inlineHelpText>
    <label>Staff</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/referral_template_by_response_type__c/fields/Staff_attachment_categories__c.field-meta.xml
<CustomField>
    <fullName>Staff_attachment_categories__c</fullName>
    <description>Staff attachment categories</description>
    <inlineHelpText>Staff attachment categories</inlineHelpText>
    <label>Staff Attachment Categories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendReferral_Test.cls
@isTest
private class SendReferral_Test {
    
    static Case referralCase;
    static Contact customer ;
    static  Contact staff;
    static Contact additionalContact;
    static Additional_Corro_Recipients__c additionalRecipient;
    static referral_template_by_response_type__c templateSetting;

    static void setupTestData() {
        
        //populate customer, staff, and additional contact
        customer = new Contact(Salutation='Mr',LastName='Customer', Firstname='Contact',Email='customer@contact.com');
        staff = new Contact(Salutation='Mr',LastName='Staff', Firstname='Contact',Email='staff@contact.com');
        additionalContact = new Contact(Salutation='Mr',LastName='Additional', Firstname='Contact',Email='additional@contact.com');

        insert new List<Contact>{customer,staff,additionalContact};

        //populate a case record type transport ministreal correspondance
        Map<String,Schema.RecordTypeInfo> rtMapByName =Schema.SObjectType.Case.getRecordTypeInfosByName();
        Schema.RecordTypeInfo minCorRoadRecordType=rtMapByName.get(GlobalConstants.CASE_RECORD_TYPE_LABEL_MINCORR_ROAD);

        referralCase=new Case(
            contactId=customer.Id,
            staff_contact__c=staff.Id,
            recordtypeId=minCorRoadRecordType.getRecordTypeId(),
            response_type__c=GlobalConstants.CASE_RESPONSE_TYPE_PARTIAL_REFERRAL,
            subject= 'test',
            description ='test',
            status=GlobalConstants.MAGS_APPROVED_MIN_CORRO
        );
        
        insert referralCase;
        
        //populate additional corro recipients
        additionalRecipient= new Additional_Corro_Recipients__c(case__c=referralCase.Id,contact__c=additionalContact.Id);
        insert additionalRecipient;
        
        //populate custom settings for Referral
        templateSetting = new referral_template_by_response_type__c(
            
            Name='Partial Referral',
            Additional_Contacts__c='Partial_Referral_Additional_contacts_Template',
            Customer__c='Partial_Referral_Customer_Template',
            Staff__c='Partial_Referral_Staff_Template', 
            Staff_attachment_categories__c='Signed Response', 
            customer_attachment_categories__c='Signed Response', 
            additional_contact_attachment_categories__c='Signed Response,Incoming'
        );
        insert templateSetting;
        

        NoteOrAttachment__c noraIncoming= new NoteOrAttachment__c(
            Name='incoming',
            Category__c='Incoming',
            case__c=referralCase.Id,
            File_Name__c='incoming'
        );
       
        NoteOrAttachment__c noraResponse= new NoteOrAttachment__c(
            Name='Unsigned Response',
            Category__c='Signed Response',
            case__c=referralCase.Id,
            File_Name__c='Signed Response'
        );
        insert new list<NoteOrAttachment__c>{noraResponse,noraIncoming};
       
       
        //todo insert attachments
        Attachment incoming= new Attachment();
        incoming.Body=Blob.valueOf('incoming');
        incoming.Name='incoming';
        incoming.parentId=noraIncoming.Id;
        
        noraIncoming.Attachment__c = incoming.Id;
        
        update noraIncoming;
        
        //todo insert attachments
        Attachment usResponse= new Attachment();
        usResponse.Body=Blob.valueOf('Signed Response');
        usResponse.Name='Signed Response';
        usResponse.parentId=noraResponse.Id;
        insert new List<Attachment>{incoming,usResponse};

        noraResponse.Attachment__c = usResponse.Id;
        
        update noraResponse;
    }
    
    @isTest static void test_sendReferral() {
        
        setupCaseRecTypesToExcludeCS();
        setupTestData();
        
        //set up the id parameter of current page and invoke the sendReferral method
        Test.startTest();
        PageReference sendReferralPageReference= Page.SendReferral;
        system.assertNotEquals(referralCase,null);
        system.assertNotEquals(referralCase.id,null);
        system.assertNotEquals(sendReferralPageReference.getParameters(),null);

        sendReferralPageReference.getParameters().put('id',referralCase.id);
        Test.setCurrentPage(sendReferralPageReference);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Additional_Corro_Recipients__c>{additionalRecipient});
        ssc.setSelected(new List<Additional_Corro_Recipients__c>{additionalRecipient});
        Referrals sendMail = new Referrals(ssc);

        Test.stopTest();
        for(ApexPages.Message msg : ApexPages.getMessages()) {
            System.debug(msg.getSummary());
            System.debug(msg.getDetail());

        }
        system.assertNotEquals(sendMail.recipients,null);
    }
    
    @isTest static void test_send() {
        
        setupCaseRecTypesToExcludeCS();
        setupTestData();
        
        //set up the id parameter of current page and invoke the send method
        //set up the id parameter of current page and invoke the sendReferral method
        PageReference sendReferralPageReference= Page.SendReferral;
        system.assertNotEquals(referralCase,null);
        system.assertNotEquals(referralCase.id,null);
        system.assertNotEquals(sendReferralPageReference.getParameters(),null);
        sendReferralPageReference.getParameters().put('id',referralCase.id);
        Test.setCurrentPage(sendReferralPageReference);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Additional_Corro_Recipients__c>{additionalRecipient});
        ssc.setSelected(new List<Additional_Corro_Recipients__c>{additionalRecipient});
        Referrals sendMail= new Referrals(ssc);
        Test.startTest();
        
        for(Referrals.Recipient recipient : sendMail.recipients) {
            recipient.doSend = true;
        }
        
        sendMail.send();
        Test.stopTest();
        
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
           
            System.debug(msg.getSummary());
            System.debug(msg.getDetail());

        }
        
        Case updatedCase = [select id, Are_All_Recipients_Referrel__c, status from Case where Id=:sendMail.caseId];
        //system.assertEquals(updatedCase.Are_All_Recipients_Referrel__c, true);   
    }
    
    @isTest static void test_sendReferralSettingFailure() {
        
        setupCaseRecTypesToExcludeCS();
        setupTestData();
        
        List<referral_template_by_response_type__c> referralCustomSettings = referral_template_by_response_type__c.getall().values();
        
        delete referralCustomSettings;
        
        //set up the id parameter of current page and invoke the send method
        //set up the id parameter of current page and invoke the sendReferral method
        PageReference sendReferralPageReference= Page.SendReferral;
        system.assertNotEquals(referralCase,null);
        system.assertNotEquals(referralCase.id,null);
        system.assertNotEquals(sendReferralPageReference.getParameters(),null);
        sendReferralPageReference.getParameters().put('id',referralCase.id);
        Test.setCurrentPage(sendReferralPageReference);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Additional_Corro_Recipients__c>{additionalRecipient});
        ssc.setSelected(new List<Additional_Corro_Recipients__c>{additionalRecipient});
        Referrals sendMail= new Referrals(ssc);
        Test.startTest();
        
        for(Referrals.Recipient recipient : sendMail.recipients) {
            recipient.doSend = true;
        }
        
        sendMail.send();
        Test.stopTest();
        
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
           
            System.debug(msg.getSummary());
            System.debug(msg.getDetail());

        }
        
        Case updatedCase= [select id, Are_All_Recipients_Referrel__c, status from Case where Id = :sendMail.caseId];
        system.assertEquals(updatedCase.Are_All_Recipients_Referrel__c, false);   
    }
    
    @isTest static void test_sendReferralFailure() {
        
        setupCaseRecTypesToExcludeCS();
        setupTestData();
        
        //set up the id parameter of current page and invoke the send method
        //set up the id parameter of current page and invoke the sendReferral method
        PageReference sendReferralPageReference= Page.SendReferral;
        system.assertNotEquals(referralCase,null);
        system.assertNotEquals(referralCase.id,null);
        system.assertNotEquals(sendReferralPageReference.getParameters(),null);
        
        //sendReferralPageReference.getParameters().put('id', referralCase.id);
        Test.setCurrentPage(sendReferralPageReference);
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Additional_Corro_Recipients__c>{});
        ssc.setSelected(new List<Additional_Corro_Recipients__c>{});
        Referrals sendMail = new Referrals(ssc);
        
        Case updatedCase= [select id, Are_All_Recipients_Referrel__c, status from Case where Id = :referralCase.Id];
        system.assertEquals(updatedCase.Are_All_Recipients_Referrel__c, false);   
    }
    
    public static void setupCaseRecTypesToExcludeCS() {
   
      List<CaseRecordTypesToExcludeFromRtFlip__c> rtToExclude = new List<CaseRecordTypesToExcludeFromRtFlip__c>();
      rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'General Ministerial Correspondence', Record_Type_Name__c = 'General Ministerial Correspondence'));
      rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Roads & Freight Ministerial Cor', Record_Type_Name__c = 'Roads & Freight Ministerial Correspondence'));
      rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Transport Ministerial Correspondence', Record_Type_Name__c = 'Transport Ministerial Correspondence'));
      rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Campaign', Record_Type_Name__c = 'Campaign'));
      rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Campaign Member', Record_Type_Name__c = 'Campaign Member'));
      rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Erroneous Cases', Record_Type_Name__c = 'Erroneous Cases Ministerial Correspondence'));
      insert rtToExclude;
    } 
}