force-app/main/default/objects/User_Audit__c/User_Audit__c.object-meta.xml
<CustomObject>
    <label>User Audit</label>
    <nameField>
        <label>User Audit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Audit__c/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <label>Activation Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Audit__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Audit__c/fields/Audited_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Audited_User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Audit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Audit__c/fields/Last_Modified_By_User__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Modified By User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Last_Modified_By_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Audit__c/fields/User_License__c.field-meta.xml
<CustomField>
    <fullName>User_License__c</fullName>
    <label>User License</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddUserAudit.cls
public class AddUserAudit {
    
    @future    
     public static void createUserAuditRecord(Id auditedUserId, Id last_Modified_By_User, Datetime last_Modified_Date, String activation_Status, String userLicense, String agency){

		list<User_Audit__c> userAudits = new list<User_Audit__c>();
        //Add user Audit 
         User_Audit__c userAudit = new User_Audit__c();
         userAudit.Activation_Status__c = activation_Status;
         userAudit.Last_Modified_By_User__c = last_Modified_By_User;
         userAudit.Last_Modified_Date__c = last_Modified_Date;
         userAudit.Audited_User_Id__c = auditedUserId;
         userAudit.User_License__c = userLicense;
         userAudit.Agency__c = agency;
         userAudits.add(userAudit);
         
       if(!userAudits.isEmpty() && !Test.isRunningTest())
            insert userAudits;
    }
}