force-app/main/default/objects/WebFeedbackRelatedTo__c/WebFeedbackRelatedTo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Website feedback related to</label>
</CustomObject>

force-app/main/default/objects/WebFeedbackRelatedTo__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Related To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WebFeedbackRelatedTo__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WebsitesForWebForm__c/WebsitesForWebForm__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Websites for webform</label>
</CustomObject>

force-app/main/default/objects/WebsitesForWebForm__c/fields/Website_Name__c.field-meta.xml
<CustomField>
    <fullName>Website_Name__c</fullName>
    <description>Name of website to be displayed on webform</description>
    <inlineHelpText>Name of website to be displayed on webform</inlineHelpText>
    <label>Website Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WebsiteComponentController.cls
public with sharing class WebsiteComponentController {
    public Boolean isIE8 {get; set;}
    public Integer textBoxHeight {get; set;}
    public static final Double CHARACTER_FONT_SIZE_ON_WEBFORM = 20.0;

    public List<String> websiteOptions {
        get{
            Map<String, WebsitesForWebForm__c> options = WebsitesForWebForm__c.getAll();
            List<String> optionValues = new List<String>();
            List<Integer> sortOrder = new List<Integer>();
            Map<Integer, WebsitesForWebForm__c> mapOfWebs = new Map<Integer, WebsitesForWebForm__c>();
            for(WebsitesForWebForm__c website : options.values()) {
                sortOrder.add((Integer)website.Sort_Order__c);
                mapOfWebs.put((Integer)website.Sort_Order__c, website);
            }
            sortOrder.sort();
            for(Integer index : sortOrder) {
                optionValues.add(mapOfWebs.get(index).Website_Name__c);
                if(mapOfWebs.get(index).Website_Name__c.length() > textBoxHeight) {
                    textBoxHeight = mapOfWebs.get(index).Website_Name__c.length();
                }
            }
            textBoxHeight = (Integer)((Math.ceil(textBoxHeight/CHARACTER_FONT_SIZE_ON_WEBFORM) + 1) * CHARACTER_FONT_SIZE_ON_WEBFORM);
            return optionValues;
        }
        set{}}  
    
    /*Dec 2016 - SP : SFCOE - 872 : remove thumbnails : new method added for displaying values as a dropdown on website*/
    public List<SelectOption> websiteOptionsDropDown{
        get{
            Map<String, WebsitesForWebForm__c> options = WebsitesForWebForm__c.getAll();
            List<SelectOption> websiteOptionsList = new List<SelectOption>();
            websiteOptionsList.add(new SelectOption('','Please select'));
            List<Integer> listOfValues = new List<Integer>();
            Map<Integer, String> orderVsValue = new Map<Integer, String>();
            for(WebsitesForWebForm__c option : options.values()) {            
                listOfValues.add(Integer.valueOf(option.Sort_Order__c));
                orderVsValue.put(Integer.valueOf(option.Sort_Order__c), option.Website_Name__c);
            }
            listOfValues.sort();
            for(Integer values : listOfValues) {
                String websiteName = orderVsValue.get(values);
                if(websiteName.indexOf('(') != -1 && websiteName.indexOf('State Transit') == -1)
					websiteName = websiteName.substring(0, websiteName.indexOf('('));
                
                websiteOptionsList.add(new SelectOption(orderVsValue.get(values), websiteName));
            }
            websiteOptionsList.add(new SelectOption('Other', 'Other'));
            return websiteOptionsList;
            
        }
        set{}}
    
    public List<SelectOption> relatedTo{
        get{
            Map<String, WebFeedbackRelatedTo__c> options = WebFeedbackRelatedTo__c.getAll();
            List<SelectOption> relatedToOptions = new List<SelectOption>();
            relatedToOptions.add(new SelectOption('','Please select'));
            List<Integer> listOfValues = new List<Integer>();
            Map<Integer, String> orderVsValue = new Map<Integer, String>();
            for(WebFeedbackRelatedTo__c option : options.values()) {
                listOfValues.add(Integer.valueOf(option.Sort_Order__c));
                orderVsValue.put(Integer.valueOf(option.Sort_Order__c), option.Related_To__c);
            }
            listOfValues.sort();
            for(Integer values : listOfValues) {
                
                String relatedToValuesName = orderVsValue.get(values);
                if(relatedToValuesName.indexOf('(') != -1)
					relatedToValuesName = relatedToValuesName.substring(0, relatedToValuesName.indexOf('(')-1);
                
                relatedToOptions.add(new SelectOption(orderVsValue.get(values), relatedToValuesName));
            }
            return relatedToOptions;
            
        }
        set{}} 
        
    public List<SelectOption> yesNoOption { set{}
        get{
            List<SelectOption> options = new List<SelectOption>();
            options.add(new SelectOption('Yes','Yes'));
            options.add(new SelectOption('No','No'));
            return options;
        }
        } 
    
    public WebsiteComponentController() {
        textBoxHeight = 0;
        String userAgent = ApexPages.currentPage().getHeaders().get('User-Agent');
        if(!String.isBlank(userAgent) && userAgent.contains('MSIE 8')) {
            isIE8 = true;
        } else {
            isIE8 = false;
        }
    }
    
}