force-app/main/default/objects/WebFeedbackRelatedTo__c/WebFeedbackRelatedTo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Website feedback related to</label>
</CustomObject>

force-app/main/default/objects/WebFeedbackRelatedTo__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Related To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WebFeedbackRelatedTo__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WebsitesForWebForm__c/WebsitesForWebForm__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Websites for webform</label>
</CustomObject>

force-app/main/default/objects/WebsitesForWebForm__c/fields/Website_Name__c.field-meta.xml
<CustomField>
    <fullName>Website_Name__c</fullName>
    <description>Name of website to be displayed on webform</description>
    <inlineHelpText>Name of website to be displayed on webform</inlineHelpText>
    <label>Website Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WebsiteComponentController_Test.cls
@isTest
private class WebsiteComponentController_Test {
    
    private static testMethod void testForAvailableWebsites() {
        List<WebsitesForWebForm__c> websites = new List<WebsitesForWebForm__c>();
        websites.add(new WebsitesForWebForm__c(Name='newcastlebuses.info',Website_Name__c='newcastlebuses.info', Sort_Order__c = 1));
        websites.add(new WebsitesForWebForm__c(Name='nswtrainlink.info',Website_Name__c='nswtrainlink.info', Sort_Order__c = 2));
        insert websites;
        
        System.Test.startTest();
        System.Test.setCurrentPage(System.Page.WebToCaseForm);
        ApexPages.currentPage().getHeaders().put('User-Agent', 'MSIE 8');
        WebsiteComponentController acc = new WebsiteComponentController();
        List<String> websiteList = acc.websiteOptions ;
        List<SelectOption> websiteOptions = acc.websiteOptionsDropDown;
        System.Test.stopTest();
        System.assert(websiteList.size() == 2);
        System.assertNotEquals(websiteOptions,null);
    }
    
    private static testMethod void testForRelatedToField() {
        List<WebFeedbackRelatedTo__c> relatedTo = new List<WebFeedbackRelatedTo__c>();
        relatedTo.add(new WebFeedbackRelatedTo__c(name = '1', Related_To__c = 'Service disruption info', Sort_Order__c = 1));
        relatedTo.add(new WebFeedbackRelatedTo__c(name = '2', Related_To__c = 'Ticketing information', Sort_Order__c = 2));
        insert relatedTo;
        System.Test.startTest();
        System.Test.setCurrentPage(System.Page.WebToCaseForm);
        ApexPages.currentPage().getHeaders().put('User-Agent', 'MSIE 11');
        WebsiteComponentController acc = new WebsiteComponentController();
        List<SelectOption> relatedToList = acc.relatedTo;
        System.Test.stopTest();
        System.assert(relatedToList.size() == 3);
    }
    
    private static testMethod void testForOptions() {
        System.Test.startTest();
        WebsiteComponentController acc = new WebsiteComponentController();
        List<SelectOption> options = acc.yesNoOption;
        System.Test.stopTest();
        System.assert(options.size() == 2);
    }
}