force-app/main/default/objects/CaseRecordTypesToExcludeFromRtFlip__c/CaseRecordTypesToExcludeFromRtFlip__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of case record types that needs to be excluded from case record type flips</description>
    <label>CaseRecordTypesToExcludeFromRtFlip</label>
</CustomObject>

force-app/main/default/objects/CaseRecordTypesToExcludeFromRtFlip__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <inlineHelpText>Record type name/label</inlineHelpText>
    <label>Record Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Response</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Unsigned Response</fullName>
            </value>
            <value>
                <fullName>Enclosures</fullName>
            </value>
            <value>
                <fullName>Incoming</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/IsMinCorroCaseNote__c.field-meta.xml
<CustomField>
    <fullName>IsMinCorroCaseNote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Note is associated to a MinCorro case</description>
    <label>IsMinCorroCaseNote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/objects/Precedent__c/Precedent__c.object-meta.xml
<CustomObject>
    <label>Precedent</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Precedent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Precedents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Precedent__c/fields/Precedent_Case__c.field-meta.xml
<CustomField>
    <fullName>Precedent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Precedent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Precedent Cases</relationshipLabel>
    <relationshipName>PrecedentCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Precedent__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Precedent Cases</relationshipLabel>
    <relationshipName>Precedents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PreviousCorro_Document_Count__c/PreviousCorro_Document_Count__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to get total number of previous corro documents to be shown in mo view.</description>
    <label>PreviousCorro Document Count</label>
</CustomObject>

force-app/main/default/objects/PreviousCorro_Document_Count__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AttachmentInformation_Test.cls
@isTest
private class AttachmentInformation_Test {
    
    
    @testSetup
    static void setUpCase(){
        setupCaseRecTypesToExcludeCS();

        Contact newContact = new Contact();
        newContact.LastName = 'Test';
        newContact.Email = 'test@test.com';
        newContact.Phone = '1234234';
        insert newContact;

        Case transportCase1 = getTransportCaseRecord();
        
        transportCase1.OBO__c = newContact.Id;

        Case transportCase2 = getTransportCaseRecord();
       
        transportCase2.OBO__c = newContact.Id;
        insert new List<Case>{transportCase1, transportCase2};

        PreviousCorro_Document_Count__c setting = new PreviousCorro_Document_Count__c();
        setting.Name = 'Previous Corro';
        setting.Count__c = 3;
        insert setting;

    }
        
    @isTest static void getIncomingAttachmentTest() {

        Test.startTest();
        List<Case> getCase = [Select Id FROM Case LIMIT 1];
        
        if(getCase.size() > 0){
            createAttachment(getCase[0].Id, GlobalConstants.INCOMING,'Incoming PDF');
            Map<Id,AttachmentInfo> attachmentMap;
            attachmentMap = AttachmentInformation.getIncomingAttachment(getCase[0].Id,GlobalConstants.INCOMING);
            System.assertEquals(1,attachmentMap.size());
        }
        Test.stopTest();
    }

    @isTest static void getAdviceAttachmentTest() {

        Test.startTest();
        List<Case> getCase = [Select Id FROM Case LIMIT 1];
        if(getCase.size() > 0){
            createAttachment(getCase[0].Id, GlobalConstants.ATTACHMENT_CATEGORY_ADVICE,'APN123');
            createAttachment(getCase[0].Id, '','Advice');

            Map<Id,AttachmentInfo> attachmentMap;
            attachmentMap = AttachmentInformation.getAdviceAttachment(getCase[0].Id);
            System.assertEquals(1,attachmentMap.size());
            attachmentMap = AttachmentInformation.getAdviceAttachment(getCase[0].Id);
            System.assertEquals(1,attachmentMap.size());
        }
        Test.stopTest();
    }

    @isTest static void getPrecedentAttachmentTest() {

        Test.startTest();
        List<Case> getCase = [Select Id FROM Case LIMIT 2];
        if(getCase.size() > 0){
    
            createAttachment(getCase[0].Id, GlobalConstants.ATTACHMENT_CATEGORY_SIGNED_RESPONSE,'Signed Response');
            
            Precedent__c precdentCase = new Precedent__c();
            precdentCase.Related_Case__c = getCase[1].Id;
            precdentCase.Precedent_Case__c = getCase[0].Id;
            insert precdentCase;

            Map<Id,AttachmentInfo> attachmentMap;
            attachmentMap = AttachmentInformation.getPrecedentAttachment(getCase[1].Id);
            System.assertEquals(1,attachmentMap.size());
        }
        Test.stopTest();
    }

    @isTest static void getPreviousCorroAttachmentTest() {
        Test.startTest();
        List<Case> getCase = [Select Id FROM Case ORDER BY CreatedDate DESC LIMIT 2];
        if(getCase.size() > 0){
    
            createAttachment(getCase[0].Id, GlobalConstants.ATTACHMENT_CATEGORY_SIGNED_RESPONSE,'Signed Response');
            createAttachment(getCase[1].Id, GlobalConstants.ATTACHMENT_CATEGORY_SIGNED_RESPONSE,'Signed Response');
            
            Map<Id,AttachmentInfo> attachmentMap;
            attachmentMap = AttachmentInformation.getPreviousCorroAttachment(getCase[0].Id);
            System.assertEquals(1,attachmentMap.size());
        }
        Test.stopTest();
    }

    private static void createAttachment(String caseId, String attachmentCategory,String name){

        NoteOrAttachment__c responseCustomAttachment;

        responseCustomAttachment = new NoteOrAttachment__c();
        responseCustomAttachment.Name = name;
        responseCustomAttachment.ContentType__c = 'application/pdf';
        responseCustomAttachment.Case__c = caseId;
        responseCustomAttachment.IsMinCorroCaseNote__c = TRUE;
        responseCustomAttachment.Category__c = attachmentCategory;
       
        insert responseCustomAttachment;
       
        Attachment attach = new Attachment();    
        attach.Name = name;
        Blob bodyBlob = Blob.valueOf(name);
        attach.body = bodyBlob;
        attach.parentId = responseCustomAttachment.Id;
        insert attach;
        
        responseCustomAttachment.Attachment__c = attach.Id;
        update responseCustomAttachment;
    }

    /*------------------------------------------------------------------- ----------------
    Author:        
    Description:   This method creates a transport case record sobject
    -----------------------------------------------------------------------------------*/
    private static Case getTransportCaseRecord() {
       
        RecordType rt = [Select Id From RecordType Where DeveloperName =: GlobalConstants.CASE_RECORD_TYPE_NAME_MINCORR_TRANSPORT limit 1];
       
        return new Case(Subject = 'Pothole',
                            Description = 'Theres a pothole in the east street, west end crossing in front of busstop',                       
                            Status = 'MAGS Approved',
                            RecordTypeId = rt.Id,
                            Priority = 'Normal',
                            Modes__c = 'MAGS', 
                            MO_User__c = NULL,
                            Response_Type__c = 'Draft response',
                            Signatory__c = 'Minister for Transport and Infrastructure');
    }

    public static void setupCaseRecTypesToExcludeCS() {
   
        List<CaseRecordTypesToExcludeFromRtFlip__c> rtToExclude = new List<CaseRecordTypesToExcludeFromRtFlip__c>();
        rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'General Ministerial Correspondence', Record_Type_Name__c = 'General Ministerial Correspondence'));
        rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Roads & Freight Ministerial Cor', Record_Type_Name__c = 'Roads & Freight Ministerial Correspondence'));
        rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Transport Ministerial Correspondence', Record_Type_Name__c = 'Transport Ministerial Correspondence'));
        rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Campaign', Record_Type_Name__c = 'Campaign'));
        rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Campaign Member', Record_Type_Name__c = 'Campaign Member'));
        rtToExclude.add(new CaseRecordTypesToExcludeFromRtFlip__c(Name= 'Erroneous Cases', Record_Type_Name__c = 'Erroneous Cases Ministerial Correspondence'));
        insert rtToExclude;
    }
    
}