force-app/main/default/objects/DFSIScheduledJobRun__c/DFSIScheduledJobRun__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom settings is to capture the scheduled job end time</description>
    <label>DFSIScheduledJobRun</label>
</CustomObject>

force-app/main/default/objects/DFSIScheduledJobRun__c/fields/LastJobEndTime__c.field-meta.xml
<CustomField>
    <fullName>LastJobEndTime__c</fullName>
    <description>This field captures the end time of the last job</description>
    <label>LastJobEndTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DFSICaseFeedbackAssistScheduleTest.cls
@istest
global class DFSICaseFeedbackAssistScheduleTest {
    
    @testSetup
    static void init() {
        DFSIScheduledJobRun__c jobSetting = new DFSIScheduledJobRun__c(Name='DFSI', LastJobEndTime__c = Datetime.now());
        insert jobSetting;
    }
    @istest
    static void testSchedule(){
		init();        
        Test.startTest();

        DFSICaseFeedbackAssistSchedule ds = new DFSICaseFeedbackAssistSchedule();
		String sch = '0 0 23 * * ?'; 
        
        Id jobID=system.schedule('Test DFSI Feedback Assist Schedule', sch, ds); 
        CronTrigger ct = [SELECT TimesTriggered, NextFireTime
    					  FROM CronTrigger 
                          WHERE Id = :jobID];
        System.assertEquals(0, ct.TimesTriggered);

        Test.stopTest();
    }
}