force-app/main/default/objects/Case_sharing_criteria_for_SNSW__c/Case_sharing_criteria_for_SNSW__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of criterion to auto-share cases created from web with SNSW. List of entries will be used with OR condition.</description>
    <label>Case sharing criteria for SNSW</label>
</CustomObject>

force-app/main/default/objects/Case_sharing_criteria_for_SNSW__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>API name of field to be used for criteria matching</description>
    <inlineHelpText>API name of field to be used for criteria matching</inlineHelpText>
    <label>Field</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_sharing_criteria_for_SNSW__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>value of field to be used for criteria matching</description>
    <inlineHelpText>value of field to be used for criteria matching</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AutoShareWebCasesWithSNSW.cls
public without sharing class AutoShareWebCasesWithSNSW {

    private List<Case> cases;
    private Map<String, Case_sharing_criteria_for_SNSW__c> sharingCriterions;
    public AutoShareWebCasesWithSNSW(List<Case> cases) {
        if(cases == null || cases.isEmpty()) {
            throw new InvalidDataException('Failed to share case with SNSW. Case details missing');
        }
        this.cases = cases;
        sharingCriterions = Case_sharing_criteria_for_SNSW__c.getAll();
    }
    
    public void shareQualifiedCases() {
        for(Case caseRecord : cases) {
            if(isQualifiedForSharing(caseRecord)) {
                caseRecord.Responsible_Party__c = GlobalConstants.RESPONSIBLE_PARTY_SNSW;
            }
        }
    }
    
    private Boolean isQualifiedForSharing(Case caseRecord) {        
        for(Case_sharing_criteria_for_SNSW__c criteria : sharingCriterions.values()) {
            String currValue = String.valueOf(caseRecord.get(criteria.Field__c));
            System.debug(LoggingLevel.INFO, 'Current Value: ' + currValue);
            System.debug(LoggingLevel.INFO, 'Criteria Value: ' + criteria.Value__c);
            
            if(GlobalConstants.WEB2CASE_ORIGIN.equalsIgnoreCase(caseRecord.Origin) && currValue != null && criteria.Value__c.equalsIgnoreCase(currValue)
                    && (String.isBlank(caseRecord.Created_By_Email__c) || !caseRecord.Created_By_Email__c.contains(GlobalConstants.SNSW_EMAIL_DOMAIN) )) {
                return true;
            }
        }
        return false;
    }
    
    public class InvalidDataException extends Exception {}
}