force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Customer_facing_sort_order__c.field-meta.xml
<CustomField>
    <fullName>Customer_facing_sort_order__c</fullName>
    <label>Customer facing sort order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Customer_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Value__c</fullName>
    <description>Allows the customer facing value to be different from the internal / staff-facing taxonomy value</description>
    <inlineHelpText>Defines the value that customers can select if this taxonomy item is visible in customer-facing channels (i.e. on the web).</inlineHelpText>
    <label>Customer Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaxonomySorter.cls
public with sharing class TaxonomySorter {
    private static final Integer HIGH_SORT_INT_VALUE = 99999;
    private static final String HIGH_SORT_STR_VALUE = 'ZZZZZZ';
    
    public static List<Taxonomy_Metadata__c> sort(List<Taxonomy_Metadata__c> taxonomy) {
        List<Taxonomy_Metadata__c> sortedTaxonomy = new List<Taxonomy_Metadata__c>();
        if(taxonomy == null || taxonomy.isEmpty()) {
            return sortedTaxonomy;
        }
        Set<String> taxoValues = new Set<String>();
        Map<Integer, List<Taxonomy_Metadata__c>> orderVsTaxo = new Map<Integer, List<Taxonomy_Metadata__c>>();
        for(Taxonomy_Metadata__c taxo : taxonomy) {
            if(taxo.Customer_facing_sort_order__c == null) {
                taxo.Customer_facing_sort_order__c = HIGH_SORT_INT_VALUE;
            }
            if(!orderVsTaxo.containsKey(Integer.valueOf(taxo.Customer_facing_sort_order__c))) {
                orderVsTaxo.put(Integer.valueOf(taxo.Customer_facing_sort_order__c), new List<Taxonomy_Metadata__c>());
            }
            if(!taxoValues.contains(taxo.Customer_Value__c)) {
                orderVsTaxo.get(Integer.valueOf(taxo.Customer_facing_sort_order__c)).add(taxo);
                taxoValues.add(taxo.Customer_Value__c);
            }            
        }
        
        for(Integer order : orderVsTaxo.keySet()) {
            orderVsTaxo.put(order, sortBasedOnName(orderVsTaxo.get(order)));
        }
        
        List<Integer> taxoOrder = new List<Integer>();
        taxoOrder.addAll(orderVsTaxo.keySet());
        taxoOrder.sort();
        for(Integer order : taxoOrder) {
            if(order == HIGH_SORT_INT_VALUE) {
                for(Taxonomy_Metadata__c taxo : orderVsTaxo.get(order)) {
                    taxo.Customer_facing_sort_order__c = null;
                }
            }
            sortedTaxonomy.addAll(orderVsTaxo.get(order));
        }
        
        return sortedTaxonomy;
    }
    
    private static List<Taxonomy_Metadata__c> sortBasedOnName(List<Taxonomy_Metadata__c> taxonomy) {
        List<Taxonomy_Metadata__c> sortedTaxo = new List<Taxonomy_Metadata__c>();
        Set<String> taxoValues = new Set<String>();
        Map<String, List<Taxonomy_Metadata__c>> nameVsTaxo = new Map<String, List<Taxonomy_Metadata__c>>();
        for(Taxonomy_Metadata__c taxo : taxonomy) {
            if(String.isBlank(taxo.Customer_Value__c)) {
                taxo.Customer_Value__c = HIGH_SORT_STR_VALUE;
            }
            if(!nameVsTaxo.containsKey(taxo.Customer_Value__c)) {
                nameVsTaxo.put(taxo.Customer_Value__c, new List<Taxonomy_Metadata__c>());
            }
            if(!taxoValues.contains(taxo.Customer_Value__c)) {
                nameVsTaxo.get(taxo.Customer_Value__c).add(taxo);
                taxoValues.add(taxo.Customer_Value__c);
            }            
        }
        List<String> taxoNames = new List<String>();
        taxoNames.addAll(nameVsTaxo.keySet());
        taxoNames.sort();
        for(String name : taxoNames) {
            if(name == HIGH_SORT_STR_VALUE) {
                for(Taxonomy_Metadata__c taxo : nameVsTaxo.get(name)) {
                    taxo.Customer_Value__c = '';
                }
            }
            sortedTaxo.addAll(nameVsTaxo.get(name));
        }
        return sortedTaxo;
    }
}