force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>NSW Trains</fullName>
            </value>
            <value>
                <fullName>RMS</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>STA</fullName>
            </value>
            <value>
                <fullName>Sydney Trains</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>PBO</fullName>
            </value>
            <value>
                <fullName>Newcastle Transport</fullName>
            </value>
            <value>
                <fullName>LRO</fullName>
            </value>
            <value>
                <fullName>MTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Customer_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Value__c</fullName>
    <description>Allows the customer facing value to be different from the internal / staff-facing taxonomy value</description>
    <inlineHelpText>Defines the value that customers can select if this taxonomy item is visible in customer-facing channels (i.e. on the web).</inlineHelpText>
    <label>Customer Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access &amp; Convenience</fullName>
            </value>
            <value>
                <fullName>Cleanliness</fullName>
            </value>
            <value>
                <fullName>Comfort</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Security</fullName>
            </value>
            <value>
                <fullName>Ticketing</fullName>
            </value>
            <value>
                <fullName>Timeliness</fullName>
            </value>
            <value>
                <fullName>Timetables</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Staff/Customer Service</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Licensing &amp; Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Issue_Accountability__c.field-meta.xml
<CustomField>
    <fullName>Issue_Accountability__c</fullName>
    <inlineHelpText>Defines which area is accountable for case management when this taxonomy item is selected (where case management can be determined purely by case category or location alone)</inlineHelpText>
    <label>Issue Accountability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Customer Liaison Team</fullName>
            </value>
            <value>
                <fullName>Depot</fullName>
            </value>
            <value>
                <fullName>IDD Pacific Highway</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Maritime Boating Operations</fullName>
            </value>
            <value>
                <fullName>Maritime Statewide Coordination</fullName>
            </value>
            <value>
                <fullName>Road Maintenance</fullName>
            </value>
            <value>
                <fullName>SEG Government Information Services</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>Speed Limits and Cameras</fullName>
            </value>
            <value>
                <fullName>Traffic Management &amp; Safety</fullName>
            </value>
            <value>
                <fullName>JMD - TOLLING</fullName>
            </value>
            <value>
                <fullName>Road rules</fullName>
            </value>
            <value>
                <fullName>IDD - CONTRACTS &amp; PROJECT STRATEGY</fullName>
            </value>
            <value>
                <fullName>IDD - Greater Sydney Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Freight &amp; Regional Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Commercial</fullName>
            </value>
            <value>
                <fullName>IDD - Pacific Highway Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Western Sydney Program Office</fullName>
            </value>
            <value>
                <fullName>RMS - CEP - Govt Information Services</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Sydney or Regional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <label>KPI</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Cleanliness</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Internal Matters</fullName>
            </value>
            <value>
                <fullName>OTR</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Ticketing</fullName>
            </value>
            <value>
                <fullName>Timetable</fullName>
            </value>
            <value>
                <fullName>Not Categorised</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Taxonomy_Metadata__c.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Taxonomy_Metadata__c.Type__c</field>
            <operation>equals</operation>
            <value>Mode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Meta Categorisations</relationshipLabel>
    <relationshipName>Child_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Customer_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Customer_Facing__c</fullName>
    <inlineHelpText>Indicates whether this value is available for selection on customer-facing channels (i.e. web)</inlineHelpText>
    <label>Status - Customer Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Staff_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Staff_Facing__c</fullName>
    <inlineHelpText>Identifies whether this value is available (active) for selection in staff-facing channels</inlineHelpText>
    <label>Status - Staff Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebToCaseCreator_Test.cls
@isTest
private class WebToCaseCreator_Test {
    
    private static Case caseRecord;
    private static String mode;
    
    private static testMethod void testForInvalidData() {
        System.Test.startTest();
        try {
            WebToCaseCreator caseCreator = new WebToCaseCreator(caseRecord);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }       
        System.Test.stopTest();
    }
    
    private static testMethod void testForRmsCaseWithSubCategorySelected() {
        mode = 'Road';
        setUpTestData();
        caseRecord.Taxonomy_Transaction__c = 'Road rules';
        caseRecord.Taxonomy_Symptom__c = 'Parking rules';
        System.Test.startTest();
        WebToCaseCreator caseCreator = new WebToCaseCreator(caseRecord);
        caseRecord = caseCreator.insertCase();
        System.Test.stopTest();
        List<Case> cases = [SELECT Id, Taxonomy_Transaction__c, Taxonomy_Symptom__c, Agency__c FROM Case WHERE Id = :caseRecord.Id];
        System.assert(!cases.isEmpty());
        System.assert(cases[0].Taxonomy_Transaction__c == 'Road rules');
        System.assert(cases[0].Taxonomy_Symptom__c == 'Parking rules');
        System.assert(cases[0].Agency__c == 'SNSW');
    }
    
    private static testMethod void testForRmsCaseWithSubCategoryNotSelected() {
        mode = 'Road';
        setUpTestData();
        caseRecord.Taxonomy_Transaction__c = 'Road rules';
        System.Test.startTest();
        WebToCaseCreator caseCreator = new WebToCaseCreator(caseRecord);
        caseRecord = caseCreator.insertCase();
        System.Test.stopTest();
        List<Case> cases = [SELECT Id, Taxonomy_Transaction__c, Taxonomy_Symptom__c, Agency__c FROM Case WHERE Id = :caseRecord.Id];
        System.assert(!cases.isEmpty());
        System.assert(cases[0].Taxonomy_Transaction__c == 'Road rules');
        System.assert(String.isBlank(cases[0].Taxonomy_Symptom__c));
        System.assert(String.isBlank(cases[0].Agency__c));
    }
    
    private static testMethod void testForRmsCaseWithoutCategory() {
        mode = 'Road';
        setUpTestData();
        caseRecord.Taxonomy_Transaction__c = '';
        System.Test.startTest();
        WebToCaseCreator caseCreator = new WebToCaseCreator(caseRecord);
        caseRecord = caseCreator.insertCase();
        System.Test.stopTest();
        List<Case> cases = [SELECT Id, Taxonomy_Transaction__c, Taxonomy_Symptom__c, Agency__c FROM Case WHERE Id = :caseRecord.Id];
        System.assert(!cases.isEmpty());
        System.assert(String.isBlank(cases[0].Taxonomy_Transaction__c));
        System.assert(String.isBlank(cases[0].Taxonomy_Symptom__c));
        System.assert(String.isBlank(cases[0].Agency__c));
    }
    
    private static testMethod void testForBusCaseWithoutCategory() {
        mode = 'Bus';
        setUpTestData();
        caseRecord.Taxonomy_Transaction__c = '';
        System.Test.startTest();
        WebToCaseCreator caseCreator = new WebToCaseCreator(caseRecord);
        caseRecord = caseCreator.insertCase();
        System.Test.stopTest();
        List<Case> cases = [SELECT Id, Taxonomy_Transaction__c, Taxonomy_Symptom__c, Agency__c FROM Case WHERE Id = :caseRecord.Id];
        System.assert(!cases.isEmpty());
        System.assert(String.isBlank(cases[0].Taxonomy_Transaction__c));
        System.assert(String.isBlank(cases[0].Taxonomy_Symptom__c));
        System.assert(String.isBlank(cases[0].Agency__c));
    }

    private static testMethod void testForSNSWCaseCreatedBySNSWTeam() {
        mode = 'Road';
        setUpTestData();
        caseRecord.Taxonomy_Transaction__c = 'Road rules';
        caseRecord.Taxonomy_Symptom__c = 'Parking rules';
        caseRecord.Created_By_Email__c = 'test' + GlobalConstants.SNSW_EMAIL_DOMAIN;
        System.Test.startTest();
        WebToCaseCreator caseCreator = new WebToCaseCreator(caseRecord);
        caseRecord = caseCreator.insertCase();
        System.Test.stopTest();
        List<Case> cases = [SELECT Id, Taxonomy_Transaction__c, Taxonomy_Symptom__c, Agency__c FROM Case WHERE Id = :caseRecord.Id];
        System.assert(!cases.isEmpty());
        System.assert(cases[0].Taxonomy_Transaction__c == 'Road rules');
        System.assert(cases[0].Taxonomy_Symptom__c == 'Parking rules');
        System.assert(cases[0].Agency__c == 'RMS');
    }
    
    private static void setUpTestData() {
        createCase();
        createTaxonomy();
    }
    
    private static void createCase() {
        caseRecord = new Case();
        caseRecord.Modes__c = mode;
        caseRecord.Taxonomy_Accountability__c = '';
        caseRecord.Taxonomy_Location__c = 'Sydney';
        caseRecord.Agency__c = '';
        caseRecord.Origin = 'Web';
        caseRecord.Priority = 'Normal';
        caseRecord.Type = 'Compliment';
        caseRecord.Description = 'Test case for web to case creation'; 
    }
    
    private static void createTaxonomy() {      
        Taxonomy_Metadata__c roadTaxonomy = new Taxonomy_Metadata__c();
        roadTaxonomy.Type__c = 'Mode';
        roadTaxonomy.Status_Customer_Facing__c = 'Active';
        roadTaxonomy.Status_Staff_Facing__c = 'Active';
        roadTaxonomy.Customer_Value__c = mode;
        roadTaxonomy.Name = mode;
        
        insert roadTaxonomy;
        
        List<Taxonomy_Metadata__c> level1Taxonomies = new List<Taxonomy_Metadata__c>();
        Taxonomy_Metadata__c level1Loc = new Taxonomy_Metadata__c();
        level1Loc.Type__c = 'Location';
        level1Loc.Status_Customer_Facing__c = 'Active';
        level1Loc.Status_Staff_Facing__c = 'Active';
        level1Loc.Customer_Value__c = 'Region';
        level1Loc.Name = 'Region';
        level1Loc.Parent_Id__c = roadTaxonomy.Id;
        level1Taxonomies.add(level1Loc);
        
        Taxonomy_Metadata__c level1Issue = new Taxonomy_Metadata__c();
        level1Issue.Type__c = 'Issue';
        level1Issue.Status_Customer_Facing__c = 'Active';
        level1Issue.Status_Staff_Facing__c = 'Active';
        level1Issue.Customer_Value__c = 'Road';
        level1Issue.Name = 'Road';
        level1Issue.Parent_Id__c = roadTaxonomy.Id;
        level1Taxonomies.add(level1Issue);
        
        insert level1Taxonomies;
        
        List<Taxonomy_Metadata__c> level2Taxonomies = new List<Taxonomy_Metadata__c>();
        Taxonomy_Metadata__c level2Loc = new Taxonomy_Metadata__c();
        level2Loc.Type__c = 'Location';
        level2Loc.Status_Customer_Facing__c = 'Active';
        level2Loc.Status_Staff_Facing__c = 'Active';
        level2Loc.Customer_Value__c = 'Sydney';
        level2Loc.Name = 'Sydney';
        level2Loc.Parent_Id__c = level1Loc.Id;
        level2Taxonomies.add(level2Loc);
        
        Taxonomy_Metadata__c level2Issue = new Taxonomy_Metadata__c();
        level2Issue.Type__c = 'Issue';
        level2Issue.Status_Customer_Facing__c = 'Active';
        level2Issue.Status_Staff_Facing__c = 'Active';
        level2Issue.Customer_Value__c = 'Road rules';
        level2Issue.Name = 'Road rules';
        level2Issue.Parent_Id__c = level1Issue.Id;
        level2Taxonomies.add(level2Issue);
        
        insert level2Taxonomies;
        
        List<Taxonomy_Metadata__c> level3Taxonomies = new List<Taxonomy_Metadata__c>();
        Taxonomy_Metadata__c taxonomyLoc = new Taxonomy_Metadata__c();
        taxonomyLoc.Agency__c = '';
        taxonomyLoc.Customer_Value__c = 'Sydney';
        taxonomyLoc.Name = 'Sydney';
        taxonomyLoc.Issue_Accountability__c = 'Test Location Taxonomy';
        taxonomyLoc.Driver__c = '';
        taxonomyLoc.KPI__c = '';
        taxonomyLoc.Parent_Id__c = level2Loc.Id;
        taxonomyLoc.Status_Customer_Facing__c = 'Active';
        taxonomyLoc.Status_Staff_Facing__c = 'Active';
        taxonomyLoc.Type__c = 'Location'; 

        Taxonomy_Metadata__c taxonomyIssue = new Taxonomy_Metadata__c();
        taxonomyIssue.Agency__c = 'SNSW';
        taxonomyIssue.Customer_Value__c = 'Parking rules';
        taxonomyIssue.Name = 'Parking rules';
        taxonomyIssue.Issue_Accountability__c = 'Test Location Taxonomy';
        taxonomyIssue.Driver__c = '';
        taxonomyIssue.KPI__c = '';
        taxonomyIssue.Parent_Id__c = level2Issue.Id;
        taxonomyIssue.Status_Customer_Facing__c = 'Active';
        taxonomyIssue.Status_Staff_Facing__c = 'Active';
        taxonomyIssue.Type__c = 'Issue';        
        level3Taxonomies.add(taxonomyIssue);
        level3Taxonomies.add(taxonomyLoc);
        insert level3Taxonomies;
    }
}