force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>NSW Trains</fullName>
            </value>
            <value>
                <fullName>RMS</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>STA</fullName>
            </value>
            <value>
                <fullName>Sydney Trains</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>PBO</fullName>
            </value>
            <value>
                <fullName>Newcastle Transport</fullName>
            </value>
            <value>
                <fullName>LRO</fullName>
            </value>
            <value>
                <fullName>MTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Customer_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Value__c</fullName>
    <description>Allows the customer facing value to be different from the internal / staff-facing taxonomy value</description>
    <inlineHelpText>Defines the value that customers can select if this taxonomy item is visible in customer-facing channels (i.e. on the web).</inlineHelpText>
    <label>Customer Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access &amp; Convenience</fullName>
            </value>
            <value>
                <fullName>Cleanliness</fullName>
            </value>
            <value>
                <fullName>Comfort</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Security</fullName>
            </value>
            <value>
                <fullName>Ticketing</fullName>
            </value>
            <value>
                <fullName>Timeliness</fullName>
            </value>
            <value>
                <fullName>Timetables</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Staff/Customer Service</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Licensing &amp; Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Issue_Accountability__c.field-meta.xml
<CustomField>
    <fullName>Issue_Accountability__c</fullName>
    <inlineHelpText>Defines which area is accountable for case management when this taxonomy item is selected (where case management can be determined purely by case category or location alone)</inlineHelpText>
    <label>Issue Accountability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Customer Liaison Team</fullName>
            </value>
            <value>
                <fullName>Depot</fullName>
            </value>
            <value>
                <fullName>IDD Pacific Highway</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Maritime Boating Operations</fullName>
            </value>
            <value>
                <fullName>Maritime Statewide Coordination</fullName>
            </value>
            <value>
                <fullName>Road Maintenance</fullName>
            </value>
            <value>
                <fullName>SEG Government Information Services</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>Speed Limits and Cameras</fullName>
            </value>
            <value>
                <fullName>Traffic Management &amp; Safety</fullName>
            </value>
            <value>
                <fullName>JMD - TOLLING</fullName>
            </value>
            <value>
                <fullName>Road rules</fullName>
            </value>
            <value>
                <fullName>IDD - CONTRACTS &amp; PROJECT STRATEGY</fullName>
            </value>
            <value>
                <fullName>IDD - Greater Sydney Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Freight &amp; Regional Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Commercial</fullName>
            </value>
            <value>
                <fullName>IDD - Pacific Highway Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Western Sydney Program Office</fullName>
            </value>
            <value>
                <fullName>RMS - CEP - Govt Information Services</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Sydney or Regional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <label>KPI</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Cleanliness</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Internal Matters</fullName>
            </value>
            <value>
                <fullName>OTR</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Ticketing</fullName>
            </value>
            <value>
                <fullName>Timetable</fullName>
            </value>
            <value>
                <fullName>Not Categorised</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Taxonomy_Metadata__c.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Taxonomy_Metadata__c.Type__c</field>
            <operation>equals</operation>
            <value>Mode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Meta Categorisations</relationshipLabel>
    <relationshipName>Child_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Customer_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Customer_Facing__c</fullName>
    <inlineHelpText>Indicates whether this value is available for selection on customer-facing channels (i.e. web)</inlineHelpText>
    <label>Status - Customer Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Staff_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Staff_Facing__c</fullName>
    <inlineHelpText>Identifies whether this value is available (active) for selection in staff-facing channels</inlineHelpText>
    <label>Status - Staff Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebToCaseConcessionTest.cls
@isTest
private class WebToCaseConcessionTest {
    
    private static Case caseRecord;
    
    private static testMethod void testForInitialisationOfAttachments() {
        setUpTestData();
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        System.Test.startTest();
        PageReference pageRef = Page.WebToCaseFormConcession;
        pageRef.getParameters().put('source', 'tfnsw');
        pageRef.getParameters().put('about', 'non-modal');
        pageRef.getHeaders().put('True-Client-IP','123.123.123.123');
        Test.setCurrentPage(pageRef);
        WebToCaseConcession_CX classInstance = new WebToCaseConcession_CX(controller);
        List<Attachment> attachments = classInstance.attachments ;
        System.Test.stopTest();
        System.assert(attachments != null);
        System.assert(!attachments.isEmpty());
    }
    
    private static testMethod void testForAllowedFileExtensions() {
        setUpTestData();
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        System.Test.startTest();
        PageReference pageRef = Page.WebToCaseFormConcession;
        pageRef.getParameters().put('source', 'tfnsw');
        pageRef.getParameters().put('about', 'non-modal');
        pageRef.getHeaders().put('True-Client-IP','123.123.123.123');
        Test.setCurrentPage(pageRef);
        WebToCaseConcession_CX classInstance = new WebToCaseConcession_CX(controller);
        String fileExtns = classInstance.getAllowedFileAttachments() ;
        classInstance.setAllowedFileAttachments('.docx');
        System.Test.stopTest();
        System.assert(fileExtns != null);       
    }
    
    private static testMethod void testForException() {
        setUpTestData();
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        System.Test.startTest();
        PageReference pageRef = Page.WebToCaseFormConcession;
        pageRef.getParameters().put('source', 'tfnsw');
        pageRef.getParameters().put('about', 'non-modal');
        pageRef.getHeaders().put('True-Client-IP','123.123.123.123');
        Test.setCurrentPage(pageRef);
        WebToCaseConcession_CX classInstance = new WebToCaseConcession_CX(controller);
        classInstance.caseRecord = null;
        PageReference pgRef = classInstance.createCase();
        System.Test.stopTest();
        System.assert(pgRef != null);       
    }
    
    private static testMethod void testForControllerInitialisation(){
        setUpTestData();
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        System.Test.startTest();
        PageReference pageRef = Page.WebToCaseFormConcession;
        pageRef.getParameters().put('source', 'tfnsw');
        pageRef.getParameters().put('about', 'non-modal');
        pageRef.getHeaders().put('X-Salesforce-SIP', '123.124.124.124');
        Test.setCurrentPage(pageRef);
        WebToCaseConcession_CX classInstance = new WebToCaseConcession_CX(controller);
        String errorMessage = classInstance.errorMessage;
        String sourceTfnsw = WebToCaseConcession_CX.sourceTfnsw;
        System.Test.stopTest();
        System.assert(classInstance.caseRecord != null);
        System.assert(classInstance.contactPerson != null);
        System.assert(classInstance.attachments != null);
        System.assert(sourceTfnsw == GlobalConstants.MODE_TFNSW);
    }
    
    private static testMethod void testForConcessionTaxonomy(){
        setUpTestData();
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        System.Test.startTest();
        PageReference pageRef = Page.WebToCaseFormConcession;
        pageRef.getParameters().put('source', 'tfnsw');
        pageRef.getParameters().put('about', 'non-modal');
        Test.setCurrentPage(pageRef);
        List<WebToCase_CX.CaseCategorization> taxonomy = WebToCaseConcession_CX.retrieveConcessionTaxonomy();
        System.Test.stopTest();
        System.assert(taxonomy != null );
        System.assert(taxonomy.size() == 1);        
    }
    
    private static testMethod void testForCaseCreation(){
        setUpTestData();
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        System.Test.startTest();
        PageReference pageRef = Page.WebToCaseFormConcession;
        pageRef.getParameters().put('source', 'tfnsw');
        pageRef.getParameters().put('about', 'non-modal');
        Test.setCurrentPage(pageRef);
        WebToCaseConcession_CX classInstance = new WebToCaseConcession_CX(controller);
        classInstance.caseRecord.Users_Ip_address__c = '124.123.124.124';
        classInstance.caseRecord.Type_of_Application__c = 'New Application';
        classInstance.caseRecord.Type = 'Enquiry';
        classInstance.contactPerson.LastName = 'User';
        classInstance.contactPerson.FirstName = 'Test';
        classInstance.contactPerson.MailingStreet = '477 Pitt Street';
        classInstance.contactPerson.MailingState = 'NSW';
        classInstance.contactPerson.MailingCity = 'Sydney';
        classInstance.contactPerson.MailingPostalCode = '2000';
        classInstance.contactPerson.MailingCountryCode = 'AU';
        classInstance.contactPerson.MailingCountry = 'Australia';
        
        PageReference pgRef = classInstance.createCase();
        System.Test.stopTest();
        System.assert(pgRef != null);
        System.assert(classInstance.caseRecord.Id != null);
        
    }
    
    
    private static testMethod void testForError(){
        setUpTestData();
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        System.Test.startTest();
        PageReference pageRef = Page.WebToCaseFormConcession;
        pageRef.getParameters().put('source', 'tfnsw');
        pageRef.getParameters().put('about', 'non-modal');
        Test.setCurrentPage(pageRef);
        WebToCaseConcession_CX classInstance = new WebToCaseConcession_CX(controller);
        classInstance.caseRecord.Users_Ip_address__c = null;
        
        PageReference pgRef = classInstance.createCase();
        System.Test.stopTest();
        System.assert(pgRef != null);
        System.assert(classInstance.caseRecord.Id == null);     
    }
    
    private static void setUpTestData() {
        createCase();
        createTaxonomy();
    }
    
    private static void createCase() {
        caseRecord = new Case();
        caseRecord.Modes__c = 'Non-modal';
        caseRecord.Taxonomy_Accountability__c = '';
        caseRecord.Taxonomy_Location__c = 'Sydney';
        caseRecord.Agency__c = '';
        caseRecord.Origin = 'Web';
        caseRecord.Priority = 'Normal';
        caseRecord.Type = 'Enquiry';
        caseRecord.Description = 'Test case for web to case creation'; 
    }
    
    private static void createTaxonomy() {      
        Taxonomy_Metadata__c nonModeTaxonomy = new Taxonomy_Metadata__c();
        nonModeTaxonomy.Type__c = 'Mode';
        nonModeTaxonomy.Status_Customer_Facing__c = 'Active';
        nonModeTaxonomy.Status_Staff_Facing__c = 'Active';
        nonModeTaxonomy.Customer_Value__c = 'Non-modal';
        nonModeTaxonomy.Name = 'Non-modal';
        
        insert nonModeTaxonomy;
        
        List<Taxonomy_Metadata__c> level1Taxonomies = new List<Taxonomy_Metadata__c>();
        
        Taxonomy_Metadata__c level1Issue = new Taxonomy_Metadata__c();
        level1Issue.Type__c = 'Issue';
        level1Issue.Status_Customer_Facing__c = 'Active';
        level1Issue.Status_Staff_Facing__c = 'Active';
        level1Issue.Customer_Value__c = 'Concessions and schemes';
        level1Issue.Name = 'Concessions and schemes';
        level1Issue.Parent_Id__c = nonModeTaxonomy.Id;
        level1Taxonomies.add(level1Issue);
        
        insert level1Taxonomies;
        
        List<Taxonomy_Metadata__c> level2Taxonomies = new List<Taxonomy_Metadata__c>();
        
        Taxonomy_Metadata__c level2Issue = new Taxonomy_Metadata__c();
        level2Issue.Type__c = 'Issue';
        level2Issue.Status_Customer_Facing__c = 'Active';
        level2Issue.Status_Staff_Facing__c = 'Active';
        level2Issue.Customer_Value__c = 'Road rules';
        level2Issue.Name = 'Road rules';
        level2Issue.Parent_Id__c = level1Issue.Id;
        level2Taxonomies.add(level2Issue);
        
        insert level2Taxonomies;
        
        List<Taxonomy_Metadata__c> level3Taxonomies = new List<Taxonomy_Metadata__c>();
        
        Taxonomy_Metadata__c taxonomyIssue = new Taxonomy_Metadata__c();
        taxonomyIssue.Agency__c = 'SNSW';
        taxonomyIssue.Customer_Value__c = 'Parking rules';
        taxonomyIssue.Name = 'Parking rules';
        taxonomyIssue.Issue_Accountability__c = 'Test Location Taxonomy';
        taxonomyIssue.Driver__c = '';
        taxonomyIssue.KPI__c = '';
        taxonomyIssue.Parent_Id__c = level2Issue.Id;
        taxonomyIssue.Status_Customer_Facing__c = 'Active';
        taxonomyIssue.Status_Staff_Facing__c = 'Active';
        taxonomyIssue.Display_on_Concession_Form__c = true;
        taxonomyIssue.Type__c = 'Issue';        
        level3Taxonomies.add(taxonomyIssue);
        insert level3Taxonomies;
    }
}