force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>NSW Trains</fullName>
            </value>
            <value>
                <fullName>RMS</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>STA</fullName>
            </value>
            <value>
                <fullName>Sydney Trains</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>PBO</fullName>
            </value>
            <value>
                <fullName>Newcastle Transport</fullName>
            </value>
            <value>
                <fullName>LRO</fullName>
            </value>
            <value>
                <fullName>MTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Customer_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Value__c</fullName>
    <description>Allows the customer facing value to be different from the internal / staff-facing taxonomy value</description>
    <inlineHelpText>Defines the value that customers can select if this taxonomy item is visible in customer-facing channels (i.e. on the web).</inlineHelpText>
    <label>Customer Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Taxonomy_Metadata__c.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Taxonomy_Metadata__c.Type__c</field>
            <operation>equals</operation>
            <value>Mode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Meta Categorisations</relationshipLabel>
    <relationshipName>Child_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Customer_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Customer_Facing__c</fullName>
    <inlineHelpText>Indicates whether this value is available for selection on customer-facing channels (i.e. web)</inlineHelpText>
    <label>Status - Customer Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Staff_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Staff_Facing__c</fullName>
    <inlineHelpText>Identifies whether this value is available (active) for selection in staff-facing channels</inlineHelpText>
    <label>Status - Staff Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseCFSApiTaxonomyRestService_Test.cls
@isTest
private class CaseCFSApiTaxonomyRestService_Test {
    
    static testMethod void getAllTest() {
        setupTaxonomy();
        RestRequest req = new RestRequest();
        RestContext.response = new RestResponse();
        
        req.requestURI = System.URL.getSalesforceBaseUrl() + '/services/apexrest/v1/salesforce/taxonomy';
        req.httpMethod = 'POST';
        
        String JSONString = '{}';
           
        req.requestBody = Blob.valueOf(JSONString);   

        RestContext.request = req;

        CaseCFSApiTaxonomyRestService.doPost();
        
        RestResponse res = RestContext.response;
        System.Assert(res.statusCode==200);
    }
    
    static testMethod void getIssueTest() {
        setupTaxonomy();
        RestRequest req = new RestRequest();
        RestContext.response = new RestResponse();
        
        req.requestURI = System.URL.getSalesforceBaseUrl() + '/services/apexrest/v1/salesforce/taxonomy';
        req.httpMethod = 'POST';
        
        String JSONString = '{"Type":"Issue"}';
           
        req.requestBody = Blob.valueOf(JSONString);

        RestContext.request = req;

        CaseCFSApiTaxonomyRestService.doPost();
        
        RestResponse res = RestContext.response;
        System.Assert(res.statusCode==200);
    }
    
    static testMethod void getModeTest() {
        setupTaxonomy();
        RestRequest req = new RestRequest();
        RestContext.response = new RestResponse();
        
        req.requestURI = System.URL.getSalesforceBaseUrl() + '/services/apexrest/v1/salesforce/taxonomy';
        req.httpMethod = 'POST';
        
        String JSONString = '{"Mode":"Road"}';
           
        req.requestBody = Blob.valueOf(JSONString);
           
        RestContext.request = req;

        CaseCFSApiTaxonomyRestService.doPost();
        
        RestResponse res = RestContext.response;
        System.Assert(res.statusCode==200);
        
    }
    
    static testMethod void getAllLevelsTest() {
        setupTaxonomy();
        RestRequest req = new RestRequest();
        RestContext.response = new RestResponse();
        
        req.requestURI = System.URL.getSalesforceBaseUrl() + '/services/apexrest/v1/salesforce/taxonomy';
        req.httpMethod = 'POST';
        
        String JSONString = '{"Type":"Issue",'+
                              '"Mode":"Road",'+
                              '"Level1":"Roads",'+
                              '"Level2":"Traffic Management & Safety",'+
                              '"Level3":"Safety barriers"'+
                            '}';
           
        req.requestBody = Blob.valueOf(JSONString);
        
        RestContext.request = req;

        CaseCFSApiTaxonomyRestService.doPost();
        
        RestResponse res = RestContext.response;
        System.Assert(res.statusCode==200);
        
    }
    
    static testMethod void getFieldNameError() {
        setupTaxonomy();
        RestRequest req = new RestRequest();
        RestContext.response = new RestResponse();
        
        req.requestURI = System.URL.getSalesforceBaseUrl() + '/services/apexrest/v1/salesforce/taxonomy';
        req.httpMethod = 'POST';
        
        String JSONString = '{"Type":"Issue",'+
                              '"Mode":"Road",'+
                              '"Issue1":"Roads",'+
                              '"Level2":"Traffic Management & Safety",'+
                              '"Level3":"Safety barriers"'+
                            '}';
           
        req.requestBody = Blob.valueOf(JSONString);
        
        RestContext.request = req;

        CaseCFSApiTaxonomyRestService.doPost();
        
        RestResponse res = RestContext.response;
        System.Assert(res.statusCode==400);
        
    }
    
    static testMethod void getJSONError() {
        setupTaxonomy();
        RestRequest req = new RestRequest();
        RestContext.response = new RestResponse();
        
        req.requestURI = System.URL.getSalesforceBaseUrl() + '/services/apexrest/v1/salesforce/taxonomy';
        req.httpMethod = 'POST';
        
        String JSONString = '{"Type":"Issue",'+
                              '"Mode":"Road",'+
                              '"Issue1":"Roads",'+
                              '"Level2":"Traffic Management & Safety"'+
                              '"Level3":"Safety barriers"'+
                            '}';
           
        req.requestBody = Blob.valueOf(JSONString);
        
        RestContext.request = req;

        CaseCFSApiTaxonomyRestService.doPost();
        
        RestResponse res = RestContext.response;
        System.Assert(res.statusCode==400);
        
    }
    
    public static void setupTaxonomy() {      
        Taxonomy_Metadata__c mode = new Taxonomy_Metadata__c(Type__c='Issue', Status_Customer_Facing__c='Active', 
        Status_Staff_Facing__c='Active', Name='Road', Agency__c='RMS', Customer_Value__c ='Road');
        insert mode;
        
        Taxonomy_Metadata__c level1 = new Taxonomy_Metadata__c(Type__c='Issue', Status_Customer_Facing__c='Active', 
        Status_Staff_Facing__c='Active', Name='Roads', Agency__c='RMS', Customer_Value__c ='Roads', Parent_Id__c = mode.Id);
        insert level1;

        Taxonomy_Metadata__c level2 = new Taxonomy_Metadata__c( Type__c='Issue', Parent_Id__c = level1.Id,Status_Customer_Facing__c='Active', Status_Staff_Facing__c='Active',  Name='Traffic Management & Safety',  Agency__c='RMS', Customer_Value__c ='Traffic Management & Safety');
        insert level2;

        Taxonomy_Metadata__c level3 = new Taxonomy_Metadata__c( Type__c='Issue', Parent_Id__c = level2.Id, Status_Customer_Facing__c='Active', Status_Staff_Facing__c='Active',  Name='Safety barriers',  Agency__c='RMS', Customer_Value__c ='Safety barriers');
        insert level3;
    }
}