force-app/main/default/objects/Maximum_Triage_Rows__mdt/Maximum_Triage_Rows__mdt.object-meta.xml
<CustomObject>
    <description>Maximum number of rows which will be getting triaged in 1 transaction.</description>
    <label>Maximum Triage Rows</label>
    <pluralLabel>Maximum Triage Rows</pluralLabel>
</CustomObject>

force-app/main/default/objects/Maximum_Triage_Rows__mdt/fields/No_of_rows__c.field-meta.xml
<CustomField>
    <fullName>No_of_rows__c</fullName>
    <label>No of rows</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Priority_Keywords__mdt/Priority_Keywords__mdt.object-meta.xml
<CustomObject>
    <description>Place to store the keywords that determine whether a case is defaulted to a high priority case.</description>
    <label>Priority Keyword</label>
    <pluralLabel>Priority Keywords</pluralLabel>
</CustomObject>

force-app/main/default/objects/Priority_Keywords__mdt/fields/BusinessPriorityScore__c.field-meta.xml
<CustomField>
    <fullName>BusinessPriorityScore__c</fullName>
    <description>The &quot;business priority score&quot; of this keyword. Higher score indicates a higher priority. A value of zero indicates a totally innocent word, while a value of 1000 would signify a word that, alone, would indicate high business priority.  Values of 50,100,150 etc would indicate an important word, but one that, alone, may not pass the score over the threshold.  All words in the description are evaluated and added up, which creates the total score.</description>
    <inlineHelpText>Enter a value indicate the business priority level of this keyword. Zero indicates no security threat; 100 signals important; use 1000 for words such as bomb that, when they appear, should always be treated as high threat.</inlineHelpText>
    <label>Business Priority Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Priority_Keywords__mdt/fields/Is_Multi_Word__c.field-meta.xml
<CustomField>
    <fullName>Is_Multi_Word__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This should be ticked if the word is multi word. For e.g. for record &#39;anti-social&#39; this should be ticked. Also the record should be stored without special characters i.e. hyphens, spaces etc. So words like &#39;anit-social&#39; will be stored as &#39;antisocial&#39;</description>
    <inlineHelpText>This should be ticked if the word is multi word. For e.g. for record &#39;anti-social&#39; this should be ticked. Also the record should be stored without special characters i.e. hyphens, spaces etc.</inlineHelpText>
    <label>Is Multi Word</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Priority_Keywords__mdt/fields/SecurityThreatScore__c.field-meta.xml
<CustomField>
    <fullName>SecurityThreatScore__c</fullName>
    <description>The &quot;security threat score&quot; of this keyword.  Higher score indicates a higher priority.  A value of zero indicates a totally innocent word, while a value of 1000 would signify a word that, alone, would high security threat.  Values of 50,100,150 etc would indicate an important word, but one that, alone, may not pass the score over the threshold.</description>
    <inlineHelpText>Enter a value indicate the security threat level of this keyword.  Zero indicates no security threat; 100 signals important; use 1000 for words such as bomb that, when they appear, should always be treated as high threat.</inlineHelpText>
    <label>Security Threat Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Profanities__mdt/Profanities__mdt.object-meta.xml
<CustomObject>
    <description>Contains the list of profanities that auto-triage will scrub against.  Auto-triage will automatically add &quot;ed&quot; and &quot;ing&quot; to each of these words, e.g. one entry &quot;tesst&quot; will also scrub &quot;tessted&quot; and &quot;tessting&quot;.  Words must be entered into this list in all lowercase.</description>
    <label>Profanity</label>
    <pluralLabel>Profanities</pluralLabel>
</CustomObject>

force-app/main/default/objects/Safe_Website__mdt/Safe_Website__mdt.object-meta.xml
<CustomObject>
    <description>This is a list of known &quot;safe websites&quot; - e.g. www.transportnsw.info.  The original intent of this list is, should a complaint be submitted with a URL in the description that is not contained in this Safe List, it would be redacted from the complaint into a private note.</description>
    <label>Safe Website</label>
    <pluralLabel>Safe Websites</pluralLabel>
</CustomObject>

force-app/main/default/objects/Safe_Website__mdt/fields/DomainName__c.field-meta.xml
<CustomField>
    <fullName>DomainName__c</fullName>
    <description>The domain name that is to be allowed on the safe list.  If only a domain name is entered (e.g. transportnsw.info) then any hostname that matches the domain will be allowed on the safe list (e.g. www.transportnsw.info, www2.transportnsw.info, transportnsw.info).  If a FQDN is entered here, then only that specific hostname will be allowed.  This is not the intended use, as sometimes people abbreviate the www. off the URL (e.g. transportnsw.info/abcd).  It is expected that admins will enter only the domain name and allow all URLs that end with that domain name.</description>
    <inlineHelpText>Enter the &quot;domain&quot; of the website to be allowed, e.g. &quot;transportnsw.info&quot;.  Leave off the &quot;www.&quot; part of the domain, unless you know what you&#39;re doing (using the FQDM will restrict to only the FQDN being marked as safe versus the whole domain).</inlineHelpText>
    <label>Domain Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Threshold_Score__mdt/Threshold_Score__mdt.object-meta.xml
<CustomObject>
    <description>Threshold Score for Business Priority and Security threat. There should be only 1 record in this setting.</description>
    <label>Threshold Score</label>
    <pluralLabel>Threshold Score</pluralLabel>
</CustomObject>

force-app/main/default/objects/Threshold_Score__mdt/fields/Business_Priority_Score__c.field-meta.xml
<CustomField>
    <fullName>Business_Priority_Score__c</fullName>
    <label>Business Priority Score</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Threshold_Score__mdt/fields/Security_Threat_Score__c.field-meta.xml
<CustomField>
    <fullName>Security_Threat_Score__c</fullName>
    <label>Security Threat Score</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/URL_Identifier__mdt/URL_Identifier__mdt.object-meta.xml
<CustomObject>
    <description>Records in this metadata type will be used to scrub the URLs in case description during triage. Records would thereby govern what qualifies to be a URL</description>
    <label>URL Identifier</label>
    <pluralLabel>URL Identifier</pluralLabel>
</CustomObject>

force-app/main/default/classes/CaseAutoTriage.cls
/*---------------------------------------------------------------------------------------
Author:        Arxxus
Description:   this class will
               1. scrub the profanity words with text <profanity>
               2. scrub bad urls (determined from safe website custom metadata) with <bad_url>
               3. calculate the SecurityThreatScore__c and BusinessPriorityScore__c
Test Class:    CaseAutoTriage_Test 
-----------------------------------------------------------------------------------------*/
public class CaseAutoTriage {

    public static String originalDescription;
    private List<Case> cases = new List<Case>();
    private Set<String> profanities = new Set<string>();
    private Set<String> allowedwebLinksSet = new Set<string>();
    private Set<String> urlIdentifier = new Set<String>();
    private Map<String, Priority_Keywords__mdt> priorityKeyMap = null; // new Map<String, Priority_Keywords__mdt>();
    private Map<String, Priority_Keywords__mdt> multiWordPriorityKeyword = null;
    private Threshold_Score__mdt thresholdScores; 
    private final String powerPartnerUserType = 'PowerPartner';
    private Integer maxRowsAllowed;
    
    private Pattern MyPattern = Pattern.compile('^((https?|ftp)://)??(www[.])??([a-zA-Z0-9]|-)+?([.][a-zA-Z0-9(-|/|=|#|@|%|&|?)??]+?)+?$');
    
    private Pattern emailPattern = Pattern.compile('^[a-z0-9._%+-/!#$%&\'*=?^_`{|}~]+@[a-z0-9.-]+\\.[a-z]{2,4}$');
    
    public CaseAutoTriage(List<Case> cases) {
        profanities.addAll(getProfanityList([SELECT MasterLabel, DeveloperName FROM Profanities__mdt]));
        allowedwebLinksSet.addAll(getWebLinksList([SELECT DomainName__c FROM Safe_Website__mdt]));
        priorityKeyMap = getPriorityKeyList([SELECT MasterLabel, BusinessPriorityScore__c,SecurityThreatScore__c FROM Priority_Keywords__mdt]);
        multiWordPriorityKeyword = getMultiWordPriorityKeyword([SELECT MasterLabel, BusinessPriorityScore__c,SecurityThreatScore__c FROM Priority_Keywords__mdt WHERE Is_Multi_Word__c = true]);
        urlIdentifier.addAll(getURLIdentifierList([SELECT MasterLabel, DeveloperName FROM URL_Identifier__mdt]));
        thresholdScores = [Select MasterLabel, Business_Priority_Score__c, Security_Threat_Score__c FROM Threshold_Score__mdt limit 1];
        maxRowsAllowed = [SELECT Id, No_of_rows__c FROM Maximum_Triage_Rows__mdt LIMIT 1].No_of_rows__c.intValue(); 
        this.cases = cases;
    }   
    
    public void ProfanityFilterandHPScoreCalculator(){
        System.debug('case auto triage check.'+maxRowsAllowed);
        if(this.cases == null || UserInfo.getUserType() == powerPartnerUserType || this.cases.size() > maxRowsAllowed ) return;
        //Long exStart = DateTime.now().getTime(); // Test Variable for Execution time check
        // start and stop a clock, and report on processing time.
        // for testing / performance testing purposes.
        Id roadRT = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Road').getRecordTypeId();
        Id maritimeRT = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Maritime').getRecordTypeId();
        
        for(Case c : cases){
            
            if(c.Description == null || c.IsMinCorroCase__c || c.RecordTypeId == roadRT || c.RecordTypeId == maritimeRT || c.Original_Description__c != null) continue; 
            System.debug('case needs to be triaged.');
            originalDescription = c.Description;
            c.BusinessPriorityScore__c = 0;
            c.SecurityThreatScore__c = 0;
            
            // FIRST, take all "words" from the Description and store in a HashSet
            String lowerDescription = c.Description.toLowerCase();
            Set<String> descriptionWords = new Set<String>(lowerDescription.split('\\W+')); //Changed to Add Special Character Considerations.
            // SECOND, determine which priority words were used
            Set<String> priorityWordsAppearing = new Set<String>(priorityKeyMap.keySet());

            // TODO: need special handling for multi-words!
            priorityWordsAppearing.retainAll(descriptionWords);

            // THEN, check for profanity using a similar approach
            Set<String> profanityFound = new Set<String>(profanities);
            profanityFound.retainAll(descriptionWords);

            for (String thisWord : profanityFound) {
                // when we have a confirmed match, we then replaceAll on it
                thisWord = '(?i)\\b'+ thisWord+'\\b';
                c.Description = c.Description.replaceAll(thisWord, '[profanity]'); 
            }

            // THEN, check for profanity with spaces
            for (String thisprofaneWord : profanities) {
                if (hasAllLetters(thisprofaneWord, descriptionWords)) {
                    // If we get here, we've found that all letters appear separately as words; e.g. "t e s s t"
                    // so there's a possibility that they exist together - now we can make the more expensive 
                    // call to do a full sweep of the description field using any non-word chars as delimiters
                    // this will catch "t.e.s.s.t" or "t!e!s!s!t" or even "t!#@ e#$@ s!@# s!@$ t" 
                    // Append a regular exp for case insensitivity, joined the splited array 
                    // Took a substring(3) of the resulting join, to eliminate the preceeding nonword 
                    thisprofaneWord = '(?i)\\b' + (String.join(thisprofaneWord.split(''),'\\W+')).substring(3) + '\\b';
                    c.Description = c.Description.replaceAll(thisprofaneWord, '[profanity]');  // replaced  - Dipanjan
                }
            }
            
            for(String thisUrl : lowerDescription.split('\\s+')){ // Splited the lowerDescription Again because from descriptionWords set all special characters was removed, hence not catching urls.
                String splittedWord = thisUrl;
                thisUrl = thisUrl.replaceAll('[()><\'\";,]','');
                if(!emailPattern.matcher(thisUrl).matches() &&  MyPattern.matcher(thisUrl).matches() && isIdentifiedAsURL(thisUrl) ){ 
                    String urlHost = thisUrl;
                    if(thisUrl.startsWith('http') || thisUrl.startsWith('ftp')){
                        URL url = new URL(thisUrl);
                        urlHost = url.getHost();
                    }
                    if(!isPresentInAllowedwebLinksSet(urlHost)){
                        splittedWord = splittedWord.replaceAll('\\?', '\\\\?');
                        splittedWord = splittedWord.replaceAll('\\+', '\\\\+');
                        splittedWord = splittedWord.replaceAll('\\(', '\\\\(');
                        splittedWord = splittedWord.replaceAll('\\)', '\\\\)');
                        splittedWord = splittedWord.replaceAll('\\<', '\\\\<');
                        splittedWord = splittedWord.replaceAll('\\>', '\\\\>');
                        c.Description = c.Description.replaceAll('(?i)'+splittedWord, '[bad_url]');  
                    }                                               
                }
                                              
            }
            // NEXT, Add scores for those words
            Set<String> scoredWords = new Set<String>(); 
            for (String thisPriorityWord : lowerDescription.split('\\b')) { 
                if(!priorityKeyMap.containsKey(thisPriorityWord)) continue;
                System.debug('priority word: '+thisPriorityWord);
                Priority_Keywords__mdt priorityKeyword = priorityKeyMap.get(thisPriorityWord);
                if (priorityKeyword != null && !scoredWords.contains(thisPriorityWord)) {
                    c.SecurityThreatScore__c += (priorityKeyWord.SecurityThreatScore__c != null? priorityKeyWord.SecurityThreatScore__c:0);
                    c.BusinessPriorityScore__c += (priorityKeyWord.BusinessPriorityScore__c != null?priorityKeyWord.BusinessPriorityScore__c:0);
                    scoredWords.add(thisPriorityWord);
                }
            }
            String lowercaseDescAfterProfanity = c.Description.toLowercase();
            String descWithoutSpCharacters = lowercaseDescAfterProfanity.replaceAll('[^a-zA-Z0-9]','');
            for(String label : multiWordPriorityKeyword.keySet()) {
                if(descWithoutSpCharacters.contains(label) && !scoredWords.contains(label)) {
                    Priority_Keywords__mdt keyword = multiWordPriorityKeyword.get(label);
                    c.SecurityThreatScore__c += (keyword.SecurityThreatScore__c != null? keyword.SecurityThreatScore__c:0);
                    c.BusinessPriorityScore__c += (keyword.BusinessPriorityScore__c != null?keyword.BusinessPriorityScore__c:0);
                    scoredWords.add(label);
                }
            }
            
            if(!c.Description.equals(originalDescription)){
                c.Original_Description__c = originalDescription;
                c.CaseIsFiltered__c = true;
            }else{
                c.Original_Description__c = null;
                c.CaseIsFiltered__c = false;
            }
            
            if(thresholdScores != null && thresholdScores.Security_Threat_Score__c != null && c.SecurityThreatScore__c > 0 &&  c.SecurityThreatScore__c >= thresholdScores.Security_Threat_Score__c) {
                c.Priority = GlobalConstants.CASE_PRIORITY_HIGH;
            }
            if(thresholdScores != null && thresholdScores.Business_Priority_Score__c != null && c.BusinessPriorityScore__c > 0 && c.BusinessPriorityScore__c >= thresholdScores.Business_Priority_Score__c) {
                c.Priority = GlobalConstants.CASE_PRIORITY_HIGH;
            }
        } 
        
    }
    
    /**
     * hasAllLetters : a recursive method that returns true if all letters in a word
     * appear individually as words in the descriptionWords
     * 
     * e.g. first call with parameter "tesst" checks to see if "t" is a word in the Set
     *      if it is, calls itself with "esst" then checks to see if "e" is a word in the Set
     *      so on with "sst", "st" and eventually "t"  If the final "t" evalutes to true,
     *      recursion stops and true is returned.
     *      The first time a letter is not found as a word, false is returned and no further
     *      analysis is done.
     * 
     * Author: Arxxus
     * Date: 27/10/2016
     */
    
    public boolean hasAllLetters(String thisprofaneWordtocheck, Set<String> descriptionWords) {
        if (descriptionWords.contains(thisprofaneWordtocheck.substring(0,1))) {
            if (thisprofaneWordtocheck.length() == 1) {
                return true;
            }
            return(hasAllLetters(thisprofaneWordtocheck.substring(1), descriptionWords));
        } else {
            return(false);
        }
    }

    /**
     * Load the list of Profanity into a List of Strings.
     * Takes a parameter which is a list of profanity words.
     * Automatically adds *ed and *ing to the resulting List
     * any more documentation.
     */

    public List<String> getProfanityList(List<Profanities__mdt> profanityWords){
        List<String> profanityList = new List<String>(); 
        for(Profanities__mdt prof:profanityWords) {
            String thisWordprof = prof.MasterLabel.toLowerCase();
            profanityList.add(thisWordprof);
            profanityList.add(thisWordprof + 'ed');
            profanityList.add(thisWordprof + 'ing');
        }
        return profanityList;
    }

    /**
     * Load the list of allowed web links into a List of Strings.
     */

    public List<String> getWebLinksList(List<Safe_Website__mdt> listofwebLinks){
        List<String> webLinkList = new List<String>(); 
        for(Safe_Website__mdt web:listofwebLinks){
            webLinkList.add(web.DomainName__c);
        }    
        return webLinkList;
    }
    
    private Boolean isPresentInAllowedwebLinksSet(String urlHost) {
        for(String linkset : allowedwebLinksSet) {
            if(urlHost.contains(linkset)){
                return true;
            }
        }
        return false;
    }
    
    /**
     * Load the list of allowed url identifier.
     */

    public List<String> getURLIdentifierList(List<URL_Identifier__mdt> urlIdentifiers){
        List<String> urlIdf = new List<String>(); 
        for(URL_Identifier__mdt url:urlIdentifiers){
            urlIdf.add(url.MasterLabel);
        }    
        return urlIdf;
    }
    
    private Boolean isIdentifiedAsURL(String url){
        System.debug('identifying url.'+url);
        for(String urlIdf : urlIdentifier) {
            if(url.contains(urlIdf)) return true;
        }
        return false;
    }
    
    /**
     *  Load the list of priority words and scores into a map
     */

    public Map<String, Priority_Keywords__mdt> getPriorityKeyList(List<Priority_Keywords__mdt> listofpriorityKeys) {
        Map<String, Priority_Keywords__mdt> priorityKeyMap = new Map<String, Priority_Keywords__mdt>(); 
        for(Priority_Keywords__mdt pri:listofpriorityKeys){
            priorityKeyMap.put(pri.MasterLabel, pri);           // no need toLowerCase all since validation rule requires them to be in lower at rest
        }    
        return priorityKeyMap;
    }
    
    public Map<String, Priority_Keywords__mdt> getMultiWordPriorityKeyword(List<Priority_Keywords__mdt> listofpriorityKeys) {
        Map<String, Priority_Keywords__mdt> priorityKeyMap = new Map<String, Priority_Keywords__mdt>(); 
        for(Priority_Keywords__mdt pri:listofpriorityKeys){
            priorityKeyMap.put(pri.MasterLabel, pri);           // no need toLowerCase all since validation rule requires them to be in lower at rest
        }    
        return priorityKeyMap;
    }
    
    
}