force-app/main/default/objects/Agency_Specific_License_Email_Config__c/Agency_Specific_License_Email_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Agency Specific Licenses Overuse Report Email Recipient Configuration.</description>
    <label>Agency Specific License Email Config</label>
</CustomObject>

force-app/main/default/objects/Agency_Specific_License_Email_Config__c/fields/Recepient_Email__c.field-meta.xml
<CustomField>
    <fullName>Recepient_Email__c</fullName>
    <label>Recepient Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Agency_Specific_License_limits__c/Agency_Specific_License_limits__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Agency Specific User License limits</description>
    <label>Agency Specific License limits</label>
</CustomObject>

force-app/main/default/objects/Agency_Specific_License_limits__c/fields/Max_Force_com_Licenses_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Max_Force_com_Licenses_Allowed__c</fullName>
    <label>Max Force com Licenses Allowed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Agency_Specific_License_limits__c/fields/Max_Service_Cloud_Licenses_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Max_Service_Cloud_Licenses_Allowed__c</fullName>
    <label>Max Service Cloud Licenses Allowed</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NotifyForLicenseOveruse_Test.cls
//JIRA# SFCOE-1837 Send an email notification with User License overuse information (test class) - 26-05

@isTest
public class NotifyForLicenseOveruse_Test {
    static testmethod void testschedule(){
        Test.StartTest();
        
        Agency_Specific_License_limits__c agencyLimitsConfigRMS = new Agency_Specific_License_limits__c();
        agencyLimitsConfigRMS.name = 'RMS';
        agencyLimitsConfigRMS.Max_Force_com_Licenses_Allowed__c = 1;
        agencyLimitsConfigRMS.Max_Service_Cloud_Licenses_Allowed__c = 2;
        insert agencyLimitsConfigRMS;
        
        Agency_Specific_License_Email_Config__c recepientEmails = new Agency_Specific_License_Email_Config__c();
        recepientEmails.Name = 'Salesforce Requests';
        recepientEmails.Recepient_Email__c = 'salesforcerequests@transport.nsw.gov.au';
        insert recepientEmails;
        
        NotifyForLicenseOveruse sh1 = new NotifyForLicenseOveruse();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Test', sch, sh1);

        Test.stopTest();
    }
    
}