force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Is_Shared_S2S__c.field-meta.xml
<CustomField>
    <fullName>Is_Shared_S2S__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating if custom attachment record is shared via S2S</description>
    <label>Is Shared S2S</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Shared__c.field-meta.xml
<CustomField>
    <fullName>Shared__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating if standard attachment related to custom attachment is shared or not</description>
    <inlineHelpText>Flag indicating if standard attachment related to custom attachment is shared or not</inlineHelpText>
    <label>Shared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/classes/NewAttachmentsSharedWithSNSW.cls
public without sharing class NewAttachmentsSharedWithSNSW {

    private Map<Id, NoteOrAttachment__c> attachments;
    private static Boolean allAttachmentsShared = false;
    public NewAttachmentsSharedWithSNSW(Map<Id, NoteOrAttachment__c> attachments) {
        if(attachments == null || attachments.isEmpty()) {
            throw new InvalidDataException('Failed to share case attachments. Custom attachment details missing');
        }
        this.attachments = attachments;
    }
    
    public void shareAttachments() {
        if(allAttachmentsShared) {
            return;
        }
        List<Attachment> attachmentsToShare = new List<Attachment>();
        Map<Id, Id> attachmentVsCase = new Map<Id,Id>();
        Set<Id> sharedCustomAttachments = new Set<Id>();
        for(NoteOrAttachment__c customAttachment : [SELECT Id, Case__c, Attachment__c 
                                                    FROM NoteOrAttachment__c 
                                                    WHERE Id IN :attachments.keySet()
                                                        AND Case__r.Shared__c = true]) {
            if(attachments.get(customAttachment.Id).Attachment__c != null && !attachments.get(customAttachment.Id).Is_Shared_S2S__c) {
                attachmentVsCase.put((Id) attachments.get(customAttachment.Id).Attachment__c, customAttachment.Case__c);                
            }            
        }
                
        for(Attachment existingAttachment :[SELECT ParentId, Name, IsPrivate, IsPartnerShared,  Id, Description, ContentType,  Body 
                                            FROM Attachment 
                                            WHERE Id IN :attachmentVsCase.keySet()
                                                AND IsPrivate = false
                                                AND IsPartnerShared = false]) {
            
            Attachment newAttachment = new Attachment();
            newAttachment.ParentId = attachmentVsCase.get(existingAttachment.Id);
            newAttachment.Name = existingAttachment.Name;
            newAttachment.IsPrivate = existingAttachment.IsPrivate;
            newAttachment.Description = existingAttachment.Description;
            newAttachment.ContentType = existingAttachment.ContentType;
            newAttachment.Body = existingAttachment.Body;
            
            attachmentsToShare.add(newAttachment);
            sharedCustomAttachments.add(existingAttachment.ParentId);
        }
        
        if(!attachmentsToShare.isEmpty()) {
            System.debug(LoggingLevel.INFO, 'Number of attachments to be shared: ' + attachmentsToShare.size());
            S2SAttachmentShareStatusRetriever.shareAttachment = true;
            insert attachmentsToShare;
            allAttachmentsShared = true;
            for(NoteOrAttachment__c attach : attachments.values()) {
                if(sharedCustomAttachments.contains(attach.Id)) {
                    attach.Is_Shared_S2S__c = true;
                }
            }
        }
    }
    
    public class InvalidDataException extends Exception {}
}