force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/CaseArticle__c.field-meta.xml
<CustomField>
    <fullName>CaseArticle__c</fullName>
    <label>CaseArticle</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <inlineHelpText>This allows user to mark security disposition of the record. Default is &quot;Standard&quot;</inlineHelpText>
    <label>Privacy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW NOTE</description>
    <label>Note</label>
</RecordType>

force-app/main/default/objects/SignedResponse__kav/SignedResponse__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Signed Response From Ministers</description>
    <label>Signed Response</label>
    <pluralLabel>Signed Responses</pluralLabel>
</CustomObject>

force-app/main/default/classes/KnowledgeArticleToAttachmentConverter.cls
public without sharing class KnowledgeArticleToAttachmentConverter {
	/*---------------------------------------------------------------------------------------
	Author:        Manish Damle
	Company:       Arxxus.com
	Description:   This method is responsible for converting the Case Articles to
	               NoteOrAttachment records whenever User clicks on Manager Supporting
	               Documents button.
	               
	Test Class:    MassEditAttachment_CX_Test
	History
	<Date>         <Authors Name>     <Brief Description of Change>
	22/07/2015     Manish Damle       Created
	-----------------------------------------------------------------------------------------*/
	public void convert(list <NoteOrAttachment__c> existingNoteOrAttachments, Case caseRecord) {
		try {
			set <Id> articleIds = new set <Id>();
	        map <String, NoteOrAttachment__c> kaIdVsAttachment = new map <String,NoteOrAttachment__c> ();
	        map <String, Attachment> attachments = new map <String, Attachment>();
	        map <String, NoteOrAttachment__c> customAttachments = new map <String, NoteOrAttachment__c>();
	        Id attachmentRecordTypeId = [Select Id 
                                         From RecordType 
                                         Where SObjectType = 'NoteOrAttachment__c' 
                                         And DeveloperName =: GlobalConstants.NOTEORATTACHMENT_RECORDTYPENAME_ATTACHMENT].Id; 
            
	        for(NoteOrAttachment__c noteOrAttachment : existingNoteOrAttachments) {
	        	if(noteOrAttachment.CaseArticle__c != null)
	            	kaIdVsAttachment.put(noteOrAttachment.CaseArticle__c, noteOrAttachment);
	       }

	        for(CaseArticle ca: [Select Id, KnowledgeArticleId From CaseArticle Where CaseId =: caseRecord.Id]) {
	            articleIds.add(ca.KnowledgeArticleId);
	        }
	        
	        system.debug('----Case Articles----' + articleIds);
	        //NOTE: We can not bind variable with PublishStatus and Language field on KAV. We must use direct values.
	        for(SignedResponse__kav signedResponse : [Select Id,Title, UrlName, ArticleNumber, Summary, KnowledgeArticleId, 
                                                      		 SignedResponse__Name__s, SignedResponse__ContentType__s, SignedResponse__Body__s 
	                                                  From SignedResponse__kav 
	                                                  Where PublishStatus = 'Online' 
	                                                  And language = 'en_US' 
	                                                  And IsLatestVersion = true 
	                                                  And KnowledgeArticleId IN: articleIds]) {

	            system.debug('----Article----' + signedResponse.SignedResponse__Name__s + '---Id---' + signedResponse.Id + '---Number--' + signedResponse.ArticleNumber);
	            
	            if(signedResponse.KnowledgeArticleId != null && !kaIdVsAttachment.containsKey(signedResponse.KnowledgeArticleId)) {
	                attachments.put(signedResponse.KnowledgeArticleId + '-' + signedResponse.SignedResponse__Name__s, 
	                				new Attachment(Name = signedResponse.KnowledgeArticleId + '-' + signedResponse.SignedResponse__Name__s,
                                                   Body = signedResponse.SignedResponse__Body__s,
                                                   ContentType = signedResponse.SignedResponse__ContentType__s));

	                customAttachments.put(signedResponse.KnowledgeArticleId + '-' + signedResponse.SignedResponse__Name__s, 
	                	            	  new NoteOrAttachment__c(Name = signedResponse.SignedResponse__Name__s,
		                                                          Privacy__c = GlobalConstants.NOTEORATTACHMENT_PRIVACY_STANDARD,
		                                                          Case__c = caseRecord.Id,
		                                                          OwnerId = caseRecord.OwnerId,
		                                                          CaseArticle__c = signedResponse.KnowledgeArticleId,
		                                                          RecordTypeId = attachmentRecordTypeId));
	            }
	        }

	        system.debug('----Custom Attachments----' + customAttachments.size());
	        if(customAttachments.size() > 0) {
	            insert customAttachments.values();
	            for(String fileName : customAttachments.keySet()) {
	                if(attachments.containsKey(fileName) 
	                    && customAttachments.get(fileName) != null 
	                    && customAttachments.get(fileName).Id != null) {
	                    attachments.get(fileName).ParentId = customAttachments.get(fileName).Id;
	                }
	            }
	            
	            insert attachments.values();
	            
	            for(Attachment att: attachments.values()) {
	                if(customAttachments.containsKey(att.Name) 
	                   && customAttachments.get(att.Name) != null 
	                   && customAttachments.get(att.Name).Id != null) {
	                    customAttachments.get(att.Name).Attachment__c = att.Id;
	                    customAttachments.get(att.Name).ContentType__c = att.ContentType;
	                }
	            }
	            
	            update customAttachments.values();
	        }
        }Catch(Exception e){
        	System.debug('----@Kav To Attachment Conversion Failed-----' + e.getMessage() + '--LINE--' + e.getLineNumber());
        	//Throw exception. - Added by Ian F, tfNSW, 21/08/2017
            Throw(e);
        }
	}
}