force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/DFSIAttachmentId__c.field-meta.xml
<CustomField>
    <fullName>DFSIAttachmentId__c</fullName>
    <description>Attachment Id from DFSI</description>
    <label>DFSIAttachmentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/classes/DFSIAttachmentMetadata.cls
public class DFSIAttachmentMetadata {
	
	public DFSIAttribute attributes;
	public String Id;
	public String Name;
	public String ContentType;
	public String ParentId;
	public String Title;
	public String RecordType;

	public static List<DFSIAttachmentMetadata> parse(String jsonStr) {
		if(jsonStr == null || jsonStr == '')
			return null;
		return (List<DFSIAttachmentMetadata>) JSON.deserialize(jsonStr, List<DFSIAttachmentMetadata>.class);
	}

	public NoteOrAttachment__c convert() {
		NoteOrAttachment__c result = new NoteOrAttachment__c();
		result.Name = this.Name;
		result.ContentType__c = this.ContentType;
		result.DFSIAttachmentId__c = this.Id;
		result.RecordTypeId = Schema.SObjectType.NoteOrAttachment__c.getRecordTypeInfosByName().get('Attachment').getRecordTypeId();
		return result;
	}
}