force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Is_Shared_S2S__c.field-meta.xml
<CustomField>
    <fullName>Is_Shared_S2S__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating if custom attachment record is shared via S2S</description>
    <label>Is Shared S2S</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Shared__c.field-meta.xml
<CustomField>
    <fullName>Shared__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating if standard attachment related to custom attachment is shared or not</description>
    <inlineHelpText>Flag indicating if standard attachment related to custom attachment is shared or not</inlineHelpText>
    <label>Shared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/classes/ShareAttachmentsBatch.cls
global  without sharing class ShareAttachmentsBatch implements Database.Batchable<sObject>{

    global final String query = 'SELECT Id, Case__c FROM NoteOrAttachment__c WHERE Is_Shared_S2S__c = true AND Shared__c = false';

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<NoteOrAttachment__c> scope){
        Set<Id> sharedCases = new Set<Id>();
        for(NoteOrAttachment__c customAttachment : scope){
            sharedCases.add(customAttachment.Case__c);
            customAttachment.Shared__c = true;
        }
        Map<Id, Id> attachmentsToShare = new Map<Id, Id>();
        for(Attachment attach : [SELECT Id, ParentId FROM Attachment WHERE ParentId IN :sharedCases AND IsPrivate = false]) {
            attachmentsToShare.put(attach.Id, attach.ParentId);
        }
        S2SConnectionHelper.shareRecord(attachmentsToShare, GlobalConstants.S2S_CONNECTION_NAME);
        update scope;
    }

    global void finish(Database.BatchableContext BC){
        List<NoteOrAttachment__c> attachments = (List<NoteOrAttachment__c>) Database.query(query);
        if(!attachments.isEmpty()) {
            ShareAttachmentsBatch shareAttBatch = new ShareAttachmentsBatch();
            Database.executeBatch(shareAttBatch);
        }
    }
}