force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Attachment_DateTime__c</fullName>
    <description>Used for CFM API (Mobile App), stores date time provided by Feedback2Go App</description>
    <label>Attachment DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <description>This field will return the pdf attachment id from the attachments</description>
    <formula>IF(NOT(ISBLANK(PDF_Attachment__c)), PDF_Attachment__c,Attachment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/CaseArticle__c.field-meta.xml
<CustomField>
    <fullName>CaseArticle__c</fullName>
    <label>CaseArticle</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <formula>Case__r.CaseNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Response</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Unsigned Response</fullName>
            </value>
            <value>
                <fullName>Enclosures</fullName>
            </value>
            <value>
                <fullName>Incoming</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Conga_Response_PDF_Generated__c.field-meta.xml
<CustomField>
    <fullName>Conga_Response_PDF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for code purpose to track if PDF is generated for the current Response WordML document.</description>
    <inlineHelpText>This field is used for code purpose to track if PDF is generated for the current Response WordML document.</inlineHelpText>
    <label>Conga Response PDF Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Desktop_Editing__c.field-meta.xml
<CustomField>
    <fullName>Desktop_Editing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Response marked for editing in desktop</description>
    <inlineHelpText>Response marked for editing in desktop</inlineHelpText>
    <label>Mark For Desktop Editing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>Stores the standard attachment file name</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Is_Image__c.field-meta.xml
<CustomField>
    <fullName>Is_Image__c</fullName>
    <formula>OR(ContentType__c = &quot;image/png&quot;, ContentType__c = &quot;image/jpeg&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Image</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/IsMinCorroCaseNote__c.field-meta.xml
<CustomField>
    <fullName>IsMinCorroCaseNote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Note is associated to a MinCorro case</description>
    <label>IsMinCorroCaseNote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/IsMinCorroRelated__c.field-meta.xml
<CustomField>
    <fullName>IsMinCorroRelated__c</fullName>
    <description>Determines whether associated case is Min Corro. Persisted in IsMinCorroCaseNote for use in Sharing rules to Serco</description>
    <formula>Case__r.IsMinCorroCase__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsMinCorroRelated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/PDF_Attachment__c.field-meta.xml
<CustomField>
    <fullName>PDF_Attachment__c</fullName>
    <description>This field will store the Id of the attachment of the type pdf</description>
    <label>PDF Attachment__c</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <inlineHelpText>This allows user to mark security disposition of the record. Default is &quot;Standard&quot;</inlineHelpText>
    <label>Privacy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Rejection_Comment__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Comment__c</fullName>
    <label>Rejection Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Requires_Printing__c.field-meta.xml
<CustomField>
    <fullName>Requires_Printing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Printing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Response_PDF__c.field-meta.xml
<CustomField>
    <fullName>Response_PDF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used to identify the response PDF generated using WordML document from by Thunderhead.</description>
    <inlineHelpText>Field used to identify the response PDF generated using WordML document from by Thunderhead.</inlineHelpText>
    <label>Response PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Printing sequence</description>
    <inlineHelpText>Printing sequence number</inlineHelpText>
    <label>Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cover Letter</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Advise Request</fullName>
            </value>
            <value>
                <fullName>Article</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/View__c.field-meta.xml
<CustomField>
    <fullName>View__c</fullName>
    <formula>IF( $Profile.Name == &#39;TfNSW Operator Portal User&#39;,IF(RecordType.Name == &quot;Attachment&quot;, HYPERLINK(&quot;/operatorportal/servlet/servlet.FileDownload?file=&quot; + Attachment_Id__c,&quot;View&quot;),&quot;&quot;),IF(RecordType.Name == &quot;Attachment&quot;, HYPERLINK(&quot;/servlet/servlet.FileDownload?file=&quot; + Attachment_Id__c,&quot;View&quot;),&quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>View</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/classes/AttachmentAfterInsertTriggerHandler.cls
/*------------------------------------------------------------
Author:        Dipankar Barman
Company:       Arxxus.com
Description:   A utility class for the Attachment Trigger

Test Class:    AttachmentTriggerDispatcher_Test
History
04/05/2015     Dipankar Barman       Created
10/03/2017     Arxxus                Updated - Optimised code to avoid 101 SOQL limit
06/07/2018     Ian Fitzgerald        Added check for "DoNotCreateNOA" in file name
------------------------------------------------------------*/
public without sharing class AttachmentAfterInsertTriggerHandler extends TriggerHandlerBase{
    List<ApplicationLogMessage> messages =new List<ApplicationLogMessage>();
    static final String HTML_COMPONENT_PREFIX =  '02S';//added for send referral 101 soql
    static Id ATTACHMENT_RECORDTYPE_ID=null;//added for send referral 101 soql
    public override void mainEntry(TriggerParameters tp) {
        process(tp);        
    }
    
    public override void inProgressEntry(TriggerParameters tp) {
        System.debug('This is an example for reentrant code...');
    }
    
    private static List<String> inProgressJobStatus = new List<String> {'Queued', 'Preparing', 'Processing', 'Holding'};
    
    /*------------------------------------------------------------
    Author:        Dipankar Barman
    Company:       Arxxus.com
    Description:   Handler function to create NotesAndAttachment objects on inserting corresponding related attachemnts 
    History
    04/05/2015     Dipankar Barman       Created
    25/06/2015     Manish Damle          Added record type and removed the File Name
    ------------------------------------------------------------*/
    private void process(TriggerParameters tp) {
        List<NoteOrAttachment__c> noteOrAttachments = new List<NoteOrAttachment__c>();
        try{
            //added for send referral 101 soql
            if (ATTACHMENT_RECORDTYPE_ID==null){
                ATTACHMENT_RECORDTYPE_ID = [Select Id From RecordType Where SObjectType = 'NoteOrAttachment__c' And DeveloperName = 'Attachment'].Id;
            }

            Set<Id> parentIds = new Set<Id>();
            MAP<Id,Attachment> nonCaseParentIds= new MAP<Id,Attachment>();
            system.debug('get attachment :: ' + tp.newList);
            for(Attachment attach : (List<Attachment>)tp.newList){
                //Check to see if Parent Id is a Case Id
                if (((String)attach.ParentId).startsWith(GlobalConstants.CASE_ID_PREFIX)) {
                    parentIds.add(attach.ParentId);
                }else if(attach.ParentId!=null && !((String)attach.ParentId).startsWith(HTML_COMPONENT_PREFIX)) {//added for send referral 101 soql
                    nonCaseParentIds.put(attach.ParentId, attach);
                }
            }
            Map<Id,NoteOrAttachment__c> noteOrAttachmentMapForUpdate = new Map<Id,NoteOrAttachment__c>([SELECT Id, OwnerId, Name, RecordTypeId, CreatedDate, CreatedById,  Attachment_Id__c, Attachment__c, Body__c, CaseArticle__c, CaseNumber__c, Case__c, Category__c, ContentType__c, File_Name__c, IsMinCorroCaseNote__c, IsMinCorroRelated__c, Is_Image__c, PDF_Attachment__c, Privacy__c, Requires_Printing__c, Sequence__c, Type__c, View__c, Attachment_DateTime__c, Conga_Response_PDF_Generated__c, Desktop_Editing__c, Response_PDF__c, Rejection_Comment__c FROM NoteOrAttachment__c WHERE Id IN :nonCaseParentIds.keySet() and CreatedBy.Name=:GlobalConstants.MIN_COR_API_INTEGRATION_USERNAME]);
            system.debug('thisattachment by ::: ' + noteOrAttachmentMapForUpdate );
            for (Id noteOrAttachmentId: noteOrAttachmentMapForUpdate.keySet()){
                NoteOrAttachment__c noteOrAttachment=noteOrAttachmentMapForUpdate.get(noteOrAttachmentId);
                Attachment attach=nonCaseParentIds.get(noteOrAttachmentId);
                noteOrAttachment.Attachment__c=attach.Id;
                noteOrAttachment.Category__c=GlobalConstants.INCOMING;
                noteOrAttachment.ContentType__c=attach.ContentType;
            }


            Map<Id,Case> caseMap = null;//broken in two lines for send referral 101 soql
            if (parentIds.size()>0) caseMap= new Map<Id,Case>([SELECT Id, OwnerId FROM Case WHERE Id IN :parentIds]);
            /*
             * SNSW Changes START: Changes to share case attachments with SNSW
             */
            Map<Id, Id> attachmentVsCase = new Map<Id,Id>();
            /*
             * SNSW Changes END: Changes to share case attachments with SNSW
             */
            for(Attachment attachment: (List<Attachment>)tp.newList){
               //Check to see if Parent Id is a Case Id
               if (((String)attachment.ParentId).startsWith(GlobalConstants.CASE_ID_PREFIX) &&
                     !attachment.Name.contains('DoNotCreateNOA')) {
                    //Create a NoteOrAttachment record
                    NoteOrAttachment__c noteOrAttachment = new NoteOrAttachment__c();
                    noteOrAttachment.Attachment__c        = attachment.Id;
                    noteOrAttachment.Case__c              = attachment.ParentId;
                    noteOrAttachment.Name                 = attachment.Name;
                    noteOrAttachment.Requires_Printing__c = false;
                    noteOrAttachment.OwnerId              = attachment.OwnerId;
                    noteOrAttachment.ContentType__c       = attachment.ContentType;
                    noteOrAttachment.RecordTypeId         = ATTACHMENT_RECORDTYPE_ID;
                    
                    if(noteOrAttachment.Name.length() > 80) {
                     
                     String name = noteOrAttachment.Name;
                     
                     String fileExtension = name.substring(name.lastIndexOf('.'), name.length());
                     name = name.substring(0, 80-fileExtension.length());
                     noteOrAttachment.Name = name+fileExtension;
                    }
                    noteOrAttachments.add(noteOrAttachment);
                    /*
                     * SNSW Changes START: Changes to share case attachments with SNSW
                     */
                    if(!attachment.IsPartnerShared) {
                        System.debug(LoggingLevel.INFO, 'Attachment is not shared by partner');
                        attachmentVsCase.put(attachment.Id, attachment.ParentId);
                    } else if(caseMap.get(attachment.ParentId) != null) {
                        noteOrAttachment.OwnerId = caseMap.get(attachment.ParentId).OwnerId;
                    }
                    /*
                     * SNSW Changes END: Changes to share case attachments with SNSW
                     */
               }   
            }
            if(!noteOrAttachmentMapForUpdate.isEmpty()) update noteOrAttachmentMapForUpdate.values();
            
            //insert NoteOrAttachments
            System.debug(LoggingLevel.INFO, 'Number of custom attachments to create: ' + noteOrAttachments.size());
            if (!noteOrAttachments.isEmpty() && !S2SAttachmentShareStatusRetriever.shareAttachment) insert noteOrAttachments;
            /*
             * SNSW Changes START: Changes to share case attachments with SNSW
             */
            System.debug(LoggingLevel.INFO, 'Current attachment share status flag: ' + S2SAttachmentShareStatusRetriever.shareAttachment);
            if(!attachmentVsCase.isEmpty() && S2SAttachmentShareStatusRetriever.shareAttachment) {
                System.debug(LoggingLevel.INFO, 'Sharing ' + attachmentVsCase.size() + ' attachments.');
                List<ApexClass> batchClass = [SELECT Id FROM ApexClass WHERE Name = 'ShareAttachmentsBatch'];

                List<AsyncApexJob> existingJobs = [ SELECT Id, Status 
                                                    FROM AsyncApexJob 
                                                    WHERE Status IN :inProgressJobStatus
                                                        AND ApexClassId = :batchClass[0].Id];
                if(existingJobs.isEmpty()) {
                    System.debug(LoggingLevel.INFO, 'Execute batch to share attachments');
                    ShareAttachmentsBatch shareAttBatch = new ShareAttachmentsBatch();
                    System.scheduleBatch(shareAttBatch, 'Share attachments with SNSW',  5);
                }
            }
            /*
             * SNSW Changes END: Changes to share case attachments with SNSW
             */
        }catch(Exception e){
            system.debug('-----AttachmentAfterInsertTriggerHandler Exception---' + e.getMessage() + '---LINE---' + e.getLineNumber());
            ApplicationLogMessage message= new ApplicationLogMessage();
            message.source='AttachmentAfterInsertTriggerHandler';
            message.sourceFunction='process';
            if (tp!=null && tp.newMap!=null)  message.referenceInfo=JSON.serialize(tp.newMap.keySet());
            message.logMessage=e.getMessage();
            message.ex=e;
            message.debugLevel='Error';
            messages.add(message);
            ApplicationLogUtility.logMessage(messages);
            messages.clear();
            //THROW_EXCEPTIONS is a global constant, it is set to the current user's "Throw Exceptions" value 
            //"Throw Exceptions" is a checkbox on the User record. - Added by Ian F, tfNSW, 21/08/2017
            if (GlobalConstants.THROW_EXCEPTIONS){
                Throw(e);
            }
        }
    }
}