force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Is_Shared_S2S__c.field-meta.xml
<CustomField>
    <fullName>Is_Shared_S2S__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating if custom attachment record is shared via S2S</description>
    <label>Is Shared S2S</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <inlineHelpText>This allows user to mark security disposition of the record. Default is &quot;Standard&quot;</inlineHelpText>
    <label>Privacy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/classes/CaseAttachmentsSharedWithSNSW.cls
public without sharing class CaseAttachmentsSharedWithSNSW {

    private List<Case> sharedCases;
    private static Boolean allAttachmentsShared = false;
    public CaseAttachmentsSharedWithSNSW(List<Case> sharedCases) {
        if(sharedCases == null || sharedCases.isEmpty()) {
            throw new InvalidDataException('Failed to share case attachments. Case details missing');
        }
        this.sharedCases = sharedCases;
    }
    
    public void shareAttachments() {
        if(allAttachmentsShared) {
            return;
        }
        List<Attachment> attachmentsToShare = new List<Attachment>();
        Set<Id> existingAttachmentIds = new Set<Id>();
        Map<Id, Id> customAttachmentVsCase = new Map<Id,Id>();
        Set<Id> sharedCustomAttachments = new Set<Id>();
        Map<Id, NoteOrAttachment__c> customAttachmentMap = 
                    new Map<Id, NoteOrAttachment__c>([  SELECT Id, Case__c, Attachment__c, Is_Shared_S2S__c, Privacy__c 
                                                        FROM NoteOrAttachment__c 
                                                        WHERE Case__c IN :sharedCases
                                                            AND Is_Shared_S2S__c = false]);
        for(NoteOrAttachment__c customAttachment : customAttachmentMap.values()) {
            if(customAttachment.Attachment__c != null && customAttachment.Privacy__c != GlobalConstants.NOTEORATTACHMENT_PRIVACY_RESTRICTED) {
                existingAttachmentIds.add(customAttachment.Attachment__c);
                customAttachmentVsCase.put(customAttachment.Id, customAttachment.Case__c);
            }            
        }
        
        for(Attachment existingAttachment :[SELECT ParentId, Name, IsPrivate, Id, Description, ContentType,  Body 
                                            FROM Attachment 
                                            WHERE Id IN :existingAttachmentIds
                                                AND IsPrivate = false
                                                AND IsPartnerShared = false]) {
            Attachment newAttachment = new Attachment();
            newAttachment.ParentId = customAttachmentVsCase.get(existingAttachment.ParentId);
            newAttachment.Name = existingAttachment.Name;
            newAttachment.IsPrivate = existingAttachment.IsPrivate;
            newAttachment.Description = existingAttachment.Description;
            newAttachment.ContentType = existingAttachment.ContentType;
            newAttachment.Body = existingAttachment.Body;
            
            attachmentsToShare.add(newAttachment);
            sharedCustomAttachments.add(existingAttachment.ParentId);
        }
        
        if(!attachmentsToShare.isEmpty()) {            
            System.debug(LoggingLevel.INFO, 'Number of attachments to be shared: ' + attachmentsToShare.size());
            S2SAttachmentShareStatusRetriever.shareAttachment = true;
            insert attachmentsToShare;
            allAttachmentsShared = true;
            List<NoteOrAttachment__c> customAttachmentToUpdate = new List<NoteOrAttachment__c>();
            for(NoteOrAttachment__c attach : customAttachmentMap.values()) {
                if(sharedCustomAttachments.contains(attach.Id)) {
                    attach.Is_Shared_S2S__c = true;
                    customAttachmentToUpdate.add(attach);
                }
            }
            update customAttachmentToUpdate;
        }
    }
    
    public class InvalidDataException extends Exception {}
}