force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Signed Response</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Unsigned Response</fullName>
            </value>
            <value>
                <fullName>Enclosures</fullName>
            </value>
            <value>
                <fullName>Incoming</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Conga_Response_PDF_Generated__c.field-meta.xml
<CustomField>
    <fullName>Conga_Response_PDF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for code purpose to track if PDF is generated for the current Response WordML document.</description>
    <inlineHelpText>This field is used for code purpose to track if PDF is generated for the current Response WordML document.</inlineHelpText>
    <label>Conga Response PDF Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>Stores the standard attachment file name</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Response_Document_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Response_Document_File_Name__c</fullName>
    <formula>&#39;response_&#39;+LEFT(Text(NOW() + ((1/24)*11)), LEN(TEXT(NOW() + ((1/24)*11))) - 4)</formula>
    <label>Response Document File Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW NOTE</description>
    <label>Note</label>
</RecordType>

force-app/main/default/classes/NoteOrAttBeforeUpdateTriggerHandler.cls
/*------------------------------------------------------------
Author:        Manish Damle
Company:       Arxxus.com
Description:   A utility class for the Private Note trigger

Test Class:    NoteOrAttachmentTriggerDispatcher_Test
History
20/07/2015     Manish Damle       Created
23/11/2016     Arxxus             Update to rename Thunderhead wordML file 
------------------------------------------------------------*/
public class NoteOrAttBeforeUpdateTriggerHandler extends TriggerHandlerBase{
    
    List<ApplicationLogMessage> messages =new List<ApplicationLogMessage>();
    public boolean exceptionInvoked = FALSE;

    public override void mainEntry(TriggerParameters tp) {
        process(tp);
    }
    
    public override void inProgressEntry(TriggerParameters tp) {
        System.debug('This is an example for reentrant code...');
    }
    
    /*------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   Handler function updates the owner of the NoteOrAttachment to case owner when
                   case lookup value changes
    
    History
    20/07/2015     Manish Damle       Created
    23/11/2016     Arxxus             Update to rename Thunderhead wordML file 
    ------------------------------------------------------------*/
    private void process(TriggerParameters tp) {
        
        try {
            
            map <Id,Id> noteOrAttVsCaseIds = new map<Id,Id>();
            for(NoteOrAttachment__c att : (list <NoteOrAttachment__c>) tp.newList) {
                
                NoteOrAttachment__c newAtt = (NoteOrAttachment__c) tp.newMap.get(att.Id);
                NoteOrAttachment__c oldAtt = (NoteOrAttachment__c) tp.oldMap.get(att.Id);
                
                if(newAtt.Attachment__c != null 
                   && oldAtt.Case__c != null
                   && newAtt.Case__c != null
                   && oldAtt.Case__c != newAtt.Case__c 
                   && (newAtt.Category__c == 'Signed Response' || newAtt.Category__c == 'Amendment')
                   && newAtt.ContentType__c == 'application/pdf') {
                       noteOrAttVsCaseIds.put(newAtt.Id, newAtt.Case__c);
                }   
                
                // renaming the thunderhead wordML file
                if(newAtt.ContentType__c == 'application/msword' 
                   && newAtt.Conga_Response_PDF_Generated__c == FALSE
                   && newAtt.name.startsWith('response_')) {
                   
                   System.debug('Trying to rename file:'+newAtt.Name);
                   System.debug('Trying to rename file:'+newAtt.File_Name__c);
                   
                   //renaming the Thunderhead response draft
                   newAtt.Name = newAtt.Response_Document_File_Name__c+'.doc';
                }
            }
            
            if(noteOrAttVsCaseIds.size() > 0) {
                map <Id, Case> cases = new map <Id, Case> ([Select Id, OwnerId From Case Where Id IN: noteOrAttVsCaseIds.values()]);
                for(Id noteOrAttId : noteOrAttVsCaseIds.keySet()) {
                    if(cases.containsKey(noteOrAttVsCaseIds.get(noteOrAttId)) && cases.get(noteOrAttVsCaseIds.get(noteOrAttId)) != null) {
                        NoteOrAttachment__c newAtt = (NoteOrAttachment__c) tp.newMap.get(noteOrAttId);
                        newAtt.OwnerId =  cases.get(noteOrAttVsCaseIds.get(noteOrAttId)).OwnerId;
                    }
                }
            }
            
            /*
             * SNSW Changes START: Changes to share attachment with SNSW for qualified cases
             */
             System.debug(LoggingLevel.INFO, 'Checking for shared cases');
             NewAttachmentsSharedWithSNSW shareAttachInstance = new NewAttachmentsSharedWithSNSW((Map<Id,NoteOrAttachment__c>) tp.newMap);
             shareAttachInstance.shareAttachments();
             /*
              * SNSW Changes END: Changes to share attachment with SNSW for qualified cases
              */
        }
        catch(Exception e) {
            
            exceptionInvoked = TRUE;
            
            ApplicationLogMessage message= new ApplicationLogMessage();
            message.source='Private_NoteBeforeUpdateTriggerHandler';
            message.sourceFunction='process';
            if (tp!=null && tp.oldMap!=null)  message.referenceInfo=JSON.serialize(tp.oldMap.keySet());
            message.logMessage=e.getMessage();
            message.ex=e;
            message.debugLevel='Error';
            messages.add(message);
            ApplicationLogUtility.logMessage(messages);
            messages.clear(); 
            //THROW_EXCEPTIONS is a global constant, it is set to the current user's "Throw Exceptions" value 
            //"Throw Exceptions" is a checkbox on the User record. - Added by Ian F, tfNSW, 21/08/2017
            if (GlobalConstants.THROW_EXCEPTIONS){
                Throw(e);
            }
        }
    }
}