force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <description>This field will return the pdf attachment id from the attachments</description>
    <formula>IF(NOT(ISBLANK(PDF_Attachment__c)), PDF_Attachment__c,Attachment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Conga_Response_PDF_Generated__c.field-meta.xml
<CustomField>
    <fullName>Conga_Response_PDF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for code purpose to track if PDF is generated for the current Response WordML document.</description>
    <inlineHelpText>This field is used for code purpose to track if PDF is generated for the current Response WordML document.</inlineHelpText>
    <label>Conga Response PDF Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <inlineHelpText>This allows user to mark security disposition of the record. Default is &quot;Standard&quot;</inlineHelpText>
    <label>Privacy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW NOTE</description>
    <label>Note</label>
</RecordType>

force-app/main/default/classes/NoteOrAttAfterUpdateTriggerHandler.cls
/*------------------------------------------------------------
Author:        Manish Damle
Company:       Arxxus.com
Description:   A utility class for the Private Note trigger

Test Class:    NoteOrAttachmentTriggerDispatcher_Test
History
20/04/2015     Manish Damle       Created
14/11/2016     Arxxus             Updated - Added code to generate PDF using conga for
                                  file of type application/msword and name starting as response_
------------------------------------------------------------*/
public class NoteOrAttAfterUpdateTriggerHandler extends TriggerHandlerBase {

    List<ApplicationLogMessage> messages = new List<ApplicationLogMessage>();

    public boolean exceptionInvoked = FALSE;

    public override void mainEntry(TriggerParameters tp) {
        process(tp);
    }

    /*------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   Handler function updates the number of private notes 
                   on a particular case record.
    
    History
    20/04/2015     Manish Damle       Created
    ------------------------------------------------------------*/
    private void process(TriggerParameters tp) {
        try{

            system.debug('---Private_NoteAfterUpdateTriggerHandler---');

            list<NoteOrAttachment__c> sharingToBeRecalculated = new list<NoteOrAttachment__c>();
            NoteOrAttachmentCustomRollUpImpl.calculateRollUp((map<Id, NoteOrAttachment__c>) tp.newMap, (map<Id,NoteOrAttachment__c>) tp.oldMap);
            NoteOrAttachmentSharingHandler sharingHandler = new NoteOrAttachmentSharingHandler();

            for(NoteOrAttachment__c att : (list<NoteOrAttachment__c>) tp.newList) {

                NoteOrAttachment__c newNoteOrAttachment = (NoteOrAttachment__c) tp.newMap.get(att.Id);
                NoteOrAttachment__c oldNoteOrAttachment = (NoteOrAttachment__c) tp.oldMap.get(att.Id);
                if((newNoteOrAttachment.OwnerId != oldNoteOrAttachment.OwnerId) 
                   || (oldNoteOrAttachment.Privacy__c != newNoteOrAttachment.Privacy__c)) {
                    sharingToBeRecalculated.add(att);
                }

                System.debug('Attachment Record New: ' + newNoteOrAttachment);
                System.debug('Attachment Record Old: ' + oldNoteOrAttachment);

                if(newNoteOrAttachment.Attachment_Id__c != NULL 
                    && newNoteOrAttachment.ContentType__c == 'application/msword' 
                    && newNoteOrAttachment.Conga_Response_PDF_Generated__c == FALSE
                    && newNoteOrAttachment.name.startsWith('response_')) {

                    GenerateResponsePDF.generate(newNoteOrAttachment.Case__c, newNoteOrAttachment.Id, newNoteOrAttachment.Attachment_Id__c, newNoteOrAttachment.Name, UserInfo.getSessionId());
                }

            }

            sharingHandler.share(sharingToBeRecalculated);

            if(NoteOrAttachmentTriggerDispatcher.currentUserIsKnowledgeUser) {
                AttachmentToKnowledgeArticleConverter converter = new AttachmentToKnowledgeArticleConverter(tp);
                converter.convert();
                converter.attachCaseArticleToNewCase();
            }

        }
        catch(Exception e) {

            exceptionInvoked = TRUE;

            ApplicationLogMessage message = new ApplicationLogMessage();
            message.source = 'NoteOrAttAfterUpdateTriggerHandler';
            message.sourceFunction = 'process';
            if(tp != null && tp.oldMap != null) 
                message.referenceInfo = JSON.serialize(tp.oldMap.keySet());
            message.logMessage = e.getMessage();
            message.ex = e;
            message.debugLevel = 'Error';
            messages.add(message);
            ApplicationLogUtility.logMessage(messages);
            messages.clear();
            //THROW_EXCEPTIONS is a global constant, it is set to the current user's "Throw Exceptions" value 
            //"Throw Exceptions" is a checkbox on the User record. - Added by Ian F, tfNSW, 21/08/2017
            if (GlobalConstants.THROW_EXCEPTIONS){
                Throw(e);
            }
        }
    }
}