force-app/main/default/objects/AllowableFileExtensions__c/AllowableFileExtensions__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of allowed file types from web to case form</description>
    <label>Allowable file extensions</label>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <description>Stores standard attachment id</description>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/classes/WebToCaseAttachmentCreator_Test.cls
@isTest
private class WebToCaseAttachmentCreator_Test {
    
    private static List<Attachment> attachments;
    private static Case caseRecord;
    
    private static testMethod void testForInvalidTestData() {
        setUpTestData(1);
        System.Test.startTest();
        try {
            WebToCaseAttachmentCreator attachmentCreator = new WebToCaseAttachmentCreator(null, attachments);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        try {
            WebToCaseAttachmentCreator attachmentCreator = new WebToCaseAttachmentCreator(caseRecord, null);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        try {
            WebToCaseAttachmentCreator attachmentCreator = new WebToCaseAttachmentCreator(caseRecord, new List<Attachment>());
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForSingleAttachment() {
        setUpTestData(1);
        System.Test.startTest();
        WebToCaseAttachmentCreator attachmentCreator = new WebToCaseAttachmentCreator(caseRecord, attachments);
        attachmentCreator.createCaseAttachment();
        System.Test.stopTest();
        List<NoteOrAttachment__c> customAttachment = [SELECT ID, Attachment__c FROM NoteOrAttachment__c WHERE Case__c = :caseRecord.Id];
        System.assert(!customAttachment.isEmpty());
        List<Attachment> caseAttachments = [SELECT Id FROM Attachment WHERE ParentId = :customAttachment];
        System.assert(!caseAttachments.isEmpty());
        System.assert(caseAttachments.size() == 1);
    }
    
    private static testMethod void testForMultipleAttachments() {
        setUpTestData(10);
        System.Test.startTest();
        WebToCaseAttachmentCreator attachmentCreator = new WebToCaseAttachmentCreator(caseRecord, attachments);
        attachmentCreator.createCaseAttachment();
        System.Test.stopTest();
        List<NoteOrAttachment__c> customAttachment = [SELECT ID, Attachment__c FROM NoteOrAttachment__c WHERE Case__c = :caseRecord.Id];
        System.assert(!customAttachment.isEmpty());
        List<Attachment> caseAttachments = [SELECT Id FROM Attachment WHERE ParentId = :customAttachment];
        System.assert(!caseAttachments.isEmpty());
        System.assert(caseAttachments.size() == 10);
    }
    
    private static testMethod void testForBlankAttachmentBody() {
        setUpTestData(1);
        attachments[0].Body = null;
        System.Test.startTest();
        WebToCaseAttachmentCreator attachmentCreator = new WebToCaseAttachmentCreator(caseRecord, attachments);
        attachmentCreator.createCaseAttachment();
        System.Test.stopTest();
        List<Attachment> caseAttachments = [SELECT Id FROM Attachment WHERE ParentId = :caseRecord.Id];
        System.assert(caseAttachments.isEmpty());       
    }
    
    private static void setUpTestData(Integer attachmentCount) {
        createCase();
        attachments = new List<Attachment>();
        for(Integer i = 0; i < attachmentCount; i++) {
            Attachment attach = new Attachment();
            attach.body = Blob.valueOf('Test attachment');
            attach.Name = 'testFile.txt';
            attachments.add(attach);
        }
        createCustomSetting();
    }
    
    private static void createCase() {      
        caseRecord = new Case();
        caseRecord.Origin = 'Web';
        caseRecord.Priority = 'Normal';
        caseRecord.Type = 'Compliment';
        caseRecord.Description = 'Test case for spam check';    
        insert caseRecord;
        caseRecord = [SELECT Id, OwnerId FROM Case WHERE Id = :caseRecord.Id];
    }
    
    private static void createCustomSetting() {
        AllowableFileExtensions__c allowedFiles = new AllowableFileExtensions__c(Name = '.txt');
        insert allowedFiles;
    }
}