force-app/main/default/objects/Ferry_route_location_level1_values__c/Ferry_route_location_level1_values__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of location level 1 values under mode=ferry. All level2 child of this list will be displayed on webform for ferry route</description>
    <label>Ferry route location level 1 values</label>
</CustomObject>

force-app/main/default/objects/Ferry_wharf_location_level1_values__c/Ferry_wharf_location_level1_values__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ist of location level 1 values under mode=ferry. All level2 child of this list will be displayed on webform under ferry wharf</description>
    <label>Ferry wharf location level 1 values</label>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>NSW Trains</fullName>
            </value>
            <value>
                <fullName>RMS</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>STA</fullName>
            </value>
            <value>
                <fullName>Sydney Trains</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>PBO</fullName>
            </value>
            <value>
                <fullName>Newcastle Transport</fullName>
            </value>
            <value>
                <fullName>LRO</fullName>
            </value>
            <value>
                <fullName>MTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Customer_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Value__c</fullName>
    <description>Allows the customer facing value to be different from the internal / staff-facing taxonomy value</description>
    <inlineHelpText>Defines the value that customers can select if this taxonomy item is visible in customer-facing channels (i.e. on the web).</inlineHelpText>
    <label>Customer Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access &amp; Convenience</fullName>
            </value>
            <value>
                <fullName>Cleanliness</fullName>
            </value>
            <value>
                <fullName>Comfort</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Security</fullName>
            </value>
            <value>
                <fullName>Ticketing</fullName>
            </value>
            <value>
                <fullName>Timeliness</fullName>
            </value>
            <value>
                <fullName>Timetables</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Staff/Customer Service</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Licensing &amp; Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Issue_Accountability__c.field-meta.xml
<CustomField>
    <fullName>Issue_Accountability__c</fullName>
    <inlineHelpText>Defines which area is accountable for case management when this taxonomy item is selected (where case management can be determined purely by case category or location alone)</inlineHelpText>
    <label>Issue Accountability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Customer Liaison Team</fullName>
            </value>
            <value>
                <fullName>Depot</fullName>
            </value>
            <value>
                <fullName>IDD Pacific Highway</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Maritime Boating Operations</fullName>
            </value>
            <value>
                <fullName>Maritime Statewide Coordination</fullName>
            </value>
            <value>
                <fullName>Road Maintenance</fullName>
            </value>
            <value>
                <fullName>SEG Government Information Services</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>Speed Limits and Cameras</fullName>
            </value>
            <value>
                <fullName>Traffic Management &amp; Safety</fullName>
            </value>
            <value>
                <fullName>JMD - TOLLING</fullName>
            </value>
            <value>
                <fullName>Road rules</fullName>
            </value>
            <value>
                <fullName>IDD - CONTRACTS &amp; PROJECT STRATEGY</fullName>
            </value>
            <value>
                <fullName>IDD - Greater Sydney Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Freight &amp; Regional Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Commercial</fullName>
            </value>
            <value>
                <fullName>IDD - Pacific Highway Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Western Sydney Program Office</fullName>
            </value>
            <value>
                <fullName>RMS - CEP - Govt Information Services</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Sydney or Regional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <label>KPI</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Cleanliness</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Internal Matters</fullName>
            </value>
            <value>
                <fullName>OTR</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Ticketing</fullName>
            </value>
            <value>
                <fullName>Timetable</fullName>
            </value>
            <value>
                <fullName>Not Categorised</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Taxonomy_Metadata__c.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Taxonomy_Metadata__c.Type__c</field>
            <operation>equals</operation>
            <value>Mode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Meta Categorisations</relationshipLabel>
    <relationshipName>Child_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Customer_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Customer_Facing__c</fullName>
    <inlineHelpText>Indicates whether this value is available for selection on customer-facing channels (i.e. web)</inlineHelpText>
    <label>Status - Customer Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_NSWT_Customer_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_NSWT_Customer_Facing__c</fullName>
    <label>Status - NSWT Customer Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_ST_Customer_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_ST_Customer_Facing__c</fullName>
    <label>Status - ST Customer Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Staff_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Staff_Facing__c</fullName>
    <inlineHelpText>Identifies whether this value is available (active) for selection in staff-facing channels</inlineHelpText>
    <label>Status - Staff Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Train_line_location_level1_values__c/Train_line_location_level1_values__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of location level 1 values under mode=train. All level2 child of this list will be displayed on webform for train line</description>
    <label>Train line location level 1 values</label>
</CustomObject>

force-app/main/default/objects/Train_station_location_level1_values__c/Train_station_location_level1_values__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of location level 1 values under mode=train. All level2 child of this list will be displayed on webform</description>
    <label>Train station location level 1 values</label>
</CustomObject>

force-app/main/default/classes/TaxonomyRetriever_Test.cls
@isTest
private class TaxonomyRetriever_Test {
    private static String mode;
    private static String category;
    private static String subcategory;
    private static String level1LocValue;
    private static String level2LocValue;
    private static String level3LocValue;
    
    private static testMethod void testForRetrievingCategory() {
        mode = 'Road';
        category = 'Road rules';
        subcategory = 'Parking rules';
        level1LocValue = 'Region';
        level2LocValue = 'Sydney';
        level3LocValue = 'Sydney';
        setUpTestData(false, false);
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveIssueCategoryAndSubCategory('');
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get('Road:Road rules'));
        System.assert(subCat.contains(subcategory));
    }
    
    private static testMethod void testForRetrievingCategoryForSydneyTrains() {
        mode = 'Train';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'Region';
        level2LocValue = 'Sydney';
        level3LocValue = 'Sydney';
        setUpTestData(false, true);
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveIssueCategoryAndSubCategory(GlobalConstants.WEBTOCASE_SOURCE_SYDNEY_TRAINS);
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get('Train:Air Pollution'));
        System.assert(subCat.contains(subcategory));
    }
    
    private static testMethod void testForRetrievingCategoryForPassesAndFares() {
        mode = 'non-modal';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'Region';
        level2LocValue = 'Sydney';
        level3LocValue = 'Sydney';
        setUpTestData(false, true);
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveIssueCategoryAndSubCategoryNonModal('tfnsw','non-modal','Tickets%2C%20Passes%20and%20Schemes');
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get('non-modal:Air Pollution'));
        System.assert(subCat.contains(subcategory));
    }    
    
    private static testMethod void testForRetrievingCategoryForNswTrains() {
        mode = 'Train';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'Region';
        level2LocValue = 'Sydney';
        level3LocValue = 'Sydney';
        setUpTestData(true, false);
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveIssueCategoryAndSubCategory(GlobalConstants.WEBTOCASE_SOURCE_NSW_TRAINS);
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get('Train:Air Pollution'));
        System.assert(subCat.contains(subcategory));
    }
    
    private static testMethod void testForRetrievingStationForSydneyTrains() {
        mode = 'Train';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'Sydney Trains Stations';
        level2LocValue = 'CBD Inner West';
        level3LocValue = 'Bondi Junction';
        setUpTestData(false, true);
        Train_station_location_level1_values__c trainStation = new Train_station_location_level1_values__c(Name=level1LocValue);
        insert trainStation;
        
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveLocationTaxonomy(GlobalConstants.WEBTOCASE_SOURCE_SYDNEY_TRAINS,mode);
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get(mode+ ':' + Label.Train_Station));
        System.assert(subCat.contains(level3LocValue));
    }
    
    private static testMethod void testForRetrievingLineForNswTrains() {
        mode = 'Train';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'NSW TrainLink Intercity Train Lines';
        level2LocValue = 'Train Line';
        level3LocValue = 'Blue Mountains Line';
        setUpTestData(true, false);
        Train_line_location_level1_values__c trainLine = new Train_line_location_level1_values__c(Name=level1LocValue);
        insert trainLine;
        
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveLocationTaxonomy(GlobalConstants.WEBTOCASE_SOURCE_NSW_TRAINS,mode);
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get(mode+ ':' + Label.Train_Line));
        System.assert(subCat.contains(level3LocValue));
    }
        
    private static testMethod void testForRetrievingFerryRoute() {
        mode = 'Ferry';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'Sydney Ferries - Ferry';
        level2LocValue = 'Manly';
        level3LocValue = 'F1 - Manly Ferry';
        setUpTestData(false, false);
        Ferry_route_location_level1_values__c ferryRoute = new Ferry_route_location_level1_values__c(Name=level1LocValue);
        insert ferryRoute;
        
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveLocationTaxonomy('',mode);
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get(mode+ ':' + Label.Ferry_Route));
        System.assert(subCat.contains(level3LocValue));
    }
    
    private static testMethod void testForRetrievingFerryWharf() {
        mode = 'Ferry';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'Sydney Ferries - Wharf';
        level2LocValue = 'Manly';
        level3LocValue = 'Manly';       
        setUpTestData(false, false);
        Ferry_wharf_location_level1_values__c ferryWharf = new Ferry_wharf_location_level1_values__c(Name=level1LocValue);
        insert ferryWharf;
        
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveLocationTaxonomy('',mode);
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get(mode+ ':' + Label.Ferry_Wharf));
        System.assert(subCat.contains(level3LocValue));
    }
    
    private static testMethod void testForRetrievingBusRoute() {
        mode = 'Bus';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'Busways Blacktown';
        level2LocValue = 'SMBSC 1';
        level3LocValue = '673';
        setUpTestData(false, false);
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveLocationTaxonomy('',mode);
        List<String> matchingBusTaxo = WebToCase_CX.getMatchingLocTaxonomy('6', mode, false);
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get(mode+ ':' + Label.Bus_Route));
        System.assert(subCat.contains(level3LocValue));
        System.assert(matchingBusTaxo.contains(level3LocValue));
        
    }
    
    private static testMethod void testForRetrievingLocationForLightRail() {
        mode = 'Light Rail';
        category = 'Air Pollution';
        subcategory = 'Air';
        level1LocValue = 'Light Rail';
        level2LocValue = 'Light Rail';
        level3LocValue = 'Dulwich Hill Line';
        setUpTestData(false, false);
        System.Test.startTest();
        Map<String,List<String>> taxonomyData = TaxonomyRetriever.retrieveLocationTaxonomy('',mode);
        System.Test.stopTest();
        System.assert(!taxonomyData.isEmpty());
        Set<String> subCat = new Set<String>();
        subCat.addAll(taxonomyData.get(mode+ ':'));
        System.assert(subCat.contains(level3LocValue));
    }
    
    private static void setUpTestData(Boolean isNswTrains, Boolean isSydneyTrains) {
        createTaxonomy(isNswTrains, isSydneyTrains);
    }   
        
    private static void createTaxonomy(Boolean isNswTrains, Boolean isSydneyTrains) {      
        Taxonomy_Metadata__c modeTaxonomy = new Taxonomy_Metadata__c();
        modeTaxonomy.Type__c = 'Mode';
        modeTaxonomy.Status_Customer_Facing__c = 'Active';
        modeTaxonomy.Status_Staff_Facing__c = 'Active';
        modeTaxonomy.Customer_Value__c = mode;
        modeTaxonomy.Name = mode;
        modeTaxonomy.Status_NSWT_Customer_Facing__c = (isNswTrains? 'Active' : 'Inactive');
        modeTaxonomy.Status_ST_Customer_Facing__c = (isSydneyTrains? 'Active' : 'Inactive');
        
        insert modeTaxonomy;
        
        List<Taxonomy_Metadata__c> level1Taxonomies = new List<Taxonomy_Metadata__c>();
        Taxonomy_Metadata__c level1Loc = new Taxonomy_Metadata__c();
        level1Loc.Type__c = 'Location';
        level1Loc.Status_Customer_Facing__c = 'Active';
        level1Loc.Status_Staff_Facing__c = 'Active';
        level1Loc.Customer_Value__c = level1LocValue;
        level1Loc.Name = level1LocValue;
        level1Loc.Parent_Id__c = modeTaxonomy.Id;
        level1Loc.Status_NSWT_Customer_Facing__c = (isNswTrains? 'Active' : 'Inactive');
        level1Loc.Status_ST_Customer_Facing__c = (isSydneyTrains? 'Active' : 'Inactive');
        level1Taxonomies.add(level1Loc);
        
        Taxonomy_Metadata__c level1Issue = new Taxonomy_Metadata__c();
        level1Issue.Type__c = 'Issue';
        level1Issue.Status_Customer_Facing__c = 'Active';
        level1Issue.Status_Staff_Facing__c = 'Active';
        level1Issue.Customer_Value__c = 'Road';
        level1Issue.Name = 'Road';
        level1Issue.Parent_Id__c = modeTaxonomy.Id;
        level1Issue.Status_NSWT_Customer_Facing__c = (isNswTrains? 'Active' : 'Inactive');
        level1Issue.Status_ST_Customer_Facing__c = (isSydneyTrains? 'Active' : 'Inactive');
        level1Taxonomies.add(level1Issue);
        
        insert level1Taxonomies;
        
        List<Taxonomy_Metadata__c> level2Taxonomies = new List<Taxonomy_Metadata__c>();
        Taxonomy_Metadata__c level2Loc = new Taxonomy_Metadata__c();
        level2Loc.Type__c = 'Location';
        level2Loc.Status_Customer_Facing__c = 'Active';
        level2Loc.Status_Staff_Facing__c = 'Active';
        level2Loc.Customer_Value__c = level2LocValue;
        level2Loc.Name = level2LocValue;
        level2Loc.Parent_Id__c = level1Loc.Id;
        level2Loc.Status_NSWT_Customer_Facing__c = (isNswTrains? 'Active' : 'Inactive');
        level2Loc.Status_ST_Customer_Facing__c = (isSydneyTrains? 'Active' : 'Inactive');
        level2Taxonomies.add(level2Loc);
        
        Taxonomy_Metadata__c level2Issue = new Taxonomy_Metadata__c();
        level2Issue.Type__c = 'Issue';
        level2Issue.Status_Customer_Facing__c = 'Active';
        level2Issue.Status_Staff_Facing__c = 'Active';
        level2Issue.Customer_Value__c = category;
        level2Issue.Name = category;
        level2Issue.Parent_Id__c = level1Issue.Id;
        level2Issue.Status_NSWT_Customer_Facing__c = (isNswTrains? 'Active' : 'Inactive');
        level2Issue.Status_ST_Customer_Facing__c = (isSydneyTrains? 'Active' : 'Inactive');
        level2Taxonomies.add(level2Issue);
        
        insert level2Taxonomies;
        
        List<Taxonomy_Metadata__c> level3Taxonomies = new List<Taxonomy_Metadata__c>();
        Taxonomy_Metadata__c taxonomyLoc = new Taxonomy_Metadata__c();
        taxonomyLoc.Agency__c = 'RMS';
        taxonomyLoc.Customer_Value__c = level3LocValue;
        taxonomyLoc.Name = level3LocValue;
        taxonomyLoc.Issue_Accountability__c = 'Test Location Taxonomy';
        taxonomyLoc.Driver__c = '';
        taxonomyLoc.KPI__c = '';
        taxonomyLoc.Parent_Id__c = level2Loc.Id;
        taxonomyLoc.Status_Customer_Facing__c = 'Active';
        taxonomyLoc.Status_Staff_Facing__c = 'Active';
        taxonomyLoc.Status_NSWT_Customer_Facing__c = (isNswTrains? 'Active' : 'Inactive');
        taxonomyLoc.Status_ST_Customer_Facing__c = (isSydneyTrains? 'Active' : 'Inactive');
        taxonomyLoc.Type__c = 'Location'; 

        Taxonomy_Metadata__c taxonomyIssue = new Taxonomy_Metadata__c();
        taxonomyIssue.Agency__c = 'RMS';
        taxonomyIssue.Customer_Value__c = subcategory;
        taxonomyIssue.Name = subcategory;
        taxonomyIssue.Issue_Accountability__c = 'Test Location Taxonomy';
        taxonomyIssue.Driver__c = '';
        taxonomyIssue.KPI__c = '';
        taxonomyIssue.Parent_Id__c = level2Issue.Id;
        taxonomyIssue.Status_Customer_Facing__c = 'Active';
        taxonomyIssue.Status_Staff_Facing__c = 'Active';
        taxonomyIssue.Status_NSWT_Customer_Facing__c = (isNswTrains? 'Active' : 'Inactive');
        taxonomyIssue.Status_ST_Customer_Facing__c = (isSydneyTrains? 'Active' : 'Inactive');
        taxonomyIssue.Type__c = 'Issue';        
        level3Taxonomies.add(taxonomyIssue);
        level3Taxonomies.add(taxonomyLoc);
        insert level3Taxonomies;
    }
}