force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Case_Description__c.field-meta.xml
<CustomField>
    <fullName>Case_Description__c</fullName>
    <label>Case Description</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_1__c</fullName>
    <label>Issue Level 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_2__c</fullName>
    <label>Issue Level 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3__c</fullName>
    <label>Issue Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Issue Level 3  metacategorisation Id</description>
    <inlineHelpText>Issue Level 3  metacategorisation Id</inlineHelpText>
    <label>Issue Level 3 Id</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_1__c</fullName>
    <label>Location Level 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_2__c</fullName>
    <label>Location Level 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3__c</fullName>
    <label>Location Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location Level 3  metacategorisation Id</description>
    <inlineHelpText>Issue Level 3  metacategorisation Id</inlineHelpText>
    <label>Location Level 3 Id</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Action Plans (Location Level 3 Id)</relationshipLabel>
    <relationshipName>Action_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>NSW Trains</fullName>
            </value>
            <value>
                <fullName>RMS</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>STA</fullName>
            </value>
            <value>
                <fullName>Sydney Trains</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>PBO</fullName>
            </value>
            <value>
                <fullName>Newcastle Transport</fullName>
            </value>
            <value>
                <fullName>LRO</fullName>
            </value>
            <value>
                <fullName>MTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access &amp; Convenience</fullName>
            </value>
            <value>
                <fullName>Cleanliness</fullName>
            </value>
            <value>
                <fullName>Comfort</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Security</fullName>
            </value>
            <value>
                <fullName>Ticketing</fullName>
            </value>
            <value>
                <fullName>Timeliness</fullName>
            </value>
            <value>
                <fullName>Timetables</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Staff/Customer Service</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Licensing &amp; Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Issue_Accountability__c.field-meta.xml
<CustomField>
    <fullName>Issue_Accountability__c</fullName>
    <inlineHelpText>Defines which area is accountable for case management when this taxonomy item is selected (where case management can be determined purely by case category or location alone)</inlineHelpText>
    <label>Issue Accountability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Customer Liaison Team</fullName>
            </value>
            <value>
                <fullName>Depot</fullName>
            </value>
            <value>
                <fullName>IDD Pacific Highway</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Maritime Boating Operations</fullName>
            </value>
            <value>
                <fullName>Maritime Statewide Coordination</fullName>
            </value>
            <value>
                <fullName>Road Maintenance</fullName>
            </value>
            <value>
                <fullName>SEG Government Information Services</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>Speed Limits and Cameras</fullName>
            </value>
            <value>
                <fullName>Traffic Management &amp; Safety</fullName>
            </value>
            <value>
                <fullName>JMD - TOLLING</fullName>
            </value>
            <value>
                <fullName>Road rules</fullName>
            </value>
            <value>
                <fullName>IDD - CONTRACTS &amp; PROJECT STRATEGY</fullName>
            </value>
            <value>
                <fullName>IDD - Greater Sydney Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Freight &amp; Regional Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Commercial</fullName>
            </value>
            <value>
                <fullName>IDD - Pacific Highway Program Office</fullName>
            </value>
            <value>
                <fullName>IDD - Western Sydney Program Office</fullName>
            </value>
            <value>
                <fullName>RMS - CEP - Govt Information Services</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Sydney or Regional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <label>KPI</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Cleanliness</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Internal Matters</fullName>
            </value>
            <value>
                <fullName>OTR</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Ticketing</fullName>
            </value>
            <value>
                <fullName>Timetable</fullName>
            </value>
            <value>
                <fullName>Not Categorised</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Taxonomy_Metadata__c.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Taxonomy_Metadata__c.Type__c</field>
            <operation>equals</operation>
            <value>Mode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Meta Categorisations</relationshipLabel>
    <relationshipName>Child_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Staff_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Staff_Facing__c</fullName>
    <inlineHelpText>Identifies whether this value is available (active) for selection in staff-facing channels</inlineHelpText>
    <label>Status - Staff Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActionPlanCategorisationAction.cls
/*------------------------------------------------------------
Author:        Vishnu Belkone
Company:       Arxxus.com
Description:   A Action_Plan__c controller extension for Action_Plan__c categorisation publisher action

Test Class:    EmailMessageTriggerDispatcher_Test
History
13 May 2015      Vishnu Belkone     created
------------------------------------------------------------*/
global with sharing class ActionPlanCategorisationAction {
    global static Final string LOCATION_TYPE='Location';
    global static Final string ISSUE_TYPE='Issue';
    global static Final string STAFF_FACING='Active';
    global static Final string ROOT_PARENT='#';
    global static Final string MODE_TYPE='Mode';
    global static Final string APOSTROPHE = '&#39;';
    public Action_Plan__c actionPlan{get;set;}
    public string caseDescription{get;set;}
    public ActionPlanCategorisationAction (ApexPages.StandardController controller){
        if(!test.isRunningTest()) controller.addFields(new List<String>{'Case_Description__c'});
         actionPlan = (Action_Plan__c) controller.getRecord();
       
        actionPlan = [select id,name,Case_Description__c from action_plan__c where id = :actionPlan.Id ];
        
        system.debug('#actionPlan.Case_Description__c'+actionPlan.Case_Description__c);
        system.debug('#Decoded actionPlan.Case_Description__c'+actionPlan.Case_Description__c);
        
        if(actionPlan.Case_Description__c != NULL){
            caseDescription = HTMLRemover.remove(actionPlan.Case_Description__c);
            system.debug('#caseDescription'+caseDescription);
            
            caseDescription = caseDescription.replace(APOSTROPHE,'\'');
            system.debug('#current Reccord'+actionPlan);
        }
    }
    
   
    
    /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   This method returns the list of modes of transport

    History
    13 May 2015       Vishnu Belkone     created
    ------------------------------------------------------------*/

    @RemoteAction
    global static List<Node> getModes(string actionPlaId) {
        StateChecker locater;
        if(null!=actionPlaId && actionPlaId.length()>=15){
             actionPlaId=String.escapeSingleQuotes(actionPlaId);
            Action_Plan__c actionPlan=[select Id, Mode__c,Parent_Case__c from Action_Plan__c where Id=:actionPlaId];
            locater= new ModeChecker(actionPlan);
        }
        List<Taxonomy_Metadata__c> modes=[select Id,Parent_Id__c,Status_Staff_Facing__c, name, Parent_Id__r.Type__c from  Taxonomy_Metadata__c where Status_Staff_Facing__c=:STAFF_FACING and Type__c=:MODE_TYPE ];
        if (null==modes) return null;
        return getNodes(modes,locater);

    }
     /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   Inner bean class represents the data for a Node

    History
    13 May 2015       Vishnu Belkone     created
    ------------------------------------------------------------*/
    global class Node{
        public String id {get;set;}//every node is given an unique id
        public String parent {get;set;}// will be used for placement within hierarchy
        public String text {get;set;}//what will be displayed on the UI
        public State state{get;set;}//selected etc

    }
     /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   Inner bean class represents the state of a Node

    History
    13 May 2015       Vishnu Belkone     created
    ------------------------------------------------------------*/
    global class State{
        public Boolean selected {get;set;}
        public Boolean opened {get;set;}
    }
    /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   Interface for checking and obtaining the state
                    of the node, based on past selections, persisted on case

    History
    13 May 2015       Vishnu Belkone     created
    ------------------------------------------------------------*/
    @TestVisible
    interface StateChecker{
        State getState(Taxonomy_metadata__c taxonomy);
    }
     /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   This method returns the list of type picklist entry from the Taxonomy metadata

    History
    13 May 2015       Vishnu Belkone     created
    ------------------------------------------------------------*/
    
    @TestVisible
    class LocationChecker implements StateChecker{
        Action_Plan__c thisAp;
        public LocationChecker(Action_Plan__c thisAp){
            this.thisAp=thisAp;
        }
        public virtual State getState (Taxonomy_metadata__c taxonomy){
            State thisState;
            if (thisAp!=null ){
                
                if (thisAp.Location_Level_3_Id__c!=null && taxonomy.id==thisAp.Location_Level_3_Id__c){
                    thisState= new State();
                    thisState.selected=true;
                }else if(thisAp.Location_Level_3_Id__c==null ){
                    if(thisAp.Location_Level_2__c!=null && !String.isEmpty(thisAp.Location_Level_2__c) && taxonomy.name.equalsIgnoreCase(thisAp.Location_Level_2__c)){
                        thisState= new State();
                        thisState.selected=false;
                        thisState.opened=true;
                    }else if (thisAp.Location_Level_2__c==null ||String.isEmpty(thisAp.Location_Level_2__c)){
                        if(thisAp.Location_Level_1__c!=null && !String.isEmpty(thisAp.Location_Level_1__c) && taxonomy.name.equalsIgnoreCase(thisAp.Location_Level_1__c)){
                            thisState= new State();
                            thisState.selected=false;
                            thisState.opened=true;
                        }else if(thisAp.Location_Level_1__c==null || String.isEmpty(thisAp.Location_Level_1__c)){
                            if(thisAp.mode__c!=null && !String.isEmpty(thisAp.mode__c) && taxonomy.name.equalsIgnoreCase(thisAp.mode__c)){
                                thisState= new State();
                                thisState.selected=false;
                                thisState.opened=true;
                            }
                        }
                    }
                }
                
            }
            return thisState;
        }
    }

    /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   Concrete implementation for checking and obtaining the state
                    of any issue, based on past selections, persisted on case

    History
    9 Apr 2015      Vishnu Belkone     created
    ------------------------------------------------------------*/
    @TestVisible
    class IssueChecker implements StateChecker{
        Action_Plan__c thisAp;
        public IssueChecker(Action_Plan__c thisAp){
            this.thisAp=thisAp;
        }
        public virtual State getState(Taxonomy_metadata__c taxonomy){
            State thisState;
            if (thisAp!=null && thisAp.Issue_Level_3_Id__c!=null && taxonomy.id==thisAp.Issue_Level_3_Id__c){
                thisState= new State();
                thisState.selected=true;

            }else if(thisAp.Issue_Level_3_Id__c==null ){
                if(thisAp.Issue_Level_2__c!=null && !String.isEmpty(thisAp.Issue_Level_2__c) && taxonomy.name.equalsIgnoreCase(thisAp.Issue_Level_2__c)){
                    thisState= new State();
                    thisState.selected=false;
                    thisState.opened=true;
                }else if (thisAp.Issue_Level_2__c==null ||String.isEmpty(thisAp.Issue_Level_2__c)){
                    if(thisAp.Issue_Level_1__c!=null && !String.isEmpty(thisAp.Issue_Level_1__c) && taxonomy.name.equalsIgnoreCase(thisAp.Issue_Level_1__c)){
                        thisState= new State();
                        thisState.selected=false;
                        thisState.opened=true;
                    }else if(thisAp.Issue_Level_1__c==null || String.isEmpty(thisAp.Issue_Level_1__c)){
                        if(thisAp.mode__c!=null && !String.isEmpty(thisAp.mode__c) && taxonomy.name.equalsIgnoreCase(thisAp.mode__c)){
                            thisState= new State();
                            thisState.selected=false;
                            thisState.opened=true;
                        }
                    }
                }
            }
            return thisState;
        }
    }


    /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   Concrete implementation for checking and obtaining the state
                    of any mode, based on past selections, persisted on case

    History
    9 Apr 2015      Vishnu Belkone     created
    ------------------------------------------------------------*/
    @TestVisible
    class ModeChecker implements StateChecker{
        Action_Plan__c thisAp;
        public ModeChecker(Action_Plan__c thisAp){
            this.thisAp=thisAp;
        }
        public virtual State getState(Taxonomy_metadata__c taxonomy){
            State thisState;
            if (thisAp!=null && thisAp.Mode__c!=null && !String.isEmpty(thisAp.Mode__c) && taxonomy.name.equalsIgnoreCase(thisAp.Mode__c) ){
                thisState= new State();
                thisState.selected=true;

            }
            return thisState;
        }
    }

   

    /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   remoteaction to obtain the list of Locations
                    caseid used to check if some issue was already persisted
                    mode based on which the Locations are fetched

    History
    9 Apr 2015      Vishnu Belkone     created
    ------------------------------------------------------------*/
    @RemoteAction
    global static List<Node> getLocations(string actionPlanId,String modeId) {
        StateChecker locater;
        modeId=String.escapeSingleQuotes(modeId);

        if(null!=actionPlanId && actionPlanId.length()>=15){
            actionPlanId=String.escapeSingleQuotes(actionPlanId);
             Action_Plan__c actionPlan=[select Id,Case_Description__c,mode__c,Issue_Level_1__c,Issue_Level_2__c,Issue_Level_3__c,Issue_Level_3_Id__c,Location_Level_1__c,Location_Level_2__c,Location_Level_3__c,Location_Level_3_Id__c from Action_Plan__c where id =:actionPlanId];
            locater= new LocationChecker(actionPlan);

        }

        
        List<Taxonomy_Metadata__c> locations=[select Id,name,Parent_Id__c,Status_Staff_Facing__c,Parent_Id__r.Type__c,Agency__c from  Taxonomy_Metadata__c where Status_Staff_Facing__c=:STAFF_FACING and Type__c=:LOCATION_TYPE 
                                                and (Parent_Id__r.Parent_Id__r.Parent_Id__c=:modeId or
                                                Parent_Id__r.Parent_Id__c=:modeId or Parent_Id__c=:modeId) Limit 10000];
        if (null==locations) return null;
        return getNodes(locations,locater);

    }

    /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   This method returns the list of nodes taking
    Inputs:        List of taxonomy be it Location or issue
                    and the corresponding checker

    History
    9 Apr 2015      Vishnu Belkone     created
    ------------------------------------------------------------*/
    @TestVisible
    static List<Node> getNodes(List<Taxonomy_Metadata__c> taxonomies, StateChecker checker ){
        MAP<String,Node> nodes= new MAP<String,Node>();//node id vs Node
        Node selected;
        for (Taxonomy_Metadata__c aTaxonomy: taxonomies){

            Node aNode=new Node();
            if (null!=checker){
                aNode.state=checker.getState(aTaxonomy);
                if (null !=aNode.state) selected=aNode;
            }
            aNode.id=aTaxonomy.Id;
            aNode.text=aTaxonomy.name;
            if (aTaxonomy.Parent_Id__c==null || aTaxonomy.Parent_Id__r.Type__c==MODE_TYPE) {
                
                aNode.parent=ROOT_PARENT;
            }else{
                aNode.parent=aTaxonomy.Parent_Id__c;
            }
            
            nodes.put(aNode.id,aNode);
        }
        if (selected!=null){
            openParent(selected,nodes);
        }

        return nodes.values();
    }
    //recursively open the parents if selected
    static void openParent(Node selected, MAP<String,Node>nodes){
        
            if (selected.state==null){
                selected.state=new State();
            }
            selected.state.opened=true;
            if (selected.parent!=ROOT_PARENT){
                openParent(nodes.get(selected.parent),nodes);
            }
    }
    /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   This method returns the list of Issues
    Inputs:        caseid used to check if some issue was already persisted
                    mode based on which the Issues are fetched

    History
    9 Apr 2015      Vishnu Belkone     created
    ------------------------------------------------------------*/
    @RemoteAction
    global static List<Node> getIssues(string actionPlanId,String modeId) {
        modeId=String.escapeSingleQuotes(modeId);
        StateChecker issueCheck;
        if(null!=actionPlanId  && actionPlanId.length()>=15){
            actionPlanId=String.escapeSingleQuotes(actionPlanId);
             Action_Plan__c actionPlan=[select Id,Case_Description__c,mode__c,Issue_Level_1__c,Issue_Level_2__c,Issue_Level_3__c,Issue_Level_3_Id__c,Location_Level_1__c,Location_Level_2__c,Location_Level_3__c,Location_Level_3_Id__c from Action_Plan__c where id =:actionPlanId];
            issueCheck= new IssueChecker(actionPlan);

        }
        List<Taxonomy_Metadata__c> issues=[select Id,name,Parent_Id__c,Status_Staff_Facing__c,Parent_Id__r.Type__c,Agency__c from  Taxonomy_Metadata__c where Status_Staff_Facing__c=:STAFF_FACING and Type__c=:ISSUE_TYPE and (Parent_Id__r.Parent_Id__r.Parent_Id__c=:modeId or
                                                Parent_Id__r.Parent_Id__c=:modeId or Parent_Id__c=:modeId) Limit 10000];
        if (null==issues) return null;
        return getNodes(issues,issueCheck);
    }

    /*------------------------------------------------------------
    Author:        Vishnu Belkone
    Company:       Arxxus.com
    Description:   This method updates the case
    Inputs:        caseid, description,mode,location,issue

    History
    9 Apr 2015      Vishnu Belkone     created
    ------------------------------------------------------------*/
    @RemoteAction
    global static void updateEx(string actionPlanId,String description,String mode,String location,String locationId,String issue,String issueId,String parentIssue,String parentLocation,String grandIssue,String grandLocation, String type) {
        List<ApplicationLogMessage> lms = new List<ApplicationLogMessage>();
        try{
            actionPlanId=String.escapeSingleQuotes(actionPlanId);
            Action_Plan__c actionPlan = [select Id,Case_Description__c,mode__c,Issue_Level_1__c,Issue_Level_2__c,Issue_Level_3__c,Issue_Level_3_Id__c,Location_Level_1__c,Location_Level_2__c,Location_Level_3__c,Location_Level_3_Id__c,Type__c from Action_Plan__c where id =:actionPlanId];
            
            if(description==null && mode==null && location==null && issue==null && type==null ) return;
            if( description==actionPlan.Case_Description__c && mode==actionPlan.Mode__c && location==actionPlan.Location_Level_3__c && issue==actionPlan.Issue_Level_3__c  ) return;
            actionPlan.Case_Description__c=description;
            List<Id> taxomyIds= new List<Id>();
            if (!String.isEmpty(locationId)) taxomyIds.add((Id)locationId);
            if (!String.isEmpty(issueId)) taxomyIds.add((Id)issueId);
            List<Taxonomy_Metadata__c> taxonomies;
            Taxonomy_Metadata__c locationTaxonomy;
            Taxonomy_Metadata__c issueTaxonomy;
            String locationAccountability;
            String issueAccountability;
            String locationAgency;
            String issueAgency;
            String issueKpi;
            String issueDriver;
            system.debug('taxomyIds - '+taxomyIds);
            if (taxomyIds.size()>0){
                taxonomies=[SELECT Agency__c,Type__c,Id, Name, Parent_Id__c, KPI__c, Driver__c, Status_Staff_Facing__c,  Issue_Accountability__c, 
                            Parent_Id__r.Agency__c,Parent_Id__r.Type__c,Parent_Id__r.Id, Parent_Id__r.Name, Parent_Id__r.Parent_Id__c, Parent_Id__r.KPI__c, Parent_Id__r.Driver__c, Parent_Id__r.Status_Staff_Facing__c, Parent_Id__r.Issue_Accountability__c,
                            Parent_Id__r.Parent_Id__r.Agency__c,Parent_Id__r.Parent_Id__r.Type__c,Parent_Id__r.Parent_Id__r.Id, Parent_Id__r.Parent_Id__r.Name, Parent_Id__r.Parent_Id__r.Parent_Id__c, Parent_Id__r.Parent_Id__r.KPI__c, Parent_Id__r.Parent_Id__r.Driver__c, Parent_Id__r.Parent_Id__r.Status_Staff_Facing__c, Parent_Id__r.Parent_Id__r.Issue_Accountability__c,
                            Parent_Id__r.Parent_Id__r.Parent_Id__r.Agency__c,Parent_Id__r.Parent_Id__r.Parent_Id__r.Type__c,Parent_Id__r.Parent_Id__r.Parent_Id__r.Id, Parent_Id__r.Parent_Id__r.Parent_Id__r.Name, Parent_Id__r.Parent_Id__r.Parent_Id__r.Parent_Id__c, Parent_Id__r.Parent_Id__r.Parent_Id__r.KPI__c, Parent_Id__r.Parent_Id__r.Parent_Id__r.Driver__c, Parent_Id__r.Parent_Id__r.Parent_Id__r.Status_Staff_Facing__c, Parent_Id__r.Parent_Id__r.Parent_Id__r.Issue_Accountability__c
                            FROM Taxonomy_Metadata__c where Id=:taxomyIds];
                for (Taxonomy_Metadata__c taxonomy:taxonomies){
                    Taxonomy_Metadata__c parent=taxonomy.Parent_Id__r;
                    Taxonomy_Metadata__c grand=parent.Parent_Id__r;
                    Taxonomy_Metadata__c modeMetadata;
                    if(grand.Parent_Id__r!=null ){
                        modeMetadata=grand.Parent_Id__r;
                    }else{
                        modeMetadata=parent.Parent_Id__r;
                    }
                    system.debug('parent - '+parent);
                    system.debug('grand - '+grand);
                    system.debug('mode - '+modeMetadata);


                    if (taxonomy.Type__c==LOCATION_TYPE) {
                        locationTaxonomy=taxonomy;
                        grandLocation=grand.name;
                        parentLocation=parent.name;

                        locationAccountability=locationTaxonomy.Issue_Accountability__c;
                        locationAgency=locationTaxonomy.Agency__c;
                    }else if (taxonomy.Type__c==ISSUE_TYPE){
                        issueTaxonomy=taxonomy;
                        grandIssue=grand.name;
                        parentIssue=parent.name;
                        issueAccountability=issueTaxonomy.Issue_Accountability__c;
                        issueKpi=issueTaxonomy.KPI__c;
                        issueDriver=issueTaxonomy.Driver__c;
                        issueAgency=issueTaxonomy.Agency__c;

                    } 
                    actionPlan.Mode__c=modeMetadata.name;
                }

            }
            
            
            

            actionPlan.Location_Level_1__c=grandLocation;
            actionPlan.Location_Level_2__c=parentLocation;
            actionPlan.Issue_Level_1__c=grandIssue;
            actionPlan.Issue_Level_2__c=parentIssue;
            if (!String.isEmpty(issueId)) actionPlan.Issue_Level_3_Id__c=issueId;

            if (!String.isEmpty(locationId)) actionPlan.Location_Level_3_Id__c=locationId;
            //actionPlan.KPI__c=issueKpi;
            //actionPlan.Key_Driver__c=issueDriver;
            actionPlan.Location_Level_3__c=location;
            actionPlan.Issue_Level_3__c=issue;
           
    //      actionPlan.Taxonomy_Accountability__c=issueAccountability!=NULL ? issueAccountability : locationAccountability;
            //actionPlan.Agency__c=issueAgency!=NULL ? issueAgency : locationAgency;

            update actionPlan;
            ApplicationLogMessage lm = new ApplicationLogMessage();
                lm.source='ActionPlanCategorisationAction';
                lm.sourceFunction='updateEx';
                
                lm.logMessage='updated ation plan  category Id- '+actionPlanId+'  \r\n description- '+description+'  \r\n mode- '+mode+'  \r\n location- '+location+'  \r\n issue- '+issue;
               
                lm.debugLevel=GlobalConstants.DEBUG;
                
                lms.add(lm);
           
            }catch(Exception e){
                ApplicationLogMessage lm = new ApplicationLogMessage();
                lm.source='ActionPlanCategorisationAction';
                lm.sourceFunction='updateEx';
                
                lm.logMessage=e.getMessage();
                lm.ex=e;
                lm.debugLevel=GlobalConstants.ERROR;
                
                lms.add(lm);
                throw e;
            }finally{
                ApplicationLogUtility.logMessage(lms);
            }
    }
}