force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be the Business hours corresponding to the Agency/Division selected on the Action plan, if a corresponding , business hr is not found the default one will be set</description>
    <inlineHelpText>The business hrs followed by the Agency / Division</inlineHelpText>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/CasePriority__c.field-meta.xml
<CustomField>
    <fullName>CasePriority__c</fullName>
    <description>Priority copied down from case</description>
    <label>Case Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MP - Standard</fullName>
            </value>
            <value>
                <fullName>Individual - Standard</fullName>
            </value>
            <value>
                <fullName>Date Sensitive – MO specified due date</fullName>
            </value>
            <value>
                <fullName>Urgent – MO specified due date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActionPlanUtility.cls
public without sharing class ActionPlanUtility {
    public static set <String> skipStatuses = new set <String> {GlobalConstants.ACTION_PLAN_NEW_STATUS, 
                                                                 GlobalConstants.ACTION_PLAN_CLOSED_STATUS, 
                                                                 GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT};
    /*------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com 
    Description:  This method will return a map parent case and its no of 
                  child action plans which are not closed
    
    History
    01/06/2015     Manish Damle       Created
    ------------------------------------------------------------*/
    public static map <Id, Integer> createCaseVsNoOfActionPlansMap(list <Action_Plan__c> actionPlans, set <Id> parent_CaseIds) {
        set <Id> parentCaseIds = new set <Id>();
        
        if(parent_CaseIds != null) {
            parentCaseIds.addAll(parent_CaseIds);
        }
        
        map <Id, Integer> parentVsChildCount = new map <Id, Integer>();
        if(actionPlans != null) {
            for(Action_plan__c anAp : actionPlans) {
                if(anAp.Parent_Case__c != null 
                    && anAp.RecordTypeId != Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME)) {
                    parentCaseIds.add(anAp.Parent_Case__c);
                }
             }
        }
         
         for(AggregateResult agResult : [Select COUNT(ID) childAps, Parent_Case__c parent 
                                         From Action_Plan__c 
                                         Where Parent_Case__c IN : parentCaseIds 
                                           And Status__c NOT IN: skipStatuses
                                         Group By Parent_Case__c] ) {
            parentVsChildCount.put((Id) agResult.get('parent'), 
                                    Integer.valueOf(agResult.get('childAps')));
         }
         system.debug('-------parentVsChildCount1--------' + parentVsChildCount);
         return parentVsChildCount;
    }
    
    /*------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:  This method will return a map parent Action Plan and its no of 
                  child action plans which are not closed
    
    History
    01/06/2015     Manish Damle       Created
    ------------------------------------------------------------*/
    public static map <Id, Integer> createApVsNoOfChildActionPlansMap(list <Action_Plan__c> actionPlans, set <Id> parent_ActionPlanIds) {
        set <Id> parentActionPlanIds = new set <Id>();
        
        if(parent_ActionPlanIds != null) {
            parentActionPlanIds.addAll(parent_ActionPlanIds);
        }
        
        map <Id, Integer> parentVsChildCount = new map <Id, Integer>();
        if(actionPlans != null) {
            for(Action_plan__c anAp : actionPlans) {
                if(anAp.Parent_Action_Plan__c != null 
                    && anAp.RecordTypeId != Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME)) {
                    parentActionPlanIds.add(anAp.Parent_Action_Plan__c);
                }
             }
        }
         
         for(AggregateResult agResult : [Select COUNT(ID) childAps, Parent_Action_Plan__c parent 
                                         From Action_Plan__c 
                                         Where Parent_Action_Plan__c IN : parentActionPlanIds 
                                           And Status__c NOT IN: skipStatuses
                                         Group By Parent_Action_Plan__c] ) {
            parentVsChildCount.put((Id) agResult.get('parent'), 
                                    Integer.valueOf(agResult.get('childAps')));
         }
         system.debug('-------parentVsChildCount2--------' + parentVsChildCount);
         return parentVsChildCount;
    }

    /*------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com 
    Description:  This method will return a map parent case and its no of 
                  child action plans which are not closed
    
    History
    01/06/2015     Manish Damle       Created
    ------------------------------------------------------------*/
    public static map <Id, Integer> createCaseVsNoOfActionPlansMap(list <Action_Plan__c> actionPlans) {
        set <Id> parentCaseIds = new set <Id>();
        map <Id, Integer> parentVsChildCount = new map <Id, Integer>();
        if(actionPlans != null) {
            for(Action_plan__c anAp : actionPlans) {
                if(anAp.Parent_Case__c != null 
                    && anAp.RecordTypeId != Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME)) {
                    parentCaseIds.add(anAp.Parent_Case__c);
                }
             }
        }
         
        for(AggregateResult agResult : [Select COUNT(ID) childAps, Parent_Case__c parent 
                                        From Action_Plan__c 
                                        Where Parent_Case__c IN : parentCaseIds 
                                        And Status__c NOT IN: skipStatuses
                                        Group By Parent_Case__c] ) {
            parentVsChildCount.put((Id) agResult.get('parent'), Integer.valueOf(agResult.get('childAps')));
        }
        
        if(actionPlans != null) {
            for(Action_plan__c anAp : actionPlans) {
                if(anAp.Parent_Case__c != null 
                    && anAp.RecordTypeId != Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME)
                    && !parentVsChildCount.containsKey(anAp.Parent_Case__c)) {
                    parentVsChildCount.put(anAp.Parent_Case__c, 0);
                }
             }
        }
            
        system.debug('-------parentVsChildCount3--------' + parentVsChildCount);
        return parentVsChildCount;
    }
    
    /*------------------------------------------------------------
    Author:      Manish Damle
    Company:     Arxxus.com 
    Description: This method will calculate the due date on the action plan.
                 Agency = RMS 
                 Priority = Individual 
                 Due Date : 13 days : Action Plan created date(incl) + 13 
                 Priority = MP 
                 Due Date : 10 days : Action Plan created date + 10 
                
                All other agency/division : Action Plan created date + 8 days    
                
    History
    13/10/2015     Manish Damle       Created
    ------------------------------------------------------------*/
    public static void stampDueDateOnActionPlan(list <Action_Plan__c> actionPlans) {
        if(actionPlans == null)
            return;
        
        for(Action_Plan__c ap: actionPlans) {
            if(ap.Parent_Action_Plan__c != null)
                continue;
            Decimal bh; 
            System.debug('---@Due Date Calculation Agency---' + ap.Agency__c);
            System.debug('---@Due Date Calculation Priority---' + ap.CasePriority__c);
            if(ap.Agency__c == GlobalConstants.RMS_AGENCY) {
                if(ap.CasePriority__c == GlobalConstants.CASE_PRIORITY_INDIVIDUAL_STANDARD) {
                    bh = BusinessHoursUtil.getActionPlanDueDateBh(GlobalConstants.RMS_PRIORITY_INDIVIDUAL_STANDARD);
                } else if(ap.CasePriority__c == GlobalConstants.CASE_PRIORITY_MP_STANDARD) {
                    bh = BusinessHoursUtil.getActionPlanDueDateBh(GlobalConstants.RMS_PRIORITY_MP_STANDARD);
                } else {
                    //ap.Due_Date__c = null;
                    bh = null;
                }
            } else {
                bh = BusinessHoursUtil.getActionPlanDueDateBh(GlobalConstants.DEFAULTBH);
            }
            System.debug('---@Due Date Calculation Business Hours---' + bh);
            if(bh != null) {
                ap.Due_Date__c = ap.Due_Date__c == null ? BusinessHoursUtil.getActionPlanDueDate(ap.BusinessHours__c, 
                                                                                             (ap.Id != null ? ap.CreatedDate.date() : Date.today()),
                                                                                             bh) : ap.Due_Date__c;
            }
            System.debug('---@Due Date Calculation Date Stamped---' + ap.Due_Date__c);
        }
    }
}