force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Case_Description__c.field-meta.xml
<CustomField>
    <fullName>Case_Description__c</fullName>
    <label>Case Description</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3__c</fullName>
    <label>Issue Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Issue Level 3  metacategorisation Id</description>
    <inlineHelpText>Issue Level 3  metacategorisation Id</inlineHelpText>
    <label>Issue Level 3 Id</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3__c</fullName>
    <label>Location Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location Level 3  metacategorisation Id</description>
    <inlineHelpText>Issue Level 3  metacategorisation Id</inlineHelpText>
    <label>Location Level 3 Id</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Action Plans (Location Level 3 Id)</relationshipLabel>
    <relationshipName>Action_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <description>The originating function in the class (e.g. UpdateDivision() )</description>
    <inlineHelpText>The originating function in the class (e.g. UpdateDivision() )</inlineHelpText>
    <label>Source Function</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>NSW Trains</fullName>
            </value>
            <value>
                <fullName>RMS</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>STA</fullName>
            </value>
            <value>
                <fullName>Sydney Trains</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>PBO</fullName>
            </value>
            <value>
                <fullName>Newcastle Transport</fullName>
            </value>
            <value>
                <fullName>LRO</fullName>
            </value>
            <value>
                <fullName>MTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Taxonomy_Metadata__c.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Taxonomy_Metadata__c.Type__c</field>
            <operation>equals</operation>
            <value>Mode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Meta Categorisations</relationshipLabel>
    <relationshipName>Child_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Status_Staff_Facing__c.field-meta.xml
<CustomField>
    <fullName>Status_Staff_Facing__c</fullName>
    <inlineHelpText>Identifies whether this value is available (active) for selection in staff-facing channels</inlineHelpText>
    <label>Status - Staff Facing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActionPlanCategoriseActionTest.cls
/*------------------------------------------------------------------------
Author:        Author
Company:       Salesforce.com
Description:   UnitTests for custom publisher action for action plan categorisation
               Tests executed:
               1 - actionPlanContextIsCaptured()
               The context of the actionPlan in which the custom publisher action was opened is captured
               2 - testGetModes()
                The modes are fetched from the medes__c picklist options configured in the Taxonomy metadata
               3 - testNodeCreation()
                Just that the bean can be set and the attributes fetched
               4 - testLocationChecker()
                LocationChecker if initialised with a actionPlan record figures out whether a Location taxonomy is already persisted in the actionPlan field
               5 - testIssueChecker()
                IssueChecker if initialised with a actionPlan record figures out whether an Issue taxonomy is already persisted in the actionPlan field
               6 - testGetLocation()
               Gets the locations from taxonomy metadata for the input mode
               7 - testWontGetLocationIfNotStaffFacing()
                Wont get Locations unless the metadata records are marked as Active for Staff facing
               8 - testGetIssues()
                Gets the Issues from taxonomy metadata for the input mode
               9 - testUpdateEx()
                We are able to update the mode, issue, Location or description for a actionPlan.
               11 - testUpdateExDoesnotUpdateIfNoInput()
                If all inputs are null no update is made to the actionPlan
               12 - testUpdateExDoesnotUpdateIfStatusQuo()
                if the input values are same as in case then no update is made to case
History
3-Jun-2015  Author  UnitTests for custom publisher action for case categorisation
----------------------------------------------------------------------------*/
@isTest
public class ActionPlanCategoriseActionTest
{
    public static Action_Plan__c anAp;


    @isTest
    static void actionPlanContextIsCaptured()

    {   Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);
        insert thisAp;
        Test.startTest();
        PageReference actionPlanCategorisation= Page.ActionPlanCategorisationUISample;
        Test.setCurrentPage(actionPlanCategorisation);
        ApexPages.StandardController std=new ApexPages.StandardController(thisAp);
        ActionPlanCategorisationAction ext= new ActionPlanCategorisationAction(std);
        Test.stopTest();

        system.assertEquals(thisAp.Id,ext.actionPlan.id);


    }
    
    
    @isTest
    static void testGetModes()
    {
        Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);
        thisAp.mode__c='Train';
        insert thisAp;

        Test.startTest();
        List<ActionPlanCategorisationAction.Node> modes=ActionPlanCategorisationAction.getModes(thisAp.Id);

        Test.stopTest();
        ActionPlanCategorisationAction.Node selectedMode;
        system.assertEquals(1,modes.size());
        for (ActionPlanCategorisationAction.Node aNode:modes){
            if ('Train'==aNode.text) selectedMode=aNode;
        }
        system.assert(selectedMode.state.selected==true);


    }
    @isTest
    static void testNodeCreation()
    {
        ActionPlanCategorisationAction.Node aNode= new ActionPlanCategorisationAction.Node();
        aNode.id='test id';
        aNode.text='test';
        aNode.parent='test parent';
        aNode.state=new ActionPlanCategorisationAction.State();
        aNode.state.selected=true;
        system.assertEquals('test id',aNode.id);
        system.assertEquals('test',aNode.text);

        system.assertEquals(true,aNode.state.selected);



    }
    @isTest
    static void testLocationChecker()
    {   Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location, issue);//'Test Location' is sent in case
        thisAp.Location_Level_3_Id__c=location.Id;
        insert thisAp;
        ActionPlanCategorisationAction.StateChecker locationChecker= new ActionPlanCategorisationAction.LocationChecker(thisAp);
        ActionPlanCategorisationAction.State state= locationChecker.getState(location);
        system.assertEquals(true,state.selected);
    }

    @isTest
    static void testIssueChecker()
    {   Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);//'Test Symptom' is sent in case
        thisAp.Issue_Level_3_Id__c=issue.Id;

        insert thisAp;

        ActionPlanCategorisationAction.StateChecker issueChecker= new ActionPlanCategorisationAction.IssueChecker(thisAp);
        ActionPlanCategorisationAction.State state= issueChecker.getState(issue);
        system.assertEquals(true,state.selected);
    }
    @isTest
    static void testGetLocation()
    {
        Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);  

        thisAp.mode__c='Train';
        thisAp.Location_Level_3__c='location1';
        thisAp.Location_Level_3_Id__c=location.Id;
        insertLocationsTaxonomy(train);
        insert thisAp;

        Test.startTest();
        List<ActionPlanCategorisationAction.Node> locations=ActionPlanCategorisationAction.getLocations(thisAp.Id,train.id);

        Test.stopTest();
        ActionPlanCategorisationAction.Node selectedLocation;
        system.assertEquals(14,locations.size());
        for (ActionPlanCategorisationAction.Node aLocation:locations){
            if (location.Id==aLocation.id) selectedLocation=aLocation;
        }
        system.assert(selectedLocation.state.selected==true);


    }
    @isTest
    static void testWontGetLocationIfNotStaffFacing()
    {   Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);
        thisAp.mode__c='Train';
        thisAp.Location_Level_3__c='location1';
        insert thisAp;
        List<Taxonomy_metadata__c> locationTaxonomies=insertLocationsTaxonomy(train);
        locationTaxonomies[0].Status_Staff_Facing__c='InActive';
        update locationTaxonomies[0];
        Test.startTest();
        List<ActionPlanCategorisationAction.Node> locations=ActionPlanCategorisationAction.getLocations(thisAp.Id,train.Id);

        Test.stopTest();
        system.assertEquals(13,locations.size());
    }
    @isTest
    static void testGetIssues()
    {   Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);
        thisAp.mode__c='Train';
        thisAp.Issue_Level_3__c='issue1';
        thisAp.Issue_Level_3_Id__c=issue.Id;
        insertIssuesTaxonomy(train);
        insert thisAp;


        Test.startTest();
        List<ActionPlanCategorisationAction.Node> issues=ActionPlanCategorisationAction.getIssues(thisAp.Id,train.Id);

        Test.stopTest();
        ActionPlanCategorisationAction.Node selectedIssue;
        system.assertEquals(14,issues.size());
        for (ActionPlanCategorisationAction.Node anIssue:issues){
            if (issue.Id==anIssue.id) selectedIssue=anIssue;
        }
        system.assert(selectedIssue.state.selected==true);


    }

    @isTest
    static void testUpdateEx()
    {
        Taxonomy_Metadata__c train=insertModeTaxonomy();
        List<Taxonomy_Metadata__c> issueTaxonomies=insertIssuesTaxonomy(train);
        List<Taxonomy_Metadata__c> locationTaxonomies=insertLocationsTaxonomy(train);

        
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);
        thisAp.mode__c='Train';
        thisAp.Issue_Level_3__c=issueTaxonomies[0].name;
        thisAp.Issue_Level_3_Id__c=issueTaxonomies[0].Id;
        thisAp.Location_Level_3__c=locationTaxonomies[0].name;
        thisAp.Location_Level_3_Id__c=locationTaxonomies[0].Id;
        insert thisAp;
        Test.startTest();
        ActionPlanCategorisationAction.updateEx(thisAp.Id
                                                    ,'Testing now'
                                                    ,'Train'
                                                    ,locationTaxonomies[0].name
                                                    ,locationTaxonomies[0].id
                                                    ,issueTaxonomies[0].name
                                                    ,issueTaxonomies[0].id
                                                    ,'Test parent Issue'
                                                    , 'Test parent Location'
                                                    , 'Test grand Issue'
                                                    , 'Test grand Location'
                                                    ,  'Test type');
        Test.stopTest();
        thisAp=[select Id,Mode__c,Case_Description__c, Location_Level_3__c,Issue_Level_3__c from Action_Plan__c where Id=:thisAp.id];
        system.assertEquals('Testing now',thisAp.Case_Description__c);
        system.assertEquals('Train',thisAp.Mode__c);
        system.assertEquals(locationTaxonomies[0].name,thisAp.Location_Level_3__c);
        system.assertEquals(issueTaxonomies[0].name,thisAp.Issue_Level_3__c);
    }

    @isTest
    static void testUpdateExDoesnotUpdateIfNoInput()
    {   Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);
        thisAp.mode__c='Train';
        thisAp.Issue_Level_3__c='issue1';
        insert thisAp;
        Test.startTest();
        ActionPlanCategorisationAction.updateEx(thisAp.Id,null,null,null,null,null,null,null,null,null,null,null);
        Test.stopTest();
        thisAp=[select Id,Mode__c,Case_Description__c, Location_Level_3__c,Issue_Level_3__c from Action_Plan__c where Id=:thisAp.id];
        system.assertEquals('I was Injured because of the sharp metal jutting out',thisAp.Case_Description__c);
        system.assertEquals('Train',thisAp.Mode__c);

    }

    @isTest
    static void testUpdateExDoesnotUpdateIfStatusQuo()
    {
        Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode');
        insert train;
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));

        Taxonomy_metadata__c issue=new Taxonomy_metadata__c(
                Parent_Id__c=issueParent.Id,
                name='issue',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issue;
        Taxonomy_metadata__c location=new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,
                name='location',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert location;
        Action_Plan__c thisAp=setupActionPlan(location,issue);
        Id issueId= thisAp.Issue_Level_3_Id__c;
        Id locationId= thisAp.Location_Level_3_Id__c;
        thisAp.mode__c='Train';
        thisAp.Issue_Level_3__c='issue1';
        insert thisAp;
        Test.startTest();
        ActionPlanCategorisationAction.updateEx(thisAp.Id,'I was Injured because of the sharp metal jutting out ','Train',null,null,issueId,locationId,'Test parent Issue', 'Test parent Location', 'Test grand Issue', 'Test grand Location',  'Test type');
        Test.stopTest();
        thisAp=[select Id,Mode__c,Case_Description__c, Location_Level_3__c,Issue_Level_3__c from Action_Plan__c where Id=:thisAp.id];
        List<Application_Log__c> categoryLog=[select id,Debug_Level__c,Source_Function__c from Application_Log__c where Debug_Level__c=:GlobalConstants.DEBUG and Source_Function__c='updateEx' ];
        system.assertEquals(0,categoryLog.size());


    }
    
    

//utility methods for populating the test data
    public static Taxonomy_metadata__c insertModeTaxonomy(){
        Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode',Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING);
        insert train;
        
        return train;
    }

    public static List<Taxonomy_metadata__c> insertLocationsTaxonomy(Taxonomy_metadata__c train){
        List<Taxonomy_metadata__c> locations= new List<Taxonomy_metadata__c>();
    
        Taxonomy_metadata__c locationParent = insertParentLocationsTaxonomy(insertGrandLocationsTaxonomy(train));
        
        for (integer ii=1;ii<10;ii++){

            Taxonomy_metadata__c aLocation= new Taxonomy_metadata__c(
                Parent_Id__c=locationParent.Id,

                name='location'+ii,
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
            locations.add(aLocation);
        }
        insert locations;
        return locations;
    }
    public static Taxonomy_metadata__c insertParentLocationsTaxonomy(Taxonomy_metadata__c locationGrand){
        
        
        Taxonomy_metadata__c locationParent=new Taxonomy_metadata__c(
                Parent_Id__c=locationGrand.Id,

                name='locationparent',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert locationParent;
        
        return locationParent;
    }
    public static Taxonomy_metadata__c insertGrandLocationsTaxonomy(Taxonomy_metadata__c mode){
        
        Taxonomy_metadata__c locationGrand=new Taxonomy_metadata__c(
                Parent_Id__c=mode.Id,

                name='locationgrand',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.LOCATION_TYPE
            );
        insert locationGrand;
        
        return locationGrand;
    }
    public static List<Taxonomy_metadata__c> insertIssuesTaxonomy(Taxonomy_metadata__c train){

        Taxonomy_metadata__c issueParent= insertParentIssuesTaxonomy(insertGrandIssuesTaxonomy(train));
        
        List<Taxonomy_metadata__c> issues= new List<Taxonomy_metadata__c>();
        for (integer ii=1;ii<10;ii++){

            Taxonomy_metadata__c anIssue= new Taxonomy_metadata__c(
                parent_id__c=issueParent.Id,
                name='issue'+ii,
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
            issues.add(anIssue);
        }
        insert issues;
        return issues;
    }
    public static Taxonomy_metadata__c insertGrandIssuesTaxonomy(Taxonomy_metadata__c mode){
        
        Taxonomy_metadata__c issueGrand=new Taxonomy_metadata__c(
                Parent_Id__c=mode.Id,

                name='issuegrand',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issueGrand;
        return issueGrand;
    }
    public static Taxonomy_metadata__c insertParentIssuesTaxonomy(Taxonomy_metadata__c issueGrand){
        
        Taxonomy_metadata__c issueParent=new Taxonomy_metadata__c(
                Parent_Id__c=issueGrand.Id,

                name='issueparent',
                Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING ,
                Type__c=ActionPlanCategorisationAction.ISSUE_TYPE
            );
        insert issueParent;
        
        return issueParent;
    }
    public static Taxonomy_metadata__c insertModeTrain(){
        
        Taxonomy_metadata__c train= new Taxonomy_metadata__c(name='Train',type__c='Mode',Status_Staff_Facing__c=ActionPlanCategorisationAction.STAFF_FACING);
        insert train;
        return train;
    }
    public static Action_Plan__c setupActionPlan(Taxonomy_metadata__c location, Taxonomy_metadata__c issue){
    
        List<RecordType> actionPlanTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Action_Plan__c' AND DeveloperName != :GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME limit 1];
        RecordType ACTION_PLAN_REC_TYPE = actionPlanTypes.size()==0?null:actionPlanTypes[0];
        anAp=new Action_Plan__c(
                                Case_Description__c='I was Injured because of the sharp metal jutting out',
                                RecordTypeId=ACTION_PLAN_REC_TYPE.Id,
                                Status__c='New',
                                Agency__c='Policy',
                                Mode__c='Test Mode',
                                Location_Level_3__c='Test Location',
                                Issue_Level_3__c='Test Symptom',
                                Location_Level_3_Id__c=issue!=null?issue.Id:null,
                                Issue_Level_3_Id__c=location!=null?location.Id:null
                                );

        return anAp;

    }
}