force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseObjectConfigurations__c/CaseObjectConfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will hold the default case owner Id</description>
    <label>Case Object Configurations</label>
</CustomObject>

force-app/main/default/objects/ReopenDuration__c/ReopenDuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>case reopen duration per agency in days since case closure</description>
    <label>Reopen Duration Per Agency</label>
</CustomObject>

force-app/main/default/objects/ReopenDuration__c/fields/duration__c.field-meta.xml
<CustomField>
    <fullName>duration__c</fullName>
    <description>Reopening within this Duration Since Closure is allowed</description>
    <label>Duration</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SMEActivitySubject__c/SMEActivitySubject__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The list of subject lines which log an activity</description>
    <label>SME Activity Subject</label>
</CustomObject>

force-app/main/default/objects/SNSW_referral_email_address__c/SNSW_referral_email_address__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>this list stores email address associated issue level 2 (issue category) for sending SNSW referral emails</description>
    <label>SNSW referral email address</label>
</CustomObject>

force-app/main/default/objects/SNSW_referral_email_address__c/fields/To_address__c.field-meta.xml
<CustomField>
    <fullName>To_address__c</fullName>
    <description>email address to whom referral email should be sent.</description>
    <inlineHelpText>email address to whom referral email should be sent.</inlineHelpText>
    <label>To address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/Taxonomy_Metadata__c.object-meta.xml
<CustomObject>
    <description>Hierarchical metadata / reference information used for classification; e.g.:
&gt; Case categorisation
&gt; Locations
&gt; Reporting hieararchical structures</description>
    <label>Meta Categorisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Categorisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>NSW Trains</fullName>
            </value>
            <value>
                <fullName>RMS</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>STA</fullName>
            </value>
            <value>
                <fullName>Sydney Trains</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>PBO</fullName>
            </value>
            <value>
                <fullName>Newcastle Transport</fullName>
            </value>
            <value>
                <fullName>LRO</fullName>
            </value>
            <value>
                <fullName>MTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Customer_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Value__c</fullName>
    <description>Allows the customer facing value to be different from the internal / staff-facing taxonomy value</description>
    <inlineHelpText>Defines the value that customers can select if this taxonomy item is visible in customer-facing channels (i.e. on the web).</inlineHelpText>
    <label>Customer Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Taxonomy_Metadata__c.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Taxonomy_Metadata__c.Type__c</field>
            <operation>equals</operation>
            <value>Mode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Meta Categorisations</relationshipLabel>
    <relationshipName>Child_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailMessageTriggerDispatcher_Test.cls
@isTest
private class EmailMessageTriggerDispatcher_Test
{
    static Contact customer;
    static Contact sme;
    static String caseRefRegex='(?<=(ref:))(.*?)(?=(:ref))';
    static final string ADVICE_REQUEST_SUBJECT = 'Advice Request-';
    static final string SME_ACTIONPLAN_WAITING_STATUS = 'New';
    private static void createContacts(){
        customer= new Contact(FirstName='dip',
                                        LastName='bar',
                                        Email='dipbar@test.com');
        insert customer;
        sme= new Contact(FirstName='sme',
                                        LastName='stud',
                                        Email='sme@test.com');
        insert sme;
    }
    
    private static void createAdviceSubjectSettings(){
        SMEActivitySubject__c adviceSubject= new SMEActivitySubject__c(Name = ADVICE_REQUEST_SUBJECT);
        insert adviceSubject;
        
        CaseObjectConfigurations__c defaultOwner = new CaseObjectConfigurations__c();
        defaultOwner.Name = 'DefaultCaseOwner';
        defaultOwner.Value__c = UserInfo.getUserId();
        insert defaultOwner;
    }

    private static void createSNSWTaxonomyData() {
        Taxonomy_Metadata__c l0 = new Taxonomy_Metadata__c(Name = 'Road', Type__c = 'Mode', Customer_Value__c = 'Road');
        insert l0;

        Taxonomy_Metadata__c l1 = new Taxonomy_Metadata__c(Name = 'Roads', Type__c = 'Issue', Parent_Id__c = l0.Id, Customer_Value__c = 'Roads');
        insert l1;

        Taxonomy_Metadata__c l2 = new Taxonomy_Metadata__c(Name = 'Tolling', Type__c = 'Issue', Parent_Id__c = l1.Id, Customer_Value__c = 'Tolling');
        insert l2;

        Taxonomy_Metadata__c l3 = new Taxonomy_Metadata__c(Name = 'E-tags', Type__c = 'Issue', Parent_Id__c = l2.Id, Customer_Value__c = 'E-tags');
        insert l3;

        Taxonomy_Metadata__c lt1 = new Taxonomy_Metadata__c(Name = 'Roads', Type__c = 'Location', Parent_Id__c = l0.Id, Customer_Value__c = 'Roads');
        insert lt1;

        Taxonomy_Metadata__c lt2 = new Taxonomy_Metadata__c(Name = 'Region', Type__c = 'Location', Parent_Id__c = lt1.Id, Customer_Value__c = 'Region');
        insert lt2;

        Taxonomy_Metadata__c lt3 = new Taxonomy_Metadata__c(Name = 'Sydney', Type__c = 'Location', Parent_Id__c = lt2.Id, Customer_Value__c = 'Sydney');
        insert lt3;
    }
    
    private static void createCustomSettingEntryForSnsw() {
        SNSW_referral_email_address__c snswSetting = new SNSW_referral_email_address__c();
        snswSetting.To_address__c = 'tnsw@service.nsw.gov.au';
        snswSetting.Name = 'Tolling';
        
        insert snswSetting;
    }

    
     @isTest
    static void inboundSnswResponseClosedCloned()
    {
        system.runAs(new User(id = UserInfo.getUserId())) {
            createContacts();
            createSNSWTaxonomyData();
            createCustomSettingEntryForSnsw();
        }
        List<Group> queues = [Select Id,DeveloperName From Group WHERE Type = 'Queue' and DeveloperName = 'SNSW_Holding'];
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Road' limit 1];
        RecordType CASE_REC_TYPE = caseTypes.size()==0?null:caseTypes[0];
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New',
                                Agency__c='SNSW',
                                RecordTypeId=CASE_REC_TYPE.Id,
                                Modes__c = 'Road',
                                Taxonomy_Moment__c = 'Roads',
                                Taxonomy_Transaction__c = 'Tolling',
                                Taxonomy_Symptom__c = 'E-tags',
                                Taxonomy_Location_Type__c = 'Roads',
                                Taxonomy_Area__c = 'Region',
                                Taxonomy_Location__c = 'Sydney',
                                OwnerId = queues[0].Id);
        insert thisCase;
        thisCase.Status='Finalised';
        update thisCase;
        List <Case> latestCases = [SELECT Id, Status,Agency__c FROM Case WHERE Id = :thisCase.Id];
        system.debug('----Updated Case Information------' + latestCases);
        EmailMessage snswResponse = new EmailMessage(FromAddress='tnsw@service.nsw.gov.au',
                                                        FromName='SNSW Team',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming = true,
                                                        ParentId=thisCase.Id,
                                                        Subject = Label.SNSW_referral_subject + ' ref:' + getThreadId(thisCase.Id) + ':ref',
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='sme@test.com');
        Test.startTest();        
        insert snswResponse;
        Test.stoptest();
        List<Case> cases= [SELECT Id, Status FROM Case WHERE ParentId = :thisCase.Id];
        //System.assert(!cases.isEmpty());
    }
    
    
    @isTest
    static void outboundAdviceCreatesActionPlan() {   
        createAdviceSubjectSettings();
        createContacts();
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New');
        insert thisCase;
     
        EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                      FromName='manager',
                                                      HtmlBody='this pothole has been repaired',
                                                      Incoming=false,
                                                      ParentId= thisCase.Id,
                                                      Subject= ADVICE_REQUEST_SUBJECT,
                                                      TextBody='this pothole has been repaired',
                                                      ToAddress='sme@test.com');
        Test.startTest();
            insert adviceOutbound;
        Test.stoptest();
        Action_Plan__c waitingAP = [Select Id, Status__c From Action_Plan__c Where Parent_Case__c =: thisCase.Id];
        system.assertEquals(waitingAP.Status__c, SME_ACTIONPLAN_WAITING_STATUS);
    }
    
    @isTest
    static void secondOutboundAdviceCreatesNoActionPlan() {    
        createAdviceSubjectSettings();
        createContacts();
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId = customer.Id,
                                Status='New');
        insert thisCase;
        EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                        FromName='manager',
                                                        HtmlBody='check out the pothole problem',
                                                        Incoming=false,
                                                        ParentId=thisCase.Id,
                                                        Subject=ADVICE_REQUEST_SUBJECT,
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='sme@test.com');
        insert adviceOutbound;
        
        EmailMessage adviceOutbound2= new EmailMessage(FromAddress='tnsw@test.com',
                                                        FromName='manager',
                                                        HtmlBody='reminder to check the pothole again',
                                                        Incoming=false,
                                                        ParentId=thisCase.Id,
                                                        Subject=ADVICE_REQUEST_SUBJECT,
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='sme@test.com');
        Test.startTest();
            insert adviceOutbound2;
        Test.stoptest();

        list <Action_Plan__c> waitingAP = [Select Id, Status__c From Action_Plan__c];
        system.assertEquals(1, waitingAP.size());
    }

    @isTest
    static void secondOutboundAdviceOnAnotherCaseCreatesActionPlan()
    {   
        system.runAs(new User(Id = UserInfo.getUserId())){
            createAdviceSubjectSettings();
            createContacts();
        }
        
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New',
                                Taxonomy_Moment__c = 'A',
                                Taxonomy_Transaction__c = 'B',
                                Taxonomy_Symptom__c = 'C',
                                Taxonomy_Location_Type__c = 'D',
                                Taxonomy_Area__c = 'E',
                                Taxonomy_Location__c = 'F');

        Case anotherCase= new Case(Subject='graffiti',
                                   Description='theres a graffiti in busstop near bondi beach',
                                   ContactId=customer.Id,
                                   Status='New',
                                   Taxonomy_Moment__c = 'A',
                                   Taxonomy_Transaction__c = 'B',
                                   Taxonomy_Symptom__c = 'C',
                                   Taxonomy_Location_Type__c = 'D',
                                   Taxonomy_Area__c = 'E',
                                   Taxonomy_Location__c = 'F');
        system.runAs(new User(Id = UserInfo.getUserId())){
            insert thisCase;    
        }
        
        system.runAs(new User(Id = UserInfo.getUserId())){
            insert anotherCase;
        }
        Test.startTest();

        system.runAs(new User(Id = UserInfo.getUserId())){
            EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                            FromName='manager',
                                                            HtmlBody='check out the pothole problem',
                                                            Incoming=false,
                                                            ParentId=thisCase.Id,
                                                            Subject=ADVICE_REQUEST_SUBJECT,
                                                            TextBody='this pothole has been repaired',
                                                            ToAddress='sme@test.com');
            insert adviceOutbound;
        }
        Test.stoptest(); 
        system.runAs(new User(Id = UserInfo.getUserId())){
            EmailMessage adviceOutbound2= new EmailMessage(FromAddress='tnsw@test.com',
                                                            FromName='manager',
                                                            HtmlBody='reminder to check the pothole again',
                                                            Incoming=false,
                                                            ParentId=anotherCase.Id,
                                                            Subject=ADVICE_REQUEST_SUBJECT,
                                                            TextBody='this pothole has been repaired',
                                                            ToAddress='sme@test.com');
            
                insert adviceOutbound2;
                   
            list<Action_Plan__c> waitingAP = [Select Id, Status__c From Action_Plan__c Where Parent_Case__c IN (:thisCase.Id, :anotherCase.Id)];
            system.assertEquals(2,waitingAP.size());

        }
        
    }
    
    @isTest
    static void inboundAdviceUpdatesActionPlan()
    {
        createContacts();
        
        createAdviceSubjectSettings();
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New',
                                Taxonomy_Moment__c = 'A',
                                Taxonomy_Transaction__c = 'B',
                                Taxonomy_Symptom__c = 'C',
                                Taxonomy_Location_Type__c = 'D',
                                Taxonomy_Area__c = 'E',
                                Taxonomy_Location__c = 'F');
        insert thisCase;
        EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                        FromName='manager',
                                                        HtmlBody='this pothole to be repaired',
                                                        Incoming=false,
                                                        ParentId=thisCase.Id,
                                                        Subject=ADVICE_REQUEST_SUBJECT,
                                                        TextBody='this pothole to be repaired',
                                                        ToAddress='sme@test.com');
        insert adviceOutbound;
        Test.startTest();
        EmailMessage adviceinbound= new EmailMessage(FromAddress='sme@test.com',
                                                        FromName='sme',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=true,
                                                        ParentId=thisCase.Id,
                                                        Subject= ADVICE_REQUEST_SUBJECT+' ref:'+getThreadId(thisCase.Id)+':ref',
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='tnsw@test.com');

        insert adviceinbound;
        Test.stoptest();
        Action_Plan__c waitingAP = [Select Id, Status__c From Action_Plan__c Where Parent_Case__c =: thisCase.Id];
        system.assertEquals('Completed',waitingAP.Status__c);

    }
    @isTest
    static void inboundRequestDoesnotUpdateActionPlanIfSubjectNotInSettings()
    {   createAdviceSubjectSettings();
        
        createContacts();
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New',
                                Taxonomy_Moment__c = 'A',
                                Taxonomy_Transaction__c = 'B',
                                Taxonomy_Symptom__c = 'C',
                                Taxonomy_Location_Type__c = 'D',
                                Taxonomy_Area__c = 'E',
                                Taxonomy_Location__c = 'F');
        insert thisCase;
        EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                        FromName='manager',
                                                        HtmlBody='this pothole to be repaired',
                                                        Incoming=false,
                                                        ParentId=thisCase.Id,
                                                        Subject=ADVICE_REQUEST_SUBJECT,
                                                        TextBody='this pothole to be repaired',
                                                        ToAddress='sme@test.com');
        insert adviceOutbound;
        Test.startTest();
        EmailMessage adviceinbound= new EmailMessage(FromAddress='sme@test.com',
                                                        FromName='sme',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=true,
                                                        ParentId=thisCase.Id,
                                                        Subject=' ref:'+getThreadId(thisCase.Id)+':ref',
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='tnsw@test.com');

        insert adviceinbound;
        Test.stoptest();
        Action_Plan__c waitingAP = [Select Id, Status__c From Action_Plan__c Where Parent_Case__c =: thisCase.Id];
        system.assertEquals(SME_ACTIONPLAN_WAITING_STATUS, waitingAP.Status__c);

    }
    @isTest
    static void outboundCustomerMailDoesNotCreateActionPlan()
    {
        createContacts();
        
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New',
                                Taxonomy_Moment__c = 'A',
                                Taxonomy_Transaction__c = 'B',
                                Taxonomy_Symptom__c = 'C',
                                Taxonomy_Location_Type__c = 'D',
                                Taxonomy_Area__c = 'E',
                                Taxonomy_Location__c = 'F');
        insert thisCase;
        EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                        FromName='manager',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=false,
                                                        ParentId=thisCase.Id,
                                                        Subject='reply to your call-',
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='dipbar@test.com');
        Test.startTest();
        insert adviceOutbound;
        Test.stoptest();
        list <Action_Plan__c> waitingAP = [Select Id, Status__c From Action_Plan__c Where Parent_Case__c =: thisCase.Id];
        system.assertEquals(waitingAP.size(),0);
    }

    @isTest
    static void inboundCustomerMailDoesNotUpdateActionPlanDoesNotClone()
    {   createAdviceSubjectSettings();

        createContacts();
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New',
                                Taxonomy_Moment__c = 'A',
                                Taxonomy_Transaction__c = 'B',
                                Taxonomy_Symptom__c = 'C',
                                Taxonomy_Location_Type__c = 'D',
                                Taxonomy_Area__c = 'E',
                                Taxonomy_Location__c = 'F');
        insert thisCase;
        EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                        FromName='manager',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=false,
                                                        ParentId=thisCase.Id,
                                                        Subject=ADVICE_REQUEST_SUBJECT,
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='sme@test.com');
        insert adviceOutbound;
        Test.startTest();
        EmailMessage customerinbound= new EmailMessage(FromAddress='dipbar@test.com',
                                                        FromName='Customer',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=true,
                                                        ParentId=thisCase.Id,
                                                        Subject='folloup- ref:'+getThreadId(thisCase.Id)+':ref',
                                                        TextBody='this pothole has not been repaired',
                                                        ToAddress='tnsw@test.com');

        insert customerinbound;
        Test.stoptest();
        Action_Plan__c waitingAP = [Select Id, Status__c From Action_Plan__c Where Parent_Case__c =: thisCase.Id];
        system.assertNotEquals(waitingAp.Status__c, 'Closed');
        List<Case> cases=[select Id From Case];
        system.assertEquals(cases.size(),1);
    }

    @isTest
    static void inboundCustomerMailCaseRecentlyClosedReopens()
    {
        createContacts();
        
        ReopenDuration__c reopenCfg= new ReopenDuration__c (name='Agency1',Duration__c=1);
        insert reopenCfg;
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New',
                                Agency__c='Agency1',
                                Taxonomy_Moment__c = 'A',
                                Taxonomy_Transaction__c = 'B',
                                Taxonomy_Symptom__c = 'C',
                                Taxonomy_Location_Type__c = 'D',
                                Taxonomy_Area__c = 'E',
                                Taxonomy_Location__c = 'F');
        insert thisCase;
        thisCase.Status='Finalised';
        update thisCase;
        EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                        FromName='manager',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=false,
                                                        ParentId=thisCase.Id,
                                                        Subject=ADVICE_REQUEST_SUBJECT,
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='sme@test.com');
        insert adviceOutbound;
        Test.startTest();
        EmailMessage customerinbound= new EmailMessage(FromAddress='dipbar@test.com',
                                                        FromName='Customer',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=true,
                                                        ParentId=thisCase.Id,
                                                        Subject='followup- ref:'+getThreadId(thisCase.Id)+':ref',
                                                        TextBody='this pothole has not been repaired',
                                                        ToAddress='tnsw@test.com');

        insert customerinbound;
        Test.stoptest();
    }

    @isTest
    static void inboundCustomerMailCaseLongTimeClosedCloned()
    {
        createContacts();
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName != :GlobalConstants.MIN_CORRO_RECTYPE_NAME limit 1];
        RecordType CASE_REC_TYPE = caseTypes.size()==0?null:caseTypes[0];
        Case thisCase= new Case(Subject='pothole',
                                Description='theres a pothole in the east street, west end crossing in front of busstop',
                                ContactId=customer.Id,
                                Status='New',
                                Agency__c='Agency1',
                                RecordTypeId=CASE_REC_TYPE.Id,
                                Taxonomy_Moment__c = 'A',
                                Taxonomy_Transaction__c = 'B',
                                Taxonomy_Symptom__c = 'C',
                                Taxonomy_Location_Type__c = 'D',
                                Taxonomy_Area__c = 'E',
                                Taxonomy_Location__c = 'F'
                                );
        insert thisCase;
        thisCase.Status='Finalised';
        update thisCase;
        EmailMessage adviceOutbound= new EmailMessage(FromAddress='tnsw@test.com',
                                                        FromName='manager',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=false,
                                                        ParentId=thisCase.Id,
                                                        Subject=ADVICE_REQUEST_SUBJECT,
                                                        TextBody='this pothole has been repaired',
                                                        ToAddress='sme@test.com');
        insert adviceOutbound;
        Test.startTest();
        EmailMessage customerinbound= new EmailMessage(FromAddress='dipbar@test.com',
                                                        FromName='Customer',
                                                        HtmlBody='this pothole has been repaired',
                                                        Incoming=true,
                                                        ParentId=thisCase.Id,
                                                        Subject='folloup- ref:'+getThreadId(thisCase.Id)+':ref',
                                                        TextBody='this pothole has not been repaired',
                                                        ToAddress='tnsw@test.com');

        insert customerinbound;
        Test.stoptest();

        List<Case> cases= [Select Id, Status From Case];
        //system.assertEquals(2, cases.size());
    }
    
   
    
    private static String getThreadId(String caseid) {
      
        String orgId= (String) UserInfo.getOrganizationId();
        String caseThreadId = '_'+
        ((string)orgId).substring(0,((string)orgId).substring(3,4)=='0'?3:4)+
        ((string)orgId).substring(4+((string)orgId).substring(4).indexOfAnyBut('0')-1,15) +'._'+
        caseid.substring(0,4) + '0' + caseid.substring(10,15);
        return caseThreadId;
    }
}