force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Print_Location_Region__c.field-meta.xml
<CustomField>
    <fullName>Print_Location_Region__c</fullName>
    <description>Office location regions where letters can be sent for signing</description>
    <inlineHelpText>Office location regions where letters can be sent for signing</inlineHelpText>
    <label>Print Location Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sydney Region</fullName>
            </value>
            <value>
                <fullName>Hunter Regional Offices</fullName>
            </value>
            <value>
                <fullName>Northern Regional Offices</fullName>
            </value>
            <value>
                <fullName>Western Regional Office</fullName>
            </value>
            <value>
                <fullName>Regional Office</fullName>
            </value>
            <value>
                <fullName>Southern Regional Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Printing_Location__c.field-meta.xml
<CustomField>
    <fullName>Printing_Location__c</fullName>
    <inlineHelpText>Printing location for RMS CE letters</inlineHelpText>
    <label>Printing Location</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Print_Location_Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>North Sydney (Miller Street)</fullName>
            </value>
            <value>
                <fullName>Parramatta (Argyle Street)</fullName>
            </value>
            <value>
                <fullName>Parramatta (Octagon)</fullName>
            </value>
            <value>
                <fullName>Parramatta (Wentworth Street)</fullName>
            </value>
            <value>
                <fullName>Newcastle (Darby &amp; Queen Streets)</fullName>
            </value>
            <value>
                <fullName>Woy Woy (George Street)</fullName>
            </value>
            <value>
                <fullName>Grafton (Fitzroy &amp; King Streets)</fullName>
            </value>
            <value>
                <fullName>Grafton (Victoria Street)</fullName>
            </value>
            <value>
                <fullName>Pacific Highway Office</fullName>
            </value>
            <value>
                <fullName>Glen Innes (Grey &amp; Ferguson Streets)</fullName>
            </value>
            <value>
                <fullName>Parkes (Currajong Street)</fullName>
            </value>
            <value>
                <fullName>Wagga Wagga (Simmons Street)</fullName>
            </value>
            <value>
                <fullName>Wollongong (Crown Street)</fullName>
            </value>
            <value>
                <fullName>Northern Regional Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/recordTypes/MCWS_Child_Action_Plan.recordType-meta.xml
<RecordType>
    <fullName>MCWS_Child_Action_Plan</fullName>
    <active>true</active>
    <description>User this record type to create action plan from the parent action plan</description>
    <label>Child Action Plan</label>
</RecordType>

force-app/main/default/objects/Action_Plan__c/recordTypes/RMS_Action_Plan.recordType-meta.xml
<RecordType>
    <fullName>RMS_Action_Plan</fullName>
    <active>true</active>
    <description>Use this record type to create action plan record of the type Agency Response</description>
    <label>Agency Response</label>
</RecordType>

force-app/main/default/classes/APStatusTransitionForPrinting_Test.cls
@isTest
private class APStatusTransitionForPrinting_Test {

    private static Action_Plan__c actionPlan;
    
    private static void setUpTestData() {
        actionPlan = new Action_Plan__c();
        actionPlan.Type__c = GlobalConstants.AP_TYPE_AGENCY_RESPONSE;
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS;
        actionPlan.Agency__c = GlobalConstants.RMS_AGENCY;
        actionPlan.RecordTypeId = retrieveAgencyResponseRT();
        actionPlan.Print_Location_Region__c = 'Sydney Region';
        actionPlan.Printing_Location__c = 'North Sydney (Miller Street)';
        insert actionPlan;
    }
    
    private static Id retrieveAgencyResponseRT() {
        List<RecordType> rts = [SELECT Id FROM RecordType WHERE SObjectType = 'Action_Plan__c' AND DeveloperName = 'RMS_Action_Plan'];
        return rts.isEmpty()? null : rts[0].Id;
    }
    
    private static Id retrieveChildActionPlanRT() {
        List<RecordType> rts = [SELECT Id FROM RecordType WHERE SObjectType = 'Action_Plan__c' AND DeveloperName = 'MCWS_Child_Action_Plan'];
        return rts.isEmpty()? null : rts[0].Id;
    }
    
    private static testMethod void testForEmptyPrintLocation() {
        setUpTestData();
        actionPlan.Printing_Location__c = null;
        update actionPlan;
        System.Test.startTest();
        try {           
            APStatusTransitionForPrinting printingInstance = new APStatusTransitionForPrinting(actionPlan.Id);
            printingInstance.performTransition();
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForInvalidData() {
        actionPlan = new Action_Plan__c();
        System.Test.startTest();
        try {           
            APStatusTransitionForPrinting printingInstance = new APStatusTransitionForPrinting(actionPlan.Id);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForActionPlanOfAdviceRequest() {
        setUpTestData();
        actionPlan.Type__c = GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST;
        update actionPlan;
        System.Test.startTest();
        try {           
            APStatusTransitionForPrinting printingInstance = new APStatusTransitionForPrinting(actionPlan.Id);
            printingInstance.performTransition();
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForActionPlanOfAgencyResponse() {
        setUpTestData();
        
        System.Test.startTest();
        try {           
            APStatusTransitionForPrinting printingInstance = new APStatusTransitionForPrinting(actionPlan.Id);
            printingInstance.performTransition();           
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        Action_Plan__c ap = [SELECT Id, Status__c  FROM Action_Plan__c WHERE Id = :actionPlan.Id];
        System.assert(GlobalConstants.ACTION_PLAN_STATUS_READY_FOR_PRINT == ap.Status__c);
    }
        
    private static testMethod void testForParentActionPlanInvalidData() {
        setUpTestData();
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_STATUS_AWAITING_SIG;
        update actionPlan;
        System.Test.startTest();
        try {           
            APStatusTransitionForPrinting printingInstance = new APStatusTransitionForPrinting(actionPlan.Id);
            printingInstance.performTransition();   
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForChildActionPlan() {
        setUpTestData();
        Id childActionPlanId = createChildActionPlan();
        System.Test.startTest();
        try {           
            APStatusTransitionForPrinting printingInstance = new APStatusTransitionForPrinting(childActionPlanId);
            printingInstance.performTransition();   
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        Action_Plan__c child = [SELECT Id, Status__c FROM Action_Plan__c WHERE Id = :childActionPlanId];
        System.assert(child.Status__c == GlobalConstants.ACTION_PLAN_STATUS_AWAITING_SIG);
    }
    
    private static Id createChildActionPlan() {
        Action_Plan__c child = new Action_Plan__c();
        child.Type__c = GlobalConstants.AP_TYPE_AGENCY_RESPONSE;
        child.Status__c = GlobalConstants.ACTION_PLAN_STATUS_AWAITING_SIG;
        child.Agency__c = GlobalConstants.RMS_AGENCY;
        child.recordTypeId = retrieveChildActionPlanRT();
        child.Parent_Action_Plan__c = actionPlan.Id;
        insert child;
        return child.Id;
    }
}