force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Date_First_Child_AP_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Date_First_Child_AP_Assigned__c</fullName>
    <label>Date First Child AP Assigned</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/StampDateFirstChildAssignedOnParent.cls
public without sharing class StampDateFirstChildAssignedOnParent {
    
    private Set<Id> parentActionPlanIds;
    
    public StampDateFirstChildAssignedOnParent(Set<Id> parentActionPlanIds) {
        if(parentActionPlanIds == null || parentActionPlanIds.isEmpty()) {
            throw new InvalidDataException('Failed to stamp date first child action plan assigned on parent. Action plan details missing');
        }
        this.parentActionPlanIds = parentActionPlanIds;
    }
    
    public void stampDate() {
        List<Action_Plan__c> parents = [SELECT Id, Date_First_Child_AP_Assigned__c 
                                        FROM Action_Plan__c 
                                        WHERE Id IN :parentActionPlanIds
                                            AND Date_First_Child_AP_Assigned__c = NULL];
        for(Action_Plan__c ap : parents) {
            ap.Date_First_Child_AP_Assigned__c = System.today();
        }
        if(!parents.isEmpty()) {
            update parents;
        }
    }
    
    public class InvalidDataException extends Exception {}
}