force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Divisions__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACCREDITATION</fullName>
            </value>
            <value>
                <fullName>Asset Standards Authority</fullName>
            </value>
            <value>
                <fullName>AUDIT &amp; RISK</fullName>
            </value>
            <value>
                <fullName>Boating Infrastructure</fullName>
            </value>
            <value>
                <fullName>BOATING OPERATIONS</fullName>
            </value>
            <value>
                <fullName>Brookvale Depot</fullName>
            </value>
            <value>
                <fullName>Bureau of Transport Statistics</fullName>
            </value>
            <value>
                <fullName>Burwood Depot</fullName>
            </value>
            <value>
                <fullName>Bus and Ferry Services Contracts</fullName>
            </value>
            <value>
                <fullName>Centre for Road and Maritime Safety</fullName>
            </value>
            <value>
                <fullName>CHIEF EXECUTIVE&#39;S OFFICE</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial and Property Management</fullName>
            </value>
            <value>
                <fullName>Commercial and Strategy</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL PROPERTY</fullName>
            </value>
            <value>
                <fullName>Commercial Services</fullName>
            </value>
            <value>
                <fullName>COMMUNICATION &amp; STAKEHOLD</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Communications and Engagement</fullName>
            </value>
            <value>
                <fullName>Community Transport Agreements</fullName>
            </value>
            <value>
                <fullName>COMM VESSEL SURVEY</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>COMPLIANCE OPERATIONS</fullName>
            </value>
            <value>
                <fullName>CONTRACT MANAGEMENT OFFICE</fullName>
            </value>
            <value>
                <fullName>Contracts, Agreements &amp; Revenue Protect</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate and Project Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
            <value>
                <fullName>Corporate Planning &amp; Performance Info</fullName>
            </value>
            <value>
                <fullName>Country Rail Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_1__c</fullName>
    <label>Issue Level 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_2__c</fullName>
    <label>Issue Level 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3__c</fullName>
    <label>Issue Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Issue Level 3  metacategorisation Id</description>
    <inlineHelpText>Issue Level 3  metacategorisation Id</inlineHelpText>
    <label>Issue Level 3 Id</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_1__c</fullName>
    <label>Location Level 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_2__c</fullName>
    <label>Location Level 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3__c</fullName>
    <label>Location Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location Level 3  metacategorisation Id</description>
    <inlineHelpText>Issue Level 3  metacategorisation Id</inlineHelpText>
    <label>Location Level 3 Id</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Action Plans (Location Level 3 Id)</relationshipLabel>
    <relationshipName>Action_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/SME_Email__c.field-meta.xml
<CustomField>
    <fullName>SME_Email__c</fullName>
    <label>SME Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActionPlanCreator.cls
/*------------------------------------------------------------
Author:         Lalit Mistry
Company:        Arxxus Technology Partners
Description:    Helper class for creating action plan for a case.
Inputs:         "emails" - advice request mails which needs to be processed to create action plan
Test Class:     ActionPlanCreator_Test
History:
------------------------------------------------------------*/
public with sharing class ActionPlanCreator {

    private Map<Id, Case> caseRecords;
    private List<EmailMessage> emails;
    private set <Id> queuesSupportingActionPlan;
    list <ApplicationLogMessage> messages = new list <ApplicationLogMessage>();
    map <Id, String> queues = new map <Id, String>();
    Id cfmActionPlanRecordTypeId = null;
    
    public ActionPlanCreator(List<EmailMessage> emails) {
        if(emails == null || emails.isEmpty()) {
            throw new InvalidParameterException('Failed to create action plan. Email details missing');
        }
        
        this.emails = emails;
        Set<Id> caseIds = new Set<Id>();
        queuesSupportingActionPlan = new set <Id>();
        
        for(EmailMessage message : this.emails) {
            if(!String.isBlank(message.ParentId)) {
                caseIds.add(message.ParentId);
            }
        }
        
        caseRecords = new Map<Id, Case> ([Select Id, Taxonomy_Moment__c, Taxonomy_Symptom__c, Taxonomy_Transaction__c,Description, Subject, Priority, CaseNumber,
                                                 Taxonomy_Area__c, Taxonomy_Location__c, Taxonomy_Location_Type__c, OwnerId, Modes__c,Agency__c,Branch__c,ContactId,
                                                 Taxonomy_Symptom_Id__c, Taxonomy_Location_Id__c
                                          From Case
                                          Where Id IN :caseIds]);
        //fetch all the Queues who support Action Plan Object.
        for(QueueSobject obj :  [Select QueueId, SObjectType 
                                 From QueueSobject 
                                 Where SObjectType = 'Action_Plan__c']) {
            queuesSupportingActionPlan.add(obj.QueueId);
        }
        
        for(Group g : [Select Id, Name From Group Where Type = 'Queue']) {
            queues.put(g.Id, g.Name);
        }
        //CFM Action Plan Record Type: added by Manish Damle on 20/05/2015
        cfmActionPlanRecordTypeId = [Select Id From RecordType Where DeveloperName =: GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME limit 1].Id;
    }
    
    /*------------------------------------------------------------
    Author:         Lalit Mistry
    Company:        Arxxus Technology Partners
    Description:    Function creates new action plan with New status on sending advice request email for a case.
    Inputs:         
    Returns:        List<Action_Plan__c> - list of action plans that are created for advice requests sent
    History:
    ------------------------------------------------------------*/
    public List<Action_Plan__c> createAdviceRequestPlans() {
        List<Action_Plan__c> adviceRequestPlans = new List<Action_Plan__c>();
        
        for(EmailMessage message :emails) {
            if(!String.isBlank(message.ParentId) && caseRecords.get(message.ParentId) != null) {
                adviceRequestPlans.add(createActionPlan(message, caseRecords.get(message.ParentId)));
            }
        }
        
        if(messages.size() > 0) {
            ApplicationLogUtility.logMessage(messages);
            messages.clear();
        }
        return adviceRequestPlans;
    }
    
    private Action_Plan__c createActionPlan(EmailMessage message, Case caseRecord) {
        Action_Plan__c actionPlan = new Action_Plan__c();
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_NEW_STATUS;
        actionPlan.Type__c = GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST;
        actionPlan.SME_Email__c = message.ToAddress;
        actionPlan.Parent_Case__c = caseRecord.Id;
        actionPlan.Mode__c = caseRecord.Modes__c;
        actionPlan.Location_Level_3__c = caseRecord.Taxonomy_Location__c;
        actionPlan.Location_Level_2__c = caseRecord.Taxonomy_Area__c;
        actionPlan.Location_Level_1__c = caseRecord.Taxonomy_Location_Type__c;
        actionPlan.Issue_Level_3__c = caseRecord.Taxonomy_Symptom__c;
        actionPlan.Issue_Level_2__c = caseRecord.Taxonomy_Transaction__c;
        actionPlan.Issue_Level_1__c = caseRecord.Taxonomy_Moment__c;   
        actionPlan.RecordTypeId = cfmActionPlanRecordTypeId;
        actionPlan.Branch__c=caseRecord.Branch__c;
        actionPlan.Agency__c = caseRecord.Agency__c;
        actionPlan.Customer__c =  caseRecord.ContactId;
        actionPlan.Issue_Level_3_Id__c = caseRecord.Taxonomy_Symptom_Id__c;
        actionPlan.Location_Level_3_Id__c = caseRecord.Taxonomy_Location_Id__c;
        if(((String) caseRecord.OwnerId).startsWith(GlobalConstants.USER_ID_PREFIX)) {
            actionPlan.OwnerId = caseRecord.OwnerId; //Case Owner is a user 
        } else if(((String) caseRecord.OwnerId).startsWith(GlobalConstants.GROUP_ID_PREFIX) && queuesSupportingActionPlan.contains(caseRecord.OwnerId)){
            actionPlan.OwnerId = caseRecord.OwnerId; //Case Owner is a queue
        } else {
            actionPlan.OwnerId = UserInfo.getUserId(); //Action Plan Owner is current user
            String missingQueueName = queues.containsKey(caseRecord.OwnerId) ? queues.get(caseRecord.OwnerId) : 'Id:' + caseRecord.OwnerId;
            ApplicationLogMessage logMessage= new ApplicationLogMessage();
            logMessage.source='ActionPlanCreator';
            logMessage.sourceFunction='CreateActionPlan';
            logMessage.payLoad = '\nCase Number: ' + caseRecord.CaseNumber +
                          '\nSubject: '     +  caseRecord.Subject +
                          '\nDescription: ' + caseRecord.Description +
                          '\nPriority: ' + caseRecord.Priority + '\n\n New Advise Request from Case created an Action Plan record with missing queue : ' + missingQueueName;
            
            logMessage.debugLevel = GlobalConstants.WARNING;
            messages.add(logMessage);
        }
        return actionPlan;
    }
    
    public class InvalidParameterException extends Exception {}
}