force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AP_NoteOrAttachment__c/AP_NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between Action Plan and Notes &amp; Attachments object. This object will store the reference of the Notes Or Attachments custom object</description>
    <label>AP Note Or Attachment</label>
    <nameField>
        <displayFormat>APNA-{00000000}</displayFormat>
        <label>Note Or Attachment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Notes Or Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AP_NoteOrAttachment__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>AP_Note_Attachment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/AP_NoteOrAttachment__c/fields/Note_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Note_Attachment__c</fullName>
    <label>Note &amp; Attachment</label>
    <referenceTo>NoteOrAttachment__c</referenceTo>
    <relationshipLabel>AP Notes &amp; Attachments</relationshipLabel>
    <relationshipName>AP_Note_Attachment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <inlineHelpText>This allows user to mark security disposition of the record. Default is &quot;Standard&quot;</inlineHelpText>
    <label>Privacy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Attachment.recordType-meta.xml
<RecordType>
    <fullName>Attachment</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW FILE ATTACHMENT</description>
    <label>Attachment</label>
</RecordType>

force-app/main/default/objects/NoteOrAttachment__c/recordTypes/Note.recordType-meta.xml
<RecordType>
    <fullName>Note</fullName>
    <active>true</active>
    <description>USE THIS RECORD TYPE TO CREATE NEW NOTE</description>
    <label>Note</label>
</RecordType>

force-app/main/default/classes/NewActionPlanAttachment_CX_Test.cls
/*-----------------------------------------------------------------------------------
Author:        Manish Damle
Company:       Arxxus.com
Description:   Test class for New Action plan page controller
History
<Date>         <Authors Name>     <Brief Description of Change>
27/04/2015     Manish Damle       Created
-----------------------------------------------------------------------------------*/
@isTest
public class NewActionPlanAttachment_CX_Test {
 	/*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   Test method for New note creation testing 
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    27/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/
    static testMethod void newNoteTest() {
        Case caseRecord  = getCaseRecord();
        insert caseRecord;
        
        Action_Plan__c ap = getActionPlanRecord(caseRecord.Id);
        insert ap;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(ap);
        PageReference pref = Page.NewActionPlanNote;
        pref.getParameters().put('display','Note');
        Test.setCurrentPageReference(pref);
        NewActionPlanAttachment_CX ctrl = new NewActionPlanAttachment_CX(stdController);
        Test.startTest();
        	ctrl.customAttachment.Name = null; //Name id required but not provided.Validation will fire
        	ctrl.customAttachment.Body__c = 'This is test note body';
        	system.assertEquals(null, ctrl.saveNote());
        	ctrl.customAttachment.Name = 'Test Note';
        	ctrl.saveNote();
        Test.stopTest();
        list <NoteOrAttachment__c> notes =  [Select Id From NoteOrAttachment__c]; //Will not be attached to the case
        system.assertEquals(1, notes.size());
        list <AP_NoteOrAttachment__c> apnotes =  [Select Id From AP_NoteOrAttachment__c Where Action_Plan__c =: ap.Id];
        system.assertEquals(1, apnotes.size());
    }
    
 	/*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   Test method for New attachment creation testing 
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    27/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/    
    static testMethod void newAttachmentTest() {
        Case caseRecord  = getCaseRecord();
        insert caseRecord;
        
        Action_Plan__c ap = getActionPlanRecord(caseRecord.Id);
        insert ap;
        
        Test.startTest();
            ApexPages.StandardController stdController = new ApexPages.StandardController(ap);
            PageReference pref = Page.NewActionPlanAttachment;
            pref.getParameters().put('display','Attachment');
            Test.setCurrentPageReference(pref);  
            NewActionPlanAttachment_CX ctrl = new NewActionPlanAttachment_CX(stdController);
        
        	ctrl.customAttachment.Body__c = 'This is test note body';
        	ctrl.sfattachment.Name = 'desert.txt';
        	ctrl.sfattachment.Body = Blob.valueOf('This for testing purpose');
        	ctrl.saveAttachment();
        Test.stopTest();
        
        list <NoteOrAttachment__c> notes =  [Select Name, Id From NoteOrAttachment__c];
        system.assertEquals(1, notes.size());
        system.assertEquals('desert.txt', notes[0].Name);
        list <AP_NoteOrAttachment__c> apnotes =  [Select Id From AP_NoteOrAttachment__c Where Action_Plan__c =: ap.Id];
        system.assertEquals(1, apnotes.size());
    }
    
 	/*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   Test method for adding the existing attachment from the case record.
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    27/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/    
    static testMethod void addExistingAttachmentTest() {
        Case caseRecord  = getCaseRecord();
        insert caseRecord;
        
        Action_Plan__c ap = getActionPlanRecord(caseRecord.Id);
        insert ap;
        
        NoteOrAttachment__c attachmentRecord = getNoteOrAttachmentRecord(caseRecord.Id);
        insert attachmentRecord;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(ap);
        PageReference pref = Page.NewActionPlanAttachment;
        pref.getParameters().put('display','Attachment');
        Test.setCurrentPageReference(pref);
        NewActionPlanAttachment_CX ctrl = new NewActionPlanAttachment_CX(stdController);
        
        Test.startTest();
		    ctrl.attachmentIdToBeCloned = attachmentRecord.Id;
        	ctrl.getAttachmentFromTheCase();        	
        	ctrl.getCaseAttachments();
        Test.stopTest();
        list <AP_NoteOrAttachment__c> apnotes =  [Select Id, Note_Attachment__c From AP_NoteOrAttachment__c Where Action_Plan__c =: ap.Id];
        system.assertEquals(1, apnotes.size());
        system.assertEquals(attachmentRecord.Id, apnotes[0].Note_Attachment__c);
        
    }
    
    /*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   Test method cover exception handling
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    27/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/    
    static testMethod void errorTest() {
        Case caseRecord  = getCaseRecord();
        insert caseRecord;
        
        Action_Plan__c ap = getActionPlanRecord(caseRecord.Id);
        insert ap;
        
        NoteOrAttachment__c attachmentRecord = getNoteOrAttachmentRecord(caseRecord.Id);
        insert attachmentRecord;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(ap);
        PageReference pref = Page.NewActionPlanAttachment;
        pref.getParameters().put('display','Attachment');
        Test.setCurrentPageReference(pref);
        NewActionPlanAttachment_CX ctrl = new NewActionPlanAttachment_CX(stdController);
        
        Test.startTest();
       		ctrl.customAttachment.Name = 'Test Note';
        	ctrl.customAttachment.Body__c = 'This is test note body';
		    system.assertEquals(null, ctrl.saveAttachment());
        Test.stopTest();
    }
    
    /*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   This method creates a case record sobject
    Inputs:        
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    27/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/
    public static Case getCaseRecord() {
        return new Case(Subject = 'Pothole',
                        Description = 'Theres a pothole in the east street, west end crossing in front of busstop',
                        Status = 'New',
                        Agency__c = 'Agency1',
                        Priority = 'Normal');
    }
    
    /*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   This method creates a action plan record sobject
    Inputs:        Parent Case Id
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    27/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/
    public static Action_Plan__c getActionPlanRecord(Id parentCaseId) {
        return new Action_Plan__c(
        	Parent_Case__c = parentCaseId,
            Mode__c = 'Bus');
    }
    
    /*-----------------------------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   This method creates a NoteOrAttachment record sobject of the type attachment
    Inputs:        Case Id
    History
    <Date>         <Authors Name>     <Brief Description of Change>
    27/04/2015     Manish Damle       Created
    -----------------------------------------------------------------------------------*/
    public static NoteOrAttachment__c getNoteOrAttachmentRecord(Id caseId) {
        return new NoteOrAttachment__c(
        	Name = 'Test Attchament',
            Privacy__c = 'Standard',
            RecordTypeId = [Select Id From RecordType Where SObjectType = 'NoteOrAttachment__c' And DeveloperName = 'Attachment'].Id,
            Case__c = CaseId
        );
    }
}