force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/AssignedSME__c.field-meta.xml
<CustomField>
    <fullName>AssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned SME</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.Branch__c</field>
            <operation>equals</operation>
            <valueField>User.Branch__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/TempAssignedSME__c.field-meta.xml
<CustomField>
    <fullName>TempAssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used in workflow which will send out an email to the Assigned SME</description>
    <label>Primary SME</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to persist log messages for future reference.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error:	Handled and unhandled exceptions that need support team visibility (e.g. A controller class failed to update a record) 

Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings) 

Info: 	Information messages useful to ensure a process is running smoothly (e.g. When a batch job runs how many records were processed?, What was the start time/end time etc) 

Warning:  	Messages that allow developers to notify support teams that application limits set during the design phase might be reached (e.g. A batch job has been set up to process 1000 records at a time. If the number of records pending to be processed exceeds the limit the support team can be notified that the limit may need to be increased due to increasing volumes)</description>
    <inlineHelpText>Debug: 	Messages that are useful to developers and support staff that are not usually logged in production but may assist with issue resolution in construct and validate phases (e.g. Log inbound and outbound messages including their payloads and timings)</inlineHelpText>
    <label>Debug Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseFilterSetting__c/CaseFilterSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Case Keyword Filter Setting</label>
</CustomObject>

force-app/main/default/objects/CaseFilterSetting__c/fields/origin__c.field-meta.xml
<CustomField>
    <fullName>origin__c</fullName>
    <description>Comma separated list of Case Origins</description>
    <inlineHelpText>Comma separated list of Case Origins</inlineHelpText>
    <label>Case Origins</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseFilterSetting__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <description>Comma separated list of Record Type API names for which keywords are to be scanned</description>
    <inlineHelpText>Comma separated list of Record Type API names for which keywords are to be scanned</inlineHelpText>
    <label>Case Record Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ActionPlanTriggerDispatcherTest.cls
@isTest
private class ActionPlanTriggerDispatcherTest
{
    @testSetup static void setup() {
        system.debug('-------Data Setup------');
        RetrieveNextUtils_WS_Test.createTestUser('CRGS Admin','CRGS_Admin');
        RetrieveNextUtils_WS_Test.createTestUser('MAGS Officer','MAGS_Officer');
		system.debug('-------Data Setup Finished------');
    }
    
    @isTest
	static void testOwnerChangedToAssignedSmeBeforeInsert() {
        Action_Plan__c ap;
        system.runAs(new User(Id = UserInfo.getUserId())) {
            RecordType rt = [Select Id From RecordType Where DeveloperName =: GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME limit 1];
            ap = new Action_Plan__c();
            ap.RecordTypeId = rt.Id;
            ap.AssignedSME__c = UserInfo.getUserId();
            ap.Status__c = 'New';
            insert ap;
        }
        
        Test.startTest();
        	Action_Plan__c ap1 = [Select Id,AssignedSME__c,TempAssignedSME__c From Action_Plan__c Where Id =: ap.Id];
        	system.assertEquals(UserInfo.getUserId(), ap1.TempAssignedSME__c);
        	system.assertEquals(null, ap1.AssignedSME__c);
        Test.stopTest();
	}
    
    
    @isTest
	static void createApVsNoOfChildActionPlansMapTest() {	
        Action_Plan__c ap, childAp;
        system.runAs(new User(Id = UserInfo.getUserId())) {
            RecordType rt = [Select Id From RecordType Where DeveloperName =: GlobalConstants.ACTION_PLAN_MCWS_AP_RECORD_TYPE_NAME limit 1];
            ap = new Action_Plan__c();
            ap.RecordTypeId = rt.Id;
            ap.AssignedSME__c = UserInfo.getUserId();
            ap.Status__c = 'New';
            insert ap;
        }
        
        Test.startTest();
            childAp = new Action_Plan__c();
            RecordType rt = [Select Id From RecordType Where DeveloperName =: GlobalConstants.CHILD_AP_RECORDTYPE_API_NAME limit 1];
            childAp.RecordTypeId = rt.Id;
            childAp.AssignedSME__c = UserInfo.getUserId();
            childAp.Status__c = 'New';
        	childAp.Parent_Action_Plan__c = ap.Id;
        Test.stopTest(); 
        map <Id, Integer> countMap = ActionPlanUtility.createApVsNoOfChildActionPlansMap(new list <Action_Plan__c> {childAp},null);
        system.assert(countMap != null);
	}
    
    @isTest
	static void updateErrorIfTriggerParameterNotProper()
	{
		ApplicationLog_Test.setLoggingSettings();
		ActionPlanBeforeUpdateTriggerHandler updater= new ActionPlanBeforeUpdateTriggerHandler();
		
		updater.mainEntry(null);
		List<Application_Log__c> caseTriggerLogs= [select Id ,Debug_Level__c from Application_Log__c ];
		system.assertEquals(GlobalConstants.ERROR,caseTriggerLogs[0].Debug_Level__c);

	}
    
   
    @isTest
    static void testCreateNewAdviceRequestActionPlanUpdatesCaseStatusAwaitingAdvice() {
    	List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
		RecordType BUS = caseTypes.size()==0?null:caseTypes[0];
        Case busCase=new Case(Subject='I was Injured because of the sharp metal jutting out ',
								Description='I was Injured because of the sharp metal jutting out ',
								RecordTypeId=BUS.Id,
								Status='New',
								Origin='Email',
								Priority='Normal');
        insert new CaseFilterSetting__c(Name='default',origin__c='Web',RecordType__c='Bus');

        insert busCase;
        Id cfmActionPlanRecordTypeId=Action_PlanTriggerDispatcher.actionPlanRecordTypes.get( GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME);

        Id fakeId= UtilityClass.getFakeId(Action_Plan__c.SObjectType);
		Action_Plan__c ap= new Action_Plan__c(Id=fakeId,Parent_Case__c=busCase.Id,assignedSme__c=UserInfo.getUserId(), ownerId=null,Status__c='New',RecordTypeId=cfmActionPlanRecordTypeId,Type__c = GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST);
		Action_Plan__c oldAp= new Action_Plan__c(Id=fakeId,Parent_Case__c=busCase.Id,assignedSme__c=UserInfo.getUserId(), ownerId=null,Status__c='New',RecordTypeId=cfmActionPlanRecordTypeId,Type__c = GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST);
		List<Action_Plan__c> oldList= new List<Action_Plan__c>();

		List<Action_Plan__c> newList= new List<Action_Plan__c>();
		newList.add(ap);
		oldList.add(oldAp);
		Map<Id, Action_Plan__c> newMap=new Map<Id, Action_Plan__c>(newList);
		Map<Id, Action_Plan__c> oldMap=new Map<Id, Action_Plan__c>(oldList);

		TriggerParameters tp=new TriggerParameters(oldList, newList, oldMap, newMap,
								false, true, false, true, false, false, false);
		ActionPlanAfterInsertTriggerHandler th= new ActionPlanAfterInsertTriggerHandler();
		Test.startTest();
		th.mainEntry(tp);
		Test.stopTest();
		Case busCaseAfter=[select Status from Case where Id=:busCase.Id];
		system.assertEquals(GlobalConstants.CASE_STATUS_AWAITING_ADVICE,busCaseAfter.Status);
    }
	
    @isTest
    static void testReceiveAdviceRequestResponseActionPlanCompletedCaseStatusReceivedAdvice() {
    	List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
		RecordType BUS = caseTypes.size() == 0 ? null : caseTypes[0];
        Case busCase=new Case(Subject = 'I was Injured because of the sharp metal jutting out ',
							  Description = 'I was Injured because of the sharp metal jutting out ',
						      RecordTypeId = BUS.Id,
						      Status = 'New',
						      Origin = 'Email',
						      Priority = 'Normal');
        insert new CaseFilterSetting__c(Name='default',origin__c='Web',RecordType__c='Bus');
        
        
        insert busCase;
        
        
        Id cfmActionPlanRecordTypeId = Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME);
        
        Action_Plan__c ap =  new Action_Plan__c(Parent_Case__c = busCase.Id, 
                                                Status__c = 'New',
                                                RecordTypeId = cfmActionPlanRecordTypeId,
                                                Type__c = GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST);
        system.runAs(new User(Id = UserInfo.getUserId())) {
            insert ap;
        }
        
        Test.startTest();
        ActionPlanAfterUpdateTriggerHandler.firstTimers=null;
        Action_Plan__c completedAp = [Select Id, Status__c From Action_Plan__c Where Id =: ap.Id];
        completedAp.Status__c = 'Completed';
        system.debug('going to update actionplan status completed');
        update completedAp;
        Test.stopTest();

        
        Case busCaseAfter = [Select Id, Status From Case Where Id =: busCase.Id];
        system.assertEquals(GlobalConstants.CASE_STATUS_ADVICE_RECEIVED,busCaseAfter.Status);
        
    }
    
     @isTest
    static void testActionPlanDelete() {
        List<RecordType> caseTypes=[SELECT ID FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName = 'Bus'];
		RecordType BUS = caseTypes.size() == 0 ? null : caseTypes[0];
        Case busCase=new Case(Subject = 'I was Injured because of the sharp metal jutting out ',
							  Description = 'I was Injured because of the sharp metal jutting out ',
						      RecordTypeId = BUS.Id,
						      Status = 'New',
						      Origin = 'Email',
						      Priority = 'Normal');
        
        insert new CaseFilterSetting__c(Name='default',origin__c='Web',RecordType__c='Bus');
        system.runAs(new User(Id = UserInfo.getUserId())) {
        	insert busCase;
        }
        
        Id cfmActionPlanRecordTypeId = Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME);
        
        Action_Plan__c ap =  new Action_Plan__c(Parent_Case__c = busCase.Id, 
                                                assignedSme__c = UserInfo.getUserId(), 
                                                Status__c = 'New',
                                                RecordTypeId = cfmActionPlanRecordTypeId,
                                                Type__c = GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST);
        system.runAs(new User(Id = UserInfo.getUserId())) {
            insert ap;
        }
        
        system.runAs(new User(Id = UserInfo.getUserId())) {
            Test.startTest();
        	    Action_Plan__c completedAp = [Select Id, Status__c From Action_Plan__c Where Id =: ap.Id];
            	delete completedAp;
            Test.stopTest();
            list <Action_Plan__c> Aps = [Select Id, Status__c From Action_Plan__c Where Id =: ap.Id];
            system.assertEquals(0, aps.size());
            
            //Error test
            ActionPlanAfterDeleteTriggerHandler handler = new ActionPlanAfterDeleteTriggerHandler();
            handler.mainEntry(null);
            
            ActionPlanAfterInsertTriggerHandler handler1 = new ActionPlanAfterInsertTriggerHandler();
            handler1.mainEntry(null);
        }
    }
}