force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/ActualDaysOverdue__c.field-meta.xml
<CustomField>
    <fullName>ActualDaysOverdue__c</fullName>
    <description>Actual Days Overdue, will record a positive or negative number with (two decimal points) that records how many days the item is overdue or underdue (e.g. 1.5 days would equate to 1.5 days overdue, -2.73 would equate to nearly two and three quarters days ahead of the due date.) This will be calculated using business hours.</description>
    <label>Actual Days Overdue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be the Business hours corresponding to the Agency/Division selected on the Action plan, if a corresponding , business hr is not found the default one will be set</description>
    <inlineHelpText>The business hrs followed by the Agency / Division</inlineHelpText>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Action_Plan_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Action_Plan_Assigned__c</fullName>
    <label>Date stamp on Action Plan Assigned</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Action_Plan_in_Progress__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Action_Plan_in_Progress__c</fullName>
    <label>Date stamp on Action Plan in Progress</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Action_Plan_in_Review__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Action_Plan_in_Review__c</fullName>
    <label>Date stamp on Action Plan in Review</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Awaiting_Approval__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Awaiting_Approval__c</fullName>
    <label>Date stamp on Awaiting Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Awaiting_Signature__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Awaiting_Signature__c</fullName>
    <label>Date stamp on Awaiting Signature</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Completed__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Completed__c</fullName>
    <description>This field contains the date and time that the Action Plan was completed.  It an action plan is ever completed more than once, this will contain the value that it was most recently completed.</description>
    <inlineHelpText>This field contains the date and time that the Action Plan was completed.  It an action plan is ever completed more than once, this will contain the value that it was most recently completed.</inlineHelpText>
    <label>Date stamp on Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_First_Completed__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_First_Completed__c</fullName>
    <description>This field contains the date and time that the Action Plan was completed. It an action plan is ever completed more than once, this value will always contain the datetime stamp of when the Action Plan was first completed. (Also see: Date stamp on Completed)</description>
    <inlineHelpText>This field contains the date and time that the Action Plan was completed. It an action plan is ever completed more than once, this value will always contain the datetime stamp of when the Action Plan was first completed. (Also see: Date stamp on Completed</inlineHelpText>
    <label>Date stamp on First Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Incorrect_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Incorrect_Assignment__c</fullName>
    <label>Date stamp on Incorrect Assignment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Ready_for_Printing__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Ready_for_Printing__c</fullName>
    <label>Date stamp on Ready for Printing</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status_Date_Last_Stamped__c.field-meta.xml
<CustomField>
    <fullName>Status_Date_Last_Stamped__c</fullName>
    <label>Status Date Last Stamped</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DateStamperOnStatusChange.cls
public with sharing class DateStamperOnStatusChange {

    private List<Action_Plan__c> newActionPlans;
    private Map<Id, Action_Plan__c> oldActionPlanMap;
    
    public DateStamperOnStatusChange(List<Action_Plan__c> newActionPlans, Map<Id, Action_Plan__c> oldActionPlanMap) {
        if(newActionPlans == null || newActionPlans.isEmpty() || oldActionPlanMap == null || oldActionPlanMap.isEmpty()) {
            throw new InvalidDataException('Failed to stamp date on status change. Action plan details missing');
        }
        this.newActionPlans = newActionPlans;
        this.oldActionPlanMap = oldActionPlanMap;
    }
    
    public void stampDate() {
        for(Action_Plan__c ap : newActionPlans) {
            if(isStatusChanged(ap)) {
                if(GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED.equalsIgnoreCase(ap.Status__c)) {
                    ap.Date_stamp_on_Action_Plan_Assigned__c = System.now();
                } else if(GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(ap.Status__c)) {
                    ap.Date_stamp_on_Action_Plan_in_Progress__c = System.now();
                } else if(GlobalConstants.ACTION_PLAN_NEW_APPROVED.equalsIgnoreCase(ap.Status__c)) {
                    ap.Date_stamp_on_Action_Plan_in_Review__c = System.now();
                } else if(GlobalConstants.ACTION_PLAN_WAITING_APPROVAL.equalsIgnoreCase(ap.Status__c)) {
                    ap.Date_stamp_on_Awaiting_Approval__c = System.now();
                } else if(GlobalConstants.ACTION_PLAN_STATUS_AWAITING_SIG.equalsIgnoreCase(ap.Status__c) && ap.Date_stamp_on_Awaiting_Signature__c == null) {
                    ap.Date_stamp_on_Awaiting_Signature__c = System.now();
                } else if(GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT.equalsIgnoreCase(ap.Status__c)) {
                    ap.Date_stamp_on_Incorrect_Assignment__c = System.now();
                } else if(GlobalConstants.ACTION_PLAN_STATUS_READY_FOR_PRINT.equalsIgnoreCase(ap.Status__c)) {
                    ap.Date_stamp_on_Ready_for_Printing__c = System.now();
                } else if (GlobalConstants.ACTION_PLAN_CLOSED_STATUS.equalsIgnoreCase(ap.Status__c)) {
                    ap.Date_stamp_on_Completed__c = System.now();
                    if (ap.Date_stamp_on_First_Completed__c == null) {                // only set First Completed if null
                        ap.Date_stamp_on_First_Completed__c = ap.Date_stamp_on_Completed__c;
                        ap.ActualDaysOverdue__c = BusinessHoursUtil.getActionPlanActualDaysOverdue(ap.BusinessHours__c, 
                                                                                               	   ap.Due_Date__c,
                                                                                               	   ap.Date_stamp_on_First_Completed__c);
                        system.debug('---@AtualDaysOverdue--Stamped---' + ap.ActualDaysOverdue__c);
                    }
                }
                ap.Status_Date_Last_Stamped__c = System.now();
            }
        }
    }
    
    private Boolean isStatusChanged(Action_Plan__c ap) {
        Boolean flag = false;
        if(ap.Status__c != oldActionPlanMap.get(ap.Id).Status__c) {
            flag = true;
        }       
        return flag;
    }
    
    public class InvalidDataException extends Exception {}

}