force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Child_Action_Plans__c.field-meta.xml
<CustomField>
    <fullName>Child_Action_Plans__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Child Action Plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Completed_Child_Action_Plans__c.field-meta.xml
<CustomField>
    <fullName>Completed_Child_Action_Plans__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Completed Child Action Plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChildActionPlanCounter.cls
public without sharing class ChildActionPlanCounter {

    private List<Action_Plan__c> childActionPlans;
    
    public ChildActionPlanCounter(List<Action_Plan__c> childActionPlans) {
        if(childActionPlans == null || childActionPlans.isEmpty()) {
            throw new InvalidDataException('Failed to count child action plan. Action Plan details missing');
        }
        this.childActionPlans = childActionPlans;
    }
    
    public void updateChildActionPlanCounter() {
        Map<Id, Action_Plan__c> parentIdVsActionPlan = retrieveParentActionPlan();
                
        List<AggregateResult> results = [   SELECT COUNT(Id) childCount, Parent_Action_Plan__c parent 
                                            FROM Action_Plan__c 
                                            WHERE Parent_Action_Plan__c IN :parentIdVsActionPlan.keySet()
                                            GROUP BY Parent_Action_Plan__c];
                                            
        for(AggregateResult result : results) {
            Action_Plan__c parent = parentIdVsActionPlan.get((Id) result.get('parent'));
            parent.Child_Action_Plans__c = Integer.valueOf(result.get('childCount'));
            parentIdVsActionPlan.put(parent.Id, parent);
        }
        
        List<AggregateResult> completedResults = [  SELECT COUNT(Id) childCount, Parent_Action_Plan__c parent 
                                                    FROM Action_Plan__c 
                                                    WHERE Parent_Action_Plan__c IN :parentIdVsActionPlan.keySet()
                                                        AND Status__c = :GlobalConstants.ACTION_PLAN_CLOSED_STATUS
                                                    GROUP BY Parent_Action_Plan__c];
                                            
        for(AggregateResult result : completedResults) {
            Action_Plan__c parent = parentIdVsActionPlan.get((Id) result.get('parent'));
            parent.Completed_Child_Action_Plans__c = Integer.valueOf(result.get('childCount'));
            parentIdVsActionPlan.put(parent.Id, parent);
        }
        
        if(!parentIdVsActionPlan.isEmpty()) {
            update parentIdVsActionPlan.values();
        }
    }   
    
    private Map<Id, Action_Plan__c> retrieveParentActionPlan() {        
        Map<Id, Action_Plan__c> parentIdVsActionPlan = new Map<Id, Action_Plan__c>();
        
        for(Action_Plan__c childActionPlan : childActionPlans) {
            if(!String.isBlank(childActionPlan.Parent_Action_Plan__c)) {
                parentIdVsActionPlan.put(childActionPlan.Parent_Action_Plan__c, new Action_Plan__c(Id = childActionPlan.Parent_Action_Plan__c, Child_Action_Plans__c = 0, Completed_Child_Action_Plans__c = 0));
            }
        }
        return parentIdVsActionPlan;
    }
    
    public class InvalidDataException extends Exception {}
}