force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/AgencyVsQueueMapping__c.field-meta.xml
<CustomField>
    <fullName>AgencyVsQueueMapping__c</fullName>
    <description>This field is used in javscript of Assign To Agency Button and also used in apex classes APStatusTransitionforAssign and APStatusTransitionForRework.

SFCOE-1802: Changes to TfNSW Agency, Division and Branch names due to restructure.</description>
    <formula>CASE(TEXT(Branch__c),
&quot;IP Fleet Program Delivery&quot;, &quot;TfNSW_I_S_Fleet_Program_Delivery_MC&quot;,
&quot;IP Infrastructure and Project Finance&quot;, &quot;TfNSW_I_P_Infrastructure_and_Project_F&quot;,
&quot;IP Operational Systems&quot;, &quot;Transport_Services_MC&quot;,
&quot;IP Placemaking and Real Estate&quot;, &quot;TfNSW_I_P_Placemaking_and_Real_Estate&quot;,
&quot;IP Parramatta Light Rail&quot;, &quot;TfNSW_I_S_Parramatta_Light_Rail_MC&quot;,
&quot;IP Precincts and Infrastructure&quot;, &quot;Transport_Projects_MC&quot;,
&quot;IP Program Management Office&quot;, &quot;TfNSW_IS_Pgm_Divisional_Mgmt_Offc_MC&quot;,
&quot;IP Newcastle Transport Program&quot;, &quot;TfNSW_I_P_Newcastle_Transport_Program&quot;,
&quot;IP Rail Program Delivery&quot;, &quot;TfNSW_IS_Rail_Service_Delivery_MC&quot;,
&quot;IP Sydney Light Rail&quot;, &quot;Light_Rail_MC&quot;,
&quot;TfNSW Services&quot;, &quot;TfNSW_CTS_Services&quot;,
&quot;TfNSW Services (Regional)&quot;, &quot;TfNSW_CTS_Services&quot;,
&quot;TfNSW Centres for Road and Maritime Safety&quot;, &quot;Centre_for_Road_Safety_MC&quot;,
&quot;TC Transport Management Centre&quot;, &quot;TfNSW_IS_Transport_Management_Centre_MC&quot;,
&quot;TC Sydney Coordination Office&quot;, &quot;TfNSW_CBD_Coordination_Office_MC&quot;,
&quot;IP Divisional Management Office&quot;, &quot;TfNSW_I_P_Divisional_Management_Office&quot;,
&quot;TfNSW Asset Standards Authority&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;FSP Freight Industry&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;FSP Innovations, Research and Reform&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;FSP Transport Planning&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;FSP Transport Policy&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;Sydney Metro&quot;, &quot;North_West_Rail_Link_MC&quot;,
&quot;Sydney Trains&quot;, &quot;Sydney_Trains_MC&quot;,
&quot;State Transit&quot;, &quot;STA_MC&quot;,
&quot;NSW TrainsLink&quot;, &quot;NSW_Trainlink_MC&quot;,

&quot;Point to Point Transport Commission&quot;, &quot;TfNSW_P2P_Transport_Commission&quot;, /* Not part of the new structure Jul19 */

/* RMS */
&quot;RMS Corporate Affairs&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Audit and Assurance&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Financial Planning and Analysis&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Sydney Division&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Maritime&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Regional and Freight&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Property and Acquisitions&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Motorways&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Technical and Project Services&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Compliance and Regulatory Services&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),

CASE(TEXT(Divisions__c),
&quot;Corporate Services&quot;, &quot;People_and_corporate_services_MC&quot;,
&quot;Customer Strategy and Technology&quot;, &quot;TfNSW_Customer_Services_MC&quot;,
&quot;Finance and Investment&quot;, &quot;Finance_MC&quot;, /* Division no longer exists */

&quot;QUEUE-NOT-FOUND&quot;
)
)</formula>
    <label>Agency Vs Queue Mapping</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/AssignedSME__c.field-meta.xml
<CustomField>
    <fullName>AssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned SME</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.Branch__c</field>
            <operation>equals</operation>
            <valueField>User.Branch__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Divisions__c.field-meta.xml
<CustomField>
    <fullName>Divisions__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Agency__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Office of the Secretary</fullName>
            </value>
            <value>
                <fullName>Customer Strategy and Technology</fullName>
            </value>
            <value>
                <fullName>Greater Sydney</fullName>
            </value>
            <value>
                <fullName>Regional and Outer Metropolitan</fullName>
            </value>
            <value>
                <fullName>Infrastructure and Place</fullName>
            </value>
            <value>
                <fullName>Safety, Environment and Regulation</fullName>
            </value>
            <value>
                <fullName>Corporate Services</fullName>
            </value>
            <value>
                <fullName>People and Culture</fullName>
            </value>
            <value>
                <fullName>Asset Maintenance</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Customer Service Delivery</fullName>
            </value>
            <value>
                <fullName>Eastern Region</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; SEQR</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Finance &amp; Administrative Services</fullName>
            </value>
            <value>
                <fullName>Fleet Operations &amp; Infrastructure</fullName>
            </value>
            <value>
                <fullName>Freight and Regional Development</fullName>
            </value>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Infrastructure Development</fullName>
            </value>
            <value>
                <fullName>Journey Management</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal - Business Support</fullName>
            </value>
            <value>
                <fullName>Light Rail</fullName>
            </value>
            <value>
                <fullName>Maritime</fullName>
            </value>
            <value>
                <fullName>Newcastle Buses, Ferries and Light Rail</fullName>
            </value>
            <value>
                <fullName>Northern Region</fullName>
            </value>
            <value>
                <fullName>North West Rail Link</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Has_Corro_Officer_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Has_Corro_Officer_Permissions__c</fullName>
    <formula>$Permission.Corro_Officer</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Corro Officer Permissions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/TempAssignedSME__c.field-meta.xml
<CustomField>
    <fullName>TempAssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used in workflow which will send out an email to the Assigned SME</description>
    <label>Primary SME</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APStatusTransitionForAssign.cls
public without sharing class APStatusTransitionForAssign extends AbstractAPStatusTransition {
    public APStatusTransitionForAssign(Id actionPlanId) {
        try {
            validateActionPlan(actionPlanId);
        } catch(Exception e) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + '. Action plan details missing');
        }
    }
    
    public override void performTransition() {
        if(!GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST.equalsIgnoreCase(actionPlan.Type__c)
                && !GlobalConstants.AP_TYPE_AGENCY_RESPONSE.equalsIgnoreCase(actionPlan.Type__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' 
                + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + '. Action plan type is other than ' 
                + GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST + ' and ' + GlobalConstants.AP_TYPE_AGENCY_RESPONSE);
        }
        
        if(GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST.equalsIgnoreCase(actionPlan.Type__c)) {
            processAdviceRequestAP();
        } else {
            processAgencyResponseAP();
        }
    }
    
    private void processAgencyResponseAP() {
        if(String.isBlank(actionPlan.Parent_Action_Plan__c)) {
            processAgencyResponseParentActionPlan();
        } else {
            processAgencyResponseChildActionPlan();
        }
    }
    
    private void processAgencyResponseParentActionPlan() {
        if(!GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(actionPlan.Status__c)
            && !GlobalConstants.ACTION_PLAN_NEW_STATUS.equalsIgnoreCase(actionPlan.Status__c)
            && !GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED.equalsIgnoreCase(actionPlan.Status__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED 
                + '. Current status is other than ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + ' and ' + GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS);
        }
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED;
        List<Group> groups = [  SELECT Id, Name 
                                FROM Group 
                                Where DeveloperName = :Label.RMS_Corro_officer_queue 
                                    AND Type = 'Queue' LIMIT 1];
        if(groups.isEmpty()) {
            throw new InvalidDataException('Failed to update action plan status to ' 
                + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + '. RMS Corro officer queue not available.');
        }
        actionPlan.OwnerId = groups[0].Id;
        update actionPlan;
    }
    
    private void processAgencyResponseChildActionPlan() {
        processAdviceRequestChildActionPlan();
    }
    
    private void processAdviceRequestAP() {
        if(String.isBlank(actionPlan.Agency__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' 
                + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + '. Agency/Division not populated on action plan.');
        }
        if(GlobalConstants.ACTION_PLAN_AGENCY_Q_NOT_FOUND.equalsIgnoreCase(actionPlan.AgencyVsQueueMapping__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' 
                + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + '. Queue detail for ' + actionPlan.Agency__c + ' is not available');
        }
    
        if(String.isBlank(actionPlan.Parent_Action_Plan__c)) {
            processAdviceRequestParentActionPlan();
        } else {
            processAdviceRequestChildActionPlan();
        }
    }
    
    private void processAdviceRequestParentActionPlan() {
        System.debug('Action plan current status: ' + actionPlan.Status__c);        
        
        if(!GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(actionPlan.Status__c)
            && !GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED.equalsIgnoreCase(actionPlan.Status__c)
            && !GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT.equalsIgnoreCase(actionPlan.Status__c)
            && !GlobalConstants.ACTION_PLAN_NEW_STATUS.equalsIgnoreCase(actionPlan.Status__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED 
                + '. Current status is other than ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + ', ' + GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT + ', ' + GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS + ' and ' + GlobalConstants.ACTION_PLAN_NEW_STATUS);
        }
        
        if(!GlobalConstants.ACTION_PLAN_NEW_STATUS.equalsIgnoreCase(actionPlan.Status__c) && String.isBlank(actionPlan.Divisions__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED 
                + '. Division is not populated on action plan');
        }
        
        if(String.isBlank(actionPlan.AssignedSME__c)) {
            populateCOQueue();            
        } else {
            actionPlan.OwnerId = actionPlan.AssignedSME__c;
            actionPlan.TempAssignedSME__c = actionPlan.AssignedSME__c;
            actionPlan.AssignedSME__c = null;
        }        
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED;
        update actionPlan;
    }
    
    private void populateCOQueue() {
        List<Group> groups = [  SELECT Id, Name 
                                FROM Group 
                                Where DeveloperName = :actionPlan.AgencyVsQueueMapping__c 
                                    AND Type = 'Queue' LIMIT 1];
        if(groups.isEmpty()) {
            throw new InvalidDataException('Failed to update action plan status to ' 
                + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + '. Queue not available for ' + actionPlan.Agency__c + '.');
        }
        actionPlan.OwnerId = groups[0].Id;
    }
    
    private void processAdviceRequestChildActionPlan() {
        System.debug('Assigned SME on action plan: ' + actionPlan.AssignedSME__c);
        //throw exception if SME is not selected on child action plan
        if(String.isBlank(actionPlan.AssignedSME__c) && actionPlan.Has_Corro_Officer_Permissions__c) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + '. SME details missing on action plan');
        }
        
        System.debug('Action plan current status: ' + actionPlan.Status__c);
        if(GlobalConstants.ACTION_PLAN_NEW_APPROVED.equalsIgnoreCase(actionPlan.Status__c)) {
            List<Action_Plan__c> parent = [SELECT Id, OwnerId FROM Action_Plan__c WHERE Id = :actionPlan.Parent_Action_Plan__c];
            if(parent.isEmpty() || parent[0].OwnerId != UserInfo.getUserId()) {
                throw new InvalidDataException('Failed to assign action plan. You are not authorised to perform assignment on action plan');
            }
        }
        
        if(!GlobalConstants.ACTION_PLAN_NEW_APPROVED.equalsIgnoreCase(actionPlan.Status__c)
            && !GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT.equalsIgnoreCase(actionPlan.Status__c)
            && !GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(actionPlan.Status__c)
            && !GlobalConstants.ACTION_PLAN_NEW_STATUS.equalsIgnoreCase(actionPlan.Status__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED 
                + '. Current status is other than ' + GlobalConstants.ACTION_PLAN_NEW_APPROVED + ', ' 
                + GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT + ', ' 
                + GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS + ' and ' + GlobalConstants.ACTION_PLAN_NEW_STATUS);
        }
        
        if(!String.isBlank(actionPlan.AssignedSME__c)) {
            actionPlan.OwnerId = actionPlan.AssignedSME__c;
            actionPlan.TempAssignedSME__c = actionPlan.AssignedSME__c;
            actionPlan.AssignedSME__c = null;
        }
        
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED;        
        update actionPlan;
    }
    
    public class InvalidDataException extends Exception {}
}