force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date__c</fullName>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <label>Approver Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Has_Liaison_Officer_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Has_Liaison_Officer_Permissions__c</fullName>
    <description>This formula returns true if the current user has the Liaison Officer permission.</description>
    <formula>$Permission.Liaison_Officer || $Permission.Corro_Officer</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Liaison Officer_Permissions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APStatusTransitionForCompleted.cls
public without sharing class APStatusTransitionForCompleted extends AbstractAPStatusTransition{
    public APStatusTransitionForCompleted(String actionPlanId) {
        try {
            validateActionPlan(actionPlanId);
        } catch(Exception e) {
            throw new InvalidDataException('Failed to complete action plan. Action plan details missing');
        }       
    }    
    
    public override void performTransition() {
        if(!GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST.equalsIgnoreCase(actionPlan.Type__c)
                && !GlobalConstants.AP_TYPE_AGENCY_RESPONSE.equalsIgnoreCase(actionPlan.Type__c)) {
            throw new InvalidDataException('Failed to complete action plan. Action plan type is other than ' 
            + GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST + ' and ' + GlobalConstants.AP_TYPE_AGENCY_RESPONSE);
        }
        
        if(!actionPlan.Has_Liaison_Officer_Permissions__c) {
            throw new InvalidDataException('Failed to complete action plan. Action Plan can only be completed by Agency/Division Liaison Officer or RMS Corro Officer.');
        }
        
        if(GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST.equalsIgnoreCase(actionPlan.Type__c)) {
            processAdviceRequestAP();
        } else {
            processAgencyResponseAP();
        }
    }
    
    private void processAgencyResponseAP() {
        System.debug('Action plan current status: ' + actionPlan.Status__c);
        if(String.isBlank(actionPlan.Parent_Action_Plan__c)) {
            processAgencyResponseParentActionPlan();
        } else {
            processAgencyResponseChildActionPlan();
        }
    }
    
    private void processAgencyResponseParentActionPlan() {
        if(!GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS .equalsIgnoreCase(actionPlan.Status__c)
                && !GlobalConstants.ACTION_PLAN_STATUS_AWAITING_SIG.equalsIgnoreCase(actionPlan.Status__c)) {
            throw new InvalidDataException('Failed to complete action plan. Current status of action plan is other than ' + GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS  + ' and ' + GlobalConstants.ACTION_PLAN_STATUS_AWAITING_SIG);
        }
        List<Action_Plan__c> apsToUpdate = new List<Action_Plan__c>();
        if(GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(actionPlan.Status__c)) {
            List<Action_Plan__c> childActionPlans = [SELECT Id, Status__c FROM Action_Plan__c WHERE Parent_Action_Plan__c = :actionPlan.Id];
            for(Action_Plan__c ap : [SELECT Id, Status__c FROM Action_Plan__c WHERE Parent_Action_Plan__c = :actionPlan.Id]) {
                ap.Status__c = GlobalConstants.ACTION_PLAN_CLOSED_STATUS;
                apsToUpdate.add(ap);
            }
        }
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_CLOSED_STATUS;
        apsToUpdate.add(actionPlan);
        update apsToUpdate;
    }
    
    private void processAgencyResponseChildActionPlan() {
        processAdviceRequestChildActionPlan();
    }
    
    private void processAdviceRequestAP() {
        System.debug('Action plan current status: ' + actionPlan.Status__c);
        if(String.isBlank(actionPlan.Parent_Action_Plan__c)) {
            processAdviceRequestParentActionPlan();
        } else {
            processAdviceRequestChildActionPlan();
        }
    }
    
    private void processAdviceRequestParentActionPlan() {
        if(!GlobalConstants.ACTION_PLAN_NEW_APPROVED.equalsIgnoreCase(actionPlan.Status__c)
                && !GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(actionPlan.Status__c)) {
            throw new InvalidDataException('Failed to complete action plan. Current status of action plan is other than ' + GlobalConstants.ACTION_PLAN_NEW_APPROVED + ' and ' + GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS);
        }
                
        if(!areChildActionPlansComplete()) {
            throw new InvalidDataException('Failed to complete action plan. Atleast one child action plan is not complete.');
        }
        
        if(!isApproverDetailsAvailable()) {
            throw new InvalidDataException('Failed to complete action plan. Please enter the final approver name, role and approval date.');
        }
        
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_CLOSED_STATUS;
        actionPlan.OwnerId = UserInfo.getUserId();
        update actionPlan;
    }
    
    private Boolean isApproverDetailsAvailable() {
        Boolean flag = true;
        if(String.isBlank(actionPlan.Approver_Name__c) 
                || actionPlan.Approval_Date__c == null 
                || String.isBlank(actionPlan.Approver_Role__c)) {
            flag = false;
        }
        return flag;
    }
    
    private Boolean areChildActionPlansComplete() {
        List<Action_Plan__c> childActionPlans = [   SELECT Id 
                                                    FROM Action_Plan__c 
                                                    WHERE Status__c != :GlobalConstants.ACTION_PLAN_CLOSED_STATUS
                                                        AND Parent_Action_Plan__c = :actionPlan.Id];
        return childActionPlans.isEmpty();      
    }
            
    private void processAdviceRequestChildActionPlan() { 
        if(!GlobalConstants.ACTION_PLAN_NEW_APPROVED.equalsIgnoreCase(actionPlan.Status__c)
                && !GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(actionPlan.Status__c)) {
            throw new InvalidDataException('Failed to complete action plan. Current status of action plan is other than ' + GlobalConstants.ACTION_PLAN_NEW_APPROVED + ' and ' + GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS);
        }
                
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_CLOSED_STATUS;
        
        List<Action_Plan__c> parent = [SELECT Id, OwnerId FROM Action_Plan__c WHERE Id = :actionPlan.Parent_Action_Plan__c];
        if(!parent.isEmpty()) {
            actionPlan.OwnerId = parent[0].OwnerId;
        }
        
        update actionPlan;
    }
    
    public class InvalidDataException extends Exception {}
}