force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date__c</fullName>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <label>Approver Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>NoteOrAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ActionPlanPDFGeneratorFromButton_Test.cls
@isTest
private class ActionPlanPDFGeneratorFromButton_Test {
    
    @testSetup 
    static void setUpPermissionSetAssignment() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email = 'standarduser@nsw.gov.au.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Australia/Sydney', UserName='md' + System.currentTimeMillis() + '@nsw.gov.au.com', isActive = true);
        insert u;
        PermissionSet pset = [Select Id From PermissionSet Where Name =: GlobalConstants.PERMISSION_SET_CORRO_OFFICER limit 1];
        insert new PermissionSetAssignment(AssigneeId=u.Id, PermissionSetId=pset.id);
    }
    
    @isTest static void generatePDFTest() {
        User u = [Select Id From User Where email = 'standarduser@nsw.gov.au.com' limit 1];
        Case caseRecord;
        Action_Plan__c ap;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            caseRecord = NoteOrAttachmentTriggerDispatcher_Test.getCaseRecord();
            insert caseRecord; 
        }
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
            RecordType rt = [Select Id From RecordType WHere DeveloperName =: GlobalConstants.ACTION_PLAN_MCWS_AP_RECORD_TYPE_NAME];
            ap = new Action_Plan__c(Status__c = 'Action Plan in Review', Parent_Case__c = caseRecord.Id, RecordTypeId = rt.Id);
            insert ap;
        }
        
        System.runAs(u) {
            Test.startTest();
            ap.Approval_Date__c = Date.today();
            ap.Approver_Name__c = 'Abc';
            ap.Approver_Role__c = 'CM';
            ap.Status__c = GlobalConstants.ACTION_PLAN_CLOSED_STATUS;
            ActionPlanAfterUpdateTriggerHandler.firstTimers = null;
            update ap;
            list <NoteOrAttachment__c> newPdfs = [Select Id, ContentType__c From NoteOrAttachment__c Where Case__c =: caseRecord.Id]; 
            system.assertEquals(1, newPdfs.size());
            system.assertEquals('application/pdf', newPdfs[0].ContentType__c);
            String result = ActionPlanPDFGeneratorFromButton.genratePDF(ap.Id);
            system.assertEquals('File generated successfully!\nYou can find the generated pdf in Case Notes & Attachments.',result);
            result = ActionPlanPDFGeneratorFromButton.genratePDF(null);
            system.assertNotEquals('File generated successfully!\nYou can find the generated pdf in Case Notes & Attachments.',result);
            Test.stopTest();
        }
    }
}