force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/AssignedSME__c.field-meta.xml
<CustomField>
    <fullName>AssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned SME</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.Branch__c</field>
            <operation>equals</operation>
            <valueField>User.Branch__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Divisions__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACCREDITATION</fullName>
            </value>
            <value>
                <fullName>Asset Standards Authority</fullName>
            </value>
            <value>
                <fullName>AUDIT &amp; RISK</fullName>
            </value>
            <value>
                <fullName>Boating Infrastructure</fullName>
            </value>
            <value>
                <fullName>BOATING OPERATIONS</fullName>
            </value>
            <value>
                <fullName>Brookvale Depot</fullName>
            </value>
            <value>
                <fullName>Bureau of Transport Statistics</fullName>
            </value>
            <value>
                <fullName>Burwood Depot</fullName>
            </value>
            <value>
                <fullName>Bus and Ferry Services Contracts</fullName>
            </value>
            <value>
                <fullName>Centre for Road and Maritime Safety</fullName>
            </value>
            <value>
                <fullName>CHIEF EXECUTIVE&#39;S OFFICE</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial and Property Management</fullName>
            </value>
            <value>
                <fullName>Commercial and Strategy</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL PROPERTY</fullName>
            </value>
            <value>
                <fullName>Commercial Services</fullName>
            </value>
            <value>
                <fullName>COMMUNICATION &amp; STAKEHOLD</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Communications and Engagement</fullName>
            </value>
            <value>
                <fullName>Community Transport Agreements</fullName>
            </value>
            <value>
                <fullName>COMM VESSEL SURVEY</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>COMPLIANCE OPERATIONS</fullName>
            </value>
            <value>
                <fullName>CONTRACT MANAGEMENT OFFICE</fullName>
            </value>
            <value>
                <fullName>Contracts, Agreements &amp; Revenue Protect</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate and Project Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
            <value>
                <fullName>Corporate Planning &amp; Performance Info</fullName>
            </value>
            <value>
                <fullName>Country Rail Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be the Business hours corresponding to the Agency/Division selected on the Action plan, if a corresponding , business hr is not found the default one will be set</description>
    <inlineHelpText>The business hrs followed by the Agency / Division</inlineHelpText>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/CasePriority__c.field-meta.xml
<CustomField>
    <fullName>CasePriority__c</fullName>
    <description>Priority copied down from case</description>
    <label>Case Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MP - Standard</fullName>
            </value>
            <value>
                <fullName>Individual - Standard</fullName>
            </value>
            <value>
                <fullName>Date Sensitive – MO specified due date</fullName>
            </value>
            <value>
                <fullName>Urgent – MO specified due date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Divisions__c.field-meta.xml
<CustomField>
    <fullName>Divisions__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Agency__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Office of the Secretary</fullName>
            </value>
            <value>
                <fullName>Customer Strategy and Technology</fullName>
            </value>
            <value>
                <fullName>Greater Sydney</fullName>
            </value>
            <value>
                <fullName>Regional and Outer Metropolitan</fullName>
            </value>
            <value>
                <fullName>Infrastructure and Place</fullName>
            </value>
            <value>
                <fullName>Safety, Environment and Regulation</fullName>
            </value>
            <value>
                <fullName>Corporate Services</fullName>
            </value>
            <value>
                <fullName>People and Culture</fullName>
            </value>
            <value>
                <fullName>Asset Maintenance</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Customer Service Delivery</fullName>
            </value>
            <value>
                <fullName>Eastern Region</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; SEQR</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Finance &amp; Administrative Services</fullName>
            </value>
            <value>
                <fullName>Fleet Operations &amp; Infrastructure</fullName>
            </value>
            <value>
                <fullName>Freight and Regional Development</fullName>
            </value>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Infrastructure Development</fullName>
            </value>
            <value>
                <fullName>Journey Management</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal - Business Support</fullName>
            </value>
            <value>
                <fullName>Light Rail</fullName>
            </value>
            <value>
                <fullName>Maritime</fullName>
            </value>
            <value>
                <fullName>Newcastle Buses, Ferries and Light Rail</fullName>
            </value>
            <value>
                <fullName>Northern Region</fullName>
            </value>
            <value>
                <fullName>North West Rail Link</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_1__c</fullName>
    <label>Issue Level 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_2__c</fullName>
    <label>Issue Level 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3__c</fullName>
    <label>Issue Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_1__c</fullName>
    <label>Location Level 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_2__c</fullName>
    <label>Location Level 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3__c</fullName>
    <label>Location Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Minister__c.field-meta.xml
<CustomField>
    <fullName>Minister__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Minister Legacy</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Action Plans (Minister)</relationshipLabel>
    <relationshipName>ActionPlansMinister</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Minister_User__c.field-meta.xml
<CustomField>
    <fullName>Minister_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Minister</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ministerial Letter</fullName>
            </value>
            <value>
                <fullName>Other Products to Follow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Referring_Mp__c.field-meta.xml
<CustomField>
    <fullName>Referring_Mp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referring Minister</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Action Plans (Referring Minister)</relationshipLabel>
    <relationshipName>Action_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/TempAssignedSME__c.field-meta.xml
<CustomField>
    <fullName>TempAssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used in workflow which will send out an email to the Assigned SME</description>
    <label>Primary SME</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/recordTypes/CFM_Action_Plan.recordType-meta.xml
<RecordType>
    <fullName>CFM_Action_Plan</fullName>
    <active>true</active>
    <description>Use this record type to create new action plan CFM cases</description>
    <label>CFM Action Plan</label>
</RecordType>

force-app/main/default/objects/ActionPlanDueDateByAgency__c/ActionPlanDueDateByAgency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This can be used for calculating the Action Plan due dates by Agency+priority as in case of RMSMP - Standard it might be 9 days which will be 9*8=72 business hrs</description>
    <label>Action Plan Due Dates by Agency</label>
</CustomObject>

force-app/main/default/objects/ActionPlanDueDateByAgency__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <label>Business hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ActionPlanBeforeInsertTriggerHandler.cls
/*------------------------------------------------------------
Author:        Manish Damle
Company:       Arxxus.com
Description:   A utility class for the Action Plan Trigger

Test Class:    Action_PlanTriggerDispatcher_Test
History
26/05/2015     Manish Damle       Created
13/01/2017     Arxxus             Updated - to include new Minister_User__c field
------------------------------------------------------------*/
public without sharing class ActionPlanBeforeInsertTriggerHandler extends TriggerHandlerBase {
    List<ApplicationLogMessage> messages =new List<ApplicationLogMessage>();
    
    //SFCOE-8 - Start    
    private static Map<String,Decimal> actionPlanDueDateByAgencyMap;
    static{
        actionPlanDueDateByAgencyMap = new Map<String,Decimal>();
        for(ActionPlanDueDateByAgency__c actionPlanDueDateByAgency :ActionPlanDueDateByAgency__c.getall().values()){
            actionPlanDueDateByAgencyMap.put(actionPlanDueDateByAgency.Name,actionPlanDueDateByAgency.BusinessHours__c);
        }
        //Schema.Sobjecttype.Action_Plan__c.getRecordTypeInfosByName().get('CFM Action Plan').getRecordTypeId();
        
    }
    //SFCOE-8 - End    
    
    public override void mainEntry(TriggerParameters tp) {
        process(tp);
    }
    
    public override void inProgressEntry(TriggerParameters tp) {
        System.debug('This is an example for reentrant code...');
    }
    
    /*------------------------------------------------------------
Author:        Manish Damle
Company:       Arxxus.com
Description:   Handler function to copying all the child cases taxonomy details in
Instructions field.

History
26/05/2015     Manish Damle       Created
------------------------------------------------------------*/
    private void process(TriggerParameters tp) {
        try {
            for (Action_plan__c anAp:(List<Action_plan__c>)tp.newList){                
                if(anAp.RecordTypeId == Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME) 
                   && anAp.AssignedSme__c != null ) {
                       anAp.ownerId = anAp.AssignedSme__c;
                       anAp.TempAssignedSme__c = anAp.AssignedSme__c;
                       anAp.AssignedSme__c = null;
                   }
                //set the business hrs if agency is populated
                if(anAp.Agency__c != null) anAp.BusinessHours__c = BusinessHoursUtil.getBusinessHour(anAp.Agency__c);
            }
            
            system.debug('---ActionPlanBeforeInsertTriggerHandler---');
            
            set <Id> parentCaseIds = new set <Id> ();
            for(Action_Plan__c ap : (list <Action_Plan__c>) tp.newList) {
                if(ap.Parent_Case__c != null) {
                    parentCaseIds.add(ap.Parent_Case__c );
                }
            }
            
            map <Id, Case> parentCases = new map <Id, Case>([Select Id, OwnerAgency__c, Child_Cases_Count__c, 
                                                             Taxonomy_Moment__c,Taxonomy_Transaction__c, 
                                                             Taxonomy_Location_Type__c, Taxonomy_Symptom__c, 
                                                             Taxonomy_Location__c, Taxonomy_Area__c ,
                                                             (Select Id, Child_Cases_Count__c, CaseNumber, 
                                                              Taxonomy_Moment__c,Taxonomy_Transaction__c, 
                                                              Taxonomy_Location_Type__c, Taxonomy_Symptom__c, 
                                                              Taxonomy_Location__c, Taxonomy_Area__c 
                                                              From Cases)
                                                             From Case 
                                                             Where Id In: parentCaseIds And RecordTypeId IN: CaseTriggerDispatcher.recordTypesMinCorro]);

            for(Action_Plan__c ap : (list <Action_Plan__c>) tp.newList) {
                if(ap.Parent_Case__c != null && parentCases.containsKey(ap.Parent_Case__c) && ap.Agency__c != GlobalConstants.RMS_AGENCY) {
                    list <Case> childCases = parentCases.get(ap.Parent_Case__c).cases;
                    if(childCases != null && childCases.size() > 0){
                        //Multi Issue Case Found
                        ap.Instructions__c = ap.Instructions__c == null ? '<b>MAGS Ministerial Correspondence Case Categorisation:</b><br/>' : ap.Instructions__c + '<br/><b>MAGS Ministerial Correspondence Case Categorisation:</b><br/>';
                        for(Case c: childCases) {
                            ap.Instructions__c += '<b>[' + c.CaseNumber + ']</b> ' + getTaxonomyData(c);
                        }
                    } else {
                        //Single issue case found
                        ap.Instructions__c = ap.Instructions__c == null ? ' <b>MAGS Ministerial Correspondence Case Categorisation:</b><br/>' : ap.Instructions__c + '<br/><b>MAGS Ministerial Correspondence Case Categorisation:</b>';
                        ap.Instructions__c += getTaxonomyData(parentCases.get(ap.Parent_Case__c));
                    }
                }
            }
            
            copyCategorisationFromParentAPToChildAP(tp);
            
            Map<Id, Case> parentCasesForCfm = new Map<Id, Case>([Select Id, Taxonomy_Moment__c,Taxonomy_Transaction__c, Taxonomy_Symptom_Id__c, Taxonomy_Location_Id__c, Agency__c,
                                                                 Taxonomy_Location_Type__c, Taxonomy_Symptom__c, Taxonomy_Location__c, Taxonomy_Area__c, Modes__c, IsMinCorroCase__c
                                                                 From Case
                                                                 Where Id In: parentCaseIds 
                                                                 And RecordTypeId Not IN: CaseTriggerDispatcher.recordTypesMinCorro]);
            
            if(!parentCasesForCfm.isEmpty()) {
                ActionPlanCategorizationForCfm categorizationSelector = new ActionPlanCategorizationForCfm ((List<Action_plan__c>) tp.newList, parentCasesForCfm);
                categorizationSelector.populateCategorizationDetails();
            }
            
            if(Action_PlanTriggerDispatcher.magsAndCrgsAdminRoles.containsKey(UserInfo.getUserRoleId())) {
                ActionPlanUtility.stampDueDateOnActionPlan((list <Action_plan__c>) tp.newList);
            }
            CaseAmendmentChecker amendmentChecker = new CaseAmendmentChecker((List<Action_Plan__c>) tp.newList);
            amendmentChecker.checkForAmendment();
            
            
            //SFCOE-1314 Populate Parent Case/AP Description if it exceeds 7000 characters - Start
            populateAPDescription(tp);
            //SFCOE-1314 - End
            
            //SFCOE-8 - 10-04-2018 - Set Default Due Date on Action Plan, If Record type = CFM Action Plan AND Agency = TfNSW, add 5 working days (not 8) for automatic Due Date - Start            
            updateDueDateOnTfNSWcfsAPs(tp.newList, parentCaseIds);
            //SFCOE-8 - End
            
        }catch(Exception e){
            ApplicationLogMessage message= new ApplicationLogMessage();
            message.source='ActionPlanBeforeInsertTriggerHandler';
            message.sourceFunction='process';
            if (tp!=null && tp.oldMap!=null)  message.referenceInfo=JSON.serialize(tp.oldMap.keySet());
            message.logMessage=e.getMessage();
            message.ex=e;
            message.debugLevel='Error';
            messages.add(message);
            ApplicationLogUtility.logMessage(messages);
            messages.clear(); 
            //THROW_EXCEPTIONS is a global constant, it is set to the current user's "Throw Exceptions" value 
            //"Throw Exceptions" is a checkbox on the User record. - Added by Ian F, tfNSW, 21/08/2017
            if (GlobalConstants.THROW_EXCEPTIONS){
                Throw(e);
            }
        }
    }
    
    //SFCOE-8 - 10-04-2018 - Set Default Due Date on Action Plan, If Record type = CFM Action Plan AND Agency = TfNSW, add 5 working days (not 8) for automatic Due Date - Start
    private void updateDueDateOnTfNSWcfsAPs(List<Action_Plan__c> allAps, set <Id> parentCaseIds) {

        map <Id, Case> parentCases = new map <Id, case> ([Select Id, ownerAgency__c From case Where Id IN: parentCaseIds]);

        for(Action_Plan__c aAP:allAps){
            Case aparentCase;
            
            System.debug('aAp.RecordTypeId: ' + aAp.RecordTypeId);
            if(aAp.RecordTypeId == Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME)) {
                System.debug('ACTION_PLAN is CFM_Action_Plan.');
                System.debug('aAP.Parent_Case__c: ' + aAP.Parent_Case__c);
                if(aAP.Parent_Case__c != null && parentCases.containsKey(aAP.Parent_Case__c)) {
                    aparentCase = parentCases.get(aAP.Parent_Case__c);
                    if (aparentCase != null && aparentCase.OwnerAgency__c.equalsIgnoreCase(GlobalConstants.AGENCY_TFNSW)){
                        System.debug('Owner Agency on Parent Case is TFNSW.');
                        Id businessHourIdTfNSWId = BusinessHoursUtil.getBusinessHour(GlobalConstants.AGENCY_TFNSW);                    
                        Decimal bh = actionPlanDueDateByAgencyMap.get('TfNSWAP');

                        if(aAp.Due_Date__c == null){
                            aAp.Due_Date__c = BusinessHoursUtil.getActionPlanDueDate(businessHourIdTfNSWId, Date.today(), bh);
                            System.debug('aAp.Due_Date__c after update' + aAp.Due_Date__c);
                        }
                    } else {System.debug('Owner Agency is Not TfNSW.');}
                } else {System.debug('No parent case found.');}
                //if(aAp.Agency__c != null && aAp.Agency__c.equalsIgnoreCase(GlobalConstants.AGENCY_TFNSW)){
                //aAp.Due_Date__c = BusinessHoursUtil.getActionPlanDueDate(businessHourIdTfNSWId, aAp.Due_Date__c == null? Date.today():aAP.Due_Date__c, bh);
                //  }
            }  
        }
    }
    //SFCOE-8 - End
    
    private String getTaxonomyData(Case caseRecord) {
        String taxonomy = '';
        taxonomy += caseRecord.Taxonomy_Moment__c == null ? ' > ' : caseRecord.Taxonomy_Moment__c + ' > ';
        taxonomy += caseRecord.Taxonomy_Transaction__c == null ? ' > ' : caseRecord.Taxonomy_Transaction__c + ' > ';
        taxonomy += caseRecord.Taxonomy_Symptom__c == null? '' : caseRecord.Taxonomy_Symptom__c;
        return taxonomy + '<br/>';
    }
    
    /*------------------------------------------------------------
Author:        Manish Damle
Company:       Arxxus.com
Description:   Copy parent action plan categorisation to the child action plan.

History
01/06/2015     Manish Damle       Created
------------------------------------------------------------*/    
    private void copyCategorisationFromParentAPToChildAP(TriggerParameters tp) {
        set <Id> parentActionPlanIds = new set <Id>();
        for (Action_plan__c anAp :(List<Action_plan__c>) tp.newList){
            if(anAp.Parent_Action_Plan__c != null)
                parentActionPlanIds.add(anAp.Parent_Action_Plan__c);                
        }
        
        map <Id, Action_Plan__c> parentActionPlans = new map <Id, Action_Plan__c> ([Select Id, Issue_Level_1__c,Issue_Level_2__c,Issue_Level_3__c,Product_Type__c,Agency__c,Divisions__c,Branch__c,
                                                                                    Mode__c, Location_Level_1__c,Location_Level_2__c, Location_Level_3__c,Minister__c, Minister_User__c, CasePriority__c,     
                                                                                    Customer__c,Referring_Mp__c,Classification__c, Case_Subject__c, Case_Description__c, OBO__c, MO_Instructions__c, Case_Creation_Date__c
                                                                                    From Action_Plan__c 
                                                                                    Where Id IN: parentActionPlanIds]);
        for (Action_plan__c anAp :(List<Action_plan__c>) tp.newList){
            if(anAp.Parent_Action_Plan__c != null && parentActionPlans.containsKey(anAp.Parent_Action_Plan__c)) {
                Action_plan__c parentAP = parentActionPlans.get(anAp.Parent_Action_Plan__c);
                anAp.Mode__c = parentAP.Mode__c;
                anAp.Issue_Level_1__c = parentAP.Issue_Level_1__c;
                anAp.Issue_Level_2__c = parentAP.Issue_Level_2__c;
                anAp.Issue_Level_3__c = parentAP.Issue_Level_3__c;
                anAp.Location_Level_1__c = parentAP.Location_Level_1__c;
                anAp.Location_Level_2__c = parentAP.Location_Level_2__c;
                anAp.Location_Level_3__c = parentAP.Location_Level_3__c;
                anAp.Product_Type__c = parentAP.Product_Type__c;
                anAp.Customer__c = parentAP.Customer__c;
                anAp.Referring_Mp__c = parentAP.Referring_Mp__c;
                anAp.Agency__c = parentAP.Agency__c;
                anAp.Minister__c = parentAP.Minister__c;
                anAp.Minister_User__c = parentAP.Minister_User__c;
                anAp.Divisions__c = parentAP.Divisions__c;
                anAp.Branch__c = parentAP.Branch__c;
                anAp.Classification__c = parentAP.Classification__c;
                anAp.Case_Subject__c = parentAp.Case_Subject__c;
                anAp.Case_Description__c = parentAp.Case_Description__c;
                anAp.CasePriority__c = parentAp.CasePriority__c;
                anAp.OBO__c = parentAp.OBO__c; 
                anAp.MO_Instructions__c = parentAp.MO_Instructions__c;
                anAp.Parent_Case_Creation_Date__c = parentAp.Case_Creation_Date__c;
            }
        }
    }
    
    
    
    
    
    //SFCOE-1314 Populate Parent Case/AP Description if it exceeds 7000 characters - Start
    //Check whether Parent is a case or an action plan, accordingly populate Description as required    
    private void populateAPDescription(TriggerParameters tp) {
        set <Id> parentActionPlanIds = new set <Id>();
        set <Id> parentCaseIds = new set <Id>();
        
        for (Action_plan__c anAp :(List<Action_plan__c>) tp.newList){
            if(anAp.Parent_Action_Plan__c != null)
                parentActionPlanIds.add(anAp.Parent_Action_Plan__c);                
        }
        
        for (Action_plan__c aAp :(List<Action_plan__c>) tp.newList){
            if(aAp.Parent_Case__c != null)
                parentCaseIds.add(aAp.Parent_Case__c);                
        }
        
        
        
        map <Id, Action_Plan__c> parentActionPlans = new map <Id, Action_Plan__c> ([Select Id, Case_Description__c From Action_Plan__c Where Id IN: parentActionPlanIds]);
        for (Action_plan__c anAp :(List<Action_plan__c>) tp.newList){
            System.debug('anAp.Case_Description__c:: ' + anAp.Case_Description__c);
            
            if(Label.Field_size_is_too_large.EqualsIgnoreCase(anAp.Case_Description__c)){
                if(anAp.Parent_Action_Plan__c != null && parentActionPlans.containsKey(anAp.Parent_Action_Plan__c)) {
                    Action_plan__c parentAP = parentActionPlans.get(anAp.Parent_Action_Plan__c);
                    anAp.Case_Description__c = parentAP.Case_Description__c;
                }
            }
        }//for
        
        
        map <Id, Case> parentCases = new map <Id, case> ([Select Id, description From case Where Id IN: parentCaseIds]);
        for (Action_plan__c anAp :(List<Action_plan__c>) tp.newList){
            System.debug('anAp.Case_Description__c:: ' + anAp.Case_Description__c);
            
            if(Label.Field_size_is_too_large.EqualsIgnoreCase(anAp.Case_Description__c)){
                if(anAp.Parent_Case__c != null && parentCases.containsKey(anAp.Parent_Case__c)) {
                    Case parentCase = parentCases.get(anAp.Parent_Case__c);
                    anAp.Case_Description__c = parentCase.description;
                }
            }
        }//for
        
        
        
    }
    
    //SFCOE-1314 - End
    
}