force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be the Business hours corresponding to the Agency/Division selected on the Action plan, if a corresponding , business hr is not found the default one will be set</description>
    <inlineHelpText>The business hrs followed by the Agency / Division</inlineHelpText>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Action_Plan_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Action_Plan_Assigned__c</fullName>
    <label>Date stamp on Action Plan Assigned</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Action_Plan_in_Progress__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Action_Plan_in_Progress__c</fullName>
    <label>Date stamp on Action Plan in Progress</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Action_Plan_in_Review__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Action_Plan_in_Review__c</fullName>
    <label>Date stamp on Action Plan in Review</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Awaiting_Approval__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Awaiting_Approval__c</fullName>
    <label>Date stamp on Awaiting Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Awaiting_Signature__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Awaiting_Signature__c</fullName>
    <label>Date stamp on Awaiting Signature</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Incorrect_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Incorrect_Assignment__c</fullName>
    <label>Date stamp on Incorrect Assignment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Date_stamp_on_Ready_for_Printing__c.field-meta.xml
<CustomField>
    <fullName>Date_stamp_on_Ready_for_Printing__c</fullName>
    <label>Date stamp on Ready for Printing</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_spent_in_Action_Plan_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Time_spent_in_Action_Plan_Assigned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time spent in Action Plan Assigned</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_spent_in_Action_Plan_in_Progress__c.field-meta.xml
<CustomField>
    <fullName>Time_spent_in_Action_Plan_in_Progress__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time spent in Action Plan in Progress</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_spent_in_Action_Plan_in_Review__c.field-meta.xml
<CustomField>
    <fullName>Time_spent_in_Action_Plan_in_Review__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time spent in Action Plan in Review</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_spent_in_Awaiting_Approval__c.field-meta.xml
<CustomField>
    <fullName>Time_spent_in_Awaiting_Approval__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time spent in Awaiting Approval</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_spent_in_Awaiting_Signature__c.field-meta.xml
<CustomField>
    <fullName>Time_spent_in_Awaiting_Signature__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time spent in Awaiting Signature</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_spent_in_Incorrect_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Time_spent_in_Incorrect_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time spent in Incorrect Assignment</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_spent_in_New__c.field-meta.xml
<CustomField>
    <fullName>Time_spent_in_New__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time spent in New</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_spent_in_Ready_for_Printing__c.field-meta.xml
<CustomField>
    <fullName>Time_spent_in_Ready_for_Printing__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time spent in Ready for Printing</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TimeSpentInStatusCalculator_Test.cls
@isTest
private class TimeSpentInStatusCalculator_Test {

    private static List<Action_Plan__c> actionPlans;
    private static Map<Id, Action_Plan__c> oldActionPlanMap;

    private static testMethod void testForInvalidData() {
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(null, null);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForInvalidAPMap() {
        setupTestData(2);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForNewStatus() {
        setupTestData(1);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_NEW_STATUS;
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        System.assert(actionPlans[0].Time_spent_in_New__c != null);
    }
    
    private static testMethod void testForRejectedIncorrectAssignment() {
        setupTestData(1);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT;
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        System.assert(actionPlans[0].Time_spent_in_Incorrect_Assignment__c  != null);
    }
    
    private static testMethod void testForAwaitingSignature() {
        setupTestData(1);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_STATUS_AWAITING_SIG;
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        System.assert(actionPlans[0].Time_spent_in_Awaiting_Signature__c  != null);
    }
    
    private static testMethod void testForReadyForPrinting() {
        setupTestData(1);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_STATUS_READY_FOR_PRINT;
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        System.assert(actionPlans[0].Time_spent_in_Ready_for_Printing__c  != null);
    }
    
    private static testMethod void testForInProgress() {
        setupTestData(1);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS;
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        System.assert(actionPlans[0].Time_spent_in_Action_Plan_in_Progress__c  != null);
    }
    
    private static testMethod void testForReadyForAssigned() {
        setupTestData(1);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED;
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        System.assert(actionPlans[0].Time_spent_in_Action_Plan_Assigned__c  != null);
    }
    
    private static testMethod void testForReadyForApproved() {
        setupTestData(1);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_NEW_APPROVED;
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        System.assert(actionPlans[0].Time_spent_in_Action_Plan_in_Review__c  != null);
    }
    
    private static testMethod void testForWaitingApproval() {
        setupTestData(1);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_WAITING_APPROVAL;
        oldActionPlanMap.put(actionPlans[0].Id, actionPlans[0]);
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        System.assert(actionPlans[0].Time_spent_in_Awaiting_Approval__c  != null);
    }   
    
    private static testMethod void testForBulkOperation() {
        setupTestData(200);
        oldActionPlanMap = new Map<Id,Action_Plan__c>();
        actionPlans[0].Status__c = GlobalConstants.ACTION_PLAN_NEW_STATUS;
        for(Action_Plan__c ap : actionPlans) {
            ap.Status__c = GlobalConstants.ACTION_PLAN_NEW_STATUS;
            oldActionPlanMap.put(ap.Id, ap);
        }
        System.Test.startTest();
        try{
            TimeSpentInStatusCalculator calculator = new TimeSpentInStatusCalculator(actionPlans, oldActionPlanMap);
            calculator.stampTimeSpent();            
        } catch(Exception e) {
            System.assert(false);
        }
        System.Test.stopTest();
        for(Action_Plan__c ap : actionPlans) {
            System.assert(ap.Time_spent_in_New__c != null);
        }
    }
    
    private static void setupTestData(Integer apCount) {
        actionPlans = new List<Action_Plan__c>();
        List<BusinessHours> businessHrs = [SELECT b.Name, b.Id FROM BusinessHours b WHERE b.IsActive = true];
        
        for(Integer index = 0; index < apCount; index++) {
            Action_Plan__c apRecord = new Action_Plan__c();
            if(!businessHrs.isEmpty()) {
                apRecord.BusinessHours__c = businessHrs[0].Id;
            }            
            apRecord.Agency__c = GlobalConstants.RMS_AGENCY;
            actionPlans.add(apRecord);
        }
        
        insert actionPlans;
        
        actionPlans = [ SELECT Id, Status__c, BusinessHours__c, CreatedDate, Date_stamp_on_Incorrect_Assignment__c, Date_stamp_on_Awaiting_Signature__c, 
                            Date_stamp_on_Ready_for_Printing__c, Date_stamp_on_Action_Plan_in_Progress__c, Date_stamp_on_Action_Plan_Assigned__c, 
                            Date_stamp_on_Action_Plan_in_Review__c, Date_stamp_on_Awaiting_Approval__c
                        FROM Action_Plan__c
                        WHERE Id IN :actionPlans];
        for(Action_Plan__c ap : actionPlans) {
            ap.Date_stamp_on_Incorrect_Assignment__c = System.now();
            ap.Date_stamp_on_Awaiting_Signature__c = System.now();
            ap.Date_stamp_on_Ready_for_Printing__c = System.now();
            ap.Date_stamp_on_Action_Plan_in_Progress__c = System.now();
            ap.Date_stamp_on_Action_Plan_Assigned__c = System.now();
            ap.Date_stamp_on_Action_Plan_in_Review__c = System.now();
            ap.Date_stamp_on_Awaiting_Approval__c = System.today();         
        }
    }

}