force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>First level nominated approver by Liaison officer.</description>
    <inlineHelpText>First level nominated approver by Liaison officer.</inlineHelpText>
    <label>Approver Level 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_level_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Level 2 approver</description>
    <label>Approver Level 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nominated level 3 approver</description>
    <label>Approver Level 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_level_3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Divisions__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACCREDITATION</fullName>
            </value>
            <value>
                <fullName>Asset Standards Authority</fullName>
            </value>
            <value>
                <fullName>AUDIT &amp; RISK</fullName>
            </value>
            <value>
                <fullName>Boating Infrastructure</fullName>
            </value>
            <value>
                <fullName>BOATING OPERATIONS</fullName>
            </value>
            <value>
                <fullName>Brookvale Depot</fullName>
            </value>
            <value>
                <fullName>Bureau of Transport Statistics</fullName>
            </value>
            <value>
                <fullName>Burwood Depot</fullName>
            </value>
            <value>
                <fullName>Bus and Ferry Services Contracts</fullName>
            </value>
            <value>
                <fullName>Centre for Road and Maritime Safety</fullName>
            </value>
            <value>
                <fullName>CHIEF EXECUTIVE&#39;S OFFICE</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial and Property Management</fullName>
            </value>
            <value>
                <fullName>Commercial and Strategy</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL PROPERTY</fullName>
            </value>
            <value>
                <fullName>Commercial Services</fullName>
            </value>
            <value>
                <fullName>COMMUNICATION &amp; STAKEHOLD</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Communications and Engagement</fullName>
            </value>
            <value>
                <fullName>Community Transport Agreements</fullName>
            </value>
            <value>
                <fullName>COMM VESSEL SURVEY</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>COMPLIANCE OPERATIONS</fullName>
            </value>
            <value>
                <fullName>CONTRACT MANAGEMENT OFFICE</fullName>
            </value>
            <value>
                <fullName>Contracts, Agreements &amp; Revenue Protect</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate and Project Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
            <value>
                <fullName>Corporate Planning &amp; Performance Info</fullName>
            </value>
            <value>
                <fullName>Country Rail Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Time_Sent_for_Last_Approval__c.field-meta.xml
<CustomField>
    <fullName>Time_Sent_for_Last_Approval__c</fullName>
    <label>Time Sent for Last Approval</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActionPlanApproverUpdateBatchTest.cls
@isTest(seeAllData = false)
public class ActionPlanApproverUpdateBatchTest {
    private static List<EmailMessage> emails;
    
    private static void setUpTestData(Integer emailCount) {
        emails = new List<EmailMessage>();
        List<Case> cases = createCases(emailCount);
        for(Case caseDetail : cases) {
            EmailMessage message = new EmailMessage();
            message.TextBody = 'Test advice request email';
            message.ParentId = caseDetail.Id;
            message.ToAddress = 'test.user@transport.gov.nsw.au';            
            emails.add(message);
        }
    }
    private static List<Case> createCases(Integer caseCount) {
        List<Case> caseRecords = new List<Case>();
        for(Integer i = 0; i < caseCount; i++) {
            Case caseRecord = new Case();
            caseRecord.Description = 'Test case for creating action plan';
            caseRecord.Origin = 'Web';
            caseRecord.Priority = 'Normal';
            caseRecord.Type = 'Feedback';
            caseRecord.Taxonomy_Symptom__c = 'Difficult to Use';
            caseRecord.Taxonomy_Location__c = '140';
            caseRecord.Taxonomy_Area__c = 'Willoughby';
            caseRecord.Taxonomy_Location_Type__c = 'Sydney Buses';
            caseRecord.Taxonomy_Transaction__c = 'Agency Website';
            caseRecord.Taxonomy_Moment__c = 'Planning the Trip';
            caseRecord.Modes__c = 'Bus';
            caseRecord.branch__c= 'test branch';
            caseRecord.Agency__c= 'test agency';            
            caseRecords.add(caseRecord);
        }        
        if(!caseRecords.isEmpty()) insert caseRecords;        
        return caseRecords;
    }
    
    static testmethod void testApproverUpdateBatch(){
        setupTestData(5);
        ActionPlanCreator apCreator = new ActionPlanCreator(emails);
        List<Action_Plan__c> actionPlans = apCreator.createAdviceRequestPlans();
        List<Id> apIds = new List<Id>();
        //actionPlans.clear();
        for(Action_Plan__c ap : [select Time_Sent_for_Last_Approval__c,Status__c from Action_Plan__c]){
            ap.Time_Sent_for_Last_Approval__c = DateTime.now();
            ap.Type__c = GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST;            
            actionPlans.add(ap);
        }
        insert actionPlans;
        List<Action_Plan__c> updatedActionPlans = new List<Action_Plan__c>();
        for(Action_Plan__c ap : actionPlans){
            ap.Response__c = 'test';
            ap.OwnerId = UserInfo.getUserId();
            ap.Status__c = GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS;
                        ap.Approver_Level_1__c = null;
            ap.Approver_Level_2__c = null;
            ap.Approver_Level_3__c = null;
            updatedActionPlans.add(ap);
        }
        update updatedActionPlans;
        //system.assertEquals(updatedActionPlans,null );
        for(Action_Plan__c ap : actionPlans){
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments('Approve.');
            req.setNextApproverIds(new Id[] {UserInfo.getUserId()});
            req.setObjectId(ap.Id);
            //Submit the approval request
            Approval.ProcessResult result = Approval.process(req);
        }
        Test.startTest();
        //ActionPlanApproverUpdateBatch ins = new ActionPlanApproverUpdateBatch();
        String CRON_EXP = '0 0 23 * * ? *';
        ActionPlanApproverUpdateBatch ins = new ActionPlanApproverUpdateBatch();
        system.schedule('Batch Job - Update Approver', CRON_EXP, ins);
        //database.executeBatch(ins);
        Test.stopTest();
        
    }

}