force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AP_NoteOrAttachment__c/AP_NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between Action Plan and Notes &amp; Attachments object. This object will store the reference of the Notes Or Attachments custom object</description>
    <label>AP Note Or Attachment</label>
    <nameField>
        <displayFormat>APNA-{00000000}</displayFormat>
        <label>Note Or Attachment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Notes Or Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AP_NoteOrAttachment__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Notes &amp; Attachments</relationshipLabel>
    <relationshipName>AP_Note_Attachment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/AP_NoteOrAttachment__c/fields/Note_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Note_Attachment__c</fullName>
    <label>Note &amp; Attachment</label>
    <referenceTo>NoteOrAttachment__c</referenceTo>
    <relationshipLabel>AP Notes &amp; Attachments</relationshipLabel>
    <relationshipName>AP_Note_Attachment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/NoteOrAttachment__c.object-meta.xml
<CustomObject>
    <description>This object masks standard Attachments &amp; Private Notes in the custom object.</description>
    <label>Note Or Attachment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Or Attachments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteOrAttachment__c/fields/Privacy__c.field-meta.xml
<CustomField>
    <fullName>Privacy__c</fullName>
    <inlineHelpText>This allows user to mark security disposition of the record. Default is &quot;Standard&quot;</inlineHelpText>
    <label>Privacy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/Requires_Printing__c.field-meta.xml
<CustomField>
    <fullName>Requires_Printing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Printing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NoteOrAttachment__c/fields/View__c.field-meta.xml
<CustomField>
    <fullName>View__c</fullName>
    <formula>IF( $Profile.Name == &#39;TfNSW Operator Portal User&#39;,IF(RecordType.Name == &quot;Attachment&quot;, HYPERLINK(&quot;/operatorportal/servlet/servlet.FileDownload?file=&quot; + Attachment_Id__c,&quot;View&quot;),&quot;&quot;),IF(RecordType.Name == &quot;Attachment&quot;, HYPERLINK(&quot;/servlet/servlet.FileDownload?file=&quot; + Attachment_Id__c,&quot;View&quot;),&quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>View</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParentNoteOrAttachmentViewer_CX.cls
/*-----------------------------------------------------------------------------------
Author:        Manish Damle
Company:       Arxxus.com
Description:   Extension class for displaying parent attachments on the child action plan
Test Class:    NewActionPlanAttachment_CX_Test
History
27/06/2015     Manish Damle       Created
-----------------------------------------------------------------------------------*/
public without sharing class ParentNoteOrAttachmentViewer_CX {
	private string childActionPlanId;
    public list <AP_NoteOrAttachment__c> attachments {get;set;}
    
    public ParentNoteOrAttachmentViewer_CX(ApexPages.StandardController controller)  {
        childActionPlanId = ApexPages.currentPage().getParameters().get('id');
        attachments = new list <AP_NoteOrAttachment__c>();
    }
    
    public PageReference init() {
        try {
            if(childActionPlanId == null || childActionPlanId == '') {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Invalid Parameters'));
                return null;
            }
            
            Action_Plan__c childActionPlan = [Select Id, Parent_Action_Plan__c From Action_Plan__c Where Id =: childActionPlanId limit 1];
            
            if(childActionPlan != null && childActionPlan.Parent_Action_Plan__c != null) {
                attachments = [Select Id, Name, Note_Attachment__r.Name, Note_Attachment__r.Privacy__c, Note_Attachment__r.View__c, Note_Attachment__r.RecordType.Name, Note_Attachment__r.Requires_Printing__c 
                               From  AP_NoteOrAttachment__c 
                               Where Action_Plan__c =: childActionPlan.Parent_Action_Plan__c And Note_Attachment__r.RecordType.Name =: GlobalConstants.NOTEORATTACHMENT_RECORDTYPENAME_ATTACHMENT] ;
            }
        }catch(Exception e) {
            system.debug('----Exception Parent Attachments------'  + e.getMessage() + '---' + e.getLineNumber());
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error occured while fetching attachments'));
            return null;
        }
        return null;
    }
}