force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_1__c</fullName>
    <label>Issue Level 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_2__c</fullName>
    <label>Issue Level 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3__c</fullName>
    <label>Issue Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Issue_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Issue_Level_3_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Issue Level 3  metacategorisation Id</description>
    <inlineHelpText>Issue Level 3  metacategorisation Id</inlineHelpText>
    <label>Issue Level 3 Id</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_1__c</fullName>
    <label>Location Level 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_2__c</fullName>
    <label>Location Level 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3__c</fullName>
    <label>Location Level 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Location_Level_3_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Level_3_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location Level 3  metacategorisation Id</description>
    <inlineHelpText>Issue Level 3  metacategorisation Id</inlineHelpText>
    <label>Location Level 3 Id</label>
    <referenceTo>Taxonomy_Metadata__c</referenceTo>
    <relationshipLabel>Action Plans (Location Level 3 Id)</relationshipLabel>
    <relationshipName>Action_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActionPlanCategorizationForCfm.cls
public with sharing class ActionPlanCategorizationForCfm {

    private Map<Id, Case> caseDetails;
    private List<Action_Plan__c> actionPlans;
    
    public ActionPlanCategorizationForCfm(List<Action_Plan__c> actionPlans, Map<Id, Case> caseDetails) {
        if(caseDetails == null || actionPlans == null || actionPlans.isEmpty() || caseDetails.isEmpty()) {
            throw new InvalidDataException('Failed to populate categorization details on action plan. Either case or action plan details missing');
        }
        this.caseDetails = caseDetails;
        this.actionPlans = actionPlans;
    }
    
    public void populateCategorizationDetails() {
        Case caseRecord;
        for(Action_Plan__c ap: actionPlans) {
            System.debug(LoggingLevel.INFO, ap.Parent_Case__c);
            if(ap.Parent_Case__c != null && caseDetails.containsKey(ap.Parent_Case__c) && !caseDetails.get(ap.Parent_Case__c).IsMinCorroCase__c) {
                caseRecord = caseDetails.get(ap.Parent_Case__c);
                ap.Agency__c = caseRecord.Agency__c;
                ap.Issue_Level_1__c = caseRecord.Taxonomy_Moment__c;
                ap.Issue_Level_2__c = caseRecord.Taxonomy_Transaction__c;
                ap.Issue_Level_3__c = caseRecord.Taxonomy_Symptom__c;
                ap.Issue_Level_3_Id__c = caseRecord.Taxonomy_Symptom_Id__c;
                ap.Location_Level_1__c = caseRecord.Taxonomy_Location_Type__c;
                ap.Location_Level_2__c = caseRecord.Taxonomy_Area__c;
                ap.Location_Level_3__c = caseRecord.Taxonomy_Location__c;
                ap.Location_Level_3_Id__c = caseRecord.Taxonomy_Location_Id__c;
                ap.Mode__c = caseRecord.Modes__c;
            }
        }        
    }
    
    public class InvalidDataException extends Exception {}
}