force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date__c</fullName>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <label>Approver Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/recordTypes/MCWS_Child_Action_Plan.recordType-meta.xml
<RecordType>
    <fullName>MCWS_Child_Action_Plan</fullName>
    <active>true</active>
    <description>User this record type to create action plan from the parent action plan</description>
    <label>Child Action Plan</label>
</RecordType>

force-app/main/default/objects/Action_Plan__c/recordTypes/RMS_Action_Plan.recordType-meta.xml
<RecordType>
    <fullName>RMS_Action_Plan</fullName>
    <active>true</active>
    <description>Use this record type to create action plan record of the type Agency Response</description>
    <label>Agency Response</label>
</RecordType>

force-app/main/default/classes/APStatusTransitionForReview_Test.cls
@isTest
private class APStatusTransitionForReview_Test {

    private static Action_Plan__c actionPlan;
    private static final String RMS_CORRO_OFFICER_PERM = 'RMS_Corro_Officer';
    private static final String GIS_ADMIN_PERM = 'RMS_GIS_Admin';
	private static final String AP_RESPONSE_TEXT = 'Test run';
    
    private static void setUpTestData(String type, String status, String response) {
        actionPlan = new Action_Plan__c();
        actionPlan.Type__c = type;
        actionPlan.Status__c = status;
        actionPlan.Agency__c = GlobalConstants.RMS_AGENCY;
        actionPlan.RecordTypeId = retrieveAgencyResponseRT();
        actionPlan.Approver_Name__c = 'Test User';
        actionPlan.Approval_Date__c = System.today();
        actionPlan.Approver_Role__c = 'Admin';
		actionPlan.Response__c = response;
        insert actionPlan;
    }
    
    private static Id retrieveAgencyResponseRT() {
        List<RecordType> rts = [SELECT Id FROM RecordType WHERE SObjectType = 'Action_Plan__c' AND DeveloperName = 'RMS_Action_Plan'];
        return rts.isEmpty()? null : rts[0].Id;
    }
    
    private static Id retrieveChildActionPlanRT() {
        List<RecordType> rts = [SELECT Id FROM RecordType WHERE SObjectType = 'Action_Plan__c' AND DeveloperName = 'MCWS_Child_Action_Plan'];
        return rts.isEmpty()? null : rts[0].Id;
    }
        
    private static testMethod void testForInvalidData() {
        actionPlan = new Action_Plan__c();
        System.Test.startTest();
        try {           
            APStatusTransitionForReview transitionInstance = new APStatusTransitionForReview(actionPlan.Id);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForActionPlanWithBlankType() {
        setUpTestData(null, GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS, AP_RESPONSE_TEXT);
        System.Test.startTest();
        try {           
            APStatusTransitionForReview transitionInstance = new APStatusTransitionForReview(actionPlan.Id);
            transitionInstance.performTransition();
            System.assert(false);
        } catch(Exception e) {
            System.assert(e.getTypeName() == 'APStatusTransitionForReview.InvalidDataException');
        }
        System.Test.stopTest();
    }
	    
    private static testMethod void testForParentAgencyResponse() {
        User u = createTestUser(RMS_CORRO_OFFICER_PERM);
        System.runAs(u) {
            setUpTestData(GlobalConstants.AP_TYPE_AGENCY_RESPONSE, GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS, AP_RESPONSE_TEXT);            
        }
        System.Test.startTest();
        System.runAs(u) {            
            try {           
                APStatusTransitionForReview transitionInstance = new APStatusTransitionForReview(actionPlan.Id);
                transitionInstance.performTransition(); 
                System.assert(false);
            } catch(Exception e) {
                System.assert(e.getTypeName() == 'APStatusTransitionForReview.InvalidDataException');
            }
        }        
        System.Test.stopTest();        
    }
    
    private static testMethod void testForAgencyResponseWithChildAP() {
        User u = createTestUser(RMS_CORRO_OFFICER_PERM);
        Id childApId;
		System.runAs(u) {
            setUpTestData(GlobalConstants.AP_TYPE_AGENCY_RESPONSE, GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS, AP_RESPONSE_TEXT);
			childApId = createChildActionPlan(GlobalConstants.AP_TYPE_AGENCY_RESPONSE, GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS, AP_RESPONSE_TEXT);
        }
        System.Test.startTest();
        System.runAs(u) {
			APStatusTransitionForReview transitionInstance = new APStatusTransitionForReview(childApId);
			transitionInstance.performTransition();            
        }
        System.Test.stopTest();
        for(Action_Plan__c ap : [   SELECT Id, Status__c  
									FROM Action_Plan__c 
									WHERE Parent_Action_Plan__c = :actionPlan.Id]) {
            System.assert(GlobalConstants.ACTION_PLAN_NEW_APPROVED == ap.Status__c);
        }
    }
	
	private static testMethod void testForChildAPWithInvalidStatus() {
        User u = createTestUser(RMS_CORRO_OFFICER_PERM);
        Id childApId;
		System.runAs(u) {
            setUpTestData(GlobalConstants.AP_TYPE_AGENCY_RESPONSE, GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS, AP_RESPONSE_TEXT);
			childApId = createChildActionPlan(GlobalConstants.AP_TYPE_AGENCY_RESPONSE, GlobalConstants.ACTION_PLAN_NEW_APPROVED, AP_RESPONSE_TEXT);
        }
        System.Test.startTest();
        System.runAs(u) {
			try{
				APStatusTransitionForReview transitionInstance = new APStatusTransitionForReview(childApId);
				transitionInstance.performTransition();
				System.assert(false);
			} catch(Exception e) {
				System.assert(e.getTypeName() == 'APStatusTransitionForReview.InvalidDataException');
			}			            
        }
        System.Test.stopTest();        
    }
    
    private static testMethod void testForChildAPAdviceRequest() {
        User u = createTestUser(RMS_CORRO_OFFICER_PERM);
		Id childApId ;
		System.runAs(u) {
            setUpTestData(GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST, GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS, AP_RESPONSE_TEXT);
            childApId = createChildActionPlan(GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST, GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS, AP_RESPONSE_TEXT);            
        }
        System.Test.startTest();
        System.runAs(u) {
            try {           
                APStatusTransitionForReview transitionInstance = new APStatusTransitionForReview(childApId);
                transitionInstance.performTransition();
            } catch(Exception e) {
                System.assert(false);
            }
        }
        System.Test.stopTest();
		Action_Plan__c ap = [SELECT Id, Status__c  FROM Action_Plan__c WHERE Id = :childApId];
        System.assert(GlobalConstants.ACTION_PLAN_NEW_APPROVED == ap.Status__c);
    }
    
    private static testMethod void testForActionPlanOfAdviceRequest() {
        User u = createTestUser(RMS_CORRO_OFFICER_PERM);
        System.runAs(u) {
            setUpTestData(GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST, GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS, AP_RESPONSE_TEXT);
        }
        System.Test.startTest();        
        System.runAs(u) {
            try{
				APStatusTransitionForReview transitionInstance = new APStatusTransitionForReview(actionPlan.Id);
				transitionInstance.performTransition();
				System.assert(false);
			} catch(Exception e) {
				System.assert(e.getTypeName() == 'APStatusTransitionForReview.InvalidDataException');
			}
        }        
        System.Test.stopTest();        
    }
    
    private static Id createChildActionPlan(String type, String status, String response) {
        Action_Plan__c child = new Action_Plan__c();
        child.Type__c = type;
        child.Status__c = GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS;
		child.Status__c = status;
        child.Agency__c = GlobalConstants.RMS_AGENCY;
        child.recordTypeId = retrieveChildActionPlanRT();
        child.Parent_Action_Plan__c = actionPlan.Id;
		child.Response__c = response;
        insert child;
        return child.Id;
    }
    
    private static User createTestUser(String permission) {
        Profile p = [SELECT Id FROM Profile WHERE Name='RMS Case Manager'];
        User u = new User(Alias = 'standt', Email='corroofficer@nsw.gov.au.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Australia/Sydney', UserName='corroofficer@nsw.gov.au.com');
        insert u;
        
        PermissionSet permSet = [Select Name, Id From PermissionSet WHERE Name = :permission];      
        PermissionSetAssignment permAssignment = new PermissionSetAssignment();
        permAssignment.AssigneeId = u.Id;
        permAssignment.PermissionSetId = permSet.Id;        
        insert permAssignment;
        return u;
    }
}