force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Divisions__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACCREDITATION</fullName>
            </value>
            <value>
                <fullName>Asset Standards Authority</fullName>
            </value>
            <value>
                <fullName>AUDIT &amp; RISK</fullName>
            </value>
            <value>
                <fullName>Boating Infrastructure</fullName>
            </value>
            <value>
                <fullName>BOATING OPERATIONS</fullName>
            </value>
            <value>
                <fullName>Brookvale Depot</fullName>
            </value>
            <value>
                <fullName>Bureau of Transport Statistics</fullName>
            </value>
            <value>
                <fullName>Burwood Depot</fullName>
            </value>
            <value>
                <fullName>Bus and Ferry Services Contracts</fullName>
            </value>
            <value>
                <fullName>Centre for Road and Maritime Safety</fullName>
            </value>
            <value>
                <fullName>CHIEF EXECUTIVE&#39;S OFFICE</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial and Property Management</fullName>
            </value>
            <value>
                <fullName>Commercial and Strategy</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL PROPERTY</fullName>
            </value>
            <value>
                <fullName>Commercial Services</fullName>
            </value>
            <value>
                <fullName>COMMUNICATION &amp; STAKEHOLD</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Communications and Engagement</fullName>
            </value>
            <value>
                <fullName>Community Transport Agreements</fullName>
            </value>
            <value>
                <fullName>COMM VESSEL SURVEY</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>COMPLIANCE OPERATIONS</fullName>
            </value>
            <value>
                <fullName>CONTRACT MANAGEMENT OFFICE</fullName>
            </value>
            <value>
                <fullName>Contracts, Agreements &amp; Revenue Protect</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate and Project Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
            <value>
                <fullName>Corporate Planning &amp; Performance Info</fullName>
            </value>
            <value>
                <fullName>Country Rail Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/SME_Email__c.field-meta.xml
<CustomField>
    <fullName>SME_Email__c</fullName>
    <label>SME Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActionPlanCreator_Test.cls
@isTest
private class ActionPlanCreator_Test{

    private static List<EmailMessage> emails;
    private static testMethod void testForInvalidData() {
        System.Test.startTest();
        try{
            ActionPlanCreator apCreator = new ActionPlanCreator(null);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        try{
            ActionPlanCreator apCreator = new ActionPlanCreator(new List<EmailMessage>());
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForSingleAdviceEmailMessage() {
        setUpTestData(1);
        System.Test.startTest();
        ActionPlanCreator apCreator = new ActionPlanCreator(emails);
        List<Action_Plan__c> actionPlans = apCreator.createAdviceRequestPlans();
        System.assert(actionPlans != null);
        System.assert(actionPlans.size() == 1);
        System.assert(actionPlans[0].SME_Email__c == emails[0].ToAddress);
        System.assert(actionPlans[0].Parent_Case__c == emails[0].ParentId);
        System.assert(actionPlans[0].Status__c == GlobalConstants.ACTION_PLAN_NEW_STATUS);
        System.assert(actionPlans[0].Type__c  == GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST);
        System.assert(actionPlans[0].Branch__c  == 'test branch');
        System.assert(actionPlans[0].Agency__c  == 'test agency');

        System.Test.stopTest();
    }
    
    private static testMethod void testForAPCreationForSupportingQueue() {
        setUpTestData(1);
        Group groupRec = [SELECT Id FROM Group g WHERE type = 'Queue' AND DeveloperName = 'Serco_Web_Triage_CFM'];
        List<Case> cases = [SELECT id, OwnerId FROM Case];
        for(Case caseRecord : cases) {
            caseRecord.OwnerId = groupRec.Id;
        }
        update cases;
        System.Test.startTest();
        ActionPlanCreator apCreator = new ActionPlanCreator(emails);
        List<Action_Plan__c> actionPlans = apCreator.createAdviceRequestPlans();
        System.assert(actionPlans != null);
        System.assert(actionPlans.size() == 1);
        System.assert(actionPlans[0].SME_Email__c == emails[0].ToAddress);
        System.assert(actionPlans[0].Parent_Case__c == emails[0].ParentId);
        System.assert(actionPlans[0].Status__c == GlobalConstants.ACTION_PLAN_NEW_STATUS);
        System.assert(actionPlans[0].Type__c  == GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST);
        System.assert(actionPlans[0].Branch__c  == 'test branch');
        System.assert(actionPlans[0].Agency__c  == 'test agency');
        System.assert(actionPlans[0].OwnerId  == groupRec.Id);

        System.Test.stopTest();
    }
    
    private static testMethod void testForAPCreationForNonSupportingQueue() {
        setUpTestData(1);
        Group groupRec = [SELECT Id FROM Group g WHERE type = 'Queue' AND DeveloperName = 'ErroneousCases_MC'];
        List<Case> cases = [SELECT id, OwnerId FROM Case];
        for(Case caseRecord : cases) {
            caseRecord.OwnerId = groupRec.Id;
        }
        update cases;
        System.Test.startTest();
        ActionPlanCreator apCreator = new ActionPlanCreator(emails);
        List<Action_Plan__c> actionPlans = apCreator.createAdviceRequestPlans();
        System.assert(actionPlans != null);
        System.assert(actionPlans.size() == 1);
        System.assert(actionPlans[0].SME_Email__c == emails[0].ToAddress);
        System.assert(actionPlans[0].Parent_Case__c == emails[0].ParentId);
        System.assert(actionPlans[0].Status__c == GlobalConstants.ACTION_PLAN_NEW_STATUS);
        System.assert(actionPlans[0].Type__c  == GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST);
        System.assert(actionPlans[0].Branch__c  == 'test branch');
        System.assert(actionPlans[0].Agency__c  == 'test agency');
        System.assert(actionPlans[0].OwnerId  == UserInfo.getUserId());

        System.Test.stopTest();
    }
    
    private static testMethod void testForBulkAdviceEmailMessage() {
        setUpTestData(10);
        System.Test.startTest();
        ActionPlanCreator apCreator = new ActionPlanCreator(emails);
        List<Action_Plan__c> actionPlans = apCreator.createAdviceRequestPlans();
        System.assert(actionPlans != null);
        System.assert(actionPlans.size() == 10);
        System.assert(actionPlans[0].SME_Email__c == emails[0].ToAddress);
        System.assert(actionPlans[0].Status__c == GlobalConstants.ACTION_PLAN_NEW_STATUS);
        System.assert(actionPlans[0].Type__c  == GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST);
        System.Test.stopTest();
    }
    
    private static testMethod void testForAdviceEmailWithoutParentId() {
        setUpTestData(1);
        emails[0].ParentId = null;
        System.Test.startTest();
        ActionPlanCreator apCreator = new ActionPlanCreator(emails);
        List<Action_Plan__c> actionPlans = apCreator.createAdviceRequestPlans();
        System.assert(actionPlans != null);
        System.assert(actionPlans.isEmpty());
        System.Test.stopTest();
    }
    
    private static void setUpTestData(Integer emailCount) {
        emails = new List<EmailMessage>();
        List<Case> cases = createCases(emailCount);
        for(Case caseDetail : cases) {
            EmailMessage message = new EmailMessage();
            message.TextBody = 'Test advice request email';
            message.ParentId = caseDetail.Id;
            message.ToAddress = 'test.user@transport.gov.nsw.au';
            
            emails.add(message);
        }
    }
    private static List<Case> createCases(Integer caseCount) {
        List<Case> caseRecords = new List<Case>();
        for(Integer i = 0; i < caseCount; i++) {
            Case caseRecord = new Case();
            caseRecord.Description = 'Test case for creating action plan';
            caseRecord.Origin = 'Web';
            caseRecord.Priority = 'Normal';
            caseRecord.Type = 'Feedback';
            caseRecord.Taxonomy_Symptom__c = 'Difficult to Use';
            caseRecord.Taxonomy_Location__c = '140';
            caseRecord.Taxonomy_Area__c = 'Willoughby';
            caseRecord.Taxonomy_Location_Type__c = 'Sydney Buses';
            caseRecord.Taxonomy_Transaction__c = 'Agency Website';
            caseRecord.Taxonomy_Moment__c = 'Planning the Trip';
            caseRecord.Modes__c = 'Bus';
            caseRecord.branch__c= 'test branch';
            caseRecord.Agency__c= 'test agency';
            
            caseRecords.add(caseRecord);
        }
        
        if(!caseRecords.isEmpty()) insert caseRecords;
        
        return caseRecords;
    }
}