force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/AssignedSME__c.field-meta.xml
<CustomField>
    <fullName>AssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned SME</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.Branch__c</field>
            <operation>equals</operation>
            <valueField>User.Branch__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be the Business hours corresponding to the Agency/Division selected on the Action plan, if a corresponding , business hr is not found the default one will be set</description>
    <inlineHelpText>The business hrs followed by the Agency / Division</inlineHelpText>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/OldStatus__c.field-meta.xml
<CustomField>
    <fullName>OldStatus__c</fullName>
    <label>Old Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/ResponseHistory__c.field-meta.xml
<CustomField>
    <fullName>ResponseHistory__c</fullName>
    <description>To capture Advice Request Response version on Submit for Approval</description>
    <inlineHelpText>To capture Advice Request Response version on Submit for Approval</inlineHelpText>
    <label>Response History</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/ReturnToOwner__c.field-meta.xml
<CustomField>
    <fullName>ReturnToOwner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return to Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/SkipValidations__c.field-meta.xml
<CustomField>
    <fullName>SkipValidations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this checkbox is checked then all the validation rules will be skipped</description>
    <label>Skip Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/TempAssignedSME__c.field-meta.xml
<CustomField>
    <fullName>TempAssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used in workflow which will send out an email to the Assigned SME</description>
    <label>Primary SME</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActionPlanBeforeUpdateTriggerHandler.cls
/*------------------------------------------------------------
Author:        Dipankar Barman
Company:       Arxxus.com
Description:   A utility class for the Action Plan Trigger

Test Class:    Action_PlanTriggerDispatcher_Test
History
04/05/2015     Dipankar Barman       Created
19/04/2017     Ian Fitzgerald        Check conditions in changeActionPlanOwnerToCaseOwnerWhenIncorrectAssignment 
                                     before making SOQL calls to save on limits 
------------------------------------------------------------*/
public without sharing class ActionPlanBeforeUpdateTriggerHandler extends TriggerHandlerBase{

    List<ApplicationLogMessage> messages =new List<ApplicationLogMessage>();
    public override void mainEntry(TriggerParameters tp) {
        process(tp);
        changeActionPlanOwnerToCaseOwnerWhenIncorrectAssignment(tp);
    }
    
    public override void inProgressEntry(TriggerParameters tp) {
        System.debug('ActionPlanBeforeUpdateTriggerHandler: This is an example for reentrant code...');
    }
    
    /*------------------------------------------------------------
    Author:        Dipankar Barman
    Company:       Arxxus.com
    Description:   Handler function to track response history in a large text area when status waiting for approval
    
    History
    04/05/2015     Dipankar Barman       Created
    22/06/2015     Manish Damle          Added check for completed status of the 
                                         action plan to trach the response history.
    ------------------------------------------------------------*/ 
    private void process(TriggerParameters tp) {
        try{
            system.debug('---ActionPlanBeforeUpdateTriggerHandler---' + Action_PlanTriggerDispatcher.triggerLoopCount);
            if(Action_PlanTriggerDispatcher.triggerLoopCount == 0) { //STATIC VARIABLE TO ALLOW THE CODE TO RUN ONLY ONCE
                system.debug('---ActionPlanBeforeUpdateTriggerHandler Loop count 0---');
                for (Action_plan__c anAp:(List<Action_plan__c>)tp.newList) {
                    //set the business hrs if agency is populated
                    if(anAp.Agency__c != null) anAp.BusinessHours__c = BusinessHoursUtil.getBusinessHour(anAp.Agency__c);
                    Action_plan__c oldAp = (Action_plan__c)tp.oldMap.get(anAp.Id);
                    system.debug('---Response History---' + anAp);  
                    if (anAp.status__c != oldAp.status__c 
                        &&((anAp.status__c.equalsIgnoreCase(GlobalConstants.ACTION_PLAN_WAITING_APPROVAL)
                            || anAp.status__c.equalsIgnoreCase(GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT)
                            || anAp.status__c.equalsIgnoreCase(GlobalConstants.ACTION_PLAN_CLOSED_STATUS)
                            ) 
                                || (anAp.status__c.equalsIgnoreCase(GlobalConstants.ACTION_PLAN_NEW_APPROVED) && !String.isBlank(anAp.Parent_Action_Plan__c)))){
                                    
                        system.debug('---Response History---');                                    
                        String currentText = '<br/>-----------------------------------<br/>' + 
                                             (anAp.response__c == null ? '' : anAp.response__c) + 
                                             '<br/><i>Submitted By - </i>' + 
                                             UserInfo.getName() + 
                                             ' <i>on - </i>' + 
                                             system.now().format() + 
                                             ' <i>Status - </i>' + anAp.Status__c;
                        anAp.ResponseHistory__c = anAp.ResponseHistory__c == null? currentText : currentText + anAp.ResponseHistory__c; 
                        system.debug('---Response History---' + anAp.ResponseHistory__c);              
                        if(anAp.ResponseHistory__c!=null && anAp.ResponseHistory__c.length() > 131071)
                            anAp.ResponseHistory__c = anAp.ResponseHistory__c.substring(0,131071);
                    }
                    
                    //Fix for WI1358 - Assigned sme is removed once the Action Plan is assigned.
                    if(anAp.RecordTypeId == Action_PlanTriggerDispatcher.actionPlanRecordTypes.get(GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME) && anAp.AssignedSme__c != null ) {
                        anAp.ownerId = anAp.AssignedSme__c;
                        anAp.TempAssignedSME__c = anAp.AssignedSme__c;
                        anAp.AssignedSme__c = null;
                    }
                }//for
                
                 //WI-0001584 - Stamp the OldStatus
                for (Action_plan__c anAp :(List<Action_plan__c>)tp.newList){
                    Action_plan__c oldAp = (Action_plan__c) tp.oldMap.get(anAp.Id);
                    anAp.OldStatus__c = oldAp.Status__c;
                    system.debug('-------Changed ap.Status__c-----' + anAp.Status__c);
                    system.debug('-------Changed ap.OldStatus__c-----' + anAp.OldStatus__c);
                }
                
                if(Action_PlanTriggerDispatcher.magsAndCrgsAdminRoles.containsKey(UserInfo.getUserRoleId())) {
                    ActionPlanUtility.stampDueDateOnActionPlan((list <Action_plan__c>) tp.newList);
                }
                Action_PlanTriggerDispatcher.triggerLoopCount ++;
            }
            changeTheOwnershipOfCAPWhenApproved(tp);
            validateChildActionPlansAreClosed(tp);
            
            DateStamperOnStatusChange dateStamper = new DateStamperOnStatusChange((List<Action_Plan__c>) tp.newList, (Map<Id, Action_Plan__c>) tp.oldMap);
            dateStamper.stampDate();
            
            TimeSpentInStatusCalculator calc = new TimeSpentInStatusCalculator((List<Action_Plan__c>) tp.newList, (Map<Id, Action_Plan__c>) tp.oldMap);
            calc.stampTimeSpent();
        }catch(Exception e){ 
            system.debug('-----ActionPlanBeforeUpdateTriggerHandler Exception---' + e.getMessage() + '---LINE---' + e.getLineNumber());
            ApplicationLogMessage message= new ApplicationLogMessage();
            message.source='ActionPlanBeforeUpdateTriggerHandler';
            message.sourceFunction='process';
            if (tp!=null && tp.oldMap!=null)  message.referenceInfo=JSON.serialize(tp.oldMap.keySet());
            message.logMessage=e.getMessage();
            message.ex=e;
            message.debugLevel='Error';
            messages.add(message);
            ApplicationLogUtility.logMessage(messages);
            messages.clear(); 
            //THROW_EXCEPTIONS is a global constant, it is set to the current user's "Throw Exceptions" value 
            //"Throw Exceptions" is a checkbox on the User record. - Added by Ian F, tfNSW, 21/08/2017
            if (GlobalConstants.THROW_EXCEPTIONS){
                Throw(e);
            }
        }
    }
        
    /*------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   Change the owner of the action plan to case owner when status of the action plan
                   changed to "Rejected-Incorrect Assignment".
                   Timebased workflow will be triggered to do this.
    History
    27/05/2015     Manish Damle       Created
    15/07/2015     Manish Damle       Updated the if condition.(WI#1083)        
    19/04/2017     Ian Fitzgerald     Check conditions before making SOQL calls to save on limits                             
    ------------------------------------------------------------*/     
    private void changeActionPlanOwnerToCaseOwnerWhenIncorrectAssignment(TriggerParameters tp) {
        try{
            set <Id> parentCaseIds = new set <Id>();
            for (Action_plan__c anAp:(List<Action_plan__c>) tp.newList) {
                Action_plan__c oldAp = (Action_plan__c) tp.oldMap.get(anAp.Id); 
                if(anAp.Parent_Case__c != null && anAp.Status__c == GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT
                   && oldAp.ReturnToOwner__c!=anAp.ReturnToOwner__c && anAp.ReturnToOwner__c==true) {
                    parentCaseIds.add(anAp.Parent_Case__c);
                }
            }
            
            if(parentCaseIds.size() > 0) {
                map<Id, Case> parentCases = new map <Id, Case> ([Select Id, OwnerId From Case Where Id IN: parentCaseIds]);
                RecordType mcws_AP_recordType = [Select Id From RecordType Where DeveloperName =: GlobalConstants.ACTION_PLAN_MCWS_AP_RECORD_TYPE_NAME limit 1];
                system.debug('----parentCases----' + parentCases);
                for (Action_plan__c anAp:(List<Action_plan__c>) tp.newList) {            
                     Action_plan__c newAp = (Action_plan__c) tp.newMap.get(anAp.Id);      
                     Action_plan__c oldAp = (Action_plan__c) tp.oldMap.get(anAp.Id);  
                     system.debug('----newAp.Status__c----' + newAp.Status__c);
                     system.debug('----oldAp.Status__c----' + oldAp.Status__c);
                     if(anAp.Parent_Case__c != null && parentCases.containsKey(anAp.Parent_Case__c))    {
                        newAp.OwnerId = parentCases.get(anAp.Parent_Case__c).OwnerId;
                        newAp.ReturnToOwner__c = false;
                        newAp.RecordTypeId = mcws_AP_recordType.Id;
                     }
                }
            }
        }catch(Exception e){
            system.debug('-----ActionPlanBeforeUpdateTriggerHandler Exception---' + e.getMessage() + '---LINE---' + e.getLineNumber());
            ApplicationLogMessage message= new ApplicationLogMessage();
            message.source='ActionPlanBeforeUpdateTriggerHandler';
            message.sourceFunction='process';
            if (tp!=null && tp.oldMap!=null)  message.referenceInfo=JSON.serialize(tp.oldMap.keySet());
            message.logMessage=e.getMessage();
            message.ex=e;
            message.debugLevel='Error';
            messages.add(message);
            ApplicationLogUtility.logMessage(messages);
            messages.clear(); 
            //THROW_EXCEPTIONS is a global constant, it is set to the current user's "Throw Exceptions" value 
            //"Throw Exceptions" is a checkbox on the User record. - Added by Ian F, tfNSW, 21/08/2017
            if (GlobalConstants.THROW_EXCEPTIONS){
                Throw(e);
            }
        }
        
    }        
    
    /*------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   This method will validate that the child action plan should be closed before closing the parent action plan
    
    History
    27/05/2015     Manish Damle       Created
    ------------------------------------------------------------*/     
    private void validateChildActionPlansAreClosed(TriggerParameters tp) {
        set <Id> parentActionPlans = new set <Id> ();
        for(Action_plan__c anAp : (list <Action_Plan__c>) tp.newList) {
            if(anAp.SkipValidations__c == false && anAp.Parent_Action_Plan__c == null && anAp.Status__c == GlobalConstants.ACTION_PLAN_CLOSED_STATUS) {
                parentActionPlans.add(anAp.Id);
            } 
        }
        
        map <Id, Integer> parentVsChildCount = ActionPlanUtility.createApVsNoOfChildActionPlansMap(null, parentActionPlans);
        for(Id apId : parentVsChildCount.keySet()) {
            if(parentVsChildCount.get(apId) > 0) {
                tp.newMap.get(apId).addError('Action plan cannot be closed. Please close all the linked action plans before closing an action plan');
            }
        }
    }
    
    /*------------------------------------------------------------
    Author:        Manish Damle
    Company:       Arxxus.com
    Description:   Whenever child action Plan is approved then ownership is
                   changed to CO i.e new status = "Action Plan in Progress".
                   #WI-0001645
    History
    12/10/2015     Manish Damle       Created
    19/04/2017     Ian Fitzgerald     Check conditions before making SOQL calls to save on limits  
    ------------------------------------------------------------*/
    private void changeTheOwnershipOfCAPWhenApproved(TriggerParameters tp) {
        map <Id,Id> childApIdVsparentId =  new map <Id, Id>();
        for(Action_plan__c anAp : (list <Action_Plan__c>) tp.newList) {
            Action_plan__c oldAp = (Action_Plan__c) tp.oldMap.get(anAp.Id);
            if(anAp.Status__c != oldAp.Status__c 
               && anAp.Status__c == GlobalConstants.ACTION_PLAN_NEW_APPROVED 
               && anAp.Parent_Action_Plan__c != null) {
                childApIdVsparentId.put(anAp.Id, anAp.Parent_Action_Plan__c); 
            }
        }
        
        System.debug('----@Approved CAPS-----' + childApIdVsparentId);
        
        if(childApIdVsparentId.size() > 0){
            map <Id, Action_Plan__c> parents = new map <Id, Action_Plan__c>([Select Id, OwnerId 
                                                                             From Action_Plan__c 
                                                                             Where Id IN: childApIdVsparentId.values()]);
            System.debug('----@Approved CAPS Parents-----' + parents);
            for(Id key : childApIdVsparentId.keySet()) {
                Action_Plan__c anAp = (Action_Plan__c) tp.newMap.get(key);
                if(parents.containsKey(childApIdVsparentId.get(key))) {
                    anAp.OwnerId = parents.get(childApIdVsparentId.get(key)).OwnerId;
                    System.debug('----@Approved CAPS Owner Updated-----' + anAp.OwnerId);
                }
            }
        }
    }
}