force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APStatusTransitionForRejectedAssignment.cls
public without sharing class APStatusTransitionForRejectedAssignment extends AbstractAPStatusTransition {
    public APStatusTransitionForRejectedAssignment(Id actionPlanId) {
        try {
            validateActionPlan(actionPlanId);
        } catch(Exception e) {
            throw new InvalidDataException('Failed to update status to ' + GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT + '. Action plan details missing');
        }
    }
    
    public override void performTransition() {
        if(!GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST.equalsIgnoreCase(actionPlan.Type__c)
                && !GlobalConstants.AP_TYPE_AGENCY_RESPONSE.equalsIgnoreCase(actionPlan.Type__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT 
            + '. Action plan type is other than ' + GlobalConstants.ACTION_PLAN_TYPE_ADVICE_REQUEST + ' and ' +  GlobalConstants.AP_TYPE_AGENCY_RESPONSE);
        }
        processAdviceRequestAP();
    }
        
    private void processAdviceRequestAP() {     
        if(String.isBlank(actionPlan.Response__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT + '. Response is not populated on action plan.');
        }
        
        System.debug('Action plan current status: ' + actionPlan.Status__c);
        if(String.isBlank(actionPlan.Parent_Action_Plan__c)) {
            processAdviceRequestParentActionPlan();
        } else {
            processAdviceRequestChildActionPlan();
        }
    }
    
    private void processAdviceRequestParentActionPlan() {
        if(!GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED.equalsIgnoreCase(actionPlan.Status__c)
                && !GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(actionPlan.Status__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT + '. Current status of action plan is other than ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + ' and ' + GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS);
        }
        //Manish Damle : 12 October, 2015
        //if(!String.isBlank(actionPlan.Parent_Case__c)) {
            //List<Case> cases = [SELECT Id, OwnerId FROM Case WHERE Id =:actionPlan.Parent_Case__c];
            //actionPlan.OwnerId = cases[0].OwnerId;
        //} Ownership change will happen after 1 hour for parent action plan.
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT;
        update actionPlan;
    }
        
    private void processAdviceRequestChildActionPlan() { 
        if(!GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED.equalsIgnoreCase(actionPlan.Status__c)
                && !GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS.equalsIgnoreCase(actionPlan.Status__c)) {
            throw new InvalidDataException('Failed to update action plan status to ' + GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT + '. Current status of action plan is other than ' + GlobalConstants.ACTION_PLAN_STATUS_ASSIGNED + ' and ' + GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS);
        }
        Action_Plan__c parent = [SELECT Id, OwnerId FROM Action_Plan__c WHERE Id = :actionPlan.Parent_Action_Plan__c];
        actionPlan.Status__c = GlobalConstants.ACTION_PLAN_INCORRECT_ASSIGNMENT;
        actionPlan.OwnerId = parent.OwnerId; 
        update actionPlan;
    }
    
    public class InvalidDataException extends Exception {}
}