force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/AgencyVsQueueMapping__c.field-meta.xml
<CustomField>
    <fullName>AgencyVsQueueMapping__c</fullName>
    <description>This field is used in javscript of Assign To Agency Button and also used in apex classes APStatusTransitionforAssign and APStatusTransitionForRework.

SFCOE-1802: Changes to TfNSW Agency, Division and Branch names due to restructure.</description>
    <formula>CASE(TEXT(Branch__c),
&quot;IP Fleet Program Delivery&quot;, &quot;TfNSW_I_S_Fleet_Program_Delivery_MC&quot;,
&quot;IP Infrastructure and Project Finance&quot;, &quot;TfNSW_I_P_Infrastructure_and_Project_F&quot;,
&quot;IP Operational Systems&quot;, &quot;Transport_Services_MC&quot;,
&quot;IP Placemaking and Real Estate&quot;, &quot;TfNSW_I_P_Placemaking_and_Real_Estate&quot;,
&quot;IP Parramatta Light Rail&quot;, &quot;TfNSW_I_S_Parramatta_Light_Rail_MC&quot;,
&quot;IP Precincts and Infrastructure&quot;, &quot;Transport_Projects_MC&quot;,
&quot;IP Program Management Office&quot;, &quot;TfNSW_IS_Pgm_Divisional_Mgmt_Offc_MC&quot;,
&quot;IP Newcastle Transport Program&quot;, &quot;TfNSW_I_P_Newcastle_Transport_Program&quot;,
&quot;IP Rail Program Delivery&quot;, &quot;TfNSW_IS_Rail_Service_Delivery_MC&quot;,
&quot;IP Sydney Light Rail&quot;, &quot;Light_Rail_MC&quot;,
&quot;TfNSW Services&quot;, &quot;TfNSW_CTS_Services&quot;,
&quot;TfNSW Services (Regional)&quot;, &quot;TfNSW_CTS_Services&quot;,
&quot;TfNSW Centres for Road and Maritime Safety&quot;, &quot;Centre_for_Road_Safety_MC&quot;,
&quot;TC Transport Management Centre&quot;, &quot;TfNSW_IS_Transport_Management_Centre_MC&quot;,
&quot;TC Sydney Coordination Office&quot;, &quot;TfNSW_CBD_Coordination_Office_MC&quot;,
&quot;IP Divisional Management Office&quot;, &quot;TfNSW_I_P_Divisional_Management_Office&quot;,
&quot;TfNSW Asset Standards Authority&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;FSP Freight Industry&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;FSP Innovations, Research and Reform&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;FSP Transport Planning&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;FSP Transport Policy&quot;, &quot;TfNSW_Freight_Strategy_and_Planning_MC&quot;,
&quot;Sydney Metro&quot;, &quot;North_West_Rail_Link_MC&quot;,
&quot;Sydney Trains&quot;, &quot;Sydney_Trains_MC&quot;,
&quot;State Transit&quot;, &quot;STA_MC&quot;,
&quot;NSW TrainsLink&quot;, &quot;NSW_Trainlink_MC&quot;,

&quot;Point to Point Transport Commission&quot;, &quot;TfNSW_P2P_Transport_Commission&quot;, /* Not part of the new structure Jul19 */

/* RMS */
&quot;RMS Corporate Affairs&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Audit and Assurance&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Financial Planning and Analysis&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Sydney Division&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Maritime&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Regional and Freight&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Property and Acquisitions&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Motorways&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Technical and Project Services&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),
&quot;RMS Compliance and Regulatory Services&quot;, IF( ISPICKVAL(Status__c, &quot;New&quot;), &quot;GIS_Admin_RMS_MC&quot;, &quot;RMS_Corro_Officer_Queue&quot;),

CASE(TEXT(Divisions__c),
&quot;Corporate Services&quot;, &quot;People_and_corporate_services_MC&quot;,
&quot;Customer Strategy and Technology&quot;, &quot;TfNSW_Customer_Services_MC&quot;,
&quot;Finance and Investment&quot;, &quot;Finance_MC&quot;, /* Division no longer exists */

&quot;QUEUE-NOT-FOUND&quot;
)
)</formula>
    <label>Agency Vs Queue Mapping</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Amendment__c.field-meta.xml
<CustomField>
    <fullName>Amendment__c</fullName>
    <label># Amendment</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date__c</fullName>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <label>Approver Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/AssignedSME__c.field-meta.xml
<CustomField>
    <fullName>AssignedSME__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned SME</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.Branch__c</field>
            <operation>equals</operation>
            <valueField>User.Branch__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Divisions__c.field-meta.xml
<CustomField>
    <fullName>Divisions__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Agency__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Office of the Secretary</fullName>
            </value>
            <value>
                <fullName>Customer Strategy and Technology</fullName>
            </value>
            <value>
                <fullName>Greater Sydney</fullName>
            </value>
            <value>
                <fullName>Regional and Outer Metropolitan</fullName>
            </value>
            <value>
                <fullName>Infrastructure and Place</fullName>
            </value>
            <value>
                <fullName>Safety, Environment and Regulation</fullName>
            </value>
            <value>
                <fullName>Corporate Services</fullName>
            </value>
            <value>
                <fullName>People and Culture</fullName>
            </value>
            <value>
                <fullName>Asset Maintenance</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Customer Service Delivery</fullName>
            </value>
            <value>
                <fullName>Eastern Region</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; SEQR</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Finance &amp; Administrative Services</fullName>
            </value>
            <value>
                <fullName>Fleet Operations &amp; Infrastructure</fullName>
            </value>
            <value>
                <fullName>Freight and Regional Development</fullName>
            </value>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Infrastructure Development</fullName>
            </value>
            <value>
                <fullName>Journey Management</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal - Business Support</fullName>
            </value>
            <value>
                <fullName>Light Rail</fullName>
            </value>
            <value>
                <fullName>Maritime</fullName>
            </value>
            <value>
                <fullName>Newcastle Buses, Ferries and Light Rail</fullName>
            </value>
            <value>
                <fullName>Northern Region</fullName>
            </value>
            <value>
                <fullName>North West Rail Link</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Has_Corro_Officer_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Has_Corro_Officer_Permissions__c</fullName>
    <formula>$Permission.Corro_Officer</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Corro Officer Permissions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Printing_Location__c.field-meta.xml
<CustomField>
    <fullName>Printing_Location__c</fullName>
    <inlineHelpText>Printing location for RMS CE letters</inlineHelpText>
    <label>Printing Location</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Print_Location_Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>North Sydney (Miller Street)</fullName>
            </value>
            <value>
                <fullName>Parramatta (Argyle Street)</fullName>
            </value>
            <value>
                <fullName>Parramatta (Octagon)</fullName>
            </value>
            <value>
                <fullName>Parramatta (Wentworth Street)</fullName>
            </value>
            <value>
                <fullName>Newcastle (Darby &amp; Queen Streets)</fullName>
            </value>
            <value>
                <fullName>Woy Woy (George Street)</fullName>
            </value>
            <value>
                <fullName>Grafton (Fitzroy &amp; King Streets)</fullName>
            </value>
            <value>
                <fullName>Grafton (Victoria Street)</fullName>
            </value>
            <value>
                <fullName>Pacific Highway Office</fullName>
            </value>
            <value>
                <fullName>Glen Innes (Grey &amp; Ferguson Streets)</fullName>
            </value>
            <value>
                <fullName>Parkes (Currajong Street)</fullName>
            </value>
            <value>
                <fullName>Wagga Wagga (Simmons Street)</fullName>
            </value>
            <value>
                <fullName>Wollongong (Crown Street)</fullName>
            </value>
            <value>
                <fullName>Northern Regional Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advice Request</fullName>
                <default>true</default>
                <label>Advice Request</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Customer-Facing Response</fullName>
            </value>
            <value>
                <fullName>Agency Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AbstractAPStatusTransition.cls
public with sharing abstract class AbstractAPStatusTransition {
    
    protected Action_Plan__c actionPlan;
    private static final String ACTION_PLAN_DETAILS_MISSING='Action plan details missing';
    
    protected void validateActionPlan(Id actionPlanId) {
        if(String.isBlank(actionPlanId)) {
            throw new InvalidDataException(ACTION_PLAN_DETAILS_MISSING);
        }
        List<Action_Plan__c> actionPlans = [SELECT Id, Status__c, Divisions__c, Parent_Case__c, Type__c, Agency__c, Parent_Action_Plan__c, AssignedSME__c, AgencyVsQueueMapping__c,
                                                Response__c, Approval_Date__c, Approver_Name__c, Approver_Role__c, Printing_Location__c, OwnerId, Amendment__c, Has_Corro_Officer_Permissions__c, Has_Liaison_Officer_Permissions__c
                                            FROM Action_Plan__c 
                                            WHERE Id = :actionPlanId];
        if(actionPlans.isEmpty()) {
            throw new InvalidDataException(ACTION_PLAN_DETAILS_MISSING);
        }
        actionPlan = actionPlans[0];
    }
    
    public abstract void performTransition();
    
    public class InvalidDataException extends Exception {}
}