force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Child_Action_Plans__c.field-meta.xml
<CustomField>
    <fullName>Child_Action_Plans__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Child Action Plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Completed_Child_Action_Plans__c.field-meta.xml
<CustomField>
    <fullName>Completed_Child_Action_Plans__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Completed Child Action Plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChildActionPlanCounter_Test.cls
@isTest
private class ChildActionPlanCounter_Test {

    private static List<Action_Plan__c> childActionPlans;
    private static Action_Plan__c parentActionPlan;
    
    @testSetup
    public static void setup() {
        PermissionSet pset = [Select Id From PermissionSet Where Name =: GlobalConstants.PERMISSION_SET_CORRO_OFFICER limit 1];
        List<PermissionSetAssignment> assignment = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId() AND PermissionSetId = :pset.id];
        if(assignment.isEmpty())
            insert new PermissionSetAssignment(AssigneeId=UserInfo.getUserId(), PermissionSetId=pset.id);
    }
    
    private static testMethod void testForInvalidData() {
        System.Test.startTest();
        try {
            ChildActionPlanCounter childCounter = new ChildActionPlanCounter(childActionPlans);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        
        try {
            childActionPlans = new List<Action_Plan__c>();
            ChildActionPlanCounter childCounter = new ChildActionPlanCounter(childActionPlans);
            System.assert(false);
        } catch(Exception e) {
            System.assert(true);
        }
        System.Test.stopTest();
    }
    
    private static testMethod void testForChildActionPlanCount() {
        setupTestData(1);
        System.Test.startTest();
        ChildActionPlanCounter counter = new ChildActionPlanCounter(childActionPlans);
        counter.updateChildActionPlanCounter();
        System.Test.stopTest();
        List<Action_Plan__c> parentAP = [SELECT Id, Child_Action_Plans__c, Completed_Child_Action_Plans__c FROM Action_Plan__c WHERE Id = :parentActionPlan.Id];
        System.assert(!parentAP.isEmpty());
        System.assert(parentAP[0].Completed_Child_Action_Plans__c == 0);
        System.assert(parentAP[0].Child_Action_Plans__c == 1);
    }
    
    private static testMethod void testForCompletedChildActionPlan() {
        setupTestData(1);
        for(Action_Plan__c child : childActionPlans) {
            child.Status__c = GlobalConstants.ACTION_PLAN_CLOSED_STATUS;
        }
        System.Test.startTest();
        system.runAs(new User(Id = UserInfo.getUserId())){
            update childActionPlans;
        }
        
        ChildActionPlanCounter counter = new ChildActionPlanCounter(childActionPlans);
        counter.updateChildActionPlanCounter();
        System.Test.stopTest();
        List<Action_Plan__c> parentAP = [SELECT Id, Child_Action_Plans__c, Completed_Child_Action_Plans__c FROM Action_Plan__c WHERE Id = :parentActionPlan.Id];
        System.assert(!parentAP.isEmpty());
        System.assert(parentAP[0].Completed_Child_Action_Plans__c == 1);
        System.assert(parentAP[0].Child_Action_Plans__c == 1);
    }
    
    private static testMethod void testForBulkification() {
        setupTestData(200);
        
        System.Test.startTest();
        ChildActionPlanCounter counter = new ChildActionPlanCounter(childActionPlans);
        counter.updateChildActionPlanCounter();
        System.Test.stopTest();
        List<Action_Plan__c> parentAP = [SELECT Id, Child_Action_Plans__c, Completed_Child_Action_Plans__c FROM Action_Plan__c WHERE Id = :parentActionPlan.Id];
        System.assert(!parentAP.isEmpty());
        System.assert(parentAP[0].Completed_Child_Action_Plans__c == 0);
        System.assert(parentAP[0].Child_Action_Plans__c == 200);
    }
    
    private static void setupTestData(Integer actionplanCount) {
        Id recordType = retrieveNonCfmRecordTypeOfAp();
        createParentActionPlan(recordType);
        createChildActionPlans(actionplanCount, recordType);
    }
    
    private static void createChildActionPlans(Integer actionplanCount, Id recordType) {
        childActionPlans = new List<Action_Plan__c>();
        Id childActionPlanRecordTypeId = [Select Id From RecordType Where DeveloperName =: GlobalConstants.CHILD_AP_RECORDTYPE_API_NAME limit 1].Id;
        for(Integer index=0; index < actionplanCount; index++) {
            Action_Plan__c ap = new Action_Plan__c();
            ap.Parent_Action_Plan__c = parentActionPlan.Id;
            ap.Status__c = GlobalConstants.ACTION_PLAN_STATUS_INPROGRESS;
            ap.RecordTypeId = childActionPlanRecordTypeId;
            ap.Response__c = 'Test response';
            childActionPlans.add(ap);
        }
        
        if(!childActionPlans.isEmpty()) {
            insert childActionPlans;
        }
    }
    
    private static void createParentActionPlan(Id recordType) {
        parentActionPlan = new Action_Plan__c();
        parentActionPlan.Agency__c = 'TfNSW';
        
        insert parentActionPlan;
    }
    
    private static Id retrieveNonCfmRecordTypeOfAp() {
        List<RecordType> rt = [SELECT Id, Name 
                                FROM RecordType 
                                WHERE sObjectType = 'Action_Plan__c' 
                                    AND DeveloperName != :GlobalConstants.ACTION_PLAN_CFM_RECORDTYPE_NAME];
        if(rt.isEmpty()) {
            return null;
        }
        return rt[0].Id;
    }
}