force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/IsAmendment__c.field-meta.xml
<CustomField>
    <fullName>IsAmendment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amendment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseAmendmentChecker.cls
public with sharing class CaseAmendmentChecker {
    
    private List<Action_Plan__c> newActionPlans;
    
    public CaseAmendmentChecker(List<Action_Plan__c> actionPlans) {
        if(actionPlans == null || actionPlans.isEmpty()) {
            throw new InvalidDataException('Failed to check amendment cases. Action plan details missing');
        }
        this.newActionPlans = actionPlans;
    }
    
    public void checkForAmendment() {
        Set<Id> caseIds = new Set<Id>();
        for(Action_Plan__c ap : newActionPlans) {
            caseIds.add(ap.Parent_Case__c);
        }
        Map<Id, Case> parentCaseMap = new Map<Id, Case> ([SELECT Id FROM Case WHERE Id IN :caseIds AND Amendment_Count__c > 0]);
        for(Action_Plan__c ap : newActionPlans) {
            if(parentCaseMap.containsKey(ap.Parent_Case__c)) {
                ap.IsAmendment__c = true;
            }
        }
    }
    
    public class InvalidDataException extends Exception {}
}