force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object will store details about action plan assigned to a user</description>
    <label>Action Plan</label>
    <nameField>
        <displayFormat>APN-{00000000}</displayFormat>
        <label>Action Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HCF</fullName>
            </value>
            <value>
                <fullName>Serco</fullName>
            </value>
            <value>
                <fullName>TfNSW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be the Business hours corresponding to the Agency/Division selected on the Action plan, if a corresponding , business hr is not found the default one will be set</description>
    <inlineHelpText>The business hrs followed by the Agency / Division</inlineHelpText>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/CasePriority__c.field-meta.xml
<CustomField>
    <fullName>CasePriority__c</fullName>
    <description>Priority copied down from case</description>
    <label>Case Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MP - Standard</fullName>
            </value>
            <value>
                <fullName>Individual - Standard</fullName>
            </value>
            <value>
                <fullName>Date Sensitive – MO specified due date</fullName>
            </value>
            <value>
                <fullName>Urgent – MO specified due date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Parent_Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Action_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Related Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected-Incorrect Assignment</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Printing</fullName>
            </value>
            <value>
                <fullName>Action Plan in Progress</fullName>
            </value>
            <value>
                <fullName>Action Plan Assigned</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan Approval</fullName>
            </value>
            <value>
                <fullName>Action Plan in Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ActionPlanDueDateByAgency__c/ActionPlanDueDateByAgency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This can be used for calculating the Action Plan due dates by Agency+priority as in case of RMSMP - Standard it might be 9 days which will be 9*8=72 business hrs</description>
    <label>Action Plan Due Dates by Agency</label>
</CustomObject>

force-app/main/default/objects/ActionPlanDueDateByAgency__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <label>Business hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BusinessHoursUtil_Test.cls
@isTest
private class BusinessHoursUtil_Test
{
    @testSetup
    static void setup() {
        list <ActionPlanDueDateByAgency__c> cs =  new list <ActionPlanDueDateByAgency__c>();
        cs.add(new ActionPlanDueDateByAgency__c(Name = 'Default', BusinessHours__c = 64));
        cs.add(new ActionPlanDueDateByAgency__c(Name = 'RMSIndividual - Standard', BusinessHours__c = 102));
        cs.add(new ActionPlanDueDateByAgency__c(Name = 'RMSMP - Standard', BusinessHours__c = 80));
        insert cs;
    }
    
	@isTest//It should get multiple business hrs including the default
	static void testSetup() {
		BusinessHoursUtil.setup();
		system.assert(BusinessHoursUtil.agencyBusinessHrsMap.size()>0);
	}

	@isTest//It should get multiple business hrs including the default
	static void testGetBusinessHour() {
		Id def = BusinessHoursUtil.getBusinessHour('Default');
		system.assertNotEquals(def,null);
	}
      
    //Individual Standard calculations
    @isTest
    static void testDueDateIndividualStandard() {
        BusinessHoursUtil.setup();
        Action_Plan__c ap = new Action_Plan__c(Status__c = 'New',
                                               Due_Date__c =  null,
                                               Parent_Action_Plan__c = null,
                                               Agency__c = GlobalConstants.RMS_AGENCY,
                                               BusinessHours__c = BusinessHoursUtil.getBusinessHour(GlobalConstants.RMS_AGENCY),
                                               CasePriority__c = GlobalConstants.CASE_PRIORITY_INDIVIDUAL_STANDARD
                                              );
        ActionPlanUtility.stampDueDateOnActionPlan(new list <Action_Plan__c> {ap});
        system.assert(ap.Due_Date__c != null);
    }
    
    //MP Standard calculations
    @isTest
    static void testDueDateMpStandard() {
        BusinessHoursUtil.setup();
        Action_Plan__c ap = new Action_Plan__c(Status__c = 'New',
                                               Due_Date__c =  null,
                                               Parent_Action_Plan__c = null,
                                               Agency__c = GlobalConstants.RMS_AGENCY,
                                               BusinessHours__c = BusinessHoursUtil.getBusinessHour(GlobalConstants.RMS_AGENCY),
                                               CasePriority__c = GlobalConstants.CASE_PRIORITY_MP_STANDARD
                                              );
        ActionPlanUtility.stampDueDateOnActionPlan(new list <Action_Plan__c> {ap});
        system.assert(ap.Due_Date__c != null);
    }
    
    //MP Standard calculations
    @isTest
    static void testDueDateOtherThanRMS() {
        BusinessHoursUtil.setup();
        Action_Plan__c ap = new Action_Plan__c(Status__c = 'New',
                                               Due_Date__c =  null,
                                               Parent_Action_Plan__c = null,
                                               Agency__c = GlobalConstants.STA_AGENCY,
                                               BusinessHours__c = BusinessHoursUtil.getBusinessHour(GlobalConstants.STA_AGENCY),
                                               CasePriority__c = GlobalConstants.CASE_PRIORITY_MP_STANDARD
                                              );
        ActionPlanUtility.stampDueDateOnActionPlan(new list <Action_Plan__c> {ap});
        system.assert(ap.Due_Date__c != null);
    }
    
    @isTest
    static void testActualDaysOverdue() {
     	Action_Plan__c ap = new Action_Plan__c(Status__c = 'New',
                                               Due_Date__c =  Date.newInstance(2015, 10, 1),
                                               Parent_Action_Plan__c = null,
                                               Agency__c = GlobalConstants.STA_AGENCY,
                                               BusinessHours__c = BusinessHoursUtil.getBusinessHour(GlobalConstants.STA_AGENCY),
                                               CasePriority__c = GlobalConstants.CASE_PRIORITY_MP_STANDARD
                                              );   
        Decimal days = BusinessHoursUtil.getActionPlanActualDaysOverdue(ap.BusinessHours__c, ap.Due_Date__c, System.now());
        System.debug('-----Days-----' + days);
        system.assert(days > 0);
    }
}