force-app/main/default/objects/AppFeedbackRelatedTo__c/AppFeedbackRelatedTo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>App feedback related to</label>
</CustomObject>

force-app/main/default/objects/AppsForWebform__c/AppsForWebform__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apps for webform</label>
</CustomObject>

force-app/main/default/objects/AppsForWebform__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sort Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AppsComponentController_Test.cls
@isTest
private class AppsComponentController_Test {
    
    private static testMethod void testForAvailableApps() {
        List<AppsForWebform__c> apps = new List<AppsForWebform__c>();
        apps.add(new AppsForWebform__c(Name='Arrivo', Sort_Order__c = 1));
        apps.add(new AppsForWebform__c(Name='Travel+', Sort_Order__c = 2));
        insert apps;        
        System.Test.startTest();
        System.Test.setCurrentPage(System.Page.WebToCaseForm);
        ApexPages.currentPage().getHeaders().put('User-Agent', 'MSIE 11');
        AppsComponentController acc = new AppsComponentController();
        List<String> optionList = acc.appOptions;
        System.Test.stopTest();
        System.assert(optionList.size() == 2);
    }
    
    private static testMethod void testForRelatedToField() {
        List<AppFeedbackRelatedTo__c> relatedTo = new List<AppFeedbackRelatedTo__c>();
        relatedTo.add(new AppFeedbackRelatedTo__c(name = 'Functionality', Sort_Order__c = 1));
        relatedTo.add(new AppFeedbackRelatedTo__c(name = 'Messaging', Sort_Order__c = 2));
        insert relatedTo;        
        System.Test.startTest();
        System.Test.setCurrentPage(System.Page.WebToCaseForm);
        ApexPages.currentPage().getHeaders().put('User-Agent', 'MSIE 8');
        AppsComponentController acc = new AppsComponentController();
        List<SelectOption> relatedToList = acc.relatedTo;
        System.Test.stopTest();
        System.assert(relatedToList.size() == 3);
    }
    
    private static testMethod void testForOptions() {
        System.Test.startTest();
        AppsComponentController acc = new AppsComponentController();
        List<SelectOption> options = acc.yesNoOption;
        System.Test.stopTest();
        System.assert(options.size() == 2);
    }
}