force-app/main/default/objects/Temp_Data_Holder__c/Temp_Data_Holder__c.object-meta.xml
<CustomObject>
    <description>Temporary Object to be used by Salesforce Practice to create 6000 Case records using Apex Callouts based on request received from business</description>
    <label>Temp Data Holder</label>
    <nameField>
        <displayFormat>MOREQ-{0000}</displayFormat>
        <label>Temp Data Holder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temp Data Holder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Contact Email</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <description>Body of incoming email</description>
    <label>Email Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <description>Subject of incoming email</description>
    <inlineHelpText>Subject of incoming email</inlineHelpText>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchCaseContactCreationTest.cls
@isTest
public class BatchCaseContactCreationTest {
    
    static testMethod void testMethod1() 
    {
        Database.BatchableContext BC;
        
        RecordType rtcm = [Select Id From RecordType where developername  = 'CampaignMember'];
        RecordType rtc = [Select Id From RecordType where developername  = 'Campaign'];
        String cfsAPIWebServiceEndpoint = 'https://transportnsw--spdev.cs58.my.salesforce.com/services/apexrest/v1/salesforce/case';
        
        Case campaign = getCaseRecord();
        campaign.Subject = 'CAMPAIGN';
        campaign.Taxonomy_Moment__c = 'A';
        campaign.Taxonomy_Transaction__c = 'B';
        campaign.Taxonomy_Location_Type__c = 'C';
        campaign.Taxonomy_Symptom__c = 'D';
        campaign.RecordTypeId = rtc.Id;  
        insert campaign;
        
        User us = [Select id from User where Id = :UserInfo.getUserId()];
        
        Temp_Data_Holder__c inboundEntry = new Temp_Data_Holder__c();
        inboundEntry.EMAIL_SUBJECT__C = 'Uber tax';
        inboundEntry.EMAIL_BODY__C = 'Im utterly disgusted that the nsw govenment think its fair to empose this tax';
        inboundEntry.CONTACT_FIRST_NAME__C = 'Justin';
        inboundEntry.CONTACT_LAST_NAME__C = 'A';
        inboundEntry.CONTACT_EMAIL__C = 'justmatel@hotmail.com';
        
        insert inboundEntry;
        
        System.runAs(us){
            Test.startTest();
            
            BatchCaseContactCreation obj = new BatchCaseContactCreation(userinfo.getSessionId(), campaign.Id, rtcm.Id, cfsAPIWebServiceEndpoint);
            DataBase.executeBatch(obj);
            obj.finish(BC);
            
            Test.stopTest();
        }
    }
    
    private static Case getCaseRecord() {
        return new Case(Status = 'Registered', Subject = 'Campaign Testing', Description = 'Campaign Testing Description');
    }
    
}