force-app/main/default/objects/Temp_Data_Holder__c/Temp_Data_Holder__c.object-meta.xml
<CustomObject>
    <description>Temporary Object to be used by Salesforce Practice to create 6000 Case records using Apex Callouts based on request received from business</description>
    <label>Temp Data Holder</label>
    <nameField>
        <displayFormat>MOREQ-{0000}</displayFormat>
        <label>Temp Data Holder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temp Data Holder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Contact Email</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <description>Body of incoming email</description>
    <label>Email Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <description>Subject of incoming email</description>
    <inlineHelpText>Subject of incoming email</inlineHelpText>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temp_Data_Holder__c/fields/Results__c.field-meta.xml
<CustomField>
    <fullName>Results__c</fullName>
    <label>Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BatchCaseContactCreation.cls
global class BatchCaseContactCreation implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
	
    String sessionId;
    String parentCaseId;
    String recordTypeId;
    String cfsAPIWebServiceEndpoint;
    
    public BatchCaseContactCreation(String sessionId, String parentCaseId, String recordTypeId, String cfsAPIWebServiceEndpoint){
        this.sessionId = sessionId;
        this.parentCaseId = parentCaseId;
        this.recordTypeId = recordTypeId;
        this.cfsAPIWebServiceEndpoint = cfsAPIWebServiceEndpoint;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Email_Subject__c, Email_Body__c, Contact_First_Name__c, Contact_Last_Name__c, Contact_Email__c, Results__c FROM Temp_Data_Holder__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Temp_Data_Holder__c> bulkCaseAndContactData) {
        for (Temp_Data_Holder__c aCaseAndContactData:bulkCaseAndContactData)
        {
            CaseAndContactJSONGenerator cc = new CaseAndContactJSONGenerator(cfsAPIWebServiceEndpoint, parentCaseId, recordTypeId, sessionId, aCaseAndContactData.Email_Subject__c, aCaseAndContactData.Email_Body__c, aCaseAndContactData.Contact_First_Name__c, aCaseAndContactData.Contact_Last_Name__c, aCaseAndContactData.Contact_Email__c, aCaseAndContactData);           
        }
        System.debug('Next Call...');
        update bulkCaseAndContactData;
    }   
    
    global void finish(Database.BatchableContext BC) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        List<String> recepientEmails = new List<String>();
        recepientEmails.add('gary.bakshi@transport.nsw.gov.au');
        email.setSubject('Salesforce Bulk CFS API Case Insertion Job Complete!');
        email.setHTMLBody('Salesforce Bulk CFS API Case Insertion Job Complete!');
        email.setToAddresses(recepientEmails);
        Messaging.sendEmail(New Messaging.SingleEmailMessage[]{email});
    }
}